# package installation and settings

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

import os
import copy
import math

from datetime import timedelta
from scipy.stats import linregress

In [2]:
import matplotlib

print(np.__version__)
print(pd.__version__)
print(matplotlib.__version__)
print(sns.__version__)

2.2.6
2.3.3
3.10.8
0.13.2

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# data import

In [4]:
def icu_data_processor(path, df_general_list):

  dfs = []

  for dirpath, dirnames, filenames in os.walk(path):
    for filename in filenames:
      if filename.endswith('.txt'):
        df_temp = pd.read_csv(os.path.join(dirpath, filename))
        df_temp['RecordID'] = filename.split('.')[0]
        df_index = []
        df_index.append(df_temp[df_temp['Parameter'] == 'RecordID'].index.values[0].item())
        df_index.append(df_temp[df_temp['Parameter'] == 'Age'].index.values[0].item())
        df_index.append(df_temp[df_temp['Parameter'] == 'Gender'].index.values[0].item())
        df_index.append(df_temp[df_temp['Parameter'] == 'Height'].index.values[0].item())
        df_index.append(df_temp[df_temp['Parameter'] == 'ICUType'].index.values[0].item())
        df_general_list.append(df_temp.iloc[df_index,])
        dfs.append(df_temp.drop(df_index, axis=0))

  return dfs

In [5]:
path = '/home/leewen/code/physionet'
df_general_list = []
dfs_a = icu_data_processor(path+'/data/set-a', df_general_list)
dfs_b = icu_data_processor(path+'/data/set-b', df_general_list)
dfs_c = icu_data_processor(path+'/data/set-c', df_general_list)

In [6]:
df_outcome_a = pd.read_csv(path+'/data/Outcomes-a.txt')
df_outcome_b = pd.read_csv(path+'/data/Outcomes-b.txt')
df_outcome_c = pd.read_csv(path+'/data/Outcomes-c.txt')

In [7]:
df_outcome = pd.concat([df_outcome_a, df_outcome_b, df_outcome_c], axis=0).reset_index(drop=True)

In [8]:
df_outcome.head(10)

   RecordID  SAPS-I  SOFA  Length_of_stay  Survival  In-hospital_death
0    132539       6     1               5        -1                  0
1    132540      16     8               8        -1                  0
2    132541      21    11              19        -1                  0
3    132543       7     1               9       575                  0
4    132545      17     2               4       918                  0
5    132547      14    11               6      1637                  0
6    132548      14     4               9        -1                  0
7    132551      19     8               6         5                  1
8    132554      11     0              17        38                  0
9    132555      14     6               8        -1                  0

In [9]:
df_outcome['In-hospital_death'].value_counts()

In-hospital_death
0    10293
1     1707
Name: count, dtype: int64

In [10]:
print(len(dfs_a))
print(len(dfs_b))
print(len(dfs_c))
print(len(df_general_list))
print(df_outcome_a.shape)
print(df_outcome_b.shape)
print(df_outcome_c.shape)
print(df_outcome.shape)

4000
4000
4000
12000
(4000, 6)
(4000, 6)
(4000, 6)
(12000, 6)

# patient demographic data

In [11]:
def process_general_data(df_general_list):

  df_list = []

  for i in range(len(df_general_list)):
    temp = df_general_list[i].T.loc['Value',].values.tolist()
    temp[0] = int(temp[0])
    df_list.append(temp)
  df_general = pd.DataFrame(df_list)
  df_general.columns = ['RecordID', 'Age', 'Gender', 'Height', 'ICUType']

  return df_general

In [12]:
df_general = process_general_data(df_general_list)

In [13]:
df_general.head(10)

   RecordID   Age  Gender  Height  ICUType
0    137188  22.0     0.0   167.6      3.0
1    140351  72.0     1.0   177.8      2.0
2    141985  61.0     1.0    -1.0      1.0
3    136263  67.0     1.0   167.6      2.0
4    141669  50.0     0.0    -1.0      3.0
5    133368  83.0     0.0   152.4      2.0
6    132765  90.0     1.0    -1.0      4.0
7    138320  66.0     1.0   175.3      1.0
8    136295  61.0     1.0    -1.0      4.0
9    134326  59.0     1.0    -1.0      4.0

In [14]:
df_general.shape

(12000, 5)

In [15]:
df_patient =  pd.merge(left=df_general, right=df_outcome, on='RecordID', how='inner')

In [16]:
df_patient.head(10)

,RecordID,Age,Gender,Height,ICUType,SAPS-I,SOFA,Length_of_stay,Survival,In-hospital_death
0,137188,22.0,0.0,167.6,3.0,15,16,13,-1,0
1,140351,72.0,1.0,177.8,2.0,22,13,15,1007,0
2,141985,61.0,1.0,-1.0,1.0,8,1,12,257,0
3,136263,67.0,1.0,167.6,2.0,17,9,9,-1,0
4,141669,50.0,0.0,-1.0,3.0,7,0,4,-1,0
5,133368,83.0,0.0,152.4,2.0,16,9,17,-1,0
6,132765,90.0,1.0,-1.0,4.0,20,10,18,120,0
7,138320,66.0,1.0,175.3,1.0,8,2,3,-1,0
8,136295,61.0,1.0,-1.0,4.0,4,2,13,-1,0
9,134326,59.0,1.0,-1.0,4.0,12,7,13,-1,0

In [17]:
df_patient.shape

(12000, 10)

In [18]:
df_patient.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   RecordID           12000 non-null  int64
 1   Age                12000 non-null  float64
 2   Gender             12000 non-null  float64
 3   Height             12000 non-null  float64
 4   ICUType            12000 non-null  float64
 5   SAPS-I             12000 non-null  int64
 6   SOFA               12000 non-null  int64
 7   Length_of_stay     12000 non-null  int64
 8   Survival           12000 non-null  int64
 9   In-hospital_death  12000 non-null  int64
dtypes: float64(4), int64(6)
memory usage: 937.6 KB

In [19]:
df_patient.describe()

,RecordID,Age,Gender,Height,ICUType,SAPS-I,SOFA,Length_of_stay,Survival,In-hospital_death
count,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000
mean,147744.694750,64.529333,0.559583,88.159075,2.778333,14.308917,6.405917,13.420167,133.932417,0.142250
std,8787.621488,17.175677,0.498468,86.081235,1.017571,6.043346,4.220225,12.812649,372.716220,0.349321
min,132539.000000,15.000000,-1.000000,-1.000000,1.000000,-1.000000,-1.000000,-1.000000,-23.000000,0.000000
25%,140100.750000,53.000000,0.000000,-1.000000,2.000000,11.000000,3.000000,6.000000,-1.000000,0.000000
50%,147739.000000,67.000000,1.000000,152.400000,3.000000,15.000000,6.000000,10.000000,-1.000000,0.000000
75%,155309.750000,78.000000,1.000000,170.200000,4.000000,18.000000,9.000000,16.000000,19.000000,0.000000
max,163037.000000,90.000000,1.000000,462.300000,4.000000,38.000000,22.000000,295.000000,2664.000000,1.000000

# missing value and outlier - patient demographic data

In [20]:
df_patient['Gender'].value_counts(dropna=False)

Gender
 1.0    6727
 0.0    5261
-1.0      12
Name: count, dtype: int64

In [21]:
df_patient['ICUType'].value_counts(dropna=False)

ICUType
3.0    4293
4.0    3408
2.0    2530
1.0    1769
Name: count, dtype: int64

In [22]:
df_patient['SAPS-I'].value_counts(dropna=False)

SAPS-I
 16    856
 15    848
 14    809
 18    774
 17    752
 13    746
 12    731
 19    674
 11    619
 10    607
 20    592
-1     518
 9     506
 21    473
 8     395
 22    366
 7     292
 23    272
 6     243
 24    213
 5     169
 25    115
 4      99
 26     82
 27     61
 28     51
 3      48
 2      27
 29     21
 30     16
 32      7
 33      6
 1       6
 31      3
 34      1
 0       1
 38      1
Name: count, dtype: int64

In [23]:
df_patient['SOFA'].value_counts(dropna=False)

SOFA
 8     1094
 7     1082
 1     1009
 6      942
 9      914
 5      897
 2      894
 4      807
 3      765
 10     733
 11     617
 12     502
-1      403
 13     383
 0      365
 14     247
 15     142
 16      81
 17      48
 18      36
 20      13
 22      11
 19      10
 21       5
Name: count, dtype: int64

In [24]:
df_patient[df_patient['Gender'] < 0].shape

(12, 10)

In [25]:
df_patient[df_patient['SAPS-I'] < 0].shape

(518, 10)

In [26]:
df_patient[df_patient['SOFA'] < 0].shape

(403, 10)

In [27]:
df_patient.loc[df_patient['Gender'] < 0, 'Gender'] = np.nan

In [28]:
df_patient.loc[df_patient['SAPS-I'] < 0, 'SAPS-I'] = np.nan

In [29]:
df_patient.loc[df_patient['SOFA'] < 0, 'SOFA'] = np.nan

In [30]:
df_patient[df_patient['Age'] < 0].shape

(0, 10)

In [31]:
df_patient[df_patient['Age'] > 130].shape

(0, 10)

In [32]:
df_patient[df_patient['Height'] < 90].shape

(5743, 10)

In [33]:
df_patient.loc[df_patient['Height'] < 10, 'Height'] = np.nan

In [34]:
df_patient[df_patient['Height'] > 250].shape

(11, 10)

In [35]:
df_patient.loc[df_patient['Height'] > 300, 'Height'] = np.nan

In [36]:
print(df_patient[df_patient['Length_of_stay'] == -1].shape)
print(df_patient[df_patient['Length_of_stay'] == 0].shape)
print(df_patient[df_patient['Length_of_stay'] == 1].shape)

(167, 10)
(0, 10)
(5, 10)

In [37]:
df_patient.loc[df_patient['Length_of_stay'] < 2, 'Length_of_stay'] = np.nan

In [38]:
print(df_patient[df_patient['Survival'] < -1].shape)
print(df_patient[df_patient['Survival'] == -1].shape)
print(df_patient[df_patient['Survival'] == 0].shape)
print(df_patient[df_patient['Survival'] == 1].shape)

(1, 10)
(7410, 10)
(6, 10)
(85, 10)

In [39]:
df_patient.loc[df_patient['Survival'] < -1, 'Survival'] = np.nan
df_patient.loc[df_patient['Survival'] == 0, 'Survival'] = np.nan
df_patient.loc[df_patient['Survival'] == 1, 'Survival'] = np.nan

In [40]:
icu_dummies = pd.get_dummies(df_patient['ICUType'], prefix='ICUType')
df_patient = pd.concat([df_patient, icu_dummies], axis=1)
df_patient.drop('ICUType', axis=1, inplace=True)

In [41]:
df_patient.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   RecordID           12000 non-null  int64
 1   Age                12000 non-null  float64
 2   Gender             11988 non-null  float64
 3   Height             6261 non-null   float64
 4   SAPS-I             11482 non-null  float64
 5   SOFA               11597 non-null  float64
 6   Length_of_stay     11828 non-null  float64
 7   Survival           11908 non-null  float64
 8   In-hospital_death  12000 non-null  int64
 9   ICUType_1.0        12000 non-null  bool
 10  ICUType_2.0        12000 non-null  bool
 11  ICUType_3.0        12000 non-null  bool
 12  ICUType_4.0        12000 non-null  bool
dtypes: bool(4), float64(7), int64(2)
memory usage: 890.8 KB

In [42]:
df_patient.describe()

,RecordID,Age,Gender,Height,SAPS-I,SOFA,Length_of_stay,Survival,In-hospital_death
count,12000.000000,12000.000000,11988.000000,6261.000000,11482.000000,11597.000000,11828.000000,11908.000000,12000.000000
mean,147744.694750,64.529333,0.561144,169.146782,14.999565,6.663275,13.629016,134.961958,0.142250
std,8787.621488,17.175677,0.496268,13.298488,5.207572,4.056709,12.786962,373.968472,0.349321
min,132539.000000,15.000000,0.000000,12.700000,0.000000,0.000000,2.000000,-1.000000,0.000000
25%,140100.750000,53.000000,0.000000,162.600000,11.000000,3.000000,6.000000,-1.000000,0.000000
50%,147739.000000,67.000000,1.000000,170.200000,15.000000,7.000000,10.000000,-1.000000,0.000000
75%,155309.750000,78.000000,1.000000,177.800000,19.000000,9.000000,17.000000,20.000000,0.000000
max,163037.000000,90.000000,1.000000,210.800000,38.000000,22.000000,295.000000,2664.000000,1.000000

# icu data time format

In [43]:
dfs_a1 = []
dfs_b1 = []
dfs_c1 = []

In [44]:
def string_to_datetime(time_string):
  if ':' not in time_string:
    raise ValueError('Invalid time format.')

  try:
    hour_string, minute_string = time_string.split(':')
    hour = int(hour_string)
    minute = int(minute_string)
    duration = timedelta(hours=hour, minutes=minute)
    total_minute = int(duration.total_seconds() / 60)
    return total_minute
  except ValueError as e:
    print(f'Could not parse {time_string}.')
    print(f'Error: {e}')
    return None

In [45]:
def time_data_processor(dfs_list1, dfs_list2):
  for i in range(len(dfs_list1)):
    df_temp = dfs_list1[i].sort_values(['Parameter', 'Time']).reset_index(drop=True)
    df_temp['Time_Minute'] = df_temp['Time'].apply(string_to_datetime)
    df_temp_col = ['RecordID', 'Parameter', 'Value', 'Time', 'Time_Minute']
    df_temp = df_temp[df_temp_col]
    dfs_list2.append(df_temp)
  return dfs_list2

In [46]:
dfs_a1 = time_data_processor(dfs_a, dfs_a1)
dfs_b1 = time_data_processor(dfs_b, dfs_b1)
dfs_c1 = time_data_processor(dfs_c, dfs_c1)
dfs = dfs_a1+dfs_b1+dfs_c1
print(len(dfs_a1))
print(len(dfs_b1))
print(len(dfs_c1))
print(len(dfs))

4000
4000
4000
12000

# missing value and outlier - icu data

## missing value

In [47]:
col_icu = ['Albumin', 'ALP', 'ALT', 'AST', 'Bilirubin', 'BUN', 'Cholesterol', 'Creatinine', 'DiasABP', 'FiO2', 'GCS', 'Glucose', 'HCO3', 'HCT', 'HR', 'K', 'Lactate', 'Mg', 'MAP', 'MechVent', 'Na', 'NIDiasABP', 'NIMAP', 'NISysABP', 'PaCO2', 'PaO2', 'pH', 'Platelets', 'RespRate', 'SaO2', 'SysABP', 'Temp', 'TroponinI', 'TroponinT', 'Urine', 'WBC', 'Weight']

In [48]:
dfs_clean = []
index_clean = []

def missing_cleaner(df, i):
  if df['Parameter'].isna().sum() != 0:
    dfs_clean.append(df.dropna(subset=['Parameter']))
    index_clean.append(i)
  else:
    dfs_clean.append(df)

In [49]:
for i in range(len(dfs)):
  missing_cleaner(dfs[i], i)

In [50]:
index_clean[0:10]

[8003, 8006, 8007, 8008, 8013, 8014, 8015, 8016, 8019, 8021]

In [51]:
dfs[8000].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 675 entries, 0 to 674
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   RecordID     675 non-null    object
 1   Parameter    675 non-null    object
 2   Value        675 non-null    float64
 3   Time         675 non-null    object
 4   Time_Minute  675 non-null    int64
dtypes: float64(1), int64(1), object(3)
memory usage: 26.5+ KB

In [52]:
dfs_clean[8000].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 675 entries, 0 to 674
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   RecordID     675 non-null    object
 1   Parameter    675 non-null    object
 2   Value        675 non-null    float64
 3   Time         675 non-null    object
 4   Time_Minute  675 non-null    int64
dtypes: float64(1), int64(1), object(3)
memory usage: 26.5+ KB

## outlier

In [53]:
def outlier_detector(df, value_dict):

  df_result = []

  for i in range(len(value_dict)):
    col = value_dict[i]['col']
    value_lower = value_dict[i]['value_lower']
    value_upper = value_dict[i]['value_upper']
    df_temp = df[df['Parameter']==col].reset_index(drop=True)
    for j in range(df_temp.shape[0]):
      if df_temp['Value'][j] > value_upper or df_temp['Value'][j] < value_lower:
        df_result.append(df_temp.loc[j,:].T.to_dict())

  return df_result

In [54]:
value_dict_icu = [
    {'col': 'Albumin', 'value_lower': 0.5, 'value_upper': 7.0},
    {'col': 'ALP', 'value_lower': 5, 'value_upper': 5000},
    {'col': 'ALT', 'value_lower': 0, 'value_upper': 20000},
    {'col': 'AST', 'value_lower': 0, 'value_upper': 20000},
    {'col': 'Bilirubin', 'value_lower': 0.1, 'value_upper': 100.0},
    {'col': 'BUN', 'value_lower': 2, 'value_upper': 300},
    {'col': 'Cholesterol', 'value_lower': 10, 'value_upper': 800},
    {'col': 'Creatinine', 'value_lower': 0, 'value_upper': 30.0},
    {'col': 'DiasABP', 'value_lower': 15, 'value_upper': 150},
    {'col': 'FiO2', 'value_lower': 0.21, 'value_upper': 1.0},
    {'col': 'GCS', 'value_lower': 3, 'value_upper': 15},
    {'col': 'Glucose', 'value_lower': 20, 'value_upper': 1500},
    {'col': 'HCO3', 'value_lower': 5, 'value_upper': 60},
    {'col': 'HCT', 'value_lower': 10, 'value_upper': 70},
    {'col': 'HR', 'value_lower': 20, 'value_upper': 300},
    {'col': 'K', 'value_lower': 1.5, 'value_upper': 10.0},
    {'col': 'Lactate', 'value_lower': 0.1, 'value_upper': 35.0},
    {'col': 'MAP', 'value_lower': 10, 'value_upper': 170},
    {'col': 'MechVent', 'value_lower': 0, 'value_upper': 1},
    {'col': 'Mg', 'value_lower': 0.3, 'value_upper': 6.0},
    {'col': 'Na', 'value_lower': 100, 'value_upper': 170},
    {'col': 'NIDiasABP', 'value_lower': 15, 'value_upper': 150},
    {'col': 'NIMAP', 'value_lower': 20, 'value_upper': 170},
    {'col': 'NISysABP', 'value_lower': 40, 'value_upper': 250},
    {'col': 'PaCO2', 'value_lower': 10, 'value_upper': 100},
    {'col': 'PaO2', 'value_lower': 20, 'value_upper': 700},
    {'col': 'pH', 'value_lower': 6.8, 'value_upper': 7.8},
    {'col': 'Platelets', 'value_lower': 10, 'value_upper': 1500},
    {'col': 'RespRate', 'value_lower': 5, 'value_upper': 60},
    {'col': 'SaO2', 'value_lower': 50, 'value_upper': 100},
    {'col': 'SysABP', 'value_lower': 40, 'value_upper': 250},
    {'col': 'Temp', 'value_lower': 25.0, 'value_upper': 42.5},
    {'col': 'TroponinI', 'value_lower': 0, 'value_upper': 50},
    {'col': 'TroponinT', 'value_lower': 0, 'value_upper': 50},
    {'col': 'Urine', 'value_lower': 0, 'value_upper': 20000},
    {'col': 'WBC', 'value_lower': 0.5, 'value_upper': 800},
    {'col': 'Weight', 'value_lower': 20, 'value_upper': 500}]

In [55]:
value_dict_normal = [
    {'col': 'Albumin', 'value_lower': 3.5, 'value_upper': 5.0},
    {'col': 'ALP', 'value_lower': 44, 'value_upper': 147},
    {'col': 'ALT', 'value_lower': 7, 'value_upper': 56},
    {'col': 'AST', 'value_lower': 5, 'value_upper': 40},
    {'col': 'Bilirubin', 'value_lower': 0.2, 'value_upper': 1.2},
    {'col': 'BUN', 'value_lower': 6, 'value_upper': 20},
    {'col': 'Cholesterol', 'value_lower': 200, 'value_upper': 200},
    {'col': 'Creatinine', 'value_lower': 0.5, 'value_upper': 1.2},
    {'col': 'DiasABP', 'value_lower': 80, 'value_upper': 80},
    {'col': 'FiO2', 'value_lower': 0.21, 'value_upper': 0.21},
    {'col': 'GCS', 'value_lower': 3, 'value_upper': 15},
    {'col': 'Glucose', 'value_lower': 70, 'value_upper': 99},
    {'col': 'HCO3', 'value_lower': 22, 'value_upper': 29},
    {'col': 'HCT', 'value_lower': 37, 'value_upper': 54},
    {'col': 'HR', 'value_lower': 60, 'value_upper': 100},
    {'col': 'K', 'value_lower': 3.5, 'value_upper': 5.0},
    {'col': 'Lactate', 'value_lower': 0.5, 'value_upper': 1.0},
    {'col': 'MAP', 'value_lower': 70, 'value_upper': 120},
    {'col': 'MechVent', 'value_lower': 0, 'value_upper': 0},
    {'col': 'Mg', 'value_lower': 0.70, 'value_upper': 1.10},
    {'col': 'Na', 'value_lower': 135, 'value_upper': 145},
    {'col': 'NIDiasABP', 'value_lower': 80, 'value_upper': 80},
    {'col': 'NIMAP', 'value_lower': 70, 'value_upper': 120},
    {'col': 'NISysABP', 'value_lower': 120, 'value_upper': 120},
    {'col': 'PaCO2', 'value_lower': 35, 'value_upper': 45},
    {'col': 'PaO2', 'value_lower': 80, 'value_upper': 100},
    {'col': 'pH', 'value_lower': 7.35, 'value_upper': 7.45},
    {'col': 'Platelets', 'value_lower': 150, 'value_upper': 450},
    {'col': 'RespRate', 'value_lower': 12, 'value_upper': 20},
    {'col': 'SaO2', 'value_lower': 95, 'value_upper': 100},
    {'col': 'SysABP', 'value_lower': 120, 'value_upper': 120},
    {'col': 'Temp', 'value_lower': 36.5, 'value_upper': 37.5},
    {'col': 'TroponinI', 'value_lower': 0, 'value_upper': 0.01},
    {'col': 'TroponinT', 'value_lower': 0, 'value_upper': 0.01},
    {'col': 'Urine', 'value_lower': 500, 'value_upper': 2000},
    {'col': 'WBC', 'value_lower': 4.5, 'value_upper': 11.0},
    {'col': 'Weight', 'value_lower': 50, 'value_upper': 60}]

In [56]:
healthy_baselines = {
    'Albumin': 4.0,
    'ALP': 75.0,
    'ALT': 25.0,
    'AST': 25.0,
    'Bilirubin': 0.7,
    'BUN': 15.0,
    'Cholesterol': 150.0,
    'Creatinine': 1.0,
    'DiasABP': 70.0,
    'FiO2': 0.21,
    'GCS': 15.0,
    'Glucose': 90.0,
    'HCO3': 24.0,
    'HCT': 40.0,
    'HR': 75.0,
    'K': 4.0,
    'Lactate': 1.0,
    'Mg': 2.0,
    'MAP': 85.0,
    'Na': 140.0,
    'NIDiasABP': 70.0,
    'NIMAP': 85.0,
    'NISysABP': 120.0,
    'PaCO2': 40.0,
    'PaO2': 90.0,
    'pH': 7.4,
    'Platelets': 250.0,
    'RespRate': 16.0,
    'SaO2': 98.0,
    'SysABP': 120.0,
    'Temp': 37.0,
    'TroponinI': 0.01,
    'TroponinT': 0.01,
    'Urine': 50.0,
    'WBC': 7.0,
    'Weight': 80.0}

In [57]:
df_outlier_combine = []

for i in range(len(dfs_clean)):
  df_outlier_temp = outlier_detector(dfs_clean[i], value_dict_icu)
  if len(df_outlier_temp) != 0:
    df_outlier_combine.append(df_outlier_temp)


df_outlier = [item for sublist in df_outlier_combine for item in sublist]
df_outlier = pd.DataFrame(df_outlier, columns = ['RecordID', 'Parameter', 'Value', 'Time', 'Time_Minute'])
df_outlier.shape

(9020, 5)

In [58]:
def outlier_to_missing(df, value_dict):
  df_new = copy.deepcopy(df)
  for i in range(len(value_dict)):
    col = value_dict[i]['col']
    value_lower = value_dict[i]['value_lower']
    value_upper = value_dict[i]['value_upper']
    if len(df_new[df_new['Parameter'] == col]) == 0:
      pass
    else:
      cond_1 = df_new['Parameter'] == col
      cond_2 = df_new['Value'] < value_lower
      cond_3 = df_new['Value'] > value_upper
      df_new.loc[cond_1 & cond_2, 'Value'] = np.nan
      df_new.loc[cond_1 & cond_3, 'Value'] = np.nan
  return df_new

In [59]:
dfs_nan = []

for i in range(len(dfs_clean)):
  dfs_nan.append(outlier_to_missing(dfs_clean[i], value_dict_icu))

In [60]:
count = 0
index_nan = []

for i in range(len(dfs_nan)):
    count += dfs_nan[i].isnull().sum().sum()
    if dfs_nan[i].isnull().sum().sum() != 0:
      index_nan.append(i)
print(count)

9020

In [61]:
index_nan[0:10]

[7, 9, 17, 20, 27, 28, 39, 40, 41, 42]

In [62]:
dfs_nan[3]['Value']

0       11.00
1       13.00
2       20.00
3        0.60
4        0.70
5        1.10
6       58.00
7       58.00
8       52.00
9       56.00
10      67.00
11      66.00
12      55.00
13      67.00
14      48.00
15      59.00
16      59.00
17      58.00
18      61.00
19      66.00
20      69.00
21      68.00
22      63.00
23      69.00
24      64.00
25      64.00
26      65.00
27      60.00
28      57.00
29      60.00
30      61.00
31      66.00
32      60.00
33      56.00
34       1.00
35       0.50
36       0.50
37       0.50
38       3.00
39       7.00
40      15.00
41      15.00
42      15.00
43      15.00
44      15.00
45     118.00
46     125.00
47      27.00
48      28.00
49      29.00
50      28.90
51      30.20
52      31.90
53      27.40
54      60.00
55      61.00
56      72.00
57      72.00
58      72.00
59      72.00
60      89.00
61      87.00
62      85.00
63      79.00
64      79.00
65      79.00
66      79.00
67      79.00
68      76.00
69      76.00
70      79.00
71      78.00
72      79.00
73      79.00
74      79.00
75      79.00
76      79.00
77      79.00
78      79.00
79      79.00
80      79.00
81      79.00
82      79.00
83      74.00
84      90.00
85      90.00
86      90.00
87      87.00
88      90.00
89       4.30
90       4.20
91      75.00
92      80.00
93      67.00
94      72.00
95      86.00
96      86.00
97      68.00
98      86.00
99      61.00
100     76.00
101     74.00
102     74.00
103     76.00
104     83.00
105     87.00
106     86.00
107     79.00
108     89.00
109     79.00
110     81.00
111     82.00
112     76.00
113     74.00
114     75.00
115     75.00
116     82.00
117     74.00
118     70.00
119      1.00
120      1.00
121      1.00
122      1.00
123      1.00
124      1.00
125      2.20
126     42.00
127     49.00
128     61.00
129     55.00
130     62.00
131     59.00
132     55.00
133     55.67
134     62.67
135     83.00
136     69.33
137     72.67
138     74.33
139     72.00
140     83.00
141     90.00
142    127.00
143     98.00
144     94.00
145    105.00
146    106.00
147    137.00
148    136.00
149     35.00
150     42.00
151     49.00
152     44.00
153     49.00
154     46.00
155     53.00
156     47.00
157    484.00
158    336.00
159    284.00
160    334.00
161    134.00
162    161.00
163    108.00
164    118.00
165     67.00
166     81.00
167    123.00
168     72.00
169     98.00
170     99.00
171     97.00
172     97.00
173    107.00
174    118.00
175     96.00
176    104.00
177    126.00
178    126.00
179     95.00
180    117.00
181     88.00
182    102.00
183     99.00
184    102.00
185    100.00
186    108.00
187    116.00
188    118.00
189    105.00
190    123.00
191    114.00
192    115.00
193    118.00
194    108.00
195    107.00
196    111.00
197    109.00
198    122.00
199    108.00
200    101.00
201     36.50
202     36.40
203     36.20
204     36.00
205     35.90
206     36.00
207     36.20
208     36.40
209     36.60
210     36.80
211     37.20
212     37.50
213     37.70
214     37.80
215     37.80
216     37.70
217     37.60
218     37.60
219     37.70
220     37.60
221     37.50
222     37.60
223     37.40
224     37.40
225     37.50
226    750.00
227    230.00
228    190.00
229    500.00
230    400.00
231    120.00
232     50.00
233     60.00
234     50.00
235     50.00
236     35.00
237     50.00
238     40.00
239     30.00
240     25.00
241     25.00
242     32.00
243    100.00
244     25.00
245     35.00
246     50.00
247      7.40
248      9.40
249     14.80
250     10.00
251     75.11
252     75.00
253     75.00
254     75.00
255     75.00
256     75.00
257     75.00
258     75.00
259     75.00
260     75.00
261     75.00
262     75.00
263     75.00
264     75.00
265     75.00
266     75.00
267     75.00
268     75.00
269     75.00
270     75.00
271     80.00
272     80.00
273     80.00
274     80.00
275     80.00
276     80.00
277     80.00
278     80.00
279     80.00
280     80.00
281     80.00
282     80.00
283     80.00
284     80.00
285     80.00
286     80.00
287      7.52
288      7.45
289      7.39
290      7.42
291      7.35
292      7.34
293      7.35
294      7.40
Name: Value, dtype: float64

In [63]:
def nan_filler(df, col):
  dfs_processed = []

  for i in col:
    df_temp = copy.deepcopy(df[df['Parameter'] == i])
    if len(df_temp) == 0:
      continue
    elif len(df_temp) == 1:
      dfs_processed.append(df_temp)
    else:
      df_temp_fill = df_temp.ffill()
      dfs_processed.append(df_temp_fill)

  df_fillna = pd.concat(dfs_processed, ignore_index=True)
  return df_fillna.reset_index(drop=True)

In [64]:
dfs_nan[6].isnull().sum()

RecordID       0
Parameter      0
Value          0
Time           0
Time_Minute    0
dtype: int64

In [65]:
df = nan_filler(dfs_nan[6], col_icu)
df.isnull().sum()

RecordID       0
Parameter      0
Value          0
Time           0
Time_Minute    0
dtype: int64

In [66]:
dfs_filled = []

for i in range(len(dfs_nan)):
    dfs_filled.append(nan_filler(dfs_nan[i], col_icu))

print(len(dfs_filled))

12000

In [67]:
count = 0

for i in range(len(dfs_filled)):
    count += dfs_filled[i].isnull().sum().sum()

print(count)

4334

In [68]:
dfs_filled[8].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 436 entries, 0 to 435
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   RecordID     436 non-null    object
 1   Parameter    436 non-null    object
 2   Value        436 non-null    float64
 3   Time         436 non-null    object
 4   Time_Minute  436 non-null    int64
dtypes: float64(1), int64(1), object(3)
memory usage: 17.2+ KB

# data frame

In [69]:
df_temp = dfs_filled[2]
df_temp

    RecordID   Parameter    Value   Time  Time_Minute
0     141985         BUN     9.00  13:39          819
1     141985         BUN    12.00  21:56         1316
2     141985         BUN     8.00  36:03         2163
3     141985  Creatinine     0.60  13:39          819
4     141985  Creatinine     0.60  21:56         1316
5     141985  Creatinine     0.40  36:03         2163
6     141985     DiasABP    56.00  29:11         1751
7     141985     DiasABP    54.00  29:26         1766
8     141985     DiasABP    54.00  30:26         1826
9     141985     DiasABP    61.00  31:26         1886
10    141985     DiasABP    51.00  32:26         1946
11    141985     DiasABP    52.00  33:26         2006
12    141985     DiasABP    59.00  34:26         2066
13    141985     DiasABP    50.00  35:26         2126
14    141985     DiasABP    52.00  36:26         2186
15    141985     DiasABP    48.00  37:26         2246
16    141985     DiasABP    50.00  38:26         2306
17    141985     DiasABP    54.00  39:26         2366
18    141985     DiasABP    53.00  40:26         2426
19    141985     DiasABP    53.00  41:26         2486
20    141985     DiasABP    54.00  42:26         2546
21    141985     DiasABP    50.00  43:26         2606
22    141985     DiasABP    48.00  44:26         2666
23    141985     DiasABP    44.00  45:26         2726
24    141985     DiasABP    45.00  46:26         2786
25    141985     DiasABP    50.00  47:26         2846
26    141985         GCS    15.00  00:11           11
27    141985         GCS    15.00  03:26          206
28    141985         GCS    15.00  07:26          446
29    141985         GCS    15.00  12:26          746
30    141985         GCS    15.00  16:11          971
31    141985         GCS    15.00  29:26         1766
32    141985         GCS    15.00  33:26         2006
33    141985         GCS    15.00  37:26         2246
34    141985         GCS    15.00  39:26         2366
35    141985         GCS    15.00  43:26         2606
36    141985         GCS    15.00  47:26         2846
37    141985     Glucose   105.00  13:39          819
38    141985     Glucose   115.00  21:56         1316
39    141985     Glucose   154.00  36:03         2163
40    141985        HCO3    28.00  13:39          819
41    141985        HCO3    25.00  21:56         1316
42    141985        HCO3    24.00  36:03         2163
43    141985         HCT    32.20  13:39          819
44    141985         HCT    28.50  21:56         1316
45    141985         HCT    27.10  36:03         2163
46    141985         HCT    32.50  43:44         2624
47    141985          HR    86.00  00:11           11
48    141985          HR    83.00  00:26           26
49    141985          HR    84.00  01:26           86
50    141985          HR    89.00  02:26          146
51    141985          HR    92.00  03:26          206
52    141985          HR    91.00  04:26          266
53    141985          HR    93.00  05:26          326
54    141985          HR    90.00  06:26          386
55    141985          HR    85.00  07:26          446
56    141985          HR    82.00  08:26          506
57    141985          HR    80.00  09:26          566
58    141985          HR    78.00  10:26          626
59    141985          HR    78.00  11:26          686
60    141985          HR    79.00  12:26          746
61    141985          HR    83.00  13:26          806
62    141985          HR    82.00  14:26          866
63    141985          HR    86.00  16:11          971
64    141985          HR    84.00  16:26          986
65    141985          HR    85.00  16:41         1001
66    141985          HR    82.00  17:26         1046
67    141985          HR    79.00  18:26         1106
68    141985          HR   103.00  29:11         1751
69    141985          HR   101.00  29:26         1766
70    141985          HR   107.00  30:26         1826
71    141985          HR   111.00  31:26         1886
72    141985          HR   107.00  32:26         1946
73    141985          HR   101.00  33:26         2006
74    141985          HR    99.00  34:26         2066
75    141985          HR    96.00  35:26         2126
76    141985          HR    95.00  36:26         2186
77    141985          HR    95.00  37:26         2246
78    141985          HR    92.00  38:26         2306
79    141985          HR    93.00  39:26         2366
80    141985          HR    90.00  40:26         2426
81    141985          HR    96.00  41:26         2486
82    141985          HR    89.00  42:26         2546
83    141985          HR    84.00  43:26         2606
84    141985          HR    83.00  44:26         2666
85    141985          HR    83.00  45:26         2726
86    141985          HR    82.00  46:26         2786
87    141985          HR    78.00  47:26         2846
88    141985           K     3.30  13:39          819
89    141985           K     3.70  21:56         1316
90    141985           K     3.40  36:03         2163
91    141985           K     3.50  43:44         2624
92    141985     Lactate     0.80  20:36         1236
93    141985     Lactate     0.70  22:04         1324
94    141985     Lactate     0.60  35:40         2140
95    141985          Mg     1.30  21:56         1316
96    141985          Mg     1.40  36:03         2163
97    141985          Mg     2.10  43:44         2624
98    141985         MAP    73.00  29:11         1751
99    141985         MAP    71.00  29:26         1766
100   141985         MAP    71.00  30:26         1826
101   141985         MAP    76.00  31:26         1886
102   141985         MAP    63.00  32:26         1946
103   141985         MAP    67.00  33:26         2006
104   141985         MAP    78.00  34:26         2066
105   141985         MAP    70.00  35:26         2126
106   141985         MAP    74.00  36:26         2186
107   141985         MAP    66.00  37:26         2246
108   141985         MAP    69.00  38:26         2306
109   141985         MAP    78.00  39:26         2366
110   141985         MAP    76.00  40:26         2426
111   141985         MAP    75.00  41:26         2486
112   141985         MAP    77.00  42:26         2546
113   141985         MAP    72.00  43:26         2606
114   141985         MAP    65.00  44:26         2666
115   141985         MAP    61.00  45:26         2726
116   141985         MAP    60.00  46:26         2786
117   141985         MAP    73.00  47:26         2846
118   141985          Na   133.00  13:39          819
119   141985          Na   134.00  21:56         1316
120   141985          Na   132.00  36:03         2163
121   141985   NIDiasABP    55.00  00:11           11
122   141985   NIDiasABP    52.00  00:26           26
123   141985   NIDiasABP    62.00  01:26           86
124   141985   NIDiasABP    56.00  02:26          146
125   141985   NIDiasABP    53.00  03:26          206
126   141985   NIDiasABP    41.00  04:26          266
127   141985   NIDiasABP    41.00  05:26          326
128   141985   NIDiasABP    46.00  06:26          386
129   141985   NIDiasABP    45.00  07:26          446
130   141985   NIDiasABP    53.00  08:26          506
131   141985   NIDiasABP    51.00  09:26          566
132   141985   NIDiasABP    53.00  10:26          626
133   141985   NIDiasABP    48.00  11:26          686
134   141985   NIDiasABP    51.00  12:26          746
135   141985   NIDiasABP    41.00  13:26          806
136   141985   NIDiasABP    47.00  14:26          866
137   141985   NIDiasABP    56.00  16:11          971
138   141985   NIDiasABP    50.00  16:26          986
139   141985   NIDiasABP    55.00  16:41         1001
140   141985   NIDiasABP    59.00  17:26         1046
141   141985   NIDiasABP    53.00  18:26         1106
142   141985   NIDiasABP    56.00  29:26         1766
143   141985   NIDiasABP    54.00  30:26         1826
144   141985   NIDiasABP    52.00  31:26         1886
145   141985   NIDiasABP    45.00  32:26         1946
146   141985   NIDiasABP    57.00  33:26         2006
147   141985   NIDiasABP    32.00  34:26         2066
148   141985   NIDiasABP    45.00  35:26         2126
149   141985   NIDiasABP    52.00  36:26         2186
150   141985   NIDiasABP    41.00  37:26         2246
151   141985   NIDiasABP    50.00  38:26         2306
152   141985   NIDiasABP    27.00  39:26         2366
153   141985   NIDiasABP    52.00  40:26         2426
154   141985   NIDiasABP    48.00  41:26         2486
155   141985   NIDiasABP    43.00  42:26         2546
156   141985   NIDiasABP    47.00  43:26         2606
157   141985   NIDiasABP    47.00  44:26         2666
158   141985   NIDiasABP    75.00  45:26         2726
159   141985   NIDiasABP    40.00  46:26         2786
160   141985   NIDiasABP    39.00  47:26         2846
161   141985       NIMAP    80.33  00:11           11
162   141985       NIMAP    73.00  00:26           26
163   141985       NIMAP    83.33  01:26           86
164   141985       NIMAP    79.00  02:26          146
165   141985       NIMAP    72.33  03:26          206
166   141985       NIMAP    62.00  04:26          266
167   141985       NIMAP    63.00  05:26          326
168   141985       NIMAP    65.00  06:26          386
169   141985       NIMAP    62.33  07:26          446
170   141985       NIMAP    75.00  08:26          506
171   141985       NIMAP    76.00  09:26          566
172   141985       NIMAP    69.67  10:26          626
173   141985       NIMAP    70.00  11:26          686
174   141985       NIMAP    74.67  12:26          746
175   141985       NIMAP    65.00  13:26          806
176   141985       NIMAP    64.33  14:26          866
177   141985       NIMAP    72.33  16:11          971
178   141985       NIMAP    64.33  16:26          986
179   141985       NIMAP    70.67  16:41         1001
180   141985       NIMAP    77.33  17:26         1046
181   141985       NIMAP    70.67  18:26         1106
182   141985       NIMAP    71.33  29:26         1766
183   141985       NIMAP    70.33  30:26         1826
184   141985       NIMAP    73.33  31:26         1886
185   141985       NIMAP    65.33  32:26         1946
186   141985       NIMAP    75.67  33:26         2006
187   141985       NIMAP    56.67  34:26         2066
188   141985       NIMAP    66.67  35:26         2126
189   141985       NIMAP    73.67  36:26         2186
190   141985       NIMAP    63.00  37:26         2246
191   141985       NIMAP    72.00  38:26         2306
192   141985       NIMAP    60.67  39:26         2366
193   141985       NIMAP    76.67  40:26         2426
194   141985       NIMAP    74.33  41:26         2486
195   141985       NIMAP    68.33  42:26         2546
196   141985       NIMAP    71.00  43:26         2606
197   141985       NIMAP    69.67  44:26         2666
198   141985       NIMAP    82.67  45:26         2726
199   141985       NIMAP    58.00  46:26         2786
200   141985       NIMAP    63.00  47:26         2846
201   141985    NISysABP   131.00  00:11           11
202   141985    NISysABP   115.00  00:26           26
203   141985    NISysABP   126.00  01:26           86
204   141985    NISysABP   125.00  02:26          146
205   141985    NISysABP   111.00  03:26          206
206   141985    NISysABP   104.00  04:26          266
207   141985    NISysABP   107.00  05:26          326
208   141985    NISysABP   103.00  06:26          386
209   141985    NISysABP    97.00  07:26          446
210   141985    NISysABP   119.00  08:26          506
211   141985    NISysABP   126.00  09:26          566
212   141985    NISysABP   103.00  10:26          626
213   141985    NISysABP   114.00  11:26          686
214   141985    NISysABP   122.00  12:26          746
215   141985    NISysABP   113.00  13:26          806
216   141985    NISysABP    99.00  14:26          866
217   141985    NISysABP   105.00  16:11          971
218   141985    NISysABP    93.00  16:26          986
219   141985    NISysABP   102.00  16:41         1001
220   141985    NISysABP   114.00  17:26         1046
221   141985    NISysABP   106.00  18:26         1106
222   141985    NISysABP   102.00  29:26         1766
223   141985    NISysABP   103.00  30:26         1826
224   141985    NISysABP   116.00  31:26         1886
225   141985    NISysABP   106.00  32:26         1946
226   141985    NISysABP   113.00  33:26         2006
227   141985    NISysABP   106.00  34:26         2066
228   141985    NISysABP   110.00  35:26         2126
229   141985    NISysABP   117.00  36:26         2186
230   141985    NISysABP   107.00  37:26         2246
231   141985    NISysABP   116.00  38:26         2306
232   141985    NISysABP   128.00  39:26         2366
233   141985    NISysABP   126.00  40:26         2426
234   141985    NISysABP   127.00  41:26         2486
235   141985    NISysABP   119.00  42:26         2546
236   141985    NISysABP   119.00  43:26         2606
237   141985    NISysABP   115.00  44:26         2666
238   141985    NISysABP    98.00  45:26         2726
239   141985    NISysABP    94.00  46:26         2786
240   141985    NISysABP   111.00  47:26         2846
241   141985       PaCO2    41.00  20:36         1236
242   141985       PaCO2    51.00  22:04         1324
243   141985       PaCO2    39.00  25:12         1512
244   141985       PaCO2    40.00  35:17         2117
245   141985       PaCO2    41.00  35:40         2140
246   141985        PaO2   267.00  20:36         1236
247   141985        PaO2   215.00  22:04         1324
248   141985        PaO2   104.00  25:12         1512
249   141985        PaO2    95.00  35:17         2117
250   141985        PaO2    97.00  35:40         2140
251   141985          pH     7.43  20:36         1236
252   141985          pH     7.35  22:04         1324
253   141985          pH     7.39  25:12         1512
254   141985          pH     7.39  35:17         2117
255   141985          pH     7.43  35:40         2140
256   141985   Platelets   346.00  13:39          819
257   141985   Platelets   400.00  21:56         1316
258   141985   Platelets   290.00  36:03         2163
259   141985        SaO2    97.00  25:12         1512
260   141985        SaO2    96.00  35:17         2117
261   141985      SysABP   102.00  29:11         1751
262   141985      SysABP   102.00  29:26         1766
263   141985      SysABP   102.00  30:26         1826
264   141985      SysABP   100.00  31:26         1886
265   141985      SysABP    80.00  32:26         1946
266   141985      SysABP    89.00  33:26         2006
267   141985      SysABP   110.00  34:26         2066
268   141985      SysABP   104.00  35:26         2126
269   141985      SysABP   111.00  36:26         2186
270   141985      SysABP    94.00  37:26         2246
271   141985      SysABP    96.00  38:26         2306
272   141985      SysABP   115.00  39:26         2366
273   141985      SysABP   115.00  40:26         2426
274   141985      SysABP   110.00  41:26         2486
275   141985      SysABP   118.00  42:26         2546
276   141985      SysABP   109.00  43:26         2606
277   141985      SysABP    94.00  44:26         2666
278   141985      SysABP    88.00  45:26         2726
279   141985      SysABP    90.00  46:26         2786
280   141985      SysABP   117.00  47:26         2846
281   141985        Temp    36.60  00:11           11
282   141985        Temp    37.30  03:26          206
283   141985        Temp    37.20  07:26          446
284   141985        Temp    36.50  08:26          506
285   141985        Temp    37.20  11:26          686
286   141985        Temp    36.60  17:26         1046
287   141985        Temp    35.60  29:26         1766
288   141985        Temp    38.20  33:26         2006
289   141985        Temp    37.20  35:26         2126
290   141985        Temp    37.30  36:26         2186
291   141985        Temp    37.30  39:26         2366
292   141985        Temp    37.00  44:26         2666
293   141985   TroponinI     0.30  21:56         1316
294   141985       Urine  1700.00  00:11           11
295   141985       Urine   220.00  03:26          206
296   141985       Urine   100.00  04:26          266
297   141985       Urine    80.00  05:26          326
298   141985       Urine    50.00  06:26          386
299   141985       Urine    50.00  07:26          446
300   141985       Urine   140.00  08:26          506
301   141985       Urine   400.00  09:26          566
302   141985       Urine   400.00  10:26          626
303   141985       Urine   400.00  11:26          686
304   141985       Urine   250.00  12:26          746
305   141985       Urine   300.00  13:26          806
306   141985       Urine   200.00  14:26          866
307   141985       Urine   200.00  16:11          971
308   141985       Urine    30.00  16:41         1001
309   141985       Urine    80.00  17:26         1046
310   141985       Urine    45.00  18:26         1106
311   141985       Urine    75.00  30:26         1826
312   141985       Urine    75.00  31:26         1886
313   141985       Urine    50.00  32:26         1946
314   141985       Urine    50.00  33:26         2006
315   141985       Urine   160.00  34:26         2066
316   141985       Urine    60.00  35:26         2126
317   141985       Urine    70.00  36:26         2186
318   141985       Urine    60.00  37:26         2246
319   141985       Urine   690.00  39:26         2366
320   141985       Urine   195.00  40:26         2426
321   141985       Urine   245.00  41:26         2486
322   141985       Urine   180.00  42:26         2546
323   141985       Urine   215.00  43:26         2606
324   141985       Urine   170.00  44:26         2666
325   141985       Urine   100.00  46:26         2786
326   141985       Urine   100.00  47:26         2846
327   141985         WBC     9.90  13:39          819
328   141985         WBC    13.50  21:56         1316
329   141985         WBC    10.60  36:03         2163
330   141985      Weight    75.00  00:00            0
331   141985      Weight    75.00  12:26          746
332   141985      Weight    75.00  13:26          806
333   141985      Weight    75.00  14:26          866
334   141985      Weight    75.00  16:11          971
335   141985      Weight    75.00  16:26          986
336   141985      Weight    75.00  16:41         1001
337   141985      Weight    75.00  17:26         1046
338   141985      Weight    75.00  18:26         1106
339   141985      Weight    75.00  29:11         1751
340   141985      Weight    75.00  29:26         1766
341   141985      Weight    75.00  30:26         1826
342   141985      Weight    75.00  31:26         1886
343   141985      Weight    75.00  32:26         1946
344   141985      Weight    75.00  33:26         2006
345   141985      Weight    75.00  34:26         2066
346   141985      Weight    75.00  35:26         2126
347   141985      Weight    75.00  36:26         2186
348   141985      Weight    75.00  37:26         2246
349   141985      Weight    75.00  38:26         2306
350   141985      Weight    75.00  39:26         2366
351   141985      Weight    75.00  40:26         2426
352   141985      Weight    75.00  41:26         2486
353   141985      Weight    75.00  42:26         2546
354   141985      Weight    75.00  43:26         2606
355   141985      Weight    75.00  44:26         2666
356   141985      Weight    75.00  45:26         2726
357   141985      Weight    75.00  46:26         2786
358   141985      Weight    75.00  47:26         2846

# helper function

In [70]:
df_sub = df_temp[df_temp['Parameter'] == 'DiasABP'].reset_index(drop=True)
df_sub

   RecordID Parameter  Value   Time  Time_Minute
0    141985   DiasABP   56.0  29:11         1751
1    141985   DiasABP   54.0  29:26         1766
2    141985   DiasABP   54.0  30:26         1826
3    141985   DiasABP   61.0  31:26         1886
4    141985   DiasABP   51.0  32:26         1946
5    141985   DiasABP   52.0  33:26         2006
6    141985   DiasABP   59.0  34:26         2066
7    141985   DiasABP   50.0  35:26         2126
8    141985   DiasABP   52.0  36:26         2186
9    141985   DiasABP   48.0  37:26         2246
10   141985   DiasABP   50.0  38:26         2306
11   141985   DiasABP   54.0  39:26         2366
12   141985   DiasABP   53.0  40:26         2426
13   141985   DiasABP   53.0  41:26         2486
14   141985   DiasABP   54.0  42:26         2546
15   141985   DiasABP   50.0  43:26         2606
16   141985   DiasABP   48.0  44:26         2666
17   141985   DiasABP   44.0  45:26         2726
18   141985   DiasABP   45.0  46:26         2786
19   141985   DiasABP   50.0  47:26         2846

In [71]:
def find_max_duration(df_data, threshold, condition_type='above'):

  if condition_type.lower() not in ['above', 'below']:
    raise ValueError('condition_type must be "above" or "below".')

  max_duration = 0
  max_begin = -1
  max_end = -1

  current_duration = 0
  current_begin = -1

  for i, value in enumerate(df_data['Value']):

    is_condition_met = False
    if condition_type.lower() == 'above':
      is_condition_met = (value >= threshold)
    elif condition_type.lower() == 'below':
      is_condition_met = (value <= threshold)

    if is_condition_met:
      if current_duration == 0:
        current_begin = i
      current_duration += 1
    else:
      if current_duration > max_duration:
        max_duration = current_duration
        max_begin = current_begin
        max_end = i - 1

      current_duration = 0
      current_begin = -1

  if current_duration > max_duration:
    max_duration = current_duration
    max_begin = current_begin
    max_end = len(df_data['Value']) - 1

  return max_duration, max_begin, max_end

In [72]:
threshold = 80
condition_type = 'below'
max_duration, max_begin, max_end = find_max_duration(df_sub, threshold, condition_type)
print(max_duration, max_begin, max_end)

20 0 19

In [73]:
def find_time_duration(df_data, max_begin, max_end):
  time_begin = df_data['Time_Minute'].iloc[max_begin]
  time_end = df_data['Time_Minute'].iloc[max_end]
  time_duration = time_end - time_begin
  return time_duration, time_begin, time_end

In [74]:
time_duration, time_begin, time_end = find_time_duration(df_sub, max_begin, max_end)
print(time_duration, time_begin, time_end)

1095 1751 2846

In [75]:
df_sub = df_temp[df_temp['Parameter'] == 'BUN'].reset_index(drop=True)
df_sub

  RecordID Parameter  Value   Time  Time_Minute
0   141985       BUN    9.0  13:39          819
1   141985       BUN   12.0  21:56         1316
2   141985       BUN    8.0  36:03         2163

In [76]:
df_sub2 = df_temp[df_temp['Parameter'] == 'Creatinine'].reset_index(drop=True)
df_sub2

  RecordID   Parameter  Value   Time  Time_Minute
0   141985  Creatinine    0.6  13:39          819
1   141985  Creatinine    0.6  21:56         1316
2   141985  Creatinine    0.4  36:03         2163

In [77]:
def find_max_bcr(df_sub, df_sub2):

  if len(df_sub2) == 0:
    return np.nan
  elif len(df_sub2) == 1:
    if df_sub2.isnull().sum().sum() != 0:
      return np.nan
    else:
      if df_sub2['Value'].iloc[0] == 0:
        return np.nan
      bcr = df_sub['Value'].iloc[0]/df_sub2['Value'].iloc[0]
      return bcr
  else:

    def aggregator(series):
      if (series == 0).any():
        return series.max()
      else:
        return series.mean()
    bun_series = df_sub.groupby('Time_Minute').agg({'Time_Minute': 'min', 'Value': aggregator}).set_index('Time_Minute').sort_index()
    cr_series = df_sub2.groupby('Time_Minute').agg({'Time_Minute': 'min', 'Value': aggregator}).set_index('Time_Minute').sort_index()

    combined_index = bun_series.index.union(cr_series.index)

    bun_aligned = bun_series.reindex(combined_index)
    cr_aligned = cr_series.reindex(combined_index)

    bun_imputed = bun_aligned.ffill()
    cr_imputed = cr_aligned.ffill()

    bun_imputed = bun_imputed.bfill()
    cr_imputed = cr_imputed.bfill()

    bcr_ratio_series = pd.Series(np.where(cr_imputed['Value'] == 0, np.nan, bun_imputed['Value']/cr_imputed['Value']))
    bcr = bcr_ratio_series.max()
    return bcr

In [78]:
find_max_bcr(df_sub, df_sub2)

np.float64(20.0)

In [79]:
df_temp = dfs_filled[0]

In [80]:
df_sub = df_temp[df_temp['Parameter'] == 'Lactate'].reset_index(drop=True)
df_sub

  RecordID Parameter  Value   Time  Time_Minute
0   137188   Lactate    1.5  07:35          455
1   137188   Lactate    1.5  09:33          573
2   137188   Lactate    1.8  15:08          908
3   137188   Lactate    1.4  22:18         1338
4   137188   Lactate    1.4  35:50         2150
5   137188   Lactate    1.4  46:43         2803

In [81]:
def find_lcr(df_sub, hour):
  TIME_INITIAL = df_sub['Time_Minute'].iloc[0]
  TARGET_TIME = hour*60

  initial_value = df_sub['Value'].iloc[0]


  if initial_value == 0:
    lcr = np.nan
  elif len(df_sub['Time_Minute'][df_sub['Time_Minute'] > TARGET_TIME]) == 0:
    lcr = np.nan
  else:
    target_index = df_sub['Time_Minute'][df_sub['Time_Minute'] > TARGET_TIME].idxmin()
    final_value = df_sub.loc[target_index]['Value']
    lcr = (initial_value-final_value)/initial_value*100

  return lcr

In [82]:
find_lcr(df_sub, 6)

np.float64(0.0)

In [83]:
find_lcr(df_sub, 12)

np.float64(-20.000000000000004)

In [84]:
df_sub = df_temp[df_temp['Parameter'] == 'PaO2'].reset_index(drop=True)
df_sub

  RecordID Parameter  Value   Time  Time_Minute
0   137188      PaO2  187.0  08:33          513
1   137188      PaO2  142.0  14:08          848
2   137188      PaO2  111.0  21:18         1278
3   137188      PaO2  115.0  26:49         1609
4   137188      PaO2   73.0  34:50         2090
5   137188      PaO2  160.0  36:46         2206
6   137188      PaO2  137.0  45:43         2743

In [85]:
df_sub2 = df_temp[df_temp['Parameter'] == 'FiO2'].reset_index(drop=True)
df_sub2

   RecordID Parameter  Value   Time  Time_Minute
0    137188      FiO2    1.0  02:04          124
1    137188      FiO2    1.0  05:47          347
2    137188      FiO2    0.8  08:34          514
3    137188      FiO2    0.8  11:43          703
4    137188      FiO2    0.7  14:29          869
5    137188      FiO2    0.7  18:44         1124
6    137188      FiO2    0.7  20:09         1209
7    137188      FiO2    0.7  23:10         1390
8    137188      FiO2    0.7  27:29         1649
9    137188      FiO2    0.6  28:29         1709
10   137188      FiO2    0.6  30:29         1829
11   137188      FiO2    0.6  33:29         2009
12   137188      FiO2    0.6  35:29         2129
13   137188      FiO2    0.5  36:59         2219
14   137188      FiO2    0.5  38:29         2309
15   137188      FiO2    0.5  42:29         2549
16   137188      FiO2    0.4  46:14         2774
17   137188      FiO2    0.4  46:59         2819

In [86]:
def find_min_pfr(df_sub, df_sub2):

  if len(df_sub2) == 0:
    return np.nan
  elif len(df_sub2) == 1:
    if df_sub2.isnull().sum().sum() != 0:
      return np.nan
    else:
      if df_sub2['Value'].iloc[0] == 0:
        return np.nan
      pfr = df_sub['Value'].iloc[0]/df_sub2['Value'].iloc[0]
      return pfr
  else:

    def aggregator(series):
      if (series == 0).any():
        return series.max()
      else:
        return series.mean()

    pao2_series = df_sub.groupby('Time_Minute').agg({'Time_Minute': 'min', 'Value': aggregator}).set_index('Time_Minute').sort_index()
    fio2_series = df_sub2.groupby('Time_Minute').agg({'Time_Minute': 'min', 'Value': aggregator}).set_index('Time_Minute').sort_index()

    combined_index = pao2_series.index.union(fio2_series.index)

    pao2_aligned = pao2_series.reindex(combined_index)
    fio2_aligned = fio2_series.reindex(combined_index)

    pao2_imputed = pao2_aligned.ffill()
    fio2_imputed = fio2_aligned.ffill()

    pao2_imputed = pao2_imputed.bfill()
    fio2_imputed = fio2_imputed.bfill()

    pfr_ratio_series = pd.Series(np.where(fio2_imputed['Value'] == 0, np.nan, pao2_imputed['Value']/fio2_imputed['Value']))
    pfr = pfr_ratio_series.min()

    return pfr

In [87]:
find_min_pfr(df_sub, df_sub2)

np.float64(121.66666666666667)

In [88]:
df_sub = df_temp[df_temp['Parameter'] == 'Urine'].reset_index(drop=True)
df_sub

   RecordID Parameter  Value   Time  Time_Minute
0    137188     Urine  200.0  02:14          134
1    137188     Urine  380.0  04:29          269
2    137188     Urine  225.0  05:29          329
3    137188     Urine  150.0  06:29          389
4    137188     Urine  125.0  08:29          509
5    137188     Urine  100.0  10:29          629
6    137188     Urine   80.0  12:29          749
7    137188     Urine   75.0  14:29          869
8    137188     Urine  175.0  16:29          989
9    137188     Urine  125.0  17:29         1049
10   137188     Urine  100.0  18:29         1109
11   137188     Urine  135.0  19:29         1169
12   137188     Urine   65.0  20:29         1229
13   137188     Urine   40.0  21:29         1289
14   137188     Urine   41.0  22:29         1349
15   137188     Urine   75.0  24:29         1469
16   137188     Urine   27.0  25:29         1529
17   137188     Urine   30.0  26:29         1589
18   137188     Urine   28.0  27:29         1649
19   137188     Urine   10.0  28:29         1709
20   137188     Urine   12.0  29:29         1769
21   137188     Urine   33.0  30:29         1829
22   137188     Urine   20.0  31:29         1889
23   137188     Urine   40.0  32:29         1949
24   137188     Urine   40.0  34:29         2069
25   137188     Urine   17.0  35:29         2129
26   137188     Urine   20.0  36:29         2189
27   137188     Urine   70.0  38:29         2309
28   137188     Urine   35.0  39:29         2369
29   137188     Urine   40.0  40:29         2429
30   137188     Urine   65.0  42:29         2549
31   137188     Urine   35.0  43:29         2609
32   137188     Urine   30.0  44:29         2669
33   137188     Urine   80.0  45:29         2729
34   137188     Urine   20.0  46:29         2789
35   137188     Urine   20.0  47:29         2849

In [89]:
df_sub2 = df_temp[df_temp['Parameter'] == 'Weight'].reset_index(drop=True)
df_sub2

   RecordID Parameter  Value   Time  Time_Minute
0    137188    Weight   59.6  00:00            0
1    137188    Weight   59.6  02:14          134
2    137188    Weight   59.6  02:29          149
3    137188    Weight   59.6  02:44          164
4    137188    Weight   59.6  02:59          179
5    137188    Weight   59.6  03:14          194
6    137188    Weight   59.6  03:29          209
7    137188    Weight   59.6  03:59          239
8    137188    Weight   59.6  04:29          269
9    137188    Weight   59.6  05:29          329
10   137188    Weight   59.6  06:29          389
11   137188    Weight   59.6  07:29          449
12   137188    Weight   59.6  08:29          509
13   137188    Weight   59.6  09:29          569
14   137188    Weight   59.6  10:29          629
15   137188    Weight   59.6  11:29          689
16   137188    Weight   59.6  12:29          749
17   137188    Weight   59.6  13:29          809
18   137188    Weight   59.6  14:29          869
19   137188    Weight   59.6  15:29          929
20   137188    Weight   59.6  15:59          959
21   137188    Weight   59.6  16:14          974
22   137188    Weight   59.6  16:29          989
23   137188    Weight   59.6  16:44         1004
24   137188    Weight   59.6  17:29         1049
25   137188    Weight   59.6  17:59         1079
26   137188    Weight   59.6  18:29         1109
27   137188    Weight   59.6  18:59         1139
28   137188    Weight   59.6  19:29         1169
29   137188    Weight   59.6  19:44         1184
30   137188    Weight   59.6  19:54         1194
31   137188    Weight   59.6  19:59         1199
32   137188    Weight   59.6  20:29         1229
33   137188    Weight   59.6  21:29         1289
34   137188    Weight   59.6  22:29         1349
35   137188    Weight   59.6  22:44         1364
36   137188    Weight   59.6  23:29         1409
37   137188    Weight   59.6  25:29         1529
38   137188    Weight   59.6  26:29         1589
39   137188    Weight   59.6  27:29         1649
40   137188    Weight   59.6  28:29         1709
41   137188    Weight   59.6  29:29         1769
42   137188    Weight   59.6  29:44         1784
43   137188    Weight   59.6  29:59         1799
44   137188    Weight   59.6  30:29         1829
45   137188    Weight   59.6  31:29         1889
46   137188    Weight   59.6  32:29         1949
47   137188    Weight   59.6  33:29         2009
48   137188    Weight   59.6  34:29         2069
49   137188    Weight   59.6  35:29         2129
50   137188    Weight   59.6  36:29         2189
51   137188    Weight   59.6  37:29         2249
52   137188    Weight   59.6  38:29         2309
53   137188    Weight   59.6  39:29         2369
54   137188    Weight   59.6  40:29         2429
55   137188    Weight   59.6  41:59         2519
56   137188    Weight   59.6  42:29         2549
57   137188    Weight   59.6  42:59         2579
58   137188    Weight   59.6  43:29         2609
59   137188    Weight   59.6  44:29         2669
60   137188    Weight   59.6  44:59         2699
61   137188    Weight   59.6  45:29         2729
62   137188    Weight   59.6  46:29         2789
63   137188    Weight   59.6  46:59         2819
64   137188    Weight   59.6  47:29         2849

In [90]:
def compute_urine_rate_slope(df_sub):

    if len(df_sub) < 2:
        return 0.0

    df_sub = df_sub.sort_values('Time_Minute').reset_index(drop=True)

    times_hrs = df_sub['Time_Minute'].values / 60.0
    volumes = df_sub['Value'].values
    time_deltas = np.diff(times_hrs, prepend=0)
    time_deltas = np.where(time_deltas == 0, 0.016, time_deltas)
    rates = volumes / time_deltas
    slope, intercept, r_val, p_val, std_err = linregress(times_hrs, rates)

    return slope

In [91]:
compute_urine_rate_slope(df_sub)

np.float64(-2.3801396449976764)

In [92]:
def find_uminr(df_sub, df_sub2):
  TIME_STABILITY_THRESHOLD = 0.1

  if len(df_sub2) == 0:
    weight_mean = np.nan
    return np.nan
  elif len(df_sub2) == 1:
    if df_sub2.isnull().sum().sum() != 0:
      weight_mean = np.nan
      return np.nan
    else:
      weight_mean = df_sub2['Value'].iloc[0]
  else:
    weight_mean = df_sub2['Value'].mean()

  urine_delta = df_sub.groupby('Time_Minute')['Value'].max()
  time_delta = df_sub.groupby('Time_Minute')['Time_Minute'].max().diff()/60
  umr_series = pd.Series(np.where((time_delta > TIME_STABILITY_THRESHOLD) & (weight_mean > 0), urine_delta/(weight_mean*time_delta), np.nan))
  uminr = umr_series.min()
  return uminr

In [93]:
find_uminr(df_sub, df_sub2)

np.float64(0.16778523489932884)

In [94]:
def find_umaxr(df_sub, df_sub2):
  TIME_STABILITY_THRESHOLD = 0.1

  if len(df_sub2) == 0:
    weight_mean = np.nan
    return np.nan
  elif len(df_sub2) == 1:
    if df_sub2.isnull().sum().sum() != 0:
      weight_mean = np.nan
      return np.nan
    else:
      weight_mean = df_sub2['Value'].iloc[0]
  else:
    weight_mean = df_sub2['Value'].mean()

  urine_delta = df_sub.groupby('Time_Minute')['Value'].max()
  time_delta = df_sub.groupby('Time_Minute')['Time_Minute'].max().diff()/60
  umr_series = pd.Series(np.where((time_delta > TIME_STABILITY_THRESHOLD) & (weight_mean > 0), urine_delta/(weight_mean*time_delta), np.nan))
  umaxr = umr_series.max()
  return umaxr

In [95]:
find_umaxr(df_sub, df_sub2)

np.float64(3.7751677852348986)

In [96]:
def find_umeanr(df_sub, df_sub2):
  TIME_STABILITY_THRESHOLD = 0.1

  if len(df_sub2) == 0:
    weight_mean = np.nan
    return np.nan
  elif len(df_sub2) == 1:
    if df_sub2.isnull().sum().sum() != 0:
      weight_mean = np.nan
      return np.nan
    else:
      weight_mean = df_sub2['Value'].iloc[0]
  else:
    weight_mean = df_sub2['Value'].mean()

  urine_delta = df_sub.groupby('Time_Minute')['Value'].max()
  time_delta = df_sub.groupby('Time_Minute')['Time_Minute'].max().diff()/60
  umr_series = pd.Series(np.where((time_delta > TIME_STABILITY_THRESHOLD) & (weight_mean > 0), urine_delta/(weight_mean*time_delta), np.nan))
  umeanr = umr_series.mean()
  return umeanr

In [97]:
find_umeanr(df_sub, df_sub2)

np.float64(0.9345104932353255)

In [98]:
df_temp = dfs_filled[3]

In [99]:
df_sub = df_temp[df_temp['Parameter'] == 'DiasABP'].reset_index(drop=True)
df_sub

   RecordID Parameter  Value   Time  Time_Minute
0    136263   DiasABP   58.0  03:11          191
1    136263   DiasABP   58.0  03:26          206
2    136263   DiasABP   52.0  03:41          221
3    136263   DiasABP   56.0  03:56          236
4    136263   DiasABP   67.0  04:11          251
5    136263   DiasABP   66.0  04:26          266
6    136263   DiasABP   55.0  05:11          311
7    136263   DiasABP   67.0  05:41          341
8    136263   DiasABP   48.0  06:11          371
9    136263   DiasABP   59.0  06:41          401
10   136263   DiasABP   59.0  07:11          431
11   136263   DiasABP   58.0  07:41          461
12   136263   DiasABP   61.0  08:11          491
13   136263   DiasABP   66.0  09:11          551
14   136263   DiasABP   69.0  10:11          611
15   136263   DiasABP   68.0  11:11          671
16   136263   DiasABP   63.0  12:11          731
17   136263   DiasABP   69.0  13:11          791
18   136263   DiasABP   64.0  14:11          851
19   136263   DiasABP   64.0  15:11          911
20   136263   DiasABP   65.0  16:11          971
21   136263   DiasABP   60.0  17:11         1031
22   136263   DiasABP   57.0  18:11         1091
23   136263   DiasABP   60.0  19:11         1151
24   136263   DiasABP   61.0  20:11         1211
25   136263   DiasABP   66.0  21:11         1271
26   136263   DiasABP   60.0  22:11         1331
27   136263   DiasABP   56.0  23:11         1391

In [100]:
df_sub2 = df_temp[df_temp['Parameter'] == 'NIDiasABP'].reset_index(drop=True)
df_sub2

  RecordID  Parameter  Value   Time  Time_Minute
0   136263  NIDiasABP   42.0  24:11         1451
1   136263  NIDiasABP   49.0  24:21         1461
2   136263  NIDiasABP   61.0  45:01         2701
3   136263  NIDiasABP   55.0  45:11         2711
4   136263  NIDiasABP   62.0  46:11         2771
5   136263  NIDiasABP   59.0  46:41         2801
6   136263  NIDiasABP   55.0  47:11         2831

In [101]:
def minutes_to_time_string(total_minutes):

  if pd.isna(total_minutes) or total_minutes is None or total_minutes < 0:
    return np.nan

  duration = timedelta(minutes=int(total_minutes))
  total_seconds = duration.total_seconds()
  total_hours = math.floor(total_seconds / 3600)
  remaining_seconds = total_seconds % 3600
  minutes = math.floor(remaining_seconds / 60)
  time_string = f"{int(total_hours):02d}:{int(minutes):02d}"

  return time_string

In [102]:
def find_uniabp(df_sub, df_sub2):

  i_series = df_sub.groupby('Time_Minute').agg({'Time_Minute': 'min', 'Value': 'min'}).set_index('Time_Minute').sort_index()
  ni_series = df_sub2.groupby('Time_Minute').agg({'Time_Minute': 'min', 'Value': 'min'}).set_index('Time_Minute').sort_index()

  match_index = i_series.index.intersection(ni_series.index)

  if len(match_index) == 0:
    delta = 0
  else:
    i_series_match = i_series.reindex(match_index)
    ni_series_match = ni_series.reindex(match_index)
    delta = 0

  uni_index = i_series.index.union(ni_series.index)

  uni_series_preindex = i_series.reindex(uni_index).fillna(ni_series)
  uni_series = uni_series_preindex.reset_index()
  df_uni = uni_series.rename(columns = {'index':'Time_Minute', 'value':'Value'})

  recordid_series = pd.Series(data=np.repeat(df_sub['RecordID'][0], len(df_uni)), name='RecordID').reset_index(drop=True)
  parameter_series = pd.Series(data=np.repeat('Uni'+df_sub['Parameter'][0], len(df_uni)), name='Parameter').reset_index(drop=True)
  value_series = round(df_uni['Value'], 2)
  time_minute_series = df_uni['Time_Minute']
  time_series = time_minute_series.apply(minutes_to_time_string)
  df_result = pd.concat([recordid_series, parameter_series, value_series, time_series, time_minute_series], axis=1)
  df_result.columns = ['RecordID', 'Parameter', 'Value', 'Time', 'Time_Minute']

  return df_result

In [103]:
def find_unidf(df_sub, df_sub2):
  if (len(df_sub) == 0) and (len(df_sub2) == 0):
    columns_list = ['RecordID', 'Parameter', 'Value', 'Time', 'Time_Minute']
    df_result = pd.DataFrame(columns=columns_list)
  elif len(df_sub) == 0:
    df_sub2['Parameter'] = 'Uni'+ df_sub2['Parameter'].str.replace('^NI', '', regex=True)
    df_result = df_sub2
  elif len(df_sub2) == 0:
    df_sub['Parameter'] = 'Uni'+df_sub['Parameter']
    df_result = df_sub
  else:
    df_result = find_uniabp(df_sub, df_sub2)

  return df_result

In [104]:
find_unidf(df_sub, df_sub2)

   RecordID   Parameter  Value   Time  Time_Minute
0    136263  UniDiasABP   58.0  03:11          191
1    136263  UniDiasABP   58.0  03:26          206
2    136263  UniDiasABP   52.0  03:41          221
3    136263  UniDiasABP   56.0  03:56          236
4    136263  UniDiasABP   67.0  04:11          251
5    136263  UniDiasABP   66.0  04:26          266
6    136263  UniDiasABP   55.0  05:11          311
7    136263  UniDiasABP   67.0  05:41          341
8    136263  UniDiasABP   48.0  06:11          371
9    136263  UniDiasABP   59.0  06:41          401
10   136263  UniDiasABP   59.0  07:11          431
11   136263  UniDiasABP   58.0  07:41          461
12   136263  UniDiasABP   61.0  08:11          491
13   136263  UniDiasABP   66.0  09:11          551
14   136263  UniDiasABP   69.0  10:11          611
15   136263  UniDiasABP   68.0  11:11          671
16   136263  UniDiasABP   63.0  12:11          731
17   136263  UniDiasABP   69.0  13:11          791
18   136263  UniDiasABP   64.0  14:11          851
19   136263  UniDiasABP   64.0  15:11          911
20   136263  UniDiasABP   65.0  16:11          971
21   136263  UniDiasABP   60.0  17:11         1031
22   136263  UniDiasABP   57.0  18:11         1091
23   136263  UniDiasABP   60.0  19:11         1151
24   136263  UniDiasABP   61.0  20:11         1211
25   136263  UniDiasABP   66.0  21:11         1271
26   136263  UniDiasABP   60.0  22:11         1331
27   136263  UniDiasABP   56.0  23:11         1391
28   136263  UniDiasABP   42.0  24:11         1451
29   136263  UniDiasABP   49.0  24:21         1461
30   136263  UniDiasABP   61.0  45:01         2701
31   136263  UniDiasABP   55.0  45:11         2711
32   136263  UniDiasABP   62.0  46:11         2771
33   136263  UniDiasABP   59.0  46:41         2801
34   136263  UniDiasABP   55.0  47:11         2831

In [105]:
def mad_stats(df1, df2):
  combined_index = df1.index.union(df2.index)

  df1_imputed = df1.reindex(combined_index).ffill().bfill()
  df2_imputed = df2.reindex(combined_index).ffill().bfill()

  mad = (df1_imputed['Value'] - df2_imputed['Value']).abs().mean()

  return mad

In [106]:
mad_stats(df_sub, df_sub2)

np.float64(7.357142857142857)

In [107]:
def find_mad(df1, df2):
  if (len(df1) == 0) and (len(df2) == 0):
    return 0
  elif len(df1) < 2:
    return 0
  elif len(df2) < 2:
    return 0
  else:
    return mad_stats(df1, df2)

In [108]:
find_mad(df_sub, df_sub2)

np.float64(7.357142857142857)

In [109]:
df_temp = dfs_filled[4]

In [110]:
df_sub = df_temp[df_temp['Parameter'] == 'Albumin'].reset_index(drop=True)
df_sub

Empty DataFrame
Columns: [RecordID, Parameter, Value, Time, Time_Minute]
Index: []

In [111]:
def compute_end_to_end_slope(df_sun):

  clean_data = df_sub.dropna(subset=['Value'])

  if len(clean_data) < 2:
    return 0.0

  v_initial = clean_data['Value'].iloc[0]
  v_final = clean_data['Value'].iloc[-1]

  t_initial = clean_data['Time_Minute'].iloc[0]
  t_final = clean_data['Time_Minute'].iloc[-1]
  t_diff = t_final - t_initial

  if t_diff == 0.0:
    return 0.0
  else:
    slope = (v_final - v_initial)/t_diff
    return slope

In [112]:
compute_end_to_end_slope(df_sub)

0.0

In [113]:
def compute_regression_slope(df_sub):
  clean_data = df_sub.dropna(subset=['Value'])

  if len(clean_data) < 2 or np.ptp(clean_data['Time_Minute']) == 0:
    return 0.0

  X = clean_data['Time_Minute'].values
  y = clean_data['Value'].values

  slope, intercept, r_value, p_value, std_err = linregress(X, y)
  return slope

In [114]:
df_sub = df_temp[df_temp['Parameter'] == 'GCS'].reset_index(drop=True)
df_sub

   RecordID Parameter  Value   Time  Time_Minute
0    141669       GCS   15.0  02:56          176
1    141669       GCS   15.0  05:56          356
2    141669       GCS   15.0  09:56          596
3    141669       GCS   15.0  13:56          836
4    141669       GCS   15.0  17:56         1076
5    141669       GCS   15.0  21:56         1316
6    141669       GCS   15.0  25:56         1556
7    141669       GCS   15.0  29:56         1796
8    141669       GCS   15.0  33:56         2036
9    141669       GCS   15.0  37:56         2276
10   141669       GCS   15.0  41:56         2516
11   141669       GCS   15.0  45:56         2756

In [115]:
compute_regression_slope(df_sub)

np.float64(0.0)

In [116]:
df_temp = dfs_filled[4]

In [117]:
df_sub = df_temp[df_temp['Parameter'] == 'TroponinI'].reset_index(drop=True)
df_sub

Empty DataFrame
Columns: [RecordID, Parameter, Value, Time, Time_Minute]
Index: []

In [118]:
df_sub2 = df_temp[df_temp['Parameter'] == 'TroponinT'].reset_index(drop=True)
df_sub2

Empty DataFrame
Columns: [RecordID, Parameter, Value, Time, Time_Minute]
Index: []

In [119]:
def combine_troponin(df_sub, df_sub2):
  i_series = df_sub.groupby('Time_Minute').agg({'Time_Minute': 'min', 'Value': 'max'}).set_index('Time_Minute').sort_index()
  t_series = df_sub2.groupby('Time_Minute').agg({'Time_Minute': 'min', 'Value': 'max'}).set_index('Time_Minute').sort_index()

  uni_index = i_series.index.union(t_series.index)

  uni_series_preindex = i_series.reindex(uni_index).fillna(t_series)
  uni_series = uni_series_preindex.reset_index()
  df_uni = uni_series.rename(columns = {'index':'Time_Minute', 'value':'Value'})

  recordid_series = pd.Series(data=np.repeat(df_sub['RecordID'][0], len(df_uni)), name='RecordID').reset_index(drop=True)
  parameter_series = pd.Series(data=np.repeat('Troponin', len(df_uni)), name='Parameter').reset_index(drop=True)
  value_series = df_uni['Value']
  time_minute_series = df_uni['Time_Minute']
  time_series = time_minute_series.apply(minutes_to_time_string)
  df_result = pd.concat([recordid_series, parameter_series, value_series, time_series, time_minute_series], axis=1)
  df_result.columns = ['RecordID', 'Parameter', 'Value', 'Time', 'Time_Minute']

  return df_result

In [120]:
def find_troponin(df_sub, df_sub2):
  if (len(df_sub) == 0) and (len(df_sub2) == 0):
    columns_list = ['RecordID', 'Parameter', 'Value', 'Time', 'Time_Minute']
    return pd.DataFrame(columns=columns_list)
  elif len(df_sub) == 0:
    df_sub2['Parameter'] = 'Troponin'
    return df_sub2
  elif len(df_sub2) == 0:
    df_sub['Parameter'] = 'Troponin'
    return df_sub
  else:
    df_result = combine_troponin(df_sub, df_sub2)
    return df_result

In [121]:
find_troponin(df_sub, df_sub2)

Empty DataFrame
Columns: [RecordID, Parameter, Value, Time, Time_Minute]
Index: []

# icu data column

In [122]:
col_stats = ['Albumin_Initial', 'Albumin_Min', 'Albumin_Max', 'Albumin_Mean', 'ALP_Initial', 'ALP_Max', 'ALT_Initial', 'ALT_Max', 'AST_Initial', 'AST_Max',
'Bilirubin_Initial', 'Bilirubin_Max', 'BUN_Initial', 'BUN_Max', 'BUN_Mean', 'BUN_Creatinine_Ratio', 'Cholesterol_Initial', 'Cholesterol_Min',
'Creatinine_Initial', 'Creatinine_Max', 'Creatinine_Mean', 'FiO2_Initial', 'FiO2_Max', 'FiO2_Mean',
'GCS_Initial', 'GCS_Final', 'GCS_Min', 'GCS_Max', 'GCS_Mean', 'Glucose_Initial', 'Glucose_Min', 'Glucose_Max', 'Glucose_Mean',
'HCO3_Initial', 'HCO3_Final', 'HCO3_Min', 'HCO3_Max', 'HCT_Initial', 'HCT_Min', 'HCT_Max', 'HCT_Mean',
'HR_Initial', 'HR_Final', 'HR_Min', 'HR_Max', 'HR_Mean', 'HR_SD', 'K_Initial', 'K_Final', 'K_Min', 'K_Max', 'K_Mean',
'Lactate_Initial', 'Lactate_Max', 'Lactate_Clearance_Rate_6H', 'Lactate_Clearance_Rate_12H', 'MechVent_Any',
'Mg_Initial', 'Mg_Min', 'Mg_Max', 'Na_Initial', 'Na_Final', 'Na_Min', 'Na_Max', 'Na_Mean',
'PaCO2_Initial', 'PaCO2_Min', 'PaCO2_Max', 'PaO2_Initial', 'PaO2_Min', 'PaO2_FiO2_Ratio',
'pH_Initial', 'pH_Min', 'pH_Max', 'pH_Mean', 'Platelets_Initial', 'Platelets_Min',
'RespRate_Initial', 'RespRate_Max', 'RespRate_Mean', 'SaO2_Initial', 'SaO2_Min',
'Temp_Initial', 'Temp_Min', 'Temp_Max', 'Temp_Mean', 'Temp_SD',
'Urine_Sum', 'Urine_MinRate', 'Urine_MaxRate', 'Urine_MeanRate',
'WBC_Initial', 'WBC_Min', 'WBC_Max', 'Weight_Initial', 'Weight_Final',
'UniDiasABP_Initial', 'UniDiasABP_Min', 'UniDiasABP_Max', 'UniDiasABP_Mean',
'UniMAP_Initial', 'UniMAP_Final', 'UniMAP_Min', 'UniMAP_Max', 'UniMAP_Mean', 'UniMAP_SD',
'UniSysABP_Initial', 'UniSysABP_Final', 'UniSysABP_Min', 'UniSysABP_Max', 'UniSysABP_Mean', 'UniSysABP_SD', 'Troponin_Max']

In [123]:
col_count = ['Albumin_Count', 'ALP_Count', 'ALT_Count', 'AST_Count', 'BUN_Count', 'Bilirubin_Count',
'Cholesterol_Count', 'Creatinine_Count', 'FiO2_Count', 'GCS_Count', 'Glucose_Count',
'HCO3_Count', 'HCT_Count', 'HR_Count', 'K_Count', 'Lactate_Count', 'MechVent_Count',
'Mg_Count', 'Na_Count', 'PaCO2_Count', 'PaO2_Count', 'pH_Count', 'Platelets_Count',
'RespRate_Count', 'SaO2_Count', 'Temp_Count', 'Urine_Count', 'WBC_Count',
'UniDiasABP_Count', 'UniMAP_Count', 'UniSysABP_Count', 'Troponin_Count']

In [124]:
col_delta = ['Albumin_Delta', 'ALP_Delta', 'ALT_Delta', 'AST_Delta', 'Bilirubin_Delta', 'BUN_Delta', 'Cholesterol_Delta', 'Creatinine_Delta',
'HCO3_Delta', 'HCT_Delta', 'K_Delta', 'Mg_Delta', 'Na_Delta', 'PaO2_Delta', 'Platelets_Delta', 'SaO2_Delta', 'WBC_Delta', 'Weight_Delta', 'Troponin_Delta']

In [125]:
col_slope = ['FiO2_Slope', 'GCS_Slope', 'Glucose_Slope', 'HR_Slope', 'PaCO2_Slope', 'pH_Slope', 'RespRate_Slope', 'Temp_Slope', 'Urine_Rate_Slope', 'UniDiasABP_Slope', 'UniMAP_Slope', 'UniSysABP_Slope']

In [126]:
col_miss = ['Albumin_Miss', 'ALP_Miss', 'ALT_Miss', 'AST_Miss', 'Bilirubin_Miss', 'BUN_Miss', 'Cholesterol_Miss', 'Creatinine_Miss',
'FiO2_Miss', 'GCS_Miss', 'Glucose_Miss', 'HCO3_Miss', 'HCT_Miss', 'HR_Miss', 'K_Miss', 'Lactate_Miss', 'MechVent_Miss', 'Mg_Miss', 'Na_Miss',
'PaCO2_Miss', 'PaO2_Miss', 'pH_Miss', 'Platelets_Miss', 'RespRate_Miss', 'SaO2_Miss', 'Temp_Miss', 'Urine_Miss', 'WBC_Miss', 'Weight_Miss',
'UniDiasABP_Miss', 'UniMAP_Miss', 'UniSysABP_Miss', 'Troponin_Miss']

In [127]:
col_last_minute = ['Albumin_Last_Minute', 'ALP_Last_Minute', 'ALT_Last_Minute', 'AST_Last_Minute', 'Bilirubin_Last_Minute', 'BUN_Last_Minute', 'Cholesterol_Last_Minute', 'Creatinine_Last_Minute',
'FiO2_Last_Minute', 'GCS_Last_Minute', 'Glucose_Last_Minute', 'HCO3_Last_Minute', 'HCT_Last_Minute', 'HR_Last_Minute', 'K_Last_Minute', 'Lactate_Last_Minute',
'MechVent_Last_Minute', 'Mg_Last_Minute', 'Na_Last_Minute', 'PaCO2_Last_Minute', 'PaO2_Last_Minute', 'pH_Last_Minute', 'Platelets_Last_Minute', 'RespRate_Last_Minute',
'SaO2_Last_Minute', 'Temp_Last_Minute', 'Urine_Last_Minute', 'WBC_Last_Minute', 'Weight_Last_Minute', 'UniDiasABP_Last_Minute', 'UniMAP_Last_Minute', 'UniSysABP_Last_Minute', 'Troponin_Last_Minute']

In [128]:
col_df = ['RecordID'] + col_stats + col_count + col_delta + col_slope + col_miss + col_last_minute

In [129]:
df_record = pd.DataFrame(columns=col_df)
df_record.loc[0] = np.nan
df_record['RecordID'] = df_temp['RecordID'].iloc[0]

In [130]:
df_record

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute
0,141669,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# icu data function

In [131]:
df_temp = dfs_filled[0]

In [132]:
df_sub = df_temp[df_temp['Parameter'] == 'Albumin'].reset_index(drop=True)
df_sub

  RecordID Parameter  Value   Time  Time_Minute
0   137188   Albumin    2.3  03:22          202
1   137188   Albumin    2.2  11:50          710
2   137188   Albumin    2.3  35:13         2113

In [133]:
# Albumin
# Albumin_Initial
# Albumin_Min
# Albumin_Max
# Albumin_Mean
# Albumin_Count
# Albumin_Delta
# Albumin_Miss
# Albumin_Last_Minute


def albumin_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_min = col+'_Min'
  col_max = col+'_Max'
  col_mean = col+'_Mean'
  col_count = col+'_Count'
  col_delta = col+'_Delta'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_min] = np.nan
    df_record[col_max] = np.nan
    df_record[col_mean] = np.nan
    df_record[col_count] = 0
    df_record[col_delta] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[ col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[ col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [134]:
albumin_stats(df_sub, df_record, 'Albumin')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [135]:
df_sub = df_temp[df_temp['Parameter'] == 'ALP'].reset_index(drop=True)
df_sub

  RecordID Parameter  Value   Time  Time_Minute
0   137188       ALP   84.0  03:22          202
1   137188       ALP   64.0  11:50          710
2   137188       ALP   55.0  35:13         2113

In [136]:
# ALP
# ALP_Initial
# ALP_Max
# ALP_Count
# ALP_Delta
# ALP_Miss
# ALP_Last_Minute


def alp_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_max = col+'_Max'
  col_count = col+'_Count'
  col_delta = col+'_Delta'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_max] = np.nan
    df_record[col_count] = 0
    df_record[col_delta] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_max] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_max] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [137]:
alp_stats(df_sub, df_record, 'ALP')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [138]:
df_sub = df_temp[df_temp['Parameter'] == 'ALT'].reset_index(drop=True)
df_sub

  RecordID Parameter  Value   Time  Time_Minute
0   137188       ALT   20.0  03:22          202
1   137188       ALT   18.0  11:50          710
2   137188       ALT   14.0  35:13         2113

In [139]:
# ALT
# ALT_Initial
# ALT_Max
# ALT_Count
# ALT_Delta
# ALT_Miss
# ALT_Last_Minute


def alt_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_max = col+'_Max'
  col_count = col+'_Count'
  col_delta = col+'_Delta'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_max] = np.nan
    df_record[col_count] = 0
    df_record[col_delta] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_max] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_max] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [140]:
alt_stats(df_sub, df_record, 'ALT')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [141]:
df_sub = df_temp[df_temp['Parameter'] == 'AST'].reset_index(drop=True)
df_sub

  RecordID Parameter  Value   Time  Time_Minute
0   137188       AST  123.0  03:22          202
1   137188       AST   97.0  11:50          710
2   137188       AST   70.0  35:13         2113

In [142]:
# AST
# AST_Initial
# AST_Max
# AST_Count
# AST_Delta
# AST_Miss
# AST_Last_Minute


def ast_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_max = col+'_Max'
  col_count = col+'_Count'
  col_delta = col+'_Delta'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_max] = np.nan
    df_record[col_count] = 0
    df_record[col_delta] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_max] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_max] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [143]:
ast_stats(df_sub, df_record, 'AST')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [144]:
df_sub = df_temp[df_temp['Parameter'] == 'Bilirubin'].reset_index(drop=True)
df_sub

  RecordID  Parameter  Value   Time  Time_Minute
0   137188  Bilirubin    6.6  03:22          202
1   137188  Bilirubin    7.6  11:50          710
2   137188  Bilirubin   11.2  35:13         2113

In [145]:
# Bilirubin
# Bilirubin_Initial
# Bilirubin_Max
# Bilirubin_Count
# Bilirubin_Delta
# Bilirubin_Miss
# Bilirubin_Last_Minute


def bilirubin_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_max = col+'_Max'
  col_count = col+'_Count'
  col_delta = col+'_Delta'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_max] = np.nan
    df_record[col_count] = 0
    df_record[col_delta] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_max] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_max] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [146]:
bilirubin_stats(df_sub, df_record, 'Bilirubin')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [147]:
df_sub = df_temp[df_temp['Parameter'] == 'BUN'].reset_index(drop=True)
df_sub

  RecordID Parameter  Value   Time  Time_Minute
0   137188       BUN    7.0  03:22          202
1   137188       BUN    5.0  11:50          710
2   137188       BUN    4.0  22:00         1320
3   137188       BUN    6.0  35:13         2113

In [148]:
df_sub2 = df_temp[df_temp['Parameter'] == 'Creatinine'].reset_index(drop=True)
df_sub2

  RecordID   Parameter  Value   Time  Time_Minute
0   137188  Creatinine    0.9  03:22          202
1   137188  Creatinine    0.7  11:50          710
2   137188  Creatinine    0.5  22:00         1320
3   137188  Creatinine    0.6  35:13         2113

In [149]:
# BUN
# BUN_Initial
# BUN_Max
# BUN_Mean
# BUN_Count
# BUN_Delta
# BUN_Miss
# BUN_Creatinine_Ratio - Max BUN/Creatinine Ratio
# BUN_Last_Minute


def bun_stats(df_sub, df_sub2, df_record, col):
  col_initial = col+'_Initial'
  col_max = col+'_Max'
  col_mean = col+'_Mean'
  col_count = col+'_Count'
  col_delta = col+'_Delta'
  col_miss = col+'_Miss'
  col_bcr = col+'_Creatinine_Ratio'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_max] = np.nan
    df_record[col_mean] = np.nan
    df_record[col_count] = 0
    df_record[col_delta] = 0
    df_record[col_miss] = 1
    df_record[col_bcr] = np.nan
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_bcr] = np.nan
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_bcr] = find_max_bcr(df_sub, df_sub2)
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_bcr] = np.nan
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_bcr] = find_max_bcr(df_sub, df_sub2)
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [150]:
bun_stats(df_sub, df_sub2, df_record, 'BUN')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [151]:
df_sub = df_temp[df_temp['Parameter'] == 'Cholesterol'].reset_index(drop=True)
df_sub

Empty DataFrame
Columns: [RecordID, Parameter, Value, Time, Time_Minute]
Index: []

In [152]:
# Cholesterol
# Cholesterol_Initial
# Cholesterol_Min
# Cholesterol_Count
# Cholesterol_Delta
# Cholesterol_Miss
# Cholesterol_Last_Minute


def cholesterol_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_min = col+'_Min'
  col_count = col+'_Count'
  col_delta = col+'_Delta'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_min] = np.nan
    df_record[col_count] = 0
    df_record[col_delta] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [153]:
cholesterol_stats(df_sub, df_record, 'Cholesterol')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [154]:
df_sub = df_temp[df_temp['Parameter'] == 'Creatinine'].reset_index(drop=True)
df_sub

  RecordID   Parameter  Value   Time  Time_Minute
0   137188  Creatinine    0.9  03:22          202
1   137188  Creatinine    0.7  11:50          710
2   137188  Creatinine    0.5  22:00         1320
3   137188  Creatinine    0.6  35:13         2113

In [155]:
# Creatinine
# Creatinine_Initial
# Creatinine_Max
# Creatinine_Mean
# Creatinine_Count
# Creatinine_Delta
# Creatinine_Miss
# Creatinine_Last_Minute


def creatinine_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_max = col+'_Max'
  col_mean = col+'_Mean'
  col_count = col+'_Count'
  col_delta = col+'_Delta'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_max] = np.nan
    df_record[col_mean] = np.nan
    df_record[col_count] = 0
    df_record[col_delta] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [156]:
creatinine_stats(df_sub, df_record, 'Creatinine')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [157]:
df_sub = df_temp[df_temp['Parameter'] == 'DiasABP'].reset_index(drop=True)
df_sub

   RecordID Parameter  Value   Time  Time_Minute
0    137188   DiasABP   65.0  17:59         1079
1    137188   DiasABP   71.0  18:29         1109
2    137188   DiasABP   69.0  18:59         1139
3    137188   DiasABP   63.0  19:29         1169
4    137188   DiasABP   59.0  19:44         1184
5    137188   DiasABP   46.0  19:54         1194
6    137188   DiasABP   45.0  19:59         1199
7    137188   DiasABP   62.0  20:29         1229
8    137188   DiasABP   60.0  21:29         1289
9    137188   DiasABP   66.0  22:29         1349
10   137188   DiasABP   62.0  22:44         1364
11   137188   DiasABP   57.0  23:29         1409
12   137188   DiasABP   63.0  24:29         1469
13   137188   DiasABP   77.0  25:29         1529
14   137188   DiasABP   58.0  26:29         1589
15   137188   DiasABP   58.0  27:29         1649
16   137188   DiasABP   43.0  28:29         1709
17   137188   DiasABP   54.0  29:29         1769
18   137188   DiasABP   43.0  29:44         1784
19   137188   DiasABP   44.0  29:59         1799
20   137188   DiasABP   63.0  30:29         1829
21   137188   DiasABP   39.0  31:29         1889
22   137188   DiasABP   56.0  32:29         1949
23   137188   DiasABP   45.0  33:29         2009
24   137188   DiasABP   40.0  34:29         2069
25   137188   DiasABP   47.0  35:29         2129
26   137188   DiasABP   58.0  36:29         2189
27   137188   DiasABP   55.0  37:29         2249
28   137188   DiasABP   57.0  38:29         2309
29   137188   DiasABP   60.0  39:29         2369
30   137188   DiasABP   61.0  40:29         2429
31   137188   DiasABP   68.0  41:59         2519
32   137188   DiasABP   65.0  42:29         2549
33   137188   DiasABP   70.0  42:59         2579
34   137188   DiasABP   67.0  43:29         2609
35   137188   DiasABP   69.0  44:29         2669
36   137188   DiasABP   64.0  44:59         2699
37   137188   DiasABP   62.0  45:29         2729
38   137188   DiasABP   57.0  46:29         2789
39   137188   DiasABP   57.0  46:59         2819
40   137188   DiasABP   66.0  47:29         2849

In [158]:
# DiasABP
# DiasABP_Initial
# DiasABP_Min
# DiasABP_Max
# DiasABP_Mean
# DiasABP_SD
# DiasABP_Time_Duration - threshold < 40 x
# DiasABP_Count
# DiasABP_Slope
# DiasABP_Miss
# DiasABP_Last_Minute


def diasabp_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_min = col+'_Min'
  col_max = col+'_Max'
  col_mean = col+'_Mean'
  col_sd = col+'_SD'
  #col_td = col+'_Time_Duration'
  #threshold = 40
  col_count = col+'_Count'
  col_slope = col+'_Slope'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_min] = np.nan
    df_record[col_max] = np.nan
    df_record[col_mean] = np.nan
    df_record[col_sd] = np.nan
    #df_record[col_td] = np.nan
    df_record[col_count] = 0
    df_record[col_slope] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_sd] = np.nan
      #df_record[col_td] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_sd] = 0
      #df_record[col_td] = 0
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_sd] = np.nan
      #df_record[col_td] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_sd] = df_sub['Value'].std()
      #max_duration, max_begin, max_end = find_max_duration(df_sub, threshold, 'below')
      #time_duration, time_begin, time_end = find_time_duration(df_sub, max_begin, max_end)
      #df_record[col_td] = time_duration
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [159]:
diasabp_stats(df_sub, df_record, 'DiasABP')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849

In [160]:
df_sub = df_temp[df_temp['Parameter'] == 'FiO2'].reset_index(drop=True)
df_sub

   RecordID Parameter  Value   Time  Time_Minute
0    137188      FiO2    1.0  02:04          124
1    137188      FiO2    1.0  05:47          347
2    137188      FiO2    0.8  08:34          514
3    137188      FiO2    0.8  11:43          703
4    137188      FiO2    0.7  14:29          869
5    137188      FiO2    0.7  18:44         1124
6    137188      FiO2    0.7  20:09         1209
7    137188      FiO2    0.7  23:10         1390
8    137188      FiO2    0.7  27:29         1649
9    137188      FiO2    0.6  28:29         1709
10   137188      FiO2    0.6  30:29         1829
11   137188      FiO2    0.6  33:29         2009
12   137188      FiO2    0.6  35:29         2129
13   137188      FiO2    0.5  36:59         2219
14   137188      FiO2    0.5  38:29         2309
15   137188      FiO2    0.5  42:29         2549
16   137188      FiO2    0.4  46:14         2774
17   137188      FiO2    0.4  46:59         2819

In [161]:
# FiO2
# FiO2_Initial
# FiO2_Max
# FiO2_Mean
# FiO2_Count
# FiO2_Slope
# FiO2_Miss
# FiO2_Last_Minute


def fio2_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_max = col+'_Max'
  col_mean = col+'_Mean'
  col_count = col+'_Count'
  col_slope = col+'_Slope'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_max] = np.nan
    df_record[col_mean] = np.nan
    df_record[col_count] = 0
    df_record[col_slope] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [162]:
fio2_stats(df_sub, df_record, 'FiO2')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.000198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849

In [163]:
df_sub = df_temp[df_temp['Parameter'] == 'GCS'].reset_index(drop=True)
df_sub

   RecordID Parameter  Value   Time  Time_Minute
0    137188       GCS    3.0  02:14          134
1    137188       GCS    6.0  04:29          269
2    137188       GCS    6.0  06:29          389
3    137188       GCS    7.0  10:29          629
4    137188       GCS    7.0  14:29          869
5    137188       GCS    7.0  18:29         1109
6    137188       GCS    4.0  22:29         1349
7    137188       GCS    4.0  26:29         1589
8    137188       GCS    7.0  30:29         1829
9    137188       GCS    4.0  34:29         2069
10   137188       GCS    4.0  38:29         2309
11   137188       GCS    7.0  42:29         2549
12   137188       GCS    7.0  46:29         2789

In [164]:
# GCS
# GCS_Initial
# GCS_Final
# GCS_Min
# GCS_Max
# GCS_Mean
# GCS_Count
# GCS_Slope
# GCS_Miss
# GCS_Last_Minute


def gcs_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_final = col+'_Final'
  col_min = col+'_Min'
  col_max = col+'_Max'
  col_mean = col+'_Mean'
  col_count = col+'_Count'
  col_slope = col+'_Slope'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_final] = np.nan
    df_record[col_min] = np.nan
    df_record[col_max] = np.nan
    df_record[col_mean] = np.nan
    df_record[col_count] = 0
    df_record[col_slope] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_final] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_final] = df_sub['Value'].iloc[-1]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_final] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_final] = df_sub['Value'].iloc[-1]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [165]:
gcs_stats(df_sub, df_record, 'GCS')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.000198,0.000168,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849

In [166]:
df_sub = df_temp[df_temp['Parameter'] == 'Glucose'].reset_index(drop=True)
df_sub

  RecordID Parameter  Value   Time  Time_Minute
0   137188   Glucose  101.0  03:22          202
1   137188   Glucose   88.0  11:50          710
2   137188   Glucose  148.0  22:00         1320
3   137188   Glucose  173.0  35:13         2113

In [167]:
# Glucose
# Glucose_Initial
# Glucose_Min
# Glucose_Max
# Glucose_Mean
# Glucose_Count
# Glucose_Slope
# Glucose_Miss
# Glucose_Last_Minute


def glucose_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_min = col+'_Min'
  col_max = col+'_Max'
  col_mean = col+'_Mean'
  col_count = col+'_Count'
  col_slope = col+'_Slope'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_min] = np.nan
    df_record[col_max] = np.nan
    df_record[col_mean] = np.nan
    df_record[col_count] = 0
    df_record[col_slope] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [168]:
glucose_stats(df_sub, df_record, 'Glucose')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.000198,0.000168,0.044188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849

In [169]:
df_sub = df_temp[df_temp['Parameter'] == 'HCO3'].reset_index(drop=True)
df_sub

  RecordID Parameter  Value   Time  Time_Minute
0   137188      HCO3   22.0  03:22          202
1   137188      HCO3   22.0  11:50          710
2   137188      HCO3   24.0  22:00         1320
3   137188      HCO3   25.0  35:13         2113

In [170]:
# HCO3
# HCO3_Initial
# HCO3_Final
# HCO3_Min
# HCO3_Max
# HCO3_Count
# HCO3_Delta
# HCO3_Miss
# HCO3_Last_Minute


def hco3_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_final = col+'_Final'
  col_min = col+'_Min'
  col_max = col+'_Max'
  col_count = col+'_Count'
  col_delta = col+'_Delta'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_final] = np.nan
    df_record[col_min] = np.nan
    df_record[col_max] = np.nan
    df_record[col_count] = 0
    df_record[col_delta] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_final] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_final] = df_sub['Value'].iloc[-1]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_final] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_final] = df_sub['Value'].iloc[-1]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [171]:
hco3_stats(df_sub, df_record, 'HCO3')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.000198,0.000168,0.044188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849

In [172]:
df_sub = df_temp[df_temp['Parameter'] == 'HCT'].reset_index(drop=True)
df_sub

  RecordID Parameter  Value   Time  Time_Minute
0   137188       HCT   29.7  03:22          202
1   137188       HCT   26.7  11:50          710
2   137188       HCT   29.7  22:00         1320
3   137188       HCT   28.8  27:18         1638
4   137188       HCT   29.0  35:13         2113
5   137188       HCT   26.6  46:39         2799

In [173]:
# HCT
# HCT_Initial
# HCT_Min
# HCT_Max
# HCT_Mean
# HCT_Count
# HCT_Delta
# HCT_Miss
# HCT_Last_Minute


def hct_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_min = col+'_Min'
  col_max = col+'_Max'
  col_mean = col+'_Mean'
  col_count = col+'_Count'
  col_delta = col+'_Delta'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_min] = np.nan
    df_record[col_max] = np.nan
    df_record[col_mean] = np.nan
    df_record[col_count] = 0
    df_record[col_delta] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [174]:
hct_stats(df_sub, df_record, 'HCT')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.000198,0.000168,0.044188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849

In [175]:
df_sub = df_temp[df_temp['Parameter'] == 'HR'].reset_index(drop=True)
df_sub

   RecordID Parameter  Value   Time  Time_Minute
0    137188        HR  109.0  02:14          134
1    137188        HR  109.0  02:29          149
2    137188        HR  111.0  02:44          164
3    137188        HR  113.0  02:59          179
4    137188        HR  113.0  03:14          194
5    137188        HR  113.0  03:29          209
6    137188        HR  124.0  03:59          239
7    137188        HR  113.0  04:29          269
8    137188        HR  116.0  05:29          329
9    137188        HR  111.0  06:29          389
10   137188        HR  115.0  07:29          449
11   137188        HR  114.0  08:29          509
12   137188        HR  120.0  09:29          569
13   137188        HR  124.0  10:29          629
14   137188        HR  130.0  11:29          689
15   137188        HR  137.0  12:29          749
16   137188        HR  133.0  13:29          809
17   137188        HR  131.0  14:29          869
18   137188        HR  139.0  15:29          929
19   137188        HR  123.0  15:59          959
20   137188        HR  131.0  16:14          974
21   137188        HR  128.0  16:29          989
22   137188        HR  124.0  16:44         1004
23   137188        HR  115.0  17:29         1049
24   137188        HR  111.0  17:59         1079
25   137188        HR  115.0  18:29         1109
26   137188        HR  113.0  18:59         1139
27   137188        HR  108.0  19:29         1169
28   137188        HR  108.0  19:44         1184
29   137188        HR  107.0  19:54         1194
30   137188        HR  107.0  19:59         1199
31   137188        HR  105.0  20:29         1229
32   137188        HR  104.0  21:29         1289
33   137188        HR  107.0  22:29         1349
34   137188        HR  107.0  22:44         1364
35   137188        HR  113.0  23:29         1409
36   137188        HR  118.0  25:29         1529
37   137188        HR  104.0  26:29         1589
38   137188        HR  131.0  27:29         1649
39   137188        HR  113.0  28:29         1709
40   137188        HR   99.0  29:29         1769
41   137188        HR   97.0  29:44         1784
42   137188        HR   96.0  29:59         1799
43   137188        HR   95.0  30:29         1829
44   137188        HR  104.0  31:29         1889
45   137188        HR  105.0  32:29         1949
46   137188        HR  102.0  33:29         2009
47   137188        HR  107.0  34:29         2069
48   137188        HR  102.0  35:29         2129
49   137188        HR   95.0  36:29         2189
50   137188        HR   95.0  37:29         2249
51   137188        HR   96.0  38:29         2309
52   137188        HR  102.0  39:29         2369
53   137188        HR   96.0  40:29         2429
54   137188        HR  105.0  41:59         2519
55   137188        HR   94.0  42:29         2549
56   137188        HR   93.0  42:59         2579
57   137188        HR   92.0  43:29         2609
58   137188        HR   90.0  44:29         2669
59   137188        HR   89.0  44:59         2699
60   137188        HR   88.0  45:29         2729
61   137188        HR   88.0  46:29         2789
62   137188        HR   90.0  46:59         2819
63   137188        HR  106.0  47:29         2849

In [176]:
# HR
# HR_Initial
# HR_Final
# HR_Min
# HR_Max
# HR_Mean
# HR_SD
# HR_Count
# HR_Slope
# HR_Miss
# HR_Last_Minute


def hr_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_final = col+'_Final'
  col_min = col+'_Min'
  col_max = col+'_Max'
  col_mean = col+'_Mean'
  col_sd = col+'_SD'
  col_count = col+'_Count'
  col_slope = col+'_Slope'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_final] = np.nan
    df_record[col_min] = np.nan
    df_record[col_max] = np.nan
    df_record[col_mean] = np.nan
    df_record[col_sd] = np.nan
    df_record[col_count] = 0
    df_record[col_slope] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_final] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_sd] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_final] = df_sub['Value'].iloc[-1]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_sd] = 0
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_final] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_sd] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_final] = df_sub['Value'].iloc[-1]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_sd] = df_sub['Value'].std()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [177]:
hr_stats(df_sub, df_record, 'HR')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.000198,0.000168,0.044188,-0.010776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849

In [178]:
df_sub = df_temp[df_temp['Parameter'] == 'K'].reset_index(drop=True)
df_sub

  RecordID Parameter  Value   Time  Time_Minute
0   137188         K    4.0  03:22          202
1   137188         K    4.0  03:32          212
2   137188         K    3.6  11:50          710
3   137188         K    4.1  22:00         1320
4   137188         K    4.6  35:13         2113

In [179]:
# K
# K_Initial
# K_Final
# K_Min
# K_Max
# K_Mean
# K_Count
# K_Delta
# K_Miss
# K_Last_Minute


def k_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_final = col+'_Final'
  col_min = col+'_Min'
  col_max = col+'_Max'
  col_mean = col+'_Mean'
  col_count = col+'_Count'
  col_delta = col+'_Delta'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_final] = np.nan
    df_record[col_min] = np.nan
    df_record[col_max] = np.nan
    df_record[col_mean] = np.nan
    df_record[col_count] = 0
    df_record[col_delta] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_final] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_final] = df_sub['Value'].iloc[-1]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_final] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_final] = df_sub['Value'].iloc[-1]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [180]:
k_stats(df_sub, df_record, 'K')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,64,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,0.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.000198,0.000168,0.044188,-0.010776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,2113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849

In [181]:
df_sub = df_temp[df_temp['Parameter'] == 'Lactate'].reset_index(drop=True)
df_sub

  RecordID Parameter  Value   Time  Time_Minute
0   137188   Lactate    1.5  07:35          455
1   137188   Lactate    1.5  09:33          573
2   137188   Lactate    1.8  15:08          908
3   137188   Lactate    1.4  22:18         1338
4   137188   Lactate    1.4  35:50         2150
5   137188   Lactate    1.4  46:43         2803

In [182]:
# Lactate
# Lactate_Initial
# Lactate_Max
# Lactate_Count
# Lactate_Miss
# Lactate_Clearance_Rate_6H - Clearance Rate (% reduction over 6h)
# Lactate_Clearance_Rate_12H - Clearance Rate (% reduction over 12h)
# Lactate_Last_Minute


def lactate_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_max = col+'_Max'
  col_count = col+'_Count'
  col_miss = col+'_Miss'
  col_cr6 = col+'_Clearance_Rate_6H'
  col_cr12 = col+'_Clearance_Rate_12H'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_max] = np.nan
    df_record[col_count] = 0
    df_record[col_miss] = 1
    df_record[col_cr6] = np.nan
    df_record[col_cr12] = np.nan
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_max] = np.nan
      df_record[col_count] = 0
      df_record[col_miss] = 1
      df_record[col_cr6] = np.nan
      df_record[col_cr12] = np.nan
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_miss] = 0
      df_record[col_cr6] = np.nan
      df_record[col_cr12] = np.nan
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_max] = np.nan
      df_record[col_count] = 0
      df_record[col_miss] = 1
      df_record[col_cr6] = np.nan
      df_record[col_cr12] = np.nan
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_miss] = 0
      df_record[col_cr6] = find_lcr(df_sub, 6)
      df_record[col_cr12] = find_lcr(df_sub, 12)
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [183]:
lactate_stats(df_sub, df_record, 'Lactate')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.06,1.5,1.8,0.0,-20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,64,5,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,0.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.000198,0.000168,0.044188,-0.010776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,2113,2803,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849

In [184]:
df_sub = df_temp[df_temp['Parameter'] == 'MAP'].reset_index(drop=True)
df_sub

   RecordID Parameter  Value   Time  Time_Minute
0    137188       MAP   81.0  17:59         1079
1    137188       MAP   85.0  18:29         1109
2    137188       MAP   87.0  18:59         1139
3    137188       MAP   80.0  19:29         1169
4    137188       MAP   76.0  19:44         1184
5    137188       MAP   64.0  19:54         1194
6    137188       MAP   65.0  19:59         1199
7    137188       MAP   75.0  20:29         1229
8    137188       MAP   75.0  21:29         1289
9    137188       MAP   84.0  22:29         1349
10   137188       MAP   82.0  22:44         1364
11   137188       MAP   77.0  23:29         1409
12   137188       MAP   81.0  24:29         1469
13   137188       MAP   95.0  25:29         1529
14   137188       MAP   77.0  26:29         1589
15   137188       MAP   84.0  27:29         1649
16   137188       MAP   68.0  28:29         1709
17   137188       MAP   72.0  29:29         1769
18   137188       MAP   61.0  29:44         1784
19   137188       MAP   60.0  29:59         1799
20   137188       MAP   81.0  30:29         1829
21   137188       MAP   63.0  31:29         1889
22   137188       MAP   77.0  32:29         1949
23   137188       MAP   67.0  33:29         2009
24   137188       MAP   62.0  34:29         2069
25   137188       MAP   67.0  35:29         2129
26   137188       MAP   72.0  36:29         2189
27   137188       MAP   70.0  37:29         2249
28   137188       MAP   74.0  38:29         2309
29   137188       MAP   83.0  39:29         2369
30   137188       MAP   78.0  40:29         2429
31   137188       MAP   87.0  41:59         2519
32   137188       MAP   83.0  42:29         2549
33   137188       MAP   87.0  42:59         2579
34   137188       MAP   84.0  43:29         2609
35   137188       MAP   86.0  44:29         2669
36   137188       MAP   83.0  44:59         2699
37   137188       MAP   80.0  45:29         2729
38   137188       MAP   73.0  46:29         2789
39   137188       MAP   74.0  46:59         2819
40   137188       MAP   86.0  47:29         2849

In [185]:
# MAP
# MAP_Initial
# MAP_Min
# MAP_Max
# MAP_Mean
# MAP_SD
# MAP_Time_Duration - threshold < 65 x
# MAP_Count
# MAP_Slope
# MAP_Miss
# MAP_Last_Minute


def map_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_min = col+'_Min'
  col_max = col+'_Max'
  col_mean = col+'_Mean'
  col_sd = col+'_SD'
  #col_td = col+'_Time_Duration'
  #threshold = 65
  col_count = col+'_Count'
  col_slope = col+'_Slope'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_min] = np.nan
    df_record[col_max] = np.nan
    df_record[col_mean] = np.nan
    df_record[col_sd] = np.nan
    #df_record[col_td] = np.nan
    df_record[col_count] = 0
    df_record[col_slope] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_sd] = np.nan
      #df_record[col_td] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_sd] = 0
      #df_record[col_td] = 0
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_sd] = np.nan
      #df_record[col_td] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_sd] = df_sub['Value'].std()
      #max_duration, max_begin, max_end = find_max_duration(df_sub, threshold, 'below')
      #time_duration, time_begin, time_end = find_time_duration(df_sub, max_begin, max_end)
      #df_record[col_td] = time_duration
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [186]:
map_stats(df_sub,df_record, 'MAP')

/tmp/ipykernel_245953/591698936.py:73: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_initial] = df_sub['Value'].iloc[0]
/tmp/ipykernel_245953/591698936.py:74: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_min] = df_sub['Value'].min()
/tmp/ipykernel_245953/591698936.py:75: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_max] = df_sub['Value'].max()
/tmp/ipykernel_245953/591698936.py:76: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_mean] = df_sub['Value'].mean()
/tmp/ipykernel_245953/591698936.py:77: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_sd] = df_sub['Value'].std()
/tmp/ipykernel_245953/591698936.py:81: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_count] = df_sub['Value'].count()
/tmp/ipykernel_245953/591698936.py:82: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_slope] = compute_regression_slope(df_sub)
/tmp/ipykernel_245953/591698936.py:83: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_miss] = 0
/tmp/ipykernel_245953/591698936.py:84: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute,MAP_Initial,MAP_Min,MAP_Max,MAP_Mean,MAP_SD,MAP_Count,MAP_Slope,MAP_Miss,MAP_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.06,1.5,1.8,0.0,-20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,64,5,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,0.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.000198,0.000168,0.044188,-0.010776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,2113,2803,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849,81.0,60.0,95.0,76.731707,8.508891,41,0.001595,0,2849

In [187]:
df_sub = df_temp[df_temp['Parameter'] == 'MechVent'].reset_index(drop=True)
df_sub

   RecordID Parameter  Value   Time  Time_Minute
0    137188  MechVent    1.0  02:04          124
1    137188  MechVent    1.0  05:47          347
2    137188  MechVent    1.0  06:29          389
3    137188  MechVent    1.0  10:29          629
4    137188  MechVent    1.0  11:43          703
5    137188  MechVent    1.0  14:29          869
6    137188  MechVent    1.0  18:44         1124
7    137188  MechVent    1.0  20:09         1209
8    137188  MechVent    1.0  23:10         1390
9    137188  MechVent    1.0  26:29         1589
10   137188  MechVent    1.0  27:29         1649
11   137188  MechVent    1.0  30:29         1829
12   137188  MechVent    1.0  33:29         2009
13   137188  MechVent    1.0  35:29         2129
14   137188  MechVent    1.0  38:29         2309
15   137188  MechVent    1.0  42:29         2549
16   137188  MechVent    1.0  46:14         2774
17   137188  MechVent    1.0  46:59         2819

In [188]:
# MechVent
# MechVent_Any - 1 if ventilated at any point
# MechVent_Count
# MechVent_Miss
# MechVent_Last_Minute


def mechvent_stats(df_sub, df_record, col):
  col_any = col+'_Any'
  col_count = col+'_Count'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_any] = np.nan
    df_record[col_count] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_any] = np.nan
      df_record[col_count] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_any] = (df_sub['Value'].iloc[0] == 1).any().astype(float)
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_any] = np.nan
      df_record[col_count] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_any] = (df_sub['Value'] == 1).any().astype(float)
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [189]:
mechvent_stats(df_sub,df_record, 'MechVent')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute,MAP_Initial,MAP_Min,MAP_Max,MAP_Mean,MAP_SD,MAP_Count,MAP_Slope,MAP_Miss,MAP_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.06,1.5,1.8,0.0,-20.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,64,5,6,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,0.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.000198,0.000168,0.044188,-0.010776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,2113,2803,2819,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849,81.0,60.0,95.0,76.731707,8.508891,41,0.001595,0,2849

In [190]:
df_sub = df_temp[df_temp['Parameter'] == 'Mg'].reset_index(drop=True)
df_sub

  RecordID Parameter  Value   Time  Time_Minute
0   137188        Mg    2.2  03:22          202
1   137188        Mg    1.7  11:50          710
2   137188        Mg    2.2  22:00         1320
3   137188        Mg    2.0  35:13         2113

In [191]:
# Mg
# Mg_Initial
# Mg_Min
# Mg_Max
# Mg_Count
# Mg_Delta
# Mg_Miss
# Mg_Last_Minute


def mg_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_min = col+'_Min'
  col_max = col+'_Max'
  col_count = col+'_Count'
  col_delta = col+'_Delta'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_min] = np.nan
    df_record[col_max] = np.nan
    df_record[col_count] = 0
    df_record[col_delta] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [192]:
mg_stats(df_sub, df_record, 'Mg')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute,MAP_Initial,MAP_Min,MAP_Max,MAP_Mean,MAP_SD,MAP_Count,MAP_Slope,MAP_Miss,MAP_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.06,1.5,1.8,0.0,-20.0,1.0,2.2,1.7,2.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,64,5,6,18,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,0.6,-0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.000198,0.000168,0.044188,-0.010776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,2113,2803,2819,2113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849,81.0,60.0,95.0,76.731707,8.508891,41,0.001595,0,2849

In [193]:
df_sub = df_temp[df_temp['Parameter'] == 'Na'].reset_index(drop=True)
df_sub

  RecordID Parameter  Value   Time  Time_Minute
0   137188        Na  136.0  03:22          202
1   137188        Na  139.0  11:50          710
2   137188        Na  136.0  22:00         1320
3   137188        Na  136.0  35:13         2113

In [194]:
# Na
# Na_Initial
# Na_Final
# Na_Min
# Na_Max
# Na_Mean
# Na_Count
# Na_Delta
# Na_Miss
# Na_Last_Minute


def na_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_final = col+'_Final'
  col_min = col+'_Min'
  col_max = col+'_Max'
  col_mean = col+'_Mean'
  col_count = col+'_Count'
  col_delta = col+'_Delta'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_final] = np.nan
    df_record[col_min] = np.nan
    df_record[col_max] = np.nan
    df_record[col_mean] = np.nan
    df_record[col_count] = 0
    df_record[col_delta] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_final] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_final] = df_sub['Value'].iloc[-1]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_final] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_final] = df_sub['Value'].iloc[-1]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [195]:
na_stats(df_sub,df_record, 'Na')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute,MAP_Initial,MAP_Min,MAP_Max,MAP_Mean,MAP_SD,MAP_Count,MAP_Slope,MAP_Miss,MAP_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.06,1.5,1.8,0.0,-20.0,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,64,5,6,18,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,0.6,-0.2,0.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.000198,0.000168,0.044188,-0.010776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,2113,2803,2819,2113,2113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849,81.0,60.0,95.0,76.731707,8.508891,41,0.001595,0,2849

In [196]:
df_sub = df_temp[df_temp['Parameter'] == 'NIDiasABP'].reset_index(drop=True)
df_sub

   RecordID  Parameter  Value   Time  Time_Minute
0    137188  NIDiasABP   60.0  02:14          134
1    137188  NIDiasABP   62.0  02:29          149
2    137188  NIDiasABP   65.0  02:44          164
3    137188  NIDiasABP   70.0  02:59          179
4    137188  NIDiasABP   72.0  03:14          194
5    137188  NIDiasABP   74.0  03:29          209
6    137188  NIDiasABP   66.0  03:59          239
7    137188  NIDiasABP   66.0  04:29          269
8    137188  NIDiasABP   64.0  05:29          329
9    137188  NIDiasABP   65.0  06:29          389
10   137188  NIDiasABP   55.0  08:29          509
11   137188  NIDiasABP   51.0  09:29          569
12   137188  NIDiasABP   46.0  10:29          629
13   137188  NIDiasABP   63.0  11:29          689
14   137188  NIDiasABP   38.0  12:29          749
15   137188  NIDiasABP   48.0  13:29          809
16   137188  NIDiasABP   62.0  14:29          869
17   137188  NIDiasABP   67.0  15:29          929
18   137188  NIDiasABP   72.0  15:59          959
19   137188  NIDiasABP   69.0  16:14          974
20   137188  NIDiasABP   69.0  16:29          989
21   137188  NIDiasABP   72.0  16:44         1004
22   137188  NIDiasABP   64.0  17:29         1049
23   137188  NIDiasABP   64.0  17:59         1079
24   137188  NIDiasABP   66.0  18:29         1109
25   137188  NIDiasABP   64.0  18:59         1139
26   137188  NIDiasABP   78.0  19:44         1184
27   137188  NIDiasABP   66.0  20:29         1229
28   137188  NIDiasABP   66.0  22:44         1364
29   137188  NIDiasABP   58.0  23:29         1409
30   137188  NIDiasABP   70.0  24:29         1469
31   137188  NIDiasABP   68.0  27:29         1649

In [197]:
# NIDiasABP
# NIDiasABP_Initial
# NIDiasABP_Min
# NIDiasABP_Max
# NIDiasABP_Mean
# NIDiasABP_SD
# NIDiasABP_Time_Duration - threshold < 40 x
# NIDiasABP_Count
# NIDiasABP_Slope
# NIDiasABP_Miss
# NIDiasABP_Last_Minute


def nidiasabp_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_min = col+'_Min'
  col_max = col+'_Max'
  col_mean = col+'_Mean'
  col_sd = col+'_SD'
  #col_td = col+'_Time_Duration'
  #threshold = 40
  col_count = col+'_Count'
  col_slope = col+'_Slope'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_min] = np.nan
    df_record[col_max] = np.nan
    df_record[col_mean] = np.nan
    df_record[col_sd] = np.nan
    #df_record[col_td] = np.nan
    df_record[col_count] = 0
    df_record[col_slope] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_sd] = np.nan
      #df_record[col_td] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_sd] = 0
      #df_record[col_td] = 0
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_sd] = np.nan
      #df_record[col_td] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_sd] = df_sub['Value'].std()
      #max_duration, max_begin, max_end = find_max_duration(df_sub, threshold, 'below')
      #time_duration, time_begin, time_end = find_time_duration(df_sub, max_begin, max_end)
      #df_record[col_td] = time_duration
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [198]:
nidiasabp_stats(df_sub,df_record, 'NIDiasABP')

/tmp/ipykernel_245953/2456799477.py:74: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_initial] = df_sub['Value'].iloc[0]
/tmp/ipykernel_245953/2456799477.py:75: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_min] = df_sub['Value'].min()
/tmp/ipykernel_245953/2456799477.py:76: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_max] = df_sub['Value'].max()
/tmp/ipykernel_245953/2456799477.py:77: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_mean] = df_sub['Value'].mean()
/tmp/ipykernel_245953/2456799477.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_sd] = df_sub['Value'].std()
/tmp/ipykernel_245953/2456799477.py:82: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_count] = df_sub['Value'].count()
/tmp/ipykernel_245953/2456799477.py:83: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_slope] = compute_regression_slope(df_sub)
/tmp/ipykernel_245953/2456799477.py:84: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_miss] = 0
/tmp/ipykernel_245953/2456799477.py:85: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute,MAP_Initial,MAP_Min,MAP_Max,MAP_Mean,MAP_SD,MAP_Count,MAP_Slope,MAP_Miss,MAP_Last_Minute,NIDiasABP_Initial,NIDiasABP_Min,NIDiasABP_Max,NIDiasABP_Mean,NIDiasABP_SD,NIDiasABP_Count,NIDiasABP_Slope,NIDiasABP_Miss,NIDiasABP_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.06,1.5,1.8,0.0,-20.0,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,64,5,6,18,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,0.6,-0.2,0.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.000198,0.000168,0.044188,-0.010776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,2113,2803,2819,2113,2113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849,81.0,60.0,95.0,76.731707,8.508891,41,0.001595,0,2849,60.0,38.0,78.0,63.75,8.466252,32,0.002046,0,1649

In [199]:
df_sub = df_temp[df_temp['Parameter'] == 'NIMAP'].reset_index(drop=True)
df_sub

   RecordID Parameter  Value   Time  Time_Minute
0    137188     NIMAP   69.0  02:14          134
1    137188     NIMAP   70.0  02:29          149
2    137188     NIMAP   75.0  02:44          164
3    137188     NIMAP   80.0  02:59          179
4    137188     NIMAP   81.0  03:14          194
5    137188     NIMAP   83.0  03:29          209
6    137188     NIMAP   76.0  03:59          239
7    137188     NIMAP   76.0  04:29          269
8    137188     NIMAP   76.0  05:29          329
9    137188     NIMAP   75.0  06:29          389
10   137188     NIMAP   64.0  08:29          509
11   137188     NIMAP   59.0  09:29          569
12   137188     NIMAP   56.0  10:29          629
13   137188     NIMAP   72.0  11:29          689
14   137188     NIMAP   48.0  12:29          749
15   137188     NIMAP   60.0  13:29          809
16   137188     NIMAP   72.0  14:29          869
17   137188     NIMAP   77.0  15:29          929
18   137188     NIMAP   81.0  15:59          959
19   137188     NIMAP   79.0  16:14          974
20   137188     NIMAP   79.0  16:29          989
21   137188     NIMAP   82.0  16:44         1004
22   137188     NIMAP   74.0  17:29         1049
23   137188     NIMAP   74.0  17:59         1079
24   137188     NIMAP   75.0  18:29         1109
25   137188     NIMAP   73.0  18:59         1139
26   137188     NIMAP   88.0  19:44         1184
27   137188     NIMAP   76.0  20:29         1229
28   137188     NIMAP   75.0  22:44         1364
29   137188     NIMAP   68.0  23:29         1409
30   137188     NIMAP   79.0  24:29         1469
31   137188     NIMAP   76.0  27:29         1649

In [200]:
# NIMAP
# NIMAP_Initial
# NIMAP_Min
# NIMAP_Max
# NIMAP_Mean
# NIMAP_SD
# NIMAP_Time_Duration - threshold < 65 x
# NIMAP_Count
# NIMAP_Slope
# NIMAP_Miss
# NIMAP_Last_Minute


def nimap_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_min = col+'_Min'
  col_max = col+'_Max'
  col_mean = col+'_Mean'
  col_sd = col+'_SD'
  #col_td = col+'_Time_Duration'
  #threshold = 65
  col_count = col+'_Count'
  col_slope = col+'_Slope'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_min] = np.nan
    df_record[col_max] = np.nan
    df_record[col_mean] = np.nan
    df_record[col_sd] = np.nan
    #df_record[col_td] = np.nan
    df_record[col_count] = 0
    df_record[col_slope] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_sd] = np.nan
      #df_record[col_td] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_sd] = 0
      #df_record[col_td] = 0
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_sd] = np.nan
      #df_record[col_td] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_sd] = df_sub['Value'].std()
      #max_duration, max_begin, max_end = find_max_duration(df_sub, threshold, 'below')
      #time_duration, time_begin, time_end = find_time_duration(df_sub, max_begin, max_end)
      #df_record[col_td] = time_duration
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [201]:
nimap_stats(df_sub, df_record, 'NIMAP')

/tmp/ipykernel_245953/2795769658.py:74: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_initial] = df_sub['Value'].iloc[0]
/tmp/ipykernel_245953/2795769658.py:75: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_min] = df_sub['Value'].min()
/tmp/ipykernel_245953/2795769658.py:76: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_max] = df_sub['Value'].max()
/tmp/ipykernel_245953/2795769658.py:77: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_mean] = df_sub['Value'].mean()
/tmp/ipykernel_245953/2795769658.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_sd] = df_sub['Value'].std()
/tmp/ipykernel_245953/2795769658.py:82: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_count] = df_sub['Value'].count()
/tmp/ipykernel_245953/2795769658.py:83: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_slope] = compute_regression_slope(df_sub)
/tmp/ipykernel_245953/2795769658.py:84: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_miss] = 0
/tmp/ipykernel_245953/2795769658.py:85: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute,MAP_Initial,MAP_Min,MAP_Max,MAP_Mean,MAP_SD,MAP_Count,MAP_Slope,MAP_Miss,MAP_Last_Minute,NIDiasABP_Initial,NIDiasABP_Min,NIDiasABP_Max,NIDiasABP_Mean,NIDiasABP_SD,NIDiasABP_Count,NIDiasABP_Slope,NIDiasABP_Miss,NIDiasABP_Last_Minute,NIMAP_Initial,NIMAP_Min,NIMAP_Max,NIMAP_Mean,NIMAP_SD,NIMAP_Count,NIMAP_Slope,NIMAP_Miss,NIMAP_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.06,1.5,1.8,0.0,-20.0,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,64,5,6,18,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,0.6,-0.2,0.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.000198,0.000168,0.044188,-0.010776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,2113,2803,2819,2113,2113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849,81.0,60.0,95.0,76.731707,8.508891,41,0.001595,0,2849,60.0,38.0,78.0,63.75,8.466252,32,0.002046,0,1649,69.0,48.0,88.0,73.375,8.381046,32,0.001885,0,1649

In [202]:
df_sub = df_temp[df_temp['Parameter'] == 'NISysABP'].reset_index(drop=True)
df_sub

   RecordID Parameter  Value   Time  Time_Minute
0    137188  NISysABP   97.0  02:14          134
1    137188  NISysABP   98.0  02:29          149
2    137188  NISysABP  107.0  02:44          164
3    137188  NISysABP  112.0  02:59          179
4    137188  NISysABP  111.0  03:14          194
5    137188  NISysABP  111.0  03:29          209
6    137188  NISysABP  106.0  03:59          239
7    137188  NISysABP  108.0  04:29          269
8    137188  NISysABP  111.0  05:29          329
9    137188  NISysABP  114.0  06:29          389
10   137188  NISysABP   91.0  08:29          509
11   137188  NISysABP   88.0  09:29          569
12   137188  NISysABP   90.0  10:29          629
13   137188  NISysABP  103.0  11:29          689
14   137188  NISysABP   82.0  12:29          749
15   137188  NISysABP   98.0  13:29          809
16   137188  NISysABP  104.0  14:29          869
17   137188  NISysABP  110.0  15:29          929
18   137188  NISysABP  108.0  15:59          959
19   137188  NISysABP  112.0  16:14          974
20   137188  NISysABP  112.0  16:29          989
21   137188  NISysABP  112.0  16:44         1004
22   137188  NISysABP  103.0  17:29         1049
23   137188  NISysABP  105.0  17:59         1079
24   137188  NISysABP  103.0  18:29         1109
25   137188  NISysABP  104.0  18:59         1139
26   137188  NISysABP  121.0  19:44         1184
27   137188  NISysABP  109.0  20:29         1229
28   137188  NISysABP  106.0  22:44         1364
29   137188  NISysABP  108.0  23:29         1409
30   137188  NISysABP  108.0  24:29         1469
31   137188  NISysABP  105.0  27:29         1649

In [203]:
# NISysABP
# NISysABP_Initial
# NISysABP_Min
# NISysABP_Max
# NISysABP_Mean
# NISysABP_SD
# NISysABP_Time_Duration - threshold < 90 x
# NISysABP_Count
# NISysABP_Slope
# NISysABP_Miss
# NISysABP_Last_Minute


def nisysabp_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_min = col+'_Min'
  col_max = col+'_Max'
  col_mean = col+'_Mean'
  col_sd = col+'_SD'
  #col_td = col+'_Time_Duration'
  #threshold = 90
  col_count = col+'_Count'
  col_slope = col+'_Slope'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_min] = np.nan
    df_record[col_max] = np.nan
    df_record[col_mean] = np.nan
    df_record[col_sd] = np.nan
    #df_record[col_td] = np.nan
    df_record[col_count] = 0
    df_record[col_slope] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_sd] = np.nan
      #df_record[col_td] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_sd] = 0
      #df_record[col_td] = 0
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_sd] = np.nan
      #df_record[col_td] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_sd] = df_sub['Value'].std()
      #max_duration, max_begin, max_end = find_max_duration(df_sub, threshold, 'below')
      #time_duration, time_begin, time_end = find_time_duration(df_sub, max_begin, max_end)
      #df_record[col_td] = time_duration
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [204]:
nisysabp_stats(df_sub, df_record, 'NISysABP')

/tmp/ipykernel_245953/1988834833.py:74: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_initial] = df_sub['Value'].iloc[0]
/tmp/ipykernel_245953/1988834833.py:75: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_min] = df_sub['Value'].min()
/tmp/ipykernel_245953/1988834833.py:76: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_max] = df_sub['Value'].max()
/tmp/ipykernel_245953/1988834833.py:77: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_mean] = df_sub['Value'].mean()
/tmp/ipykernel_245953/1988834833.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_sd] = df_sub['Value'].std()
/tmp/ipykernel_245953/1988834833.py:82: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_count] = df_sub['Value'].count()
/tmp/ipykernel_245953/1988834833.py:83: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_slope] = compute_regression_slope(df_sub)
/tmp/ipykernel_245953/1988834833.py:84: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_miss] = 0
/tmp/ipykernel_245953/1988834833.py:85: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute,MAP_Initial,MAP_Min,MAP_Max,MAP_Mean,MAP_SD,MAP_Count,MAP_Slope,MAP_Miss,MAP_Last_Minute,NIDiasABP_Initial,NIDiasABP_Min,NIDiasABP_Max,NIDiasABP_Mean,NIDiasABP_SD,NIDiasABP_Count,NIDiasABP_Slope,NIDiasABP_Miss,NIDiasABP_Last_Minute,NIMAP_Initial,NIMAP_Min,NIMAP_Max,NIMAP_Mean,NIMAP_SD,NIMAP_Count,NIMAP_Slope,NIMAP_Miss,NIMAP_Last_Minute,NISysABP_Initial,NISysABP_Min,NISysABP_Max,NISysABP_Mean,NISysABP_SD,NISysABP_Count,NISysABP_Slope,NISysABP_Miss,NISysABP_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.06,1.5,1.8,0.0,-20.0,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,64,5,6,18,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,0.6,-0.2,0.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.000198,0.000168,0.044188,-0.010776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,2113,2803,2819,2113,2113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849,81.0,60.0,95.0,76.731707,8.508891,41,0.001595,0,2849,60.0,38.0,78.0,63.75,8.466252,32,0.002046,0,1649,69.0,48.0,88.0,73.375,8.381046,32,0.001885,0,1649,97.0,82.0,121.0,104.90625,8.306078,32,0.002584,0,1649

In [205]:
df_sub = df_temp[df_temp['Parameter'] == 'PaCO2'].reset_index(drop=True)
df_sub

  RecordID Parameter  Value   Time  Time_Minute
0   137188     PaCO2   40.0  08:33          513
1   137188     PaCO2   41.0  14:08          848
2   137188     PaCO2   44.0  21:18         1278
3   137188     PaCO2   47.0  26:49         1609
4   137188     PaCO2   51.0  34:50         2090
5   137188     PaCO2   39.0  36:46         2206
6   137188     PaCO2   40.0  45:43         2743

In [206]:
# PaCO2
# PaCO2_Initial
# PaCO2_Min
# PaCO2_Max
# PaCO2_Count
# PaCO2_Slope
# PaCO2_Miss
# PaCO2_Last_Minute


def paco2_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_min = col+'_Min'
  col_max = col+'_Max'
  col_count = col+'_Count'
  col_slope = col+'_Slope'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_min] = np.nan
    df_record[col_max] = np.nan
    df_record[col_count] = 0
    df_record[col_slope] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [207]:
paco2_stats(df_sub, df_record, 'PaCO2')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute,MAP_Initial,MAP_Min,MAP_Max,MAP_Mean,MAP_SD,MAP_Count,MAP_Slope,MAP_Miss,MAP_Last_Minute,NIDiasABP_Initial,NIDiasABP_Min,NIDiasABP_Max,NIDiasABP_Mean,NIDiasABP_SD,NIDiasABP_Count,NIDiasABP_Slope,NIDiasABP_Miss,NIDiasABP_Last_Minute,NIMAP_Initial,NIMAP_Min,NIMAP_Max,NIMAP_Mean,NIMAP_SD,NIMAP_Count,NIMAP_Slope,NIMAP_Miss,NIMAP_Last_Minute,NISysABP_Initial,NISysABP_Min,NISysABP_Max,NISysABP_Mean,NISysABP_SD,NISysABP_Count,NISysABP_Slope,NISysABP_Miss,NISysABP_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.06,1.5,1.8,0.0,-20.0,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.75,40.0,39.0,51.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,64,5,6,18,4,4,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,0.6,-0.2,0.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.000198,0.000168,0.044188,-0.010776,0.000673,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,2113,2803,2819,2113,2113,2743,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849,81.0,60.0,95.0,76.731707,8.508891,41,0.001595,0,2849,60.0,38.0,78.0,63.75,8.466252,32,0.002046,0,1649,69.0,48.0,88.0,73.375,8.381046,32,0.001885,0,1649,97.0,82.0,121.0,104.90625,8.306078,32,0.002584,0,1649

In [208]:
df_sub = df_temp[df_temp['Parameter'] == 'PaO2'].reset_index(drop=True)
df_sub

  RecordID Parameter  Value   Time  Time_Minute
0   137188      PaO2  187.0  08:33          513
1   137188      PaO2  142.0  14:08          848
2   137188      PaO2  111.0  21:18         1278
3   137188      PaO2  115.0  26:49         1609
4   137188      PaO2   73.0  34:50         2090
5   137188      PaO2  160.0  36:46         2206
6   137188      PaO2  137.0  45:43         2743

In [209]:
df_sub2 = df_temp[df_temp['Parameter'] == 'FiO2'].reset_index(drop=True)
df_sub2

   RecordID Parameter  Value   Time  Time_Minute
0    137188      FiO2    1.0  02:04          124
1    137188      FiO2    1.0  05:47          347
2    137188      FiO2    0.8  08:34          514
3    137188      FiO2    0.8  11:43          703
4    137188      FiO2    0.7  14:29          869
5    137188      FiO2    0.7  18:44         1124
6    137188      FiO2    0.7  20:09         1209
7    137188      FiO2    0.7  23:10         1390
8    137188      FiO2    0.7  27:29         1649
9    137188      FiO2    0.6  28:29         1709
10   137188      FiO2    0.6  30:29         1829
11   137188      FiO2    0.6  33:29         2009
12   137188      FiO2    0.6  35:29         2129
13   137188      FiO2    0.5  36:59         2219
14   137188      FiO2    0.5  38:29         2309
15   137188      FiO2    0.5  42:29         2549
16   137188      FiO2    0.4  46:14         2774
17   137188      FiO2    0.4  46:59         2819

In [210]:
# PaO2
# PaO2_Initial
# PaO2_Min
# PaO2_Count
# PaO2_Delta
# PaO2_Miss
# PaO2_FiO2_Ratio - Min PaO2/FiO2 ​Ratio
# PaO2_Last_Minute


def pao2_stats(df_sub, df_sub2, df_record, col):
  col_initial = col+'_Initial'
  col_min = col+'_Min'
  col_count = col+'_Count'
  col_delta = col+'_Delta'
  col_miss = col+'_Miss'
  col_pfr = col+'_FiO2_Ratio'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_min] = np.nan
    df_record[col_count] = 0
    df_record[col_delta] = 0
    df_record[col_miss] = 1
    df_record[col_pfr] = np.nan
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_pfr] = np.nan
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_pfr] = find_min_pfr(df_sub, df_sub2)
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_pfr] = np.nan
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_pfr] = find_min_pfr(df_sub, df_sub2)
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [211]:
pao2_stats(df_sub, df_sub2, df_record, 'PaO2')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute,MAP_Initial,MAP_Min,MAP_Max,MAP_Mean,MAP_SD,MAP_Count,MAP_Slope,MAP_Miss,MAP_Last_Minute,NIDiasABP_Initial,NIDiasABP_Min,NIDiasABP_Max,NIDiasABP_Mean,NIDiasABP_SD,NIDiasABP_Count,NIDiasABP_Slope,NIDiasABP_Miss,NIDiasABP_Last_Minute,NIMAP_Initial,NIMAP_Min,NIMAP_Max,NIMAP_Mean,NIMAP_SD,NIMAP_Count,NIMAP_Slope,NIMAP_Miss,NIMAP_Last_Minute,NISysABP_Initial,NISysABP_Min,NISysABP_Max,NISysABP_Mean,NISysABP_SD,NISysABP_Count,NISysABP_Slope,NISysABP_Miss,NISysABP_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.06,1.5,1.8,0.0,-20.0,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.75,40.0,39.0,51.0,187.0,73.0,121.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,64,5,6,18,4,4,7,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,0.6,-0.2,0.0,-50.0,NaN,NaN,NaN,NaN,NaN,-0.000198,0.000168,0.044188,-0.010776,0.000673,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,2113,2803,2819,2113,2113,2743,2743,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849,81.0,60.0,95.0,76.731707,8.508891,41,0.001595,0,2849,60.0,38.0,78.0,63.75,8.466252,32,0.002046,0,1649,69.0,48.0,88.0,73.375,8.381046,32,0.001885,0,1649,97.0,82.0,121.0,104.90625,8.306078,32,0.002584,0,1649

In [212]:
df_sub = df_temp[df_temp['Parameter'] == 'pH'].reset_index(drop=True)
df_sub

  RecordID Parameter  Value   Time  Time_Minute
0   137188        pH   7.39  08:33          513
1   137188        pH   7.37  14:08          848
2   137188        pH   7.34  21:18         1278
3   137188        pH   7.35  26:49         1609
4   137188        pH   7.29  34:50         2090
5   137188        pH   7.37  36:46         2206
6   137188        pH   7.42  45:43         2743

In [213]:
# pH
# pH_Initial
# pH_Min
# pH_Max
# pH_Mean
# pH_Count
# pH_Slope
# pH_Miss
# pH_Last_Minute


def ph_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_min = col+'_Min'
  col_max = col+'_Max'
  col_mean = col+'_Mean'
  col_count = col+'_Count'
  col_slope = col+'_Slope'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_min] = np.nan
    df_record[col_max] = np.nan
    df_record[col_mean] = np.nan
    df_record[col_count] = 0
    df_record[col_slope] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [214]:
ph_stats(df_sub, df_record, 'pH')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute,MAP_Initial,MAP_Min,MAP_Max,MAP_Mean,MAP_SD,MAP_Count,MAP_Slope,MAP_Miss,MAP_Last_Minute,NIDiasABP_Initial,NIDiasABP_Min,NIDiasABP_Max,NIDiasABP_Mean,NIDiasABP_SD,NIDiasABP_Count,NIDiasABP_Slope,NIDiasABP_Miss,NIDiasABP_Last_Minute,NIMAP_Initial,NIMAP_Min,NIMAP_Max,NIMAP_Mean,NIMAP_SD,NIMAP_Count,NIMAP_Slope,NIMAP_Miss,NIMAP_Last_Minute,NISysABP_Initial,NISysABP_Min,NISysABP_Max,NISysABP_Mean,NISysABP_SD,NISysABP_Count,NISysABP_Slope,NISysABP_Miss,NISysABP_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.06,1.5,1.8,0.0,-20.0,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.75,40.0,39.0,51.0,187.0,73.0,121.666667,7.39,7.29,7.42,7.361429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,64,5,6,18,4,4,7,7,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,0.6,-0.2,0.0,-50.0,NaN,NaN,NaN,NaN,NaN,-0.000198,0.000168,0.044188,-0.010776,0.000673,0.000002,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,2113,2803,2819,2113,2113,2743,2743,2743,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849,81.0,60.0,95.0,76.731707,8.508891,41,0.001595,0,2849,60.0,38.0,78.0,63.75,8.466252,32,0.002046,0,1649,69.0,48.0,88.0,73.375,8.381046,32,0.001885,0,1649,97.0,82.0,121.0,104.90625,8.306078,32,0.002584,0,1649

In [215]:
df_sub = df_temp[df_temp['Parameter'] == 'Platelets'].reset_index(drop=True)
df_sub

  RecordID  Parameter  Value   Time  Time_Minute
0   137188  Platelets   85.0  03:22          202
1   137188  Platelets   71.0  11:50          710
2   137188  Platelets   88.0  35:13         2113
3   137188  Platelets   94.0  46:39         2799

In [216]:
# Platelets
# Platelets_Initial
# Platelets_Min
# Platelets_Count
# Platelets_Delta
# Platelets_Miss
# Platelets_Last_Minute


def platelets_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_min = col+'_Min'
  col_count = col+'_Count'
  col_delta = col+'_Delta'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_min] = np.nan
    df_record[col_count] = 0
    df_record[col_delta] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [217]:
platelets_stats(df_sub, df_record, 'Platelets')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute,MAP_Initial,MAP_Min,MAP_Max,MAP_Mean,MAP_SD,MAP_Count,MAP_Slope,MAP_Miss,MAP_Last_Minute,NIDiasABP_Initial,NIDiasABP_Min,NIDiasABP_Max,NIDiasABP_Mean,NIDiasABP_SD,NIDiasABP_Count,NIDiasABP_Slope,NIDiasABP_Miss,NIDiasABP_Last_Minute,NIMAP_Initial,NIMAP_Min,NIMAP_Max,NIMAP_Mean,NIMAP_SD,NIMAP_Count,NIMAP_Slope,NIMAP_Miss,NIMAP_Last_Minute,NISysABP_Initial,NISysABP_Min,NISysABP_Max,NISysABP_Mean,NISysABP_SD,NISysABP_Count,NISysABP_Slope,NISysABP_Miss,NISysABP_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.06,1.5,1.8,0.0,-20.0,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.75,40.0,39.0,51.0,187.0,73.0,121.666667,7.39,7.29,7.42,7.361429,85.0,71.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,64,5,6,18,4,4,7,7,7,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,0.6,-0.2,0.0,-50.0,9.0,NaN,NaN,NaN,NaN,-0.000198,0.000168,0.044188,-0.010776,0.000673,0.000002,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,2113,2803,2819,2113,2113,2743,2743,2743,2799,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849,81.0,60.0,95.0,76.731707,8.508891,41,0.001595,0,2849,60.0,38.0,78.0,63.75,8.466252,32,0.002046,0,1649,69.0,48.0,88.0,73.375,8.381046,32,0.001885,0,1649,97.0,82.0,121.0,104.90625,8.306078,32,0.002584,0,1649

In [218]:
df_sub = df_temp[df_temp['Parameter'] == 'RespRate'].reset_index(drop=True)
df_sub

Empty DataFrame
Columns: [RecordID, Parameter, Value, Time, Time_Minute]
Index: []

In [219]:
# RespRate
# RespRate_Initial
# RespRate_Max
# RespRate_Mean
# RespRate_Count
# RespRate_Slope
# RespRate_Miss
# RespRate_Last_Minute


def resprate_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_max = col+'_Max'
  col_mean = col+'_Mean'
  col_count = col+'_Count'
  col_slope = col+'_Slope'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_max] = np.nan
    df_record[col_mean] = np.nan
    df_record[col_count] = 0
    df_record[col_slope] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [220]:
resprate_stats(df_sub, df_record, 'RespRate')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute,MAP_Initial,MAP_Min,MAP_Max,MAP_Mean,MAP_SD,MAP_Count,MAP_Slope,MAP_Miss,MAP_Last_Minute,NIDiasABP_Initial,NIDiasABP_Min,NIDiasABP_Max,NIDiasABP_Mean,NIDiasABP_SD,NIDiasABP_Count,NIDiasABP_Slope,NIDiasABP_Miss,NIDiasABP_Last_Minute,NIMAP_Initial,NIMAP_Min,NIMAP_Max,NIMAP_Mean,NIMAP_SD,NIMAP_Count,NIMAP_Slope,NIMAP_Miss,NIMAP_Last_Minute,NISysABP_Initial,NISysABP_Min,NISysABP_Max,NISysABP_Mean,NISysABP_SD,NISysABP_Count,NISysABP_Slope,NISysABP_Miss,NISysABP_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.06,1.5,1.8,0.0,-20.0,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.75,40.0,39.0,51.0,187.0,73.0,121.666667,7.39,7.29,7.42,7.361429,85.0,71.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,64,5,6,18,4,4,7,7,7,4,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,0.6,-0.2,0.0,-50.0,9.0,NaN,NaN,NaN,NaN,-0.000198,0.000168,0.044188,-0.010776,0.000673,0.000002,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,2113,2803,2819,2113,2113,2743,2743,2743,2799,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849,81.0,60.0,95.0,76.731707,8.508891,41,0.001595,0,2849,60.0,38.0,78.0,63.75,8.466252,32,0.002046,0,1649,69.0,48.0,88.0,73.375,8.381046,32,0.001885,0,1649,97.0,82.0,121.0,104.90625,8.306078,32,0.002584,0,1649

In [221]:
df_sub = df_temp[df_temp['Parameter'] == 'SaO2'].reset_index(drop=True)
df_sub

Empty DataFrame
Columns: [RecordID, Parameter, Value, Time, Time_Minute]
Index: []

In [222]:
# SaO2
# SaO2_Initial
# SaO2_Min
# SaO2_Count
# SaO2_Delta
# SaO2_Miss
# SaO2_Last_Minute


def sao2_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_min = col+'_Min'
  col_count = col+'_Count'
  col_delta = col+'_Delta'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_min] = np.nan
    df_record[col_count] = 0
    df_record[col_delta] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [223]:
sao2_stats(df_sub, df_record, 'SaO2')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute,MAP_Initial,MAP_Min,MAP_Max,MAP_Mean,MAP_SD,MAP_Count,MAP_Slope,MAP_Miss,MAP_Last_Minute,NIDiasABP_Initial,NIDiasABP_Min,NIDiasABP_Max,NIDiasABP_Mean,NIDiasABP_SD,NIDiasABP_Count,NIDiasABP_Slope,NIDiasABP_Miss,NIDiasABP_Last_Minute,NIMAP_Initial,NIMAP_Min,NIMAP_Max,NIMAP_Mean,NIMAP_SD,NIMAP_Count,NIMAP_Slope,NIMAP_Miss,NIMAP_Last_Minute,NISysABP_Initial,NISysABP_Min,NISysABP_Max,NISysABP_Mean,NISysABP_SD,NISysABP_Count,NISysABP_Slope,NISysABP_Miss,NISysABP_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.06,1.5,1.8,0.0,-20.0,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.75,40.0,39.0,51.0,187.0,73.0,121.666667,7.39,7.29,7.42,7.361429,85.0,71.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,64,5,6,18,4,4,7,7,7,4,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,0.6,-0.2,0.0,-50.0,9.0,0,NaN,NaN,NaN,-0.000198,0.000168,0.044188,-0.010776,0.000673,0.000002,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,2113,2803,2819,2113,2113,2743,2743,2743,2799,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849,81.0,60.0,95.0,76.731707,8.508891,41,0.001595,0,2849,60.0,38.0,78.0,63.75,8.466252,32,0.002046,0,1649,69.0,48.0,88.0,73.375,8.381046,32,0.001885,0,1649,97.0,82.0,121.0,104.90625,8.306078,32,0.002584,0,1649

In [224]:
df_sub = df_temp[df_temp['Parameter'] == 'SysABP'].reset_index(drop=True)
df_sub

   RecordID Parameter  Value   Time  Time_Minute
0    137188    SysABP  112.0  17:59         1079
1    137188    SysABP  112.0  18:29         1109
2    137188    SysABP  124.0  18:59         1139
3    137188    SysABP  115.0  19:29         1169
4    137188    SysABP  107.0  19:44         1184
5    137188    SysABP   92.0  19:54         1194
6    137188    SysABP   96.0  19:59         1199
7    137188    SysABP  102.0  20:29         1229
8    137188    SysABP  103.0  21:29         1289
9    137188    SysABP  121.0  22:29         1349
10   137188    SysABP  123.0  22:44         1364
11   137188    SysABP  116.0  23:29         1409
12   137188    SysABP  115.0  24:29         1469
13   137188    SysABP  131.0  25:29         1529
14   137188    SysABP  109.0  26:29         1589
15   137188    SysABP  122.0  27:29         1649
16   137188    SysABP  106.0  28:29         1709
17   137188    SysABP  107.0  29:29         1769
18   137188    SysABP   90.0  29:44         1784
19   137188    SysABP   89.0  29:59         1799
20   137188    SysABP  117.0  30:29         1829
21   137188    SysABP  103.0  31:29         1889
22   137188    SysABP  117.0  32:29         1949
23   137188    SysABP  103.0  33:29         2009
24   137188    SysABP   97.0  34:29         2069
25   137188    SysABP  100.0  35:29         2129
26   137188    SysABP  102.0  36:29         2189
27   137188    SysABP  104.0  37:29         2249
28   137188    SysABP  111.0  38:29         2309
29   137188    SysABP  121.0  39:29         2369
30   137188    SysABP  113.0  40:29         2429
31   137188    SysABP  130.0  41:59         2519
32   137188    SysABP  119.0  42:29         2549
33   137188    SysABP  123.0  42:59         2579
34   137188    SysABP  117.0  43:29         2609
35   137188    SysABP  121.0  44:29         2669
36   137188    SysABP  116.0  44:59         2699
37   137188    SysABP  115.0  45:29         2729
38   137188    SysABP  109.0  46:29         2789
39   137188    SysABP  110.0  46:59         2819
40   137188    SysABP  123.0  47:29         2849

In [225]:
# SysABP
# SysABP_Initial
# SysABP_Min
# SysABP_Max
# SysABP_Mean
# SysABP_SD
# SysABP_Time_Duration - threshold < 90 x
# SysABP_Count
# SysABP_Slope
# SysABP_Miss
# SysABP_Last_Minute


def sysabp_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_min = col+'_Min'
  col_max = col+'_Max'
  col_mean = col+'_Mean'
  col_sd = col+'_SD'
  #col_td = col+'_Time_Duration'
  #threshold = 90
  col_count = col+'_Count'
  col_slope = col+'_Slope'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_min] = np.nan
    df_record[col_max] = np.nan
    df_record[col_mean] = np.nan
    df_record[col_sd] = np.nan
    #df_record[col_td] = np.nan
    df_record[col_count] = 0
    df_record[col_slope] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_sd] = np.nan
      #df_record[col_td] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_sd] = 0
      #df_record[col_td] = 0
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_sd] = np.nan
      #df_record[col_td] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_sd] = df_sub['Value'].std()
      #max_duration, max_begin, max_end = find_max_duration(df_sub, threshold, 'below')
      #time_duration, time_begin, time_end = find_time_duration(df_sub, max_begin, max_end)
      #df_record[col_td] = time_duration
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [226]:
sysabp_stats(df_sub, df_record, 'SysABP')

/tmp/ipykernel_245953/2051913423.py:74: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_initial] = df_sub['Value'].iloc[0]
/tmp/ipykernel_245953/2051913423.py:75: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_min] = df_sub['Value'].min()
/tmp/ipykernel_245953/2051913423.py:76: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_max] = df_sub['Value'].max()
/tmp/ipykernel_245953/2051913423.py:77: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_mean] = df_sub['Value'].mean()
/tmp/ipykernel_245953/2051913423.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_sd] = df_sub['Value'].std()
/tmp/ipykernel_245953/2051913423.py:82: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_count] = df_sub['Value'].count()
/tmp/ipykernel_245953/2051913423.py:83: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_slope] = compute_regression_slope(df_sub)
/tmp/ipykernel_245953/2051913423.py:84: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_miss] = 0
/tmp/ipykernel_245953/2051913423.py:85: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute,MAP_Initial,MAP_Min,MAP_Max,MAP_Mean,MAP_SD,MAP_Count,MAP_Slope,MAP_Miss,MAP_Last_Minute,NIDiasABP_Initial,NIDiasABP_Min,NIDiasABP_Max,NIDiasABP_Mean,NIDiasABP_SD,NIDiasABP_Count,NIDiasABP_Slope,NIDiasABP_Miss,NIDiasABP_Last_Minute,NIMAP_Initial,NIMAP_Min,NIMAP_Max,NIMAP_Mean,NIMAP_SD,NIMAP_Count,NIMAP_Slope,NIMAP_Miss,NIMAP_Last_Minute,NISysABP_Initial,NISysABP_Min,NISysABP_Max,NISysABP_Mean,NISysABP_SD,NISysABP_Count,NISysABP_Slope,NISysABP_Miss,NISysABP_Last_Minute,SysABP_Initial,SysABP_Min,SysABP_Max,SysABP_Mean,SysABP_SD,SysABP_Count,SysABP_Slope,SysABP_Miss,SysABP_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.06,1.5,1.8,0.0,-20.0,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.75,40.0,39.0,51.0,187.0,73.0,121.666667,7.39,7.29,7.42,7.361429,85.0,71.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,64,5,6,18,4,4,7,7,7,4,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,0.6,-0.2,0.0,-50.0,9.0,0,NaN,NaN,NaN,-0.000198,0.000168,0.044188,-0.010776,0.000673,0.000002,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,2113,2803,2819,2113,2113,2743,2743,2743,2799,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849,81.0,60.0,95.0,76.731707,8.508891,41,0.001595,0,2849,60.0,38.0,78.0,63.75,8.466252,32,0.002046,0,1649,69.0,48.0,88.0,73.375,8.381046,32,0.001885,0,1649,97.0,82.0,121.0,104.90625,8.306078,32,0.002584,0,1649,112.0,89.0,131.0,111.292683,10.431308,41,0.003873,0,2849

In [227]:
df_sub = df_temp[df_temp['Parameter'] == 'Temp'].reset_index(drop=True)
df_sub

   RecordID Parameter  Value   Time  Time_Minute
0    137188      Temp   37.6  02:14          134
1    137188      Temp   37.6  04:29          269
2    137188      Temp   37.7  06:29          389
3    137188      Temp   38.7  10:29          629
4    137188      Temp   38.9  12:29          749
5    137188      Temp   38.8  13:29          809
6    137188      Temp   38.8  14:29          869
7    137188      Temp   37.7  16:14          974
8    137188      Temp   37.7  16:29          989
9    137188      Temp   37.4  16:44         1004
10   137188      Temp   36.9  17:29         1049
11   137188      Temp   36.9  18:29         1109
12   137188      Temp   36.9  19:29         1169
13   137188      Temp   36.7  20:29         1229
14   137188      Temp   36.7  22:29         1349
15   137188      Temp   37.1  24:29         1469
16   137188      Temp   37.3  25:29         1529
17   137188      Temp   36.9  26:29         1589
18   137188      Temp   37.3  27:29         1649
19   137188      Temp   37.3  28:29         1709
20   137188      Temp   36.5  29:29         1769
21   137188      Temp   36.3  29:44         1784
22   137188      Temp   36.5  30:29         1829
23   137188      Temp   36.8  32:29         1949
24   137188      Temp   37.1  34:29         2069
25   137188      Temp   37.1  36:29         2189
26   137188      Temp   37.3  38:29         2309
27   137188      Temp   37.4  40:29         2429
28   137188      Temp   37.2  42:29         2549
29   137188      Temp   37.2  44:59         2699
30   137188      Temp   37.2  46:29         2789
31   137188      Temp   37.2  46:59         2819
32   137188      Temp   37.2  47:14         2834
33   137188      Temp   37.3  47:29         2849

In [228]:
# Temp
# Temp_Initial
# Temp_Min
# Temp_Max
# Temp_Mean
# Temp_SD
# Temp_Count
# Temp_Slope
# Temp_Miss
# Temp_Last_Minute


def temp_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_min = col+'_Min'
  col_max = col+'_Max'
  col_mean = col+'_Mean'
  col_sd = col+'_SD'
  col_count = col+'_Count'
  col_slope = col+'_Slope'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_min] = np.nan
    df_record[col_max] = np.nan
    df_record[col_mean] = np.nan
    df_record[col_sd] = np.nan
    df_record[col_count] = 0
    df_record[col_slope] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_sd] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_sd] = 0
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_sd] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_sd] = df_sub['Value'].std()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  return df_record

In [229]:
temp_stats(df_sub, df_record, 'Temp')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute,MAP_Initial,MAP_Min,MAP_Max,MAP_Mean,MAP_SD,MAP_Count,MAP_Slope,MAP_Miss,MAP_Last_Minute,NIDiasABP_Initial,NIDiasABP_Min,NIDiasABP_Max,NIDiasABP_Mean,NIDiasABP_SD,NIDiasABP_Count,NIDiasABP_Slope,NIDiasABP_Miss,NIDiasABP_Last_Minute,NIMAP_Initial,NIMAP_Min,NIMAP_Max,NIMAP_Mean,NIMAP_SD,NIMAP_Count,NIMAP_Slope,NIMAP_Miss,NIMAP_Last_Minute,NISysABP_Initial,NISysABP_Min,NISysABP_Max,NISysABP_Mean,NISysABP_SD,NISysABP_Count,NISysABP_Slope,NISysABP_Miss,NISysABP_Last_Minute,SysABP_Initial,SysABP_Min,SysABP_Max,SysABP_Mean,SysABP_SD,SysABP_Count,SysABP_Slope,SysABP_Miss,SysABP_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.06,1.5,1.8,0.0,-20.0,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.75,40.0,39.0,51.0,187.0,73.0,121.666667,7.39,7.29,7.42,7.361429,85.0,71.0,NaN,NaN,NaN,NaN,NaN,37.6,36.3,38.9,37.329412,0.645041,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,64,5,6,18,4,4,7,7,7,4,0,0,34,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,0.6,-0.2,0.0,-50.0,9.0,0,NaN,NaN,NaN,-0.000198,0.000168,0.044188,-0.010776,0.000673,0.000002,0,-0.000355,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,2113,2803,2819,2113,2113,2743,2743,2743,2799,0,0,2849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849,81.0,60.0,95.0,76.731707,8.508891,41,0.001595,0,2849,60.0,38.0,78.0,63.75,8.466252,32,0.002046,0,1649,69.0,48.0,88.0,73.375,8.381046,32,0.001885,0,1649,97.0,82.0,121.0,104.90625,8.306078,32,0.002584,0,1649,112.0,89.0,131.0,111.292683,10.431308,41,0.003873,0,2849

In [230]:
df_sub = df_temp[df_temp['Parameter'] == 'TroponinI'].reset_index(drop=True)
df_sub

Empty DataFrame
Columns: [RecordID, Parameter, Value, Time, Time_Minute]
Index: []

In [231]:
# TroponinI
# TroponinI_Max
# TroponinI_Count
# TroponinI_Slope
# TroponinI_Miss
# TroponinI_Last_Minute


def troponini_stats(df_sub, df_record, col):
  col_max = col+'_Max'
  col_count = col+'_Count'
  col_slope = col+'_Slope'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_max] = np.nan
    df_record[col_count] = 0
    df_record[col_slope] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_max] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_end_to_end_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_max] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_end_to_end_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [232]:
troponini_stats(df_sub, df_record, 'TroponinI')

/tmp/ipykernel_245953/1837484740.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_max] = np.nan
/tmp/ipykernel_245953/1837484740.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_count] = 0
/tmp/ipykernel_245953/1837484740.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_slope] = 0
/tmp/ipykernel_245953/1837484740.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_miss] = 1
/tmp/ipykernel_245953/1837484740.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_last_minute] = 0

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute,MAP_Initial,MAP_Min,MAP_Max,MAP_Mean,MAP_SD,MAP_Count,MAP_Slope,MAP_Miss,MAP_Last_Minute,NIDiasABP_Initial,NIDiasABP_Min,NIDiasABP_Max,NIDiasABP_Mean,NIDiasABP_SD,NIDiasABP_Count,NIDiasABP_Slope,NIDiasABP_Miss,NIDiasABP_Last_Minute,NIMAP_Initial,NIMAP_Min,NIMAP_Max,NIMAP_Mean,NIMAP_SD,NIMAP_Count,NIMAP_Slope,NIMAP_Miss,NIMAP_Last_Minute,NISysABP_Initial,NISysABP_Min,NISysABP_Max,NISysABP_Mean,NISysABP_SD,NISysABP_Count,NISysABP_Slope,NISysABP_Miss,NISysABP_Last_Minute,SysABP_Initial,SysABP_Min,SysABP_Max,SysABP_Mean,SysABP_SD,SysABP_Count,SysABP_Slope,SysABP_Miss,SysABP_Last_Minute,TroponinI_Max,TroponinI_Count,TroponinI_Slope,TroponinI_Miss,TroponinI_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.06,1.5,1.8,0.0,-20.0,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.75,40.0,39.0,51.0,187.0,73.0,121.666667,7.39,7.29,7.42,7.361429,85.0,71.0,NaN,NaN,NaN,NaN,NaN,37.6,36.3,38.9,37.329412,0.645041,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,64,5,6,18,4,4,7,7,7,4,0,0,34,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,0.6,-0.2,0.0,-50.0,9.0,0,NaN,NaN,NaN,-0.000198,0.000168,0.044188,-0.010776,0.000673,0.000002,0,-0.000355,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,2113,2803,2819,2113,2113,2743,2743,2743,2799,0,0,2849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849,81.0,60.0,95.0,76.731707,8.508891,41,0.001595,0,2849,60.0,38.0,78.0,63.75,8.466252,32,0.002046,0,1649,69.0,48.0,88.0,73.375,8.381046,32,0.001885,0,1649,97.0,82.0,121.0,104.90625,8.306078,32,0.002584,0,1649,112.0,89.0,131.0,111.292683,10.431308,41,0.003873,0,2849,NaN,0,0,1,0

In [233]:
df_sub = df_temp[df_temp['Parameter'] == 'TroponinT'].reset_index(drop=True)
df_sub

  RecordID  Parameter  Value   Time  Time_Minute
0   137188  TroponinT   0.40  03:22          202
1   137188  TroponinT   0.32  11:50          710
2   137188  TroponinT   0.22  22:00         1320

In [234]:
# TroponinT
# TroponinT_Max
# TroponinT_Count
# TroponinT_Slope
# TroponinT_Miss
# TroponinT_Last_Minute


def troponint_stats(df_sub, df_record, col):
  col_max = col+'_Max'
  col_count = col+'_Count'
  col_slope = col+'_Slope'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_max] = np.nan
    df_record[col_count] = 0
    df_record[col_slope] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_max] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_end_to_end_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_max] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_end_to_end_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [235]:
troponint_stats(df_sub, df_record, 'TroponinT')

/tmp/ipykernel_245953/2252501039.py:43: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_max] = df_sub['Value'].max()
/tmp/ipykernel_245953/2252501039.py:44: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_count] = df_sub['Value'].count()
/tmp/ipykernel_245953/2252501039.py:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_slope] = compute_end_to_end_slope(df_sub)
/tmp/ipykernel_245953/2252501039.py:46: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_miss] = 0
/tmp/ipykernel_245953/2252501039.py:47: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute,MAP_Initial,MAP_Min,MAP_Max,MAP_Mean,MAP_SD,MAP_Count,MAP_Slope,MAP_Miss,MAP_Last_Minute,NIDiasABP_Initial,NIDiasABP_Min,NIDiasABP_Max,NIDiasABP_Mean,NIDiasABP_SD,NIDiasABP_Count,NIDiasABP_Slope,NIDiasABP_Miss,NIDiasABP_Last_Minute,NIMAP_Initial,NIMAP_Min,NIMAP_Max,NIMAP_Mean,NIMAP_SD,NIMAP_Count,NIMAP_Slope,NIMAP_Miss,NIMAP_Last_Minute,NISysABP_Initial,NISysABP_Min,NISysABP_Max,NISysABP_Mean,NISysABP_SD,NISysABP_Count,NISysABP_Slope,NISysABP_Miss,NISysABP_Last_Minute,SysABP_Initial,SysABP_Min,SysABP_Max,SysABP_Mean,SysABP_SD,SysABP_Count,SysABP_Slope,SysABP_Miss,SysABP_Last_Minute,TroponinI_Max,TroponinI_Count,TroponinI_Slope,TroponinI_Miss,TroponinI_Last_Minute,TroponinT_Max,TroponinT_Count,TroponinT_Slope,TroponinT_Miss,TroponinT_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.06,1.5,1.8,0.0,-20.0,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.75,40.0,39.0,51.0,187.0,73.0,121.666667,7.39,7.29,7.42,7.361429,85.0,71.0,NaN,NaN,NaN,NaN,NaN,37.6,36.3,38.9,37.329412,0.645041,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,64,5,6,18,4,4,7,7,7,4,0,0,34,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,0.6,-0.2,0.0,-50.0,9.0,0,NaN,NaN,NaN,-0.000198,0.000168,0.044188,-0.010776,0.000673,0.000002,0,-0.000355,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,2113,2803,2819,2113,2113,2743,2743,2743,2799,0,0,2849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849,81.0,60.0,95.0,76.731707,8.508891,41,0.001595,0,2849,60.0,38.0,78.0,63.75,8.466252,32,0.002046,0,1649,69.0,48.0,88.0,73.375,8.381046,32,0.001885,0,1649,97.0,82.0,121.0,104.90625,8.306078,32,0.002584,0,1649,112.0,89.0,131.0,111.292683,10.431308,41,0.003873,0,2849,NaN,0,0,1,0,0.4,3,-0.000161,0,1320

In [236]:
df_sub = df_temp[df_temp['Parameter'] == 'Urine'].reset_index(drop=True)
df_sub

   RecordID Parameter  Value   Time  Time_Minute
0    137188     Urine  200.0  02:14          134
1    137188     Urine  380.0  04:29          269
2    137188     Urine  225.0  05:29          329
3    137188     Urine  150.0  06:29          389
4    137188     Urine  125.0  08:29          509
5    137188     Urine  100.0  10:29          629
6    137188     Urine   80.0  12:29          749
7    137188     Urine   75.0  14:29          869
8    137188     Urine  175.0  16:29          989
9    137188     Urine  125.0  17:29         1049
10   137188     Urine  100.0  18:29         1109
11   137188     Urine  135.0  19:29         1169
12   137188     Urine   65.0  20:29         1229
13   137188     Urine   40.0  21:29         1289
14   137188     Urine   41.0  22:29         1349
15   137188     Urine   75.0  24:29         1469
16   137188     Urine   27.0  25:29         1529
17   137188     Urine   30.0  26:29         1589
18   137188     Urine   28.0  27:29         1649
19   137188     Urine   10.0  28:29         1709
20   137188     Urine   12.0  29:29         1769
21   137188     Urine   33.0  30:29         1829
22   137188     Urine   20.0  31:29         1889
23   137188     Urine   40.0  32:29         1949
24   137188     Urine   40.0  34:29         2069
25   137188     Urine   17.0  35:29         2129
26   137188     Urine   20.0  36:29         2189
27   137188     Urine   70.0  38:29         2309
28   137188     Urine   35.0  39:29         2369
29   137188     Urine   40.0  40:29         2429
30   137188     Urine   65.0  42:29         2549
31   137188     Urine   35.0  43:29         2609
32   137188     Urine   30.0  44:29         2669
33   137188     Urine   80.0  45:29         2729
34   137188     Urine   20.0  46:29         2789
35   137188     Urine   20.0  47:29         2849

In [237]:
df_sub2 = df_temp[df_temp['Parameter'] == 'Weight'].reset_index(drop=True)
df_sub2

   RecordID Parameter  Value   Time  Time_Minute
0    137188    Weight   59.6  00:00            0
1    137188    Weight   59.6  02:14          134
2    137188    Weight   59.6  02:29          149
3    137188    Weight   59.6  02:44          164
4    137188    Weight   59.6  02:59          179
5    137188    Weight   59.6  03:14          194
6    137188    Weight   59.6  03:29          209
7    137188    Weight   59.6  03:59          239
8    137188    Weight   59.6  04:29          269
9    137188    Weight   59.6  05:29          329
10   137188    Weight   59.6  06:29          389
11   137188    Weight   59.6  07:29          449
12   137188    Weight   59.6  08:29          509
13   137188    Weight   59.6  09:29          569
14   137188    Weight   59.6  10:29          629
15   137188    Weight   59.6  11:29          689
16   137188    Weight   59.6  12:29          749
17   137188    Weight   59.6  13:29          809
18   137188    Weight   59.6  14:29          869
19   137188    Weight   59.6  15:29          929
20   137188    Weight   59.6  15:59          959
21   137188    Weight   59.6  16:14          974
22   137188    Weight   59.6  16:29          989
23   137188    Weight   59.6  16:44         1004
24   137188    Weight   59.6  17:29         1049
25   137188    Weight   59.6  17:59         1079
26   137188    Weight   59.6  18:29         1109
27   137188    Weight   59.6  18:59         1139
28   137188    Weight   59.6  19:29         1169
29   137188    Weight   59.6  19:44         1184
30   137188    Weight   59.6  19:54         1194
31   137188    Weight   59.6  19:59         1199
32   137188    Weight   59.6  20:29         1229
33   137188    Weight   59.6  21:29         1289
34   137188    Weight   59.6  22:29         1349
35   137188    Weight   59.6  22:44         1364
36   137188    Weight   59.6  23:29         1409
37   137188    Weight   59.6  25:29         1529
38   137188    Weight   59.6  26:29         1589
39   137188    Weight   59.6  27:29         1649
40   137188    Weight   59.6  28:29         1709
41   137188    Weight   59.6  29:29         1769
42   137188    Weight   59.6  29:44         1784
43   137188    Weight   59.6  29:59         1799
44   137188    Weight   59.6  30:29         1829
45   137188    Weight   59.6  31:29         1889
46   137188    Weight   59.6  32:29         1949
47   137188    Weight   59.6  33:29         2009
48   137188    Weight   59.6  34:29         2069
49   137188    Weight   59.6  35:29         2129
50   137188    Weight   59.6  36:29         2189
51   137188    Weight   59.6  37:29         2249
52   137188    Weight   59.6  38:29         2309
53   137188    Weight   59.6  39:29         2369
54   137188    Weight   59.6  40:29         2429
55   137188    Weight   59.6  41:59         2519
56   137188    Weight   59.6  42:29         2549
57   137188    Weight   59.6  42:59         2579
58   137188    Weight   59.6  43:29         2609
59   137188    Weight   59.6  44:29         2669
60   137188    Weight   59.6  44:59         2699
61   137188    Weight   59.6  45:29         2729
62   137188    Weight   59.6  46:29         2789
63   137188    Weight   59.6  46:59         2819
64   137188    Weight   59.6  47:29         2849

In [238]:
# Urine
# Urine_Sum = sum(x)
# Urine_MinRate - Min Rate (mL/kg/hr)
# Urine_MaxRate
# Urine_MeanRate
# Urine_Count
# Urine_Rate_Slope
# Urine_Miss
# Urine_Last_Minute


def urine_stats(df_sub, df_sub2, df_record, col):
  col_sum = col+'_Sum'
  col_minr = col+'_MinRate'
  col_maxr = col+'_MaxRate'
  col_meanr = col+'_MeanRate'
  col_count = col+'_Count'
  col_slope = col+'_Rate_Slope'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_sum] = np.nan
    df_record[col_minr] = np.nan
    df_record[col_maxr] = np.nan
    df_record[col_meanr] = np.nan
    df_record[col_count] = 0
    df_record[col_slope] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_sum] = np.nan
      df_record[col_minr] = np.nan
      df_record[col_maxr] = np.nan
      df_record[col_meanr] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_sum] = df_sub['Value'].sum()
      df_record[col_minr] = find_uminr(df_sub, df_sub2)
      df_record[col_maxr] = find_umaxr(df_sub, df_sub2)
      df_record[col_meanr] = find_umeanr(df_sub, df_sub2)
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_urine_rate_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_sum] = np.nan
      df_record[col_minr] = np.nan
      df_record[col_maxr] = np.nan
      df_record[col_meanr] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_sum] = df_sub['Value'].sum()
      df_record[col_minr] = find_uminr(df_sub, df_sub2)
      df_record[col_maxr] = find_umaxr(df_sub, df_sub2)
      df_record[col_meanr] = find_umeanr(df_sub, df_sub2)
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_urine_rate_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  return df_record

In [239]:
urine_stats(df_sub, df_sub2, df_record, 'Urine')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute,MAP_Initial,MAP_Min,MAP_Max,MAP_Mean,MAP_SD,MAP_Count,MAP_Slope,MAP_Miss,MAP_Last_Minute,NIDiasABP_Initial,NIDiasABP_Min,NIDiasABP_Max,NIDiasABP_Mean,NIDiasABP_SD,NIDiasABP_Count,NIDiasABP_Slope,NIDiasABP_Miss,NIDiasABP_Last_Minute,NIMAP_Initial,NIMAP_Min,NIMAP_Max,NIMAP_Mean,NIMAP_SD,NIMAP_Count,NIMAP_Slope,NIMAP_Miss,NIMAP_Last_Minute,NISysABP_Initial,NISysABP_Min,NISysABP_Max,NISysABP_Mean,NISysABP_SD,NISysABP_Count,NISysABP_Slope,NISysABP_Miss,NISysABP_Last_Minute,SysABP_Initial,SysABP_Min,SysABP_Max,SysABP_Mean,SysABP_SD,SysABP_Count,SysABP_Slope,SysABP_Miss,SysABP_Last_Minute,TroponinI_Max,TroponinI_Count,TroponinI_Slope,TroponinI_Miss,TroponinI_Last_Minute,TroponinT_Max,TroponinT_Count,TroponinT_Slope,TroponinT_Miss,TroponinT_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.06,1.5,1.8,0.0,-20.0,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.75,40.0,39.0,51.0,187.0,73.0,121.666667,7.39,7.29,7.42,7.361429,85.0,71.0,NaN,NaN,NaN,NaN,NaN,37.6,36.3,38.9,37.329412,0.645041,2763.0,0.167785,3.775168,0.93451,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,64,5,6,18,4,4,7,7,7,4,0,0,34,36,NaN,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,0.6,-0.2,0.0,-50.0,9.0,0,NaN,NaN,NaN,-0.000198,0.000168,0.044188,-0.010776,0.000673,0.000002,0,-0.000355,-2.38014,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,2113,2803,2819,2113,2113,2743,2743,2743,2799,0,0,2849,2849,NaN,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849,81.0,60.0,95.0,76.731707,8.508891,41,0.001595,0,2849,60.0,38.0,78.0,63.75,8.466252,32,0.002046,0,1649,69.0,48.0,88.0,73.375,8.381046,32,0.001885,0,1649,97.0,82.0,121.0,104.90625,8.306078,32,0.002584,0,1649,112.0,89.0,131.0,111.292683,10.431308,41,0.003873,0,2849,NaN,0,0,1,0,0.4,3,-0.000161,0,1320

In [240]:
df_sub = df_temp[df_temp['Parameter'] == 'WBC'].reset_index(drop=True)
df_sub

  RecordID Parameter  Value   Time  Time_Minute
0   137188       WBC   13.3  03:22          202
1   137188       WBC    9.6  11:50          710
2   137188       WBC   10.4  35:13         2113
3   137188       WBC    9.3  46:39         2799

In [241]:
# WBC
# WBC_Initial
# WBC_Min
# WBC_Max
# WBC_Count
# WBC_Delta
# WBC_Miss
# WBC_Last_Minute


def wbc_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_min = col+'_Min'
  col_max = col+'_Max'
  col_count = col+'_Count'
  col_delta = col+'_Delta'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_min] = np.nan
    df_record[col_max] = np.nan
    df_record[col_count] = 0
    df_record[col_delta] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [242]:
wbc_stats(df_sub, df_record, 'WBC')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute,MAP_Initial,MAP_Min,MAP_Max,MAP_Mean,MAP_SD,MAP_Count,MAP_Slope,MAP_Miss,MAP_Last_Minute,NIDiasABP_Initial,NIDiasABP_Min,NIDiasABP_Max,NIDiasABP_Mean,NIDiasABP_SD,NIDiasABP_Count,NIDiasABP_Slope,NIDiasABP_Miss,NIDiasABP_Last_Minute,NIMAP_Initial,NIMAP_Min,NIMAP_Max,NIMAP_Mean,NIMAP_SD,NIMAP_Count,NIMAP_Slope,NIMAP_Miss,NIMAP_Last_Minute,NISysABP_Initial,NISysABP_Min,NISysABP_Max,NISysABP_Mean,NISysABP_SD,NISysABP_Count,NISysABP_Slope,NISysABP_Miss,NISysABP_Last_Minute,SysABP_Initial,SysABP_Min,SysABP_Max,SysABP_Mean,SysABP_SD,SysABP_Count,SysABP_Slope,SysABP_Miss,SysABP_Last_Minute,TroponinI_Max,TroponinI_Count,TroponinI_Slope,TroponinI_Miss,TroponinI_Last_Minute,TroponinT_Max,TroponinT_Count,TroponinT_Slope,TroponinT_Miss,TroponinT_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.06,1.5,1.8,0.0,-20.0,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.75,40.0,39.0,51.0,187.0,73.0,121.666667,7.39,7.29,7.42,7.361429,85.0,71.0,NaN,NaN,NaN,NaN,NaN,37.6,36.3,38.9,37.329412,0.645041,2763.0,0.167785,3.775168,0.93451,13.3,9.3,13.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,64,5,6,18,4,4,7,7,7,4,0,0,34,36,4,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,0.6,-0.2,0.0,-50.0,9.0,0,-4.0,NaN,NaN,-0.000198,0.000168,0.044188,-0.010776,0.000673,0.000002,0,-0.000355,-2.38014,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,NaN,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,2113,2803,2819,2113,2113,2743,2743,2743,2799,0,0,2849,2849,2799,NaN,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849,81.0,60.0,95.0,76.731707,8.508891,41,0.001595,0,2849,60.0,38.0,78.0,63.75,8.466252,32,0.002046,0,1649,69.0,48.0,88.0,73.375,8.381046,32,0.001885,0,1649,97.0,82.0,121.0,104.90625,8.306078,32,0.002584,0,1649,112.0,89.0,131.0,111.292683,10.431308,41,0.003873,0,2849,NaN,0,0,1,0,0.4,3,-0.000161,0,1320

In [243]:
df_sub = df_temp[df_temp['Parameter'] == 'Weight'].reset_index(drop=True)
df_sub

   RecordID Parameter  Value   Time  Time_Minute
0    137188    Weight   59.6  00:00            0
1    137188    Weight   59.6  02:14          134
2    137188    Weight   59.6  02:29          149
3    137188    Weight   59.6  02:44          164
4    137188    Weight   59.6  02:59          179
5    137188    Weight   59.6  03:14          194
6    137188    Weight   59.6  03:29          209
7    137188    Weight   59.6  03:59          239
8    137188    Weight   59.6  04:29          269
9    137188    Weight   59.6  05:29          329
10   137188    Weight   59.6  06:29          389
11   137188    Weight   59.6  07:29          449
12   137188    Weight   59.6  08:29          509
13   137188    Weight   59.6  09:29          569
14   137188    Weight   59.6  10:29          629
15   137188    Weight   59.6  11:29          689
16   137188    Weight   59.6  12:29          749
17   137188    Weight   59.6  13:29          809
18   137188    Weight   59.6  14:29          869
19   137188    Weight   59.6  15:29          929
20   137188    Weight   59.6  15:59          959
21   137188    Weight   59.6  16:14          974
22   137188    Weight   59.6  16:29          989
23   137188    Weight   59.6  16:44         1004
24   137188    Weight   59.6  17:29         1049
25   137188    Weight   59.6  17:59         1079
26   137188    Weight   59.6  18:29         1109
27   137188    Weight   59.6  18:59         1139
28   137188    Weight   59.6  19:29         1169
29   137188    Weight   59.6  19:44         1184
30   137188    Weight   59.6  19:54         1194
31   137188    Weight   59.6  19:59         1199
32   137188    Weight   59.6  20:29         1229
33   137188    Weight   59.6  21:29         1289
34   137188    Weight   59.6  22:29         1349
35   137188    Weight   59.6  22:44         1364
36   137188    Weight   59.6  23:29         1409
37   137188    Weight   59.6  25:29         1529
38   137188    Weight   59.6  26:29         1589
39   137188    Weight   59.6  27:29         1649
40   137188    Weight   59.6  28:29         1709
41   137188    Weight   59.6  29:29         1769
42   137188    Weight   59.6  29:44         1784
43   137188    Weight   59.6  29:59         1799
44   137188    Weight   59.6  30:29         1829
45   137188    Weight   59.6  31:29         1889
46   137188    Weight   59.6  32:29         1949
47   137188    Weight   59.6  33:29         2009
48   137188    Weight   59.6  34:29         2069
49   137188    Weight   59.6  35:29         2129
50   137188    Weight   59.6  36:29         2189
51   137188    Weight   59.6  37:29         2249
52   137188    Weight   59.6  38:29         2309
53   137188    Weight   59.6  39:29         2369
54   137188    Weight   59.6  40:29         2429
55   137188    Weight   59.6  41:59         2519
56   137188    Weight   59.6  42:29         2549
57   137188    Weight   59.6  42:59         2579
58   137188    Weight   59.6  43:29         2609
59   137188    Weight   59.6  44:29         2669
60   137188    Weight   59.6  44:59         2699
61   137188    Weight   59.6  45:29         2729
62   137188    Weight   59.6  46:29         2789
63   137188    Weight   59.6  46:59         2819
64   137188    Weight   59.6  47:29         2849

In [244]:
# Weight
# Weight_Initial
# Weight_Final
# Weight_Count x
# Weight_Delta
# Weight_Miss
# Weight_Last_Minute


def weight_stats(df_sub, df_record, col):
  col_initial = col+'_Initial'
  col_final = col+'_Final'
  #col_count = col+'_Count'
  col_delta = col+'_Delta'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_final] = np.nan
    #df_record[col_count] = 0
    df_record[col_delta] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_final] = np.nan
      #df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_final] = df_sub['Value'].iloc[-1]
      #df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_final] = np.nan
      #df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_final] = df_sub['Value'].iloc[-1]
      #df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [245]:
weight_stats(df_sub, df_record, 'Weight')

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute,MAP_Initial,MAP_Min,MAP_Max,MAP_Mean,MAP_SD,MAP_Count,MAP_Slope,MAP_Miss,MAP_Last_Minute,NIDiasABP_Initial,NIDiasABP_Min,NIDiasABP_Max,NIDiasABP_Mean,NIDiasABP_SD,NIDiasABP_Count,NIDiasABP_Slope,NIDiasABP_Miss,NIDiasABP_Last_Minute,NIMAP_Initial,NIMAP_Min,NIMAP_Max,NIMAP_Mean,NIMAP_SD,NIMAP_Count,NIMAP_Slope,NIMAP_Miss,NIMAP_Last_Minute,NISysABP_Initial,NISysABP_Min,NISysABP_Max,NISysABP_Mean,NISysABP_SD,NISysABP_Count,NISysABP_Slope,NISysABP_Miss,NISysABP_Last_Minute,SysABP_Initial,SysABP_Min,SysABP_Max,SysABP_Mean,SysABP_SD,SysABP_Count,SysABP_Slope,SysABP_Miss,SysABP_Last_Minute,TroponinI_Max,TroponinI_Count,TroponinI_Slope,TroponinI_Miss,TroponinI_Last_Minute,TroponinT_Max,TroponinT_Count,TroponinT_Slope,TroponinT_Miss,TroponinT_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.06,1.5,1.8,0.0,-20.0,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.75,40.0,39.0,51.0,187.0,73.0,121.666667,7.39,7.29,7.42,7.361429,85.0,71.0,NaN,NaN,NaN,NaN,NaN,37.6,36.3,38.9,37.329412,0.645041,2763.0,0.167785,3.775168,0.93451,13.3,9.3,13.3,59.6,59.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,64,5,6,18,4,4,7,7,7,4,0,0,34,36,4,NaN,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,0.6,-0.2,0.0,-50.0,9.0,0,-4.0,0.0,NaN,-0.000198,0.000168,0.044188,-0.010776,0.000673,0.000002,0,-0.000355,-2.38014,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,NaN,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,2113,2803,2819,2113,2113,2743,2743,2743,2799,0,0,2849,2849,2799,2849,NaN,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849,81.0,60.0,95.0,76.731707,8.508891,41,0.001595,0,2849,60.0,38.0,78.0,63.75,8.466252,32,0.002046,0,1649,69.0,48.0,88.0,73.375,8.381046,32,0.001885,0,1649,97.0,82.0,121.0,104.90625,8.306078,32,0.002584,0,1649,112.0,89.0,131.0,111.292683,10.431308,41,0.003873,0,2849,NaN,0,0,1,0,0.4,3,-0.000161,0,1320

In [246]:
df1 = df_temp[df_temp['Parameter'] == 'DiasABP'].reset_index(drop=True)
df1

   RecordID Parameter  Value   Time  Time_Minute
0    137188   DiasABP   65.0  17:59         1079
1    137188   DiasABP   71.0  18:29         1109
2    137188   DiasABP   69.0  18:59         1139
3    137188   DiasABP   63.0  19:29         1169
4    137188   DiasABP   59.0  19:44         1184
5    137188   DiasABP   46.0  19:54         1194
6    137188   DiasABP   45.0  19:59         1199
7    137188   DiasABP   62.0  20:29         1229
8    137188   DiasABP   60.0  21:29         1289
9    137188   DiasABP   66.0  22:29         1349
10   137188   DiasABP   62.0  22:44         1364
11   137188   DiasABP   57.0  23:29         1409
12   137188   DiasABP   63.0  24:29         1469
13   137188   DiasABP   77.0  25:29         1529
14   137188   DiasABP   58.0  26:29         1589
15   137188   DiasABP   58.0  27:29         1649
16   137188   DiasABP   43.0  28:29         1709
17   137188   DiasABP   54.0  29:29         1769
18   137188   DiasABP   43.0  29:44         1784
19   137188   DiasABP   44.0  29:59         1799
20   137188   DiasABP   63.0  30:29         1829
21   137188   DiasABP   39.0  31:29         1889
22   137188   DiasABP   56.0  32:29         1949
23   137188   DiasABP   45.0  33:29         2009
24   137188   DiasABP   40.0  34:29         2069
25   137188   DiasABP   47.0  35:29         2129
26   137188   DiasABP   58.0  36:29         2189
27   137188   DiasABP   55.0  37:29         2249
28   137188   DiasABP   57.0  38:29         2309
29   137188   DiasABP   60.0  39:29         2369
30   137188   DiasABP   61.0  40:29         2429
31   137188   DiasABP   68.0  41:59         2519
32   137188   DiasABP   65.0  42:29         2549
33   137188   DiasABP   70.0  42:59         2579
34   137188   DiasABP   67.0  43:29         2609
35   137188   DiasABP   69.0  44:29         2669
36   137188   DiasABP   64.0  44:59         2699
37   137188   DiasABP   62.0  45:29         2729
38   137188   DiasABP   57.0  46:29         2789
39   137188   DiasABP   57.0  46:59         2819
40   137188   DiasABP   66.0  47:29         2849

In [247]:
df2 = df_temp[df_temp['Parameter'] == 'NIDiasABP'].reset_index(drop=True)
df2

   RecordID  Parameter  Value   Time  Time_Minute
0    137188  NIDiasABP   60.0  02:14          134
1    137188  NIDiasABP   62.0  02:29          149
2    137188  NIDiasABP   65.0  02:44          164
3    137188  NIDiasABP   70.0  02:59          179
4    137188  NIDiasABP   72.0  03:14          194
5    137188  NIDiasABP   74.0  03:29          209
6    137188  NIDiasABP   66.0  03:59          239
7    137188  NIDiasABP   66.0  04:29          269
8    137188  NIDiasABP   64.0  05:29          329
9    137188  NIDiasABP   65.0  06:29          389
10   137188  NIDiasABP   55.0  08:29          509
11   137188  NIDiasABP   51.0  09:29          569
12   137188  NIDiasABP   46.0  10:29          629
13   137188  NIDiasABP   63.0  11:29          689
14   137188  NIDiasABP   38.0  12:29          749
15   137188  NIDiasABP   48.0  13:29          809
16   137188  NIDiasABP   62.0  14:29          869
17   137188  NIDiasABP   67.0  15:29          929
18   137188  NIDiasABP   72.0  15:59          959
19   137188  NIDiasABP   69.0  16:14          974
20   137188  NIDiasABP   69.0  16:29          989
21   137188  NIDiasABP   72.0  16:44         1004
22   137188  NIDiasABP   64.0  17:29         1049
23   137188  NIDiasABP   64.0  17:59         1079
24   137188  NIDiasABP   66.0  18:29         1109
25   137188  NIDiasABP   64.0  18:59         1139
26   137188  NIDiasABP   78.0  19:44         1184
27   137188  NIDiasABP   66.0  20:29         1229
28   137188  NIDiasABP   66.0  22:44         1364
29   137188  NIDiasABP   58.0  23:29         1409
30   137188  NIDiasABP   70.0  24:29         1469
31   137188  NIDiasABP   68.0  27:29         1649

In [248]:
df_sub = find_unidf(df1, df2)
df_sub

   RecordID   Parameter  Value   Time  Time_Minute
0    137188  UniDiasABP   60.0  02:14          134
1    137188  UniDiasABP   62.0  02:29          149
2    137188  UniDiasABP   65.0  02:44          164
3    137188  UniDiasABP   70.0  02:59          179
4    137188  UniDiasABP   72.0  03:14          194
5    137188  UniDiasABP   74.0  03:29          209
6    137188  UniDiasABP   66.0  03:59          239
7    137188  UniDiasABP   66.0  04:29          269
8    137188  UniDiasABP   64.0  05:29          329
9    137188  UniDiasABP   65.0  06:29          389
10   137188  UniDiasABP   55.0  08:29          509
11   137188  UniDiasABP   51.0  09:29          569
12   137188  UniDiasABP   46.0  10:29          629
13   137188  UniDiasABP   63.0  11:29          689
14   137188  UniDiasABP   38.0  12:29          749
15   137188  UniDiasABP   48.0  13:29          809
16   137188  UniDiasABP   62.0  14:29          869
17   137188  UniDiasABP   67.0  15:29          929
18   137188  UniDiasABP   72.0  15:59          959
19   137188  UniDiasABP   69.0  16:14          974
20   137188  UniDiasABP   69.0  16:29          989
21   137188  UniDiasABP   72.0  16:44         1004
22   137188  UniDiasABP   64.0  17:29         1049
23   137188  UniDiasABP   65.0  17:59         1079
24   137188  UniDiasABP   71.0  18:29         1109
25   137188  UniDiasABP   69.0  18:59         1139
26   137188  UniDiasABP   63.0  19:29         1169
27   137188  UniDiasABP   59.0  19:44         1184
28   137188  UniDiasABP   46.0  19:54         1194
29   137188  UniDiasABP   45.0  19:59         1199
30   137188  UniDiasABP   62.0  20:29         1229
31   137188  UniDiasABP   60.0  21:29         1289
32   137188  UniDiasABP   66.0  22:29         1349
33   137188  UniDiasABP   62.0  22:44         1364
34   137188  UniDiasABP   57.0  23:29         1409
35   137188  UniDiasABP   63.0  24:29         1469
36   137188  UniDiasABP   77.0  25:29         1529
37   137188  UniDiasABP   58.0  26:29         1589
38   137188  UniDiasABP   58.0  27:29         1649
39   137188  UniDiasABP   43.0  28:29         1709
40   137188  UniDiasABP   54.0  29:29         1769
41   137188  UniDiasABP   43.0  29:44         1784
42   137188  UniDiasABP   44.0  29:59         1799
43   137188  UniDiasABP   63.0  30:29         1829
44   137188  UniDiasABP   39.0  31:29         1889
45   137188  UniDiasABP   56.0  32:29         1949
46   137188  UniDiasABP   45.0  33:29         2009
47   137188  UniDiasABP   40.0  34:29         2069
48   137188  UniDiasABP   47.0  35:29         2129
49   137188  UniDiasABP   58.0  36:29         2189
50   137188  UniDiasABP   55.0  37:29         2249
51   137188  UniDiasABP   57.0  38:29         2309
52   137188  UniDiasABP   60.0  39:29         2369
53   137188  UniDiasABP   61.0  40:29         2429
54   137188  UniDiasABP   68.0  41:59         2519
55   137188  UniDiasABP   65.0  42:29         2549
56   137188  UniDiasABP   70.0  42:59         2579
57   137188  UniDiasABP   67.0  43:29         2609
58   137188  UniDiasABP   69.0  44:29         2669
59   137188  UniDiasABP   64.0  44:59         2699
60   137188  UniDiasABP   62.0  45:29         2729
61   137188  UniDiasABP   57.0  46:29         2789
62   137188  UniDiasABP   57.0  46:59         2819
63   137188  UniDiasABP   66.0  47:29         2849

In [249]:
# UniDiasABP
# UniDiasABP_Initial
# UniDiasABP_Min
# UniDiasABP_Max
# UniDiasABP_Mean
# UniDiasABP_SD x
# UniDiasABP_Time_Duration - threshold < 40 x
# UniDiasABP_Count
# UniDiasABP_Slope
# UniDiasABP_Miss
# UniDiasABP_Last_Minute


def unidiasabp_stats(df_sub, df_record):
  col = 'UniDiasABP'
  col_initial = col+'_Initial'
  col_min = col+'_Min'
  col_max = col+'_Max'
  col_mean = col+'_Mean'
  #col_sd = col+'_SD'
  #col_td = col+'_Time_Duration'
  #threshold = 40
  col_count = col+'_Count'
  col_slope = col+'_Slope'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_min] = np.nan
    df_record[col_max] = np.nan
    df_record[col_mean] = np.nan
    #df_record[col_sd] = np.nan
    #df_record[col_td] = np.nan
    df_record[col_count] = 0
    df_record[col_slope] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      #df_record[col_sd] = np.nan
      #df_record[col_td] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      #df_record[col_sd] = 0
      #df_record[col_td] = 0
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      #df_record[col_sd] = np.nan
      #df_record[col_td] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      #df_record[col_sd] = df_sub['Value'].std()
      #max_duration, max_begin, max_end = find_max_duration(df_sub, threshold, 'below')
      #time_duration, time_begin, time_end = find_time_duration(df_sub, max_begin, max_end)
      #df_record[col_td] = time_duration
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [250]:
unidiasabp_stats(df_sub, df_record)

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute,MAP_Initial,MAP_Min,MAP_Max,MAP_Mean,MAP_SD,MAP_Count,MAP_Slope,MAP_Miss,MAP_Last_Minute,NIDiasABP_Initial,NIDiasABP_Min,NIDiasABP_Max,NIDiasABP_Mean,NIDiasABP_SD,NIDiasABP_Count,NIDiasABP_Slope,NIDiasABP_Miss,NIDiasABP_Last_Minute,NIMAP_Initial,NIMAP_Min,NIMAP_Max,NIMAP_Mean,NIMAP_SD,NIMAP_Count,NIMAP_Slope,NIMAP_Miss,NIMAP_Last_Minute,NISysABP_Initial,NISysABP_Min,NISysABP_Max,NISysABP_Mean,NISysABP_SD,NISysABP_Count,NISysABP_Slope,NISysABP_Miss,NISysABP_Last_Minute,SysABP_Initial,SysABP_Min,SysABP_Max,SysABP_Mean,SysABP_SD,SysABP_Count,SysABP_Slope,SysABP_Miss,SysABP_Last_Minute,TroponinI_Max,TroponinI_Count,TroponinI_Slope,TroponinI_Miss,TroponinI_Last_Minute,TroponinT_Max,TroponinT_Count,TroponinT_Slope,TroponinT_Miss,TroponinT_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.06,1.5,1.8,0.0,-20.0,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.75,40.0,39.0,51.0,187.0,73.0,121.666667,7.39,7.29,7.42,7.361429,85.0,71.0,NaN,NaN,NaN,NaN,NaN,37.6,36.3,38.9,37.329412,0.645041,2763.0,0.167785,3.775168,0.93451,13.3,9.3,13.3,59.6,59.6,60.0,38.0,77.0,59.859375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,64,5,6,18,4,4,7,7,7,4,0,0,34,36,4,64,NaN,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,0.6,-0.2,0.0,-50.0,9.0,0,-4.0,0.0,NaN,-0.000198,0.000168,0.044188,-0.010776,0.000673,0.000002,0,-0.000355,-2.38014,-0.001739,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,NaN,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,2113,2803,2819,2113,2113,2743,2743,2743,2799,0,0,2849,2849,2799,2849,2849,NaN,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849,81.0,60.0,95.0,76.731707,8.508891,41,0.001595,0,2849,60.0,38.0,78.0,63.75,8.466252,32,0.002046,0,1649,69.0,48.0,88.0,73.375,8.381046,32,0.001885,0,1649,97.0,82.0,121.0,104.90625,8.306078,32,0.002584,0,1649,112.0,89.0,131.0,111.292683,10.431308,41,0.003873,0,2849,NaN,0,0,1,0,0.4,3,-0.000161,0,1320

In [251]:
df1 = df_temp[df_temp['Parameter'] == 'MAP'].reset_index(drop=True)
df1

   RecordID Parameter  Value   Time  Time_Minute
0    137188       MAP   81.0  17:59         1079
1    137188       MAP   85.0  18:29         1109
2    137188       MAP   87.0  18:59         1139
3    137188       MAP   80.0  19:29         1169
4    137188       MAP   76.0  19:44         1184
5    137188       MAP   64.0  19:54         1194
6    137188       MAP   65.0  19:59         1199
7    137188       MAP   75.0  20:29         1229
8    137188       MAP   75.0  21:29         1289
9    137188       MAP   84.0  22:29         1349
10   137188       MAP   82.0  22:44         1364
11   137188       MAP   77.0  23:29         1409
12   137188       MAP   81.0  24:29         1469
13   137188       MAP   95.0  25:29         1529
14   137188       MAP   77.0  26:29         1589
15   137188       MAP   84.0  27:29         1649
16   137188       MAP   68.0  28:29         1709
17   137188       MAP   72.0  29:29         1769
18   137188       MAP   61.0  29:44         1784
19   137188       MAP   60.0  29:59         1799
20   137188       MAP   81.0  30:29         1829
21   137188       MAP   63.0  31:29         1889
22   137188       MAP   77.0  32:29         1949
23   137188       MAP   67.0  33:29         2009
24   137188       MAP   62.0  34:29         2069
25   137188       MAP   67.0  35:29         2129
26   137188       MAP   72.0  36:29         2189
27   137188       MAP   70.0  37:29         2249
28   137188       MAP   74.0  38:29         2309
29   137188       MAP   83.0  39:29         2369
30   137188       MAP   78.0  40:29         2429
31   137188       MAP   87.0  41:59         2519
32   137188       MAP   83.0  42:29         2549
33   137188       MAP   87.0  42:59         2579
34   137188       MAP   84.0  43:29         2609
35   137188       MAP   86.0  44:29         2669
36   137188       MAP   83.0  44:59         2699
37   137188       MAP   80.0  45:29         2729
38   137188       MAP   73.0  46:29         2789
39   137188       MAP   74.0  46:59         2819
40   137188       MAP   86.0  47:29         2849

In [252]:
df2 = df_temp[df_temp['Parameter'] == 'NIMAP'].reset_index(drop=True)
df2

   RecordID Parameter  Value   Time  Time_Minute
0    137188     NIMAP   69.0  02:14          134
1    137188     NIMAP   70.0  02:29          149
2    137188     NIMAP   75.0  02:44          164
3    137188     NIMAP   80.0  02:59          179
4    137188     NIMAP   81.0  03:14          194
5    137188     NIMAP   83.0  03:29          209
6    137188     NIMAP   76.0  03:59          239
7    137188     NIMAP   76.0  04:29          269
8    137188     NIMAP   76.0  05:29          329
9    137188     NIMAP   75.0  06:29          389
10   137188     NIMAP   64.0  08:29          509
11   137188     NIMAP   59.0  09:29          569
12   137188     NIMAP   56.0  10:29          629
13   137188     NIMAP   72.0  11:29          689
14   137188     NIMAP   48.0  12:29          749
15   137188     NIMAP   60.0  13:29          809
16   137188     NIMAP   72.0  14:29          869
17   137188     NIMAP   77.0  15:29          929
18   137188     NIMAP   81.0  15:59          959
19   137188     NIMAP   79.0  16:14          974
20   137188     NIMAP   79.0  16:29          989
21   137188     NIMAP   82.0  16:44         1004
22   137188     NIMAP   74.0  17:29         1049
23   137188     NIMAP   74.0  17:59         1079
24   137188     NIMAP   75.0  18:29         1109
25   137188     NIMAP   73.0  18:59         1139
26   137188     NIMAP   88.0  19:44         1184
27   137188     NIMAP   76.0  20:29         1229
28   137188     NIMAP   75.0  22:44         1364
29   137188     NIMAP   68.0  23:29         1409
30   137188     NIMAP   79.0  24:29         1469
31   137188     NIMAP   76.0  27:29         1649

In [253]:
df_sub = find_unidf(df1, df2)
df_sub

   RecordID Parameter  Value   Time  Time_Minute
0    137188    UniMAP   69.0  02:14          134
1    137188    UniMAP   70.0  02:29          149
2    137188    UniMAP   75.0  02:44          164
3    137188    UniMAP   80.0  02:59          179
4    137188    UniMAP   81.0  03:14          194
5    137188    UniMAP   83.0  03:29          209
6    137188    UniMAP   76.0  03:59          239
7    137188    UniMAP   76.0  04:29          269
8    137188    UniMAP   76.0  05:29          329
9    137188    UniMAP   75.0  06:29          389
10   137188    UniMAP   64.0  08:29          509
11   137188    UniMAP   59.0  09:29          569
12   137188    UniMAP   56.0  10:29          629
13   137188    UniMAP   72.0  11:29          689
14   137188    UniMAP   48.0  12:29          749
15   137188    UniMAP   60.0  13:29          809
16   137188    UniMAP   72.0  14:29          869
17   137188    UniMAP   77.0  15:29          929
18   137188    UniMAP   81.0  15:59          959
19   137188    UniMAP   79.0  16:14          974
20   137188    UniMAP   79.0  16:29          989
21   137188    UniMAP   82.0  16:44         1004
22   137188    UniMAP   74.0  17:29         1049
23   137188    UniMAP   81.0  17:59         1079
24   137188    UniMAP   85.0  18:29         1109
25   137188    UniMAP   87.0  18:59         1139
26   137188    UniMAP   80.0  19:29         1169
27   137188    UniMAP   76.0  19:44         1184
28   137188    UniMAP   64.0  19:54         1194
29   137188    UniMAP   65.0  19:59         1199
30   137188    UniMAP   75.0  20:29         1229
31   137188    UniMAP   75.0  21:29         1289
32   137188    UniMAP   84.0  22:29         1349
33   137188    UniMAP   82.0  22:44         1364
34   137188    UniMAP   77.0  23:29         1409
35   137188    UniMAP   81.0  24:29         1469
36   137188    UniMAP   95.0  25:29         1529
37   137188    UniMAP   77.0  26:29         1589
38   137188    UniMAP   84.0  27:29         1649
39   137188    UniMAP   68.0  28:29         1709
40   137188    UniMAP   72.0  29:29         1769
41   137188    UniMAP   61.0  29:44         1784
42   137188    UniMAP   60.0  29:59         1799
43   137188    UniMAP   81.0  30:29         1829
44   137188    UniMAP   63.0  31:29         1889
45   137188    UniMAP   77.0  32:29         1949
46   137188    UniMAP   67.0  33:29         2009
47   137188    UniMAP   62.0  34:29         2069
48   137188    UniMAP   67.0  35:29         2129
49   137188    UniMAP   72.0  36:29         2189
50   137188    UniMAP   70.0  37:29         2249
51   137188    UniMAP   74.0  38:29         2309
52   137188    UniMAP   83.0  39:29         2369
53   137188    UniMAP   78.0  40:29         2429
54   137188    UniMAP   87.0  41:59         2519
55   137188    UniMAP   83.0  42:29         2549
56   137188    UniMAP   87.0  42:59         2579
57   137188    UniMAP   84.0  43:29         2609
58   137188    UniMAP   86.0  44:29         2669
59   137188    UniMAP   83.0  44:59         2699
60   137188    UniMAP   80.0  45:29         2729
61   137188    UniMAP   73.0  46:29         2789
62   137188    UniMAP   74.0  46:59         2819
63   137188    UniMAP   86.0  47:29         2849

In [254]:
# UniMAP
# UniMAP_Initial
# UniMAP_Final
# UniMAP_Min
# UniMAP_Max
# UniMAP_Mean
# UniMAP_SD
# UniMAP_Time_Duration - threshold < 65 x
# UniMAP_Count
# UniMAP_Slope
# UniMAP_Miss
# UniMAP_Last_Minute


def unimap_stats(df_sub, df_record):
  col = 'UniMAP'
  col_initial = col+'_Initial'
  col_final = col+'_Final'
  col_min = col+'_Min'
  col_max = col+'_Max'
  col_mean = col+'_Mean'
  col_sd = col+'_SD'
  #col_td = col+'_Time_Duration'
  #threshold = 65
  col_count = col+'_Count'
  col_slope = col+'_Slope'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_final] = np.nan
    df_record[col_min] = np.nan
    df_record[col_max] = np.nan
    df_record[col_mean] = np.nan
    df_record[col_sd] = np.nan
    #df_record[col_td] = np.nan
    df_record[col_count] = 0
    df_record[col_slope] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_final] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_sd] = np.nan
      #df_record[col_td] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_final] = df_sub['Value'].iloc[-1]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_sd] = 0
      #df_record[col_td] = 0
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_final] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_sd] = np.nan
      #df_record[col_td] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_final] = df_sub['Value'].iloc[-1]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_sd] = df_sub['Value'].std()
      #max_duration, max_begin, max_end = find_max_duration(df_sub, threshold, 'below')
      #time_duration, time_begin, time_end = find_time_duration(df_sub, max_begin, max_end)
      #df_record[col_td] = time_duration
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [255]:
unimap_stats(df_sub, df_record)

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute,MAP_Initial,MAP_Min,MAP_Max,MAP_Mean,MAP_SD,MAP_Count,MAP_Slope,MAP_Miss,MAP_Last_Minute,NIDiasABP_Initial,NIDiasABP_Min,NIDiasABP_Max,NIDiasABP_Mean,NIDiasABP_SD,NIDiasABP_Count,NIDiasABP_Slope,NIDiasABP_Miss,NIDiasABP_Last_Minute,NIMAP_Initial,NIMAP_Min,NIMAP_Max,NIMAP_Mean,NIMAP_SD,NIMAP_Count,NIMAP_Slope,NIMAP_Miss,NIMAP_Last_Minute,NISysABP_Initial,NISysABP_Min,NISysABP_Max,NISysABP_Mean,NISysABP_SD,NISysABP_Count,NISysABP_Slope,NISysABP_Miss,NISysABP_Last_Minute,SysABP_Initial,SysABP_Min,SysABP_Max,SysABP_Mean,SysABP_SD,SysABP_Count,SysABP_Slope,SysABP_Miss,SysABP_Last_Minute,TroponinI_Max,TroponinI_Count,TroponinI_Slope,TroponinI_Miss,TroponinI_Last_Minute,TroponinT_Max,TroponinT_Count,TroponinT_Slope,TroponinT_Miss,TroponinT_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.06,1.5,1.8,0.0,-20.0,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.75,40.0,39.0,51.0,187.0,73.0,121.666667,7.39,7.29,7.42,7.361429,85.0,71.0,NaN,NaN,NaN,NaN,NaN,37.6,36.3,38.9,37.329412,0.645041,2763.0,0.167785,3.775168,0.93451,13.3,9.3,13.3,59.6,59.6,60.0,38.0,77.0,59.859375,69.0,86.0,48.0,95.0,75.15625,8.942885,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,64,5,6,18,4,4,7,7,7,4,0,0,34,36,4,64,64,NaN,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,0.6,-0.2,0.0,-50.0,9.0,0,-4.0,0.0,NaN,-0.000198,0.000168,0.044188,-0.010776,0.000673,0.000002,0,-0.000355,-2.38014,-0.001739,0.002434,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,NaN,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,2113,2803,2819,2113,2113,2743,2743,2743,2799,0,0,2849,2849,2799,2849,2849,2849,NaN,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849,81.0,60.0,95.0,76.731707,8.508891,41,0.001595,0,2849,60.0,38.0,78.0,63.75,8.466252,32,0.002046,0,1649,69.0,48.0,88.0,73.375,8.381046,32,0.001885,0,1649,97.0,82.0,121.0,104.90625,8.306078,32,0.002584,0,1649,112.0,89.0,131.0,111.292683,10.431308,41,0.003873,0,2849,NaN,0,0,1,0,0.4,3,-0.000161,0,1320

In [256]:
df1 = df_temp[df_temp['Parameter'] == 'SysABP'].reset_index(drop=True)
df1

   RecordID Parameter  Value   Time  Time_Minute
0    137188    SysABP  112.0  17:59         1079
1    137188    SysABP  112.0  18:29         1109
2    137188    SysABP  124.0  18:59         1139
3    137188    SysABP  115.0  19:29         1169
4    137188    SysABP  107.0  19:44         1184
5    137188    SysABP   92.0  19:54         1194
6    137188    SysABP   96.0  19:59         1199
7    137188    SysABP  102.0  20:29         1229
8    137188    SysABP  103.0  21:29         1289
9    137188    SysABP  121.0  22:29         1349
10   137188    SysABP  123.0  22:44         1364
11   137188    SysABP  116.0  23:29         1409
12   137188    SysABP  115.0  24:29         1469
13   137188    SysABP  131.0  25:29         1529
14   137188    SysABP  109.0  26:29         1589
15   137188    SysABP  122.0  27:29         1649
16   137188    SysABP  106.0  28:29         1709
17   137188    SysABP  107.0  29:29         1769
18   137188    SysABP   90.0  29:44         1784
19   137188    SysABP   89.0  29:59         1799
20   137188    SysABP  117.0  30:29         1829
21   137188    SysABP  103.0  31:29         1889
22   137188    SysABP  117.0  32:29         1949
23   137188    SysABP  103.0  33:29         2009
24   137188    SysABP   97.0  34:29         2069
25   137188    SysABP  100.0  35:29         2129
26   137188    SysABP  102.0  36:29         2189
27   137188    SysABP  104.0  37:29         2249
28   137188    SysABP  111.0  38:29         2309
29   137188    SysABP  121.0  39:29         2369
30   137188    SysABP  113.0  40:29         2429
31   137188    SysABP  130.0  41:59         2519
32   137188    SysABP  119.0  42:29         2549
33   137188    SysABP  123.0  42:59         2579
34   137188    SysABP  117.0  43:29         2609
35   137188    SysABP  121.0  44:29         2669
36   137188    SysABP  116.0  44:59         2699
37   137188    SysABP  115.0  45:29         2729
38   137188    SysABP  109.0  46:29         2789
39   137188    SysABP  110.0  46:59         2819
40   137188    SysABP  123.0  47:29         2849

In [257]:
df2 = df_temp[df_temp['Parameter'] == 'NISysABP'].reset_index(drop=True)
df2

   RecordID Parameter  Value   Time  Time_Minute
0    137188  NISysABP   97.0  02:14          134
1    137188  NISysABP   98.0  02:29          149
2    137188  NISysABP  107.0  02:44          164
3    137188  NISysABP  112.0  02:59          179
4    137188  NISysABP  111.0  03:14          194
5    137188  NISysABP  111.0  03:29          209
6    137188  NISysABP  106.0  03:59          239
7    137188  NISysABP  108.0  04:29          269
8    137188  NISysABP  111.0  05:29          329
9    137188  NISysABP  114.0  06:29          389
10   137188  NISysABP   91.0  08:29          509
11   137188  NISysABP   88.0  09:29          569
12   137188  NISysABP   90.0  10:29          629
13   137188  NISysABP  103.0  11:29          689
14   137188  NISysABP   82.0  12:29          749
15   137188  NISysABP   98.0  13:29          809
16   137188  NISysABP  104.0  14:29          869
17   137188  NISysABP  110.0  15:29          929
18   137188  NISysABP  108.0  15:59          959
19   137188  NISysABP  112.0  16:14          974
20   137188  NISysABP  112.0  16:29          989
21   137188  NISysABP  112.0  16:44         1004
22   137188  NISysABP  103.0  17:29         1049
23   137188  NISysABP  105.0  17:59         1079
24   137188  NISysABP  103.0  18:29         1109
25   137188  NISysABP  104.0  18:59         1139
26   137188  NISysABP  121.0  19:44         1184
27   137188  NISysABP  109.0  20:29         1229
28   137188  NISysABP  106.0  22:44         1364
29   137188  NISysABP  108.0  23:29         1409
30   137188  NISysABP  108.0  24:29         1469
31   137188  NISysABP  105.0  27:29         1649

In [258]:
df_sub = find_unidf(df1, df2)
df_sub

   RecordID  Parameter  Value   Time  Time_Minute
0    137188  UniSysABP   97.0  02:14          134
1    137188  UniSysABP   98.0  02:29          149
2    137188  UniSysABP  107.0  02:44          164
3    137188  UniSysABP  112.0  02:59          179
4    137188  UniSysABP  111.0  03:14          194
5    137188  UniSysABP  111.0  03:29          209
6    137188  UniSysABP  106.0  03:59          239
7    137188  UniSysABP  108.0  04:29          269
8    137188  UniSysABP  111.0  05:29          329
9    137188  UniSysABP  114.0  06:29          389
10   137188  UniSysABP   91.0  08:29          509
11   137188  UniSysABP   88.0  09:29          569
12   137188  UniSysABP   90.0  10:29          629
13   137188  UniSysABP  103.0  11:29          689
14   137188  UniSysABP   82.0  12:29          749
15   137188  UniSysABP   98.0  13:29          809
16   137188  UniSysABP  104.0  14:29          869
17   137188  UniSysABP  110.0  15:29          929
18   137188  UniSysABP  108.0  15:59          959
19   137188  UniSysABP  112.0  16:14          974
20   137188  UniSysABP  112.0  16:29          989
21   137188  UniSysABP  112.0  16:44         1004
22   137188  UniSysABP  103.0  17:29         1049
23   137188  UniSysABP  112.0  17:59         1079
24   137188  UniSysABP  112.0  18:29         1109
25   137188  UniSysABP  124.0  18:59         1139
26   137188  UniSysABP  115.0  19:29         1169
27   137188  UniSysABP  107.0  19:44         1184
28   137188  UniSysABP   92.0  19:54         1194
29   137188  UniSysABP   96.0  19:59         1199
30   137188  UniSysABP  102.0  20:29         1229
31   137188  UniSysABP  103.0  21:29         1289
32   137188  UniSysABP  121.0  22:29         1349
33   137188  UniSysABP  123.0  22:44         1364
34   137188  UniSysABP  116.0  23:29         1409
35   137188  UniSysABP  115.0  24:29         1469
36   137188  UniSysABP  131.0  25:29         1529
37   137188  UniSysABP  109.0  26:29         1589
38   137188  UniSysABP  122.0  27:29         1649
39   137188  UniSysABP  106.0  28:29         1709
40   137188  UniSysABP  107.0  29:29         1769
41   137188  UniSysABP   90.0  29:44         1784
42   137188  UniSysABP   89.0  29:59         1799
43   137188  UniSysABP  117.0  30:29         1829
44   137188  UniSysABP  103.0  31:29         1889
45   137188  UniSysABP  117.0  32:29         1949
46   137188  UniSysABP  103.0  33:29         2009
47   137188  UniSysABP   97.0  34:29         2069
48   137188  UniSysABP  100.0  35:29         2129
49   137188  UniSysABP  102.0  36:29         2189
50   137188  UniSysABP  104.0  37:29         2249
51   137188  UniSysABP  111.0  38:29         2309
52   137188  UniSysABP  121.0  39:29         2369
53   137188  UniSysABP  113.0  40:29         2429
54   137188  UniSysABP  130.0  41:59         2519
55   137188  UniSysABP  119.0  42:29         2549
56   137188  UniSysABP  123.0  42:59         2579
57   137188  UniSysABP  117.0  43:29         2609
58   137188  UniSysABP  121.0  44:29         2669
59   137188  UniSysABP  116.0  44:59         2699
60   137188  UniSysABP  115.0  45:29         2729
61   137188  UniSysABP  109.0  46:29         2789
62   137188  UniSysABP  110.0  46:59         2819
63   137188  UniSysABP  123.0  47:29         2849

In [259]:
# UniSysABP
# UniSysABP_Initial
# UniSysABP_Final
# UniSysABP_Min
# UniSysABP_Max
# UniSysABP_Mean
# UniSysABP_SD
# UniSysABP_Time_Duration - threshold < 90 x
# UniSysABP_Count
# UniSysABP_Slope
# UniSysABP_Miss
# UniSysABP_Last_Minute


def unisysabp_stats(df_sub, df_record):
  col = 'UniSysABP'
  col_initial = col+'_Initial'
  col_final = col+'_Final'
  col_min = col+'_Min'
  col_max = col+'_Max'
  col_mean = col+'_Mean'
  col_sd = col+'_SD'
  #col_td = col+'_Time_Duration'
  #threshold = 90
  col_count = col+'_Count'
  col_slope = col+'_Slope'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_initial] = np.nan
    df_record[col_final] = np.nan
    df_record[col_min] = np.nan
    df_record[col_max] = np.nan
    df_record[col_mean] = np.nan
    df_record[col_sd] = np.nan
    #df_record[col_td] = np.nan
    df_record[col_count] = 0
    df_record[col_slope] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_initial] = np.nan
      df_record[col_final] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_sd] = np.nan
      #df_record[col_td] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_final] = df_sub['Value'].iloc[-1]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_sd] = 0
      #df_record[col_td] = 0
      df_record[col_count] = 1
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_initial] = np.nan
      df_record[col_final] = np.nan
      df_record[col_min] = np.nan
      df_record[col_max] = np.nan
      df_record[col_mean] = np.nan
      df_record[col_sd] = np.nan
      #df_record[col_td] = np.nan
      df_record[col_count] = 0
      df_record[col_slope] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_initial] = df_sub['Value'].iloc[0]
      df_record[col_final] = df_sub['Value'].iloc[-1]
      df_record[col_min] = df_sub['Value'].min()
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_mean] = df_sub['Value'].mean()
      df_record[col_sd] = df_sub['Value'].std()
      #max_duration, max_begin, max_end = find_max_duration(df_sub, threshold, 'below')
      #time_duration, time_begin, time_end = find_time_duration(df_sub, max_begin, max_end)
      #df_record[col_td] = time_duration
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_slope] = compute_regression_slope(df_sub)
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [260]:
unisysabp_stats(df_sub, df_record)

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute,MAP_Initial,MAP_Min,MAP_Max,MAP_Mean,MAP_SD,MAP_Count,MAP_Slope,MAP_Miss,MAP_Last_Minute,NIDiasABP_Initial,NIDiasABP_Min,NIDiasABP_Max,NIDiasABP_Mean,NIDiasABP_SD,NIDiasABP_Count,NIDiasABP_Slope,NIDiasABP_Miss,NIDiasABP_Last_Minute,NIMAP_Initial,NIMAP_Min,NIMAP_Max,NIMAP_Mean,NIMAP_SD,NIMAP_Count,NIMAP_Slope,NIMAP_Miss,NIMAP_Last_Minute,NISysABP_Initial,NISysABP_Min,NISysABP_Max,NISysABP_Mean,NISysABP_SD,NISysABP_Count,NISysABP_Slope,NISysABP_Miss,NISysABP_Last_Minute,SysABP_Initial,SysABP_Min,SysABP_Max,SysABP_Mean,SysABP_SD,SysABP_Count,SysABP_Slope,SysABP_Miss,SysABP_Last_Minute,TroponinI_Max,TroponinI_Count,TroponinI_Slope,TroponinI_Miss,TroponinI_Last_Minute,TroponinT_Max,TroponinT_Count,TroponinT_Slope,TroponinT_Miss,TroponinT_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.06,1.5,1.8,0.0,-20.0,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.75,40.0,39.0,51.0,187.0,73.0,121.666667,7.39,7.29,7.42,7.361429,85.0,71.0,NaN,NaN,NaN,NaN,NaN,37.6,36.3,38.9,37.329412,0.645041,2763.0,0.167785,3.775168,0.93451,13.3,9.3,13.3,59.6,59.6,60.0,38.0,77.0,59.859375,69.0,86.0,48.0,95.0,75.15625,8.942885,97.0,123.0,82.0,131.0,108.609375,10.529802,NaN,3,3,3,3,4,3,0,4,18,13,4,4,6,64,5,6,18,4,4,7,7,7,4,0,0,34,36,4,64,64,64,NaN,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,0.6,-0.2,0.0,-50.0,9.0,0,-4.0,0.0,NaN,-0.000198,0.000168,0.044188,-0.010776,0.000673,0.000002,0,-0.000355,-2.38014,-0.001739,0.002434,0.004666,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,NaN,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,2113,2803,2819,2113,2113,2743,2743,2743,2799,0,0,2849,2849,2799,2849,2849,2849,2849,NaN,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849,81.0,60.0,95.0,76.731707,8.508891,41,0.001595,0,2849,60.0,38.0,78.0,63.75,8.466252,32,0.002046,0,1649,69.0,48.0,88.0,73.375,8.381046,32,0.001885,0,1649,97.0,82.0,121.0,104.90625,8.306078,32,0.002584,0,1649,112.0,89.0,131.0,111.292683,10.431308,41,0.003873,0,2849,NaN,0,0,1,0,0.4,3,-0.000161,0,1320

In [261]:
df1 = df_temp[df_temp['Parameter'] == 'TroponinI'].reset_index(drop=True)
df1

Empty DataFrame
Columns: [RecordID, Parameter, Value, Time, Time_Minute]
Index: []

In [262]:
df2 = df_temp[df_temp['Parameter'] == 'TroponinT'].reset_index(drop=True)
df2

  RecordID  Parameter  Value   Time  Time_Minute
0   137188  TroponinT   0.40  03:22          202
1   137188  TroponinT   0.32  11:50          710
2   137188  TroponinT   0.22  22:00         1320

In [263]:
df_sub = find_troponin(df1, df2)
df_sub

  RecordID Parameter  Value   Time  Time_Minute
0   137188  Troponin   0.40  03:22          202
1   137188  Troponin   0.32  11:50          710
2   137188  Troponin   0.22  22:00         1320

In [264]:
# Troponin
# Troponin_Max
# Troponin_Count
# Troponin_Delta
# Troponin_Miss
# Troponin_Last_Minute


def troponin_stats(df_sub, df_record):
  col = 'Troponin'
  col_max = col+'_Max'
  col_count = col+'_Count'
  col_delta = col+'_Delta'
  col_miss = col+'_Miss'
  col_last_minute = col+'_Last_Minute'

  if len(df_sub) == 0:
    df_record[col_max] = np.nan
    df_record[col_count] = 0
    df_record[col_delta] = 0
    df_record[col_miss] = 1
    df_record[col_last_minute] = 0
  elif len(df_sub) == 1:
    if df_sub.isnull().sum().sum() != 0:
      df_record[col_max] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]
  else:
    if df_sub.isnull().sum().sum() == len(df_sub):
      df_record[col_max] = np.nan
      df_record[col_count] = 0
      df_record[col_delta] = 0
      df_record[col_miss] = 1
      df_record[col_last_minute] = 0
    else:
      df_record[col_max] = df_sub['Value'].max()
      df_record[col_count] = df_sub['Value'].count()
      df_record[col_delta] = df_sub['Value'].iloc[-1] - df_sub['Value'].iloc[0]
      df_record[col_miss] = 0
      df_record[col_last_minute] = df_sub['Time_Minute'].iloc[-1]

  return df_record

In [265]:
troponin_stats(df_sub, df_record)

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,DiasABP_Initial,DiasABP_Min,DiasABP_Max,DiasABP_Mean,DiasABP_SD,DiasABP_Count,DiasABP_Slope,DiasABP_Miss,DiasABP_Last_Minute,MAP_Initial,MAP_Min,MAP_Max,MAP_Mean,MAP_SD,MAP_Count,MAP_Slope,MAP_Miss,MAP_Last_Minute,NIDiasABP_Initial,NIDiasABP_Min,NIDiasABP_Max,NIDiasABP_Mean,NIDiasABP_SD,NIDiasABP_Count,NIDiasABP_Slope,NIDiasABP_Miss,NIDiasABP_Last_Minute,NIMAP_Initial,NIMAP_Min,NIMAP_Max,NIMAP_Mean,NIMAP_SD,NIMAP_Count,NIMAP_Slope,NIMAP_Miss,NIMAP_Last_Minute,NISysABP_Initial,NISysABP_Min,NISysABP_Max,NISysABP_Mean,NISysABP_SD,NISysABP_Count,NISysABP_Slope,NISysABP_Miss,NISysABP_Last_Minute,SysABP_Initial,SysABP_Min,SysABP_Max,SysABP_Mean,SysABP_SD,SysABP_Count,SysABP_Slope,SysABP_Miss,SysABP_Last_Minute,TroponinI_Max,TroponinI_Count,TroponinI_Slope,TroponinI_Miss,TroponinI_Last_Minute,TroponinT_Max,TroponinT_Count,TroponinT_Slope,TroponinT_Miss,TroponinT_Last_Minute
0,141669,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.5,10.0,NaN,NaN,0.9,0.9,0.675,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.5,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.06,1.5,1.8,0.0,-20.0,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.75,40.0,39.0,51.0,187.0,73.0,121.666667,7.39,7.29,7.42,7.361429,85.0,71.0,NaN,NaN,NaN,NaN,NaN,37.6,36.3,38.9,37.329412,0.645041,2763.0,0.167785,3.775168,0.93451,13.3,9.3,13.3,59.6,59.6,60.0,38.0,77.0,59.859375,69.0,86.0,48.0,95.0,75.15625,8.942885,97.0,123.0,82.0,131.0,108.609375,10.529802,0.4,3,3,3,3,4,3,0,4,18,13,4,4,6,64,5,6,18,4,4,7,7,7,4,0,0,34,36,4,64,64,64,3,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0,-0.3,3.0,-3.1,0.6,-0.2,0.0,-50.0,9.0,0,-4.0,0.0,-0.18,-0.000198,0.000168,0.044188,-0.010776,0.000673,0.000002,0,-0.000355,-2.38014,-0.001739,0.002434,0.004666,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,2113,2113,2113,2113,2113,2113,0,2113,2819,2789,2113,2113,2799,2849,2113,2803,2819,2113,2113,2743,2743,2743,2799,0,0,2849,2849,2799,2849,2849,2849,2849,1320,65.0,39.0,77.0,58.317073,9.304405,41,0.001317,0,2849,81.0,60.0,95.0,76.731707,8.508891,41,0.001595,0,2849,60.0,38.0,78.0,63.75,8.466252,32,0.002046,0,1649,69.0,48.0,88.0,73.375,8.381046,32,0.001885,0,1649,97.0,82.0,121.0,104.90625,8.306078,32,0.002584,0,1649,112.0,89.0,131.0,111.292683,10.431308,41,0.003873,0,2849,NaN,0,0,1,0,0.4,3,-0.000161,0,1320

# extract statistics features for the whole dataset

In [266]:
df_record_all = pd.DataFrame(columns=col_df)
df_record_all.loc[0] = np.nan

for i in range(len(dfs_nan)):
  df_temp = dfs_nan[i]
  df_record = pd.DataFrame(columns=col_df)
  df_record.loc[0] = np.nan
  df_record['RecordID'] = df_temp['RecordID'].iloc[0]

  for col in col_icu:
    if col == 'Albumin':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      albumin_stats(df_sub, df_record, col)
    elif col == 'ALP':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      alp_stats(df_sub, df_record, col)
    elif col == 'ALT':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      alt_stats(df_sub, df_record, col)
    elif col == 'AST':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      ast_stats(df_sub, df_record, col)
    elif col == 'Bilirubin':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      bilirubin_stats(df_sub, df_record, col)
    elif col == 'BUN':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      df_sub2 = df_temp[df_temp['Parameter'] == 'Creatinine'].reset_index(drop=True)
      bun_stats(df_sub, df_sub2, df_record, col)
    elif col == 'Cholesterol':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      cholesterol_stats(df_sub, df_record, col)
    elif col == 'Creatinine':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      creatinine_stats(df_sub, df_record, col)
    elif col == 'DiasABP':
      col2 = 'NI'+col
      df1 = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      df2 = df_temp[df_temp['Parameter'] == col2].reset_index(drop=True)
      df_sub = find_unidf(df1, df2)
      #df_record['DiasABP_MAD'] = find_mad(df1, df2)
      unidiasabp_stats(df_sub, df_record)
    elif col == 'FiO2':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      fio2_stats(df_sub, df_record, col)
    elif col == 'GCS':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      gcs_stats(df_sub, df_record, col)
    elif col == 'Glucose':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      glucose_stats(df_sub, df_record, col)
    elif col == 'HCO3':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      hco3_stats(df_sub, df_record, col)
    elif col == 'HCT':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      hct_stats(df_sub, df_record, col)
    elif col == 'HR':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      hr_stats(df_sub, df_record, col)
    elif col == 'K':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      k_stats(df_sub, df_record, col)
    elif col == 'Lactate':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      lactate_stats(df_sub, df_record, col)
    elif col == 'Mg':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      mg_stats(df_sub, df_record, col)
    elif col == 'MAP':
      col2 = 'NI'+col
      df1 = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      df2 = df_temp[df_temp['Parameter'] == col2].reset_index(drop=True)
      df_sub = find_unidf(df1, df2)
      #df_record['MAP_MAD'] = find_mad(df1, df2)
      unimap_stats(df_sub, df_record)
    elif col == 'MechVent':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      mechvent_stats(df_sub,df_record, col)
    elif col == 'Na':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      na_stats(df_sub,df_record, col)
    elif col == 'NIDiasABP':
      pass
    elif col == 'NIMAP':
      pass
    elif col == 'NISysABP':
      pass
    elif col == 'PaCO2':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      paco2_stats(df_sub, df_record, col)
    elif col == 'PaO2':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      df_sub2 = df_temp[df_temp['Parameter'] == 'FiO2'].reset_index(drop=True)
      pao2_stats(df_sub, df_sub2, df_record, col)
    elif col == 'pH':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      ph_stats(df_sub, df_record, col)
    elif col == 'Platelets':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      platelets_stats(df_sub, df_record, col)
    elif col == 'RespRate':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      resprate_stats(df_sub, df_record, col)
    elif col == 'SaO2':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      sao2_stats(df_sub, df_record, col)
    elif col == 'SysABP':
      col2 = 'NI'+col
      df1 = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      df2 = df_temp[df_temp['Parameter'] == col2].reset_index(drop=True)
      df_sub = find_unidf(df1, df2)
      #df_record['SysABP_MAD'] = find_mad(df1, df2)
      unisysabp_stats(df_sub, df_record)
    elif col == 'Temp':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      temp_stats(df_sub, df_record, col)
    elif col == 'TroponinI':
      df1 = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      df2 = df_temp[df_temp['Parameter'] == 'TroponinT'].reset_index(drop=True)
      df_sub = find_troponin(df1, df2)
      troponin_stats(df_sub, df_record)
    elif col == 'TroponinT':
      pass
    elif col == 'Urine':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      df_sub2 = df_temp[df_temp['Parameter'] == 'Weight'].reset_index(drop=True)
      urine_stats(df_sub, df_sub2, df_record, col)
    elif col == 'WBC':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      wbc_stats(df_sub, df_record, col)
    elif col == 'Weight':
      df_sub = df_temp[df_temp['Parameter'] == col].reset_index(drop=True)
      weight_stats(df_sub, df_record, col)

  df_record_all = pd.concat([df_record_all, df_record], ignore_index=True)

# final dataframe

In [267]:
df_record_all = df_record_all.drop(index=0)
df_record_all.shape

(12000, 243)

In [268]:
df_record_all['RecordID'] = df_record_all['RecordID'].astype(int)

In [269]:
df_record_all.dtypes

RecordID                        int64
Albumin_Initial               float64
Albumin_Min                   float64
Albumin_Max                   float64
Albumin_Mean                  float64
ALP_Initial                   float64
ALP_Max                       float64
ALT_Initial                   float64
ALT_Max                       float64
AST_Initial                   float64
AST_Max                       float64
Bilirubin_Initial             float64
Bilirubin_Max                 float64
BUN_Initial                   float64
BUN_Max                       float64
BUN_Mean                      float64
BUN_Creatinine_Ratio          float64
Cholesterol_Initial           float64
Cholesterol_Min               float64
Creatinine_Initial            float64
Creatinine_Max                float64
Creatinine_Mean               float64
FiO2_Initial                  float64
FiO2_Max                      float64
FiO2_Mean                     float64
GCS_Initial                   float64
GCS_Final                     float64
GCS_Min                       float64
GCS_Max                       float64
GCS_Mean                      float64
Glucose_Initial               float64
Glucose_Min                   float64
Glucose_Max                   float64
Glucose_Mean                  float64
HCO3_Initial                  float64
HCO3_Final                    float64
HCO3_Min                      float64
HCO3_Max                      float64
HCT_Initial                   float64
HCT_Min                       float64
HCT_Max                       float64
HCT_Mean                      float64
HR_Initial                    float64
HR_Final                      float64
HR_Min                        float64
HR_Max                        float64
HR_Mean                       float64
HR_SD                         float64
K_Initial                     float64
K_Final                       float64
K_Min                         float64
K_Max                         float64
K_Mean                        float64
Lactate_Initial               float64
Lactate_Max                   float64
Lactate_Clearance_Rate_6H     float64
Lactate_Clearance_Rate_12H    float64
MechVent_Any                  float64
Mg_Initial                    float64
Mg_Min                        float64
Mg_Max                        float64
Na_Initial                    float64
Na_Final                      float64
Na_Min                        float64
Na_Max                        float64
Na_Mean                       float64
PaCO2_Initial                 float64
PaCO2_Min                     float64
PaCO2_Max                     float64
PaO2_Initial                  float64
PaO2_Min                      float64
PaO2_FiO2_Ratio               float64
pH_Initial                    float64
pH_Min                        float64
pH_Max                        float64
pH_Mean                       float64
Platelets_Initial             float64
Platelets_Min                 float64
RespRate_Initial              float64
RespRate_Max                  float64
RespRate_Mean                 float64
SaO2_Initial                  float64
SaO2_Min                      float64
Temp_Initial                  float64
Temp_Min                      float64
Temp_Max                      float64
Temp_Mean                     float64
Temp_SD                       float64
Urine_Sum                     float64
Urine_MinRate                 float64
Urine_MaxRate                 float64
Urine_MeanRate                float64
WBC_Initial                   float64
WBC_Min                       float64
WBC_Max                       float64
Weight_Initial                float64
Weight_Final                  float64
UniDiasABP_Initial            float64
UniDiasABP_Min                float64
UniDiasABP_Max                float64
UniDiasABP_Mean               float64
UniMAP_Initial                float64
UniMAP_Final                  float64
UniMAP_Min                    float64
UniMAP_Max                    float64
UniMAP_Mean                   float64
UniMAP_SD                     float64
UniSysABP_Initial             float64
UniSysABP_Final               float64
UniSysABP_Min                 float64
UniSysABP_Max                 float64
UniSysABP_Mean                float64
UniSysABP_SD                  float64
Troponin_Max                  float64
Albumin_Count                 float64
ALP_Count                     float64
ALT_Count                     float64
AST_Count                     float64
BUN_Count                     float64
Bilirubin_Count               float64
Cholesterol_Count             float64
Creatinine_Count              float64
FiO2_Count                    float64
GCS_Count                     float64
Glucose_Count                 float64
HCO3_Count                    float64
HCT_Count                     float64
HR_Count                      float64
K_Count                       float64
Lactate_Count                 float64
MechVent_Count                float64
Mg_Count                      float64
Na_Count                      float64
PaCO2_Count                   float64
PaO2_Count                    float64
pH_Count                      float64
Platelets_Count               float64
RespRate_Count                float64
SaO2_Count                    float64
Temp_Count                    float64
Urine_Count                   float64
WBC_Count                     float64
UniDiasABP_Count              float64
UniMAP_Count                  float64
UniSysABP_Count               float64
Troponin_Count                float64
Albumin_Delta                 float64
ALP_Delta                     float64
ALT_Delta                     float64
AST_Delta                     float64
Bilirubin_Delta               float64
BUN_Delta                     float64
Cholesterol_Delta             float64
Creatinine_Delta              float64
HCO3_Delta                    float64
HCT_Delta                     float64
K_Delta                       float64
Mg_Delta                      float64
Na_Delta                      float64
PaO2_Delta                    float64
Platelets_Delta               float64
SaO2_Delta                    float64
WBC_Delta                     float64
Weight_Delta                  float64
Troponin_Delta                float64
FiO2_Slope                    float64
GCS_Slope                     float64
Glucose_Slope                 float64
HR_Slope                      float64
PaCO2_Slope                   float64
pH_Slope                      float64
RespRate_Slope                float64
Temp_Slope                    float64
Urine_Rate_Slope              float64
UniDiasABP_Slope              float64
UniMAP_Slope                  float64
UniSysABP_Slope               float64
Albumin_Miss                  float64
ALP_Miss                      float64
ALT_Miss                      float64
AST_Miss                      float64
Bilirubin_Miss                float64
BUN_Miss                      float64
Cholesterol_Miss              float64
Creatinine_Miss               float64
FiO2_Miss                     float64
GCS_Miss                      float64
Glucose_Miss                  float64
HCO3_Miss                     float64
HCT_Miss                      float64
HR_Miss                       float64
K_Miss                        float64
Lactate_Miss                  float64
MechVent_Miss                 float64
Mg_Miss                       float64
Na_Miss                       float64
PaCO2_Miss                    float64
PaO2_Miss                     float64
pH_Miss                       float64
Platelets_Miss                float64
RespRate_Miss                 float64
SaO2_Miss                     float64
Temp_Miss                     float64
Urine_Miss                    float64
WBC_Miss                      float64
Weight_Miss                   float64
UniDiasABP_Miss               float64
UniMAP_Miss                   float64
UniSysABP_Miss                float64
Troponin_Miss                 float64
Albumin_Last_Minute           float64
ALP_Last_Minute               float64
ALT_Last_Minute               float64
AST_Last_Minute               float64
Bilirubin_Last_Minute         float64
BUN_Last_Minute               float64
Cholesterol_Last_Minute       float64
Creatinine_Last_Minute        float64
FiO2_Last_Minute              float64
GCS_Last_Minute               float64
Glucose_Last_Minute           float64
HCO3_Last_Minute              float64
HCT_Last_Minute               float64
HR_Last_Minute                float64
K_Last_Minute                 float64
Lactate_Last_Minute           float64
MechVent_Last_Minute          float64
Mg_Last_Minute                float64
Na_Last_Minute                float64
PaCO2_Last_Minute             float64
PaO2_Last_Minute              float64
pH_Last_Minute                float64
Platelets_Last_Minute         float64
RespRate_Last_Minute          float64
SaO2_Last_Minute              float64
Temp_Last_Minute              float64
Urine_Last_Minute             float64
WBC_Last_Minute               float64
Weight_Last_Minute            float64
UniDiasABP_Last_Minute        float64
UniMAP_Last_Minute            float64
UniSysABP_Last_Minute         float64
Troponin_Last_Minute          float64
dtype: object

In [270]:
df_combined = pd.merge(left=df_record_all, right=df_patient, on='RecordID', how='inner')
df_combined.shape

(12000, 255)

In [271]:
(df_combined.isnull().sum()/len(df_combined)*100).sort_values(ascending=False)

Cholesterol_Min               92.100000
Cholesterol_Initial           92.100000
Troponin_Max                  73.325000
RespRate_Initial              72.316667
RespRate_Mean                 72.266667
RespRate_Max                  72.266667
Lactate_Clearance_Rate_12H    69.041667
Lactate_Clearance_Rate_6H     65.150000
Albumin_Max                   59.408333
Albumin_Mean                  59.408333
Albumin_Initial               59.408333
Albumin_Min                   59.408333
ALP_Initial                   57.525000
ALP_Max                       57.525000
AST_Initial                   56.566667
ALT_Max                       56.558333
Bilirubin_Initial             56.558333
Bilirubin_Max                 56.558333
ALT_Initial                   56.558333
AST_Max                       56.550000
SaO2_Initial                  55.350000
SaO2_Min                      55.316667
Height                        47.825000
Lactate_Initial               45.200000
Lactate_Max                   45.200000
MechVent_Any                  36.825000
PaO2_FiO2_Ratio               36.741667
FiO2_Initial                  32.366667
FiO2_Max                      32.366667
FiO2_Mean                     32.366667
PaO2_Initial                  24.583333
PaO2_Min                      24.550000
PaCO2_Max                     24.541667
PaCO2_Min                     24.541667
PaCO2_Initial                 24.541667
pH_Initial                    24.200000
pH_Mean                       24.141667
pH_Max                        24.141667
pH_Min                        24.141667
Urine_MeanRate                 8.908333
Urine_MinRate                  8.908333
Urine_MaxRate                  8.908333
Weight_Initial                 8.350000
Weight_Final                   7.733333
SAPS-I                         4.316667
SOFA                           3.358333
Urine_Sum                      2.583333
Mg_Initial                     2.508333
Glucose_Initial                2.475000
Glucose_Max                    2.450000
Glucose_Min                    2.450000
Glucose_Mean                   2.450000
Mg_Max                         2.433333
Mg_Min                         2.433333
K_Initial                      2.083333
WBC_Initial                    2.083333
K_Max                          2.075000
K_Final                        2.075000
K_Mean                         2.075000
K_Min                          2.075000
WBC_Max                        1.975000
WBC_Min                        1.975000
Temp_Initial                   1.866667
Na_Initial                     1.800000
Na_Max                         1.766667
Na_Final                       1.766667
Na_Min                         1.766667
Na_Mean                        1.766667
UniDiasABP_Initial             1.733333
HCO3_Final                     1.725000
HCO3_Min                       1.725000
HCO3_Max                       1.725000
HCO3_Initial                   1.725000
Platelets_Initial              1.716667
UniSysABP_Final                1.700000
HR_Final                       1.650000
Platelets_Min                  1.650000
UniSysABP_Initial              1.650000
UniMAP_Initial                 1.641667
UniMAP_Final                   1.616667
HCT_Initial                    1.600000
HCT_Mean                       1.583333
HCT_Max                        1.583333
HCT_Min                        1.583333
Temp_SD                        1.541667
GCS_Max                        1.541667
GCS_Mean                       1.541667
GCS_Initial                    1.541667
GCS_Min                        1.541667
GCS_Final                      1.541667
Temp_Mean                      1.541667
Temp_Max                       1.541667
Temp_Min                       1.541667
HR_Initial                     1.533333
BUN_Initial                    1.533333
UniSysABP_Max                  1.533333
UniSysABP_Mean                 1.533333
UniSysABP_SD                   1.533333
UniMAP_Max                     1.533333
UniMAP_SD                      1.533333
UniMAP_Mean                    1.533333
UniSysABP_Min                  1.533333
HR_SD                          1.533333
UniDiasABP_Max                 1.533333
UniDiasABP_Mean                1.533333
UniMAP_Min                     1.533333
UniDiasABP_Min                 1.533333
HR_Max                         1.533333
HR_Min                         1.533333
HR_Mean                        1.533333
BUN_Mean                       1.525000
BUN_Creatinine_Ratio           1.525000
Creatinine_Initial             1.525000
Creatinine_Mean                1.525000
BUN_Max                        1.525000
Creatinine_Max                 1.525000
Length_of_stay                 1.433333
Weight_Delta                   0.783333
Survival                       0.766667
WBC_Delta                      0.133333
Gender                         0.100000
Mg_Delta                       0.091667
Platelets_Delta                0.066667
BUN_Delta                      0.050000
PaO2_Delta                     0.050000
SaO2_Delta                     0.050000
Na_Delta                       0.033333
AST_Delta                      0.025000
HCT_Delta                      0.016667
K_Delta                        0.008333
HCO3_Count                     0.000000
FiO2_Count                     0.000000
Creatinine_Count               0.000000
Glucose_Count                  0.000000
GCS_Count                      0.000000
BUN_Count                      0.000000
AST_Count                      0.000000
ALT_Count                      0.000000
ALP_Count                      0.000000
Albumin_Count                  0.000000
RecordID                       0.000000
Cholesterol_Count              0.000000
Bilirubin_Count                0.000000
HCT_Count                      0.000000
WBC_Count                      0.000000
UniDiasABP_Count               0.000000
Temp_Count                     0.000000
SaO2_Count                     0.000000
RespRate_Count                 0.000000
Troponin_Count                 0.000000
UniMAP_Count                   0.000000
Bilirubin_Delta                0.000000
ALT_Delta                      0.000000
Urine_Count                    0.000000
Lactate_Count                  0.000000
pH_Count                       0.000000
Platelets_Count                0.000000
HR_Count                       0.000000
K_Count                        0.000000
Creatinine_Delta               0.000000
Cholesterol_Delta              0.000000
HCO3_Delta                     0.000000
UniSysABP_Count                0.000000
Albumin_Delta                  0.000000
Troponin_Delta                 0.000000
FiO2_Slope                     0.000000
GCS_Slope                      0.000000
Glucose_Slope                  0.000000
HR_Slope                       0.000000
PaCO2_Slope                    0.000000
pH_Slope                       0.000000
RespRate_Slope                 0.000000
Temp_Slope                     0.000000
Urine_Rate_Slope               0.000000
UniDiasABP_Slope               0.000000
UniMAP_Slope                   0.000000
UniSysABP_Slope                0.000000
Albumin_Miss                   0.000000
ALP_Miss                       0.000000
ALT_Miss                       0.000000
AST_Miss                       0.000000
Bilirubin_Miss                 0.000000
BUN_Miss                       0.000000
Cholesterol_Miss               0.000000
Creatinine_Miss                0.000000
ALP_Delta                      0.000000
MechVent_Count                 0.000000
Mg_Count                       0.000000
Na_Count                       0.000000
PaCO2_Count                    0.000000
PaO2_Count                     0.000000
HR_Miss                        0.000000
HCT_Miss                       0.000000
HCO3_Miss                      0.000000
Glucose_Miss                   0.000000
GCS_Miss                       0.000000
FiO2_Miss                      0.000000
K_Miss                         0.000000
Lactate_Miss                   0.000000
Platelets_Miss                 0.000000
RespRate_Miss                  0.000000
MechVent_Miss                  0.000000
Mg_Miss                        0.000000
Na_Miss                        0.000000
PaCO2_Miss                     0.000000
PaO2_Miss                      0.000000
pH_Miss                        0.000000
UniMAP_Miss                    0.000000
UniSysABP_Miss                 0.000000
Troponin_Miss                  0.000000
Albumin_Last_Minute            0.000000
ALP_Last_Minute                0.000000
ALT_Last_Minute                0.000000
AST_Last_Minute                0.000000
Bilirubin_Last_Minute          0.000000
BUN_Last_Minute                0.000000
Cholesterol_Last_Minute        0.000000
SaO2_Miss                      0.000000
Temp_Miss                      0.000000
Urine_Miss                     0.000000
WBC_Miss                       0.000000
Weight_Miss                    0.000000
UniDiasABP_Miss                0.000000
HCT_Last_Minute                0.000000
HCO3_Last_Minute               0.000000
Glucose_Last_Minute            0.000000
GCS_Last_Minute                0.000000
FiO2_Last_Minute               0.000000
Creatinine_Last_Minute         0.000000
HR_Last_Minute                 0.000000
K_Last_Minute                  0.000000
pH_Last_Minute                 0.000000
Platelets_Last_Minute          0.000000
Lactate_Last_Minute            0.000000
MechVent_Last_Minute           0.000000
Mg_Last_Minute                 0.000000
Na_Last_Minute                 0.000000
PaCO2_Last_Minute              0.000000
PaO2_Last_Minute               0.000000
Weight_Last_Minute             0.000000
WBC_Last_Minute                0.000000
Urine_Last_Minute              0.000000
Temp_Last_Minute               0.000000
SaO2_Last_Minute               0.000000
RespRate_Last_Minute           0.000000
Troponin_Last_Minute           0.000000
UniDiasABP_Last_Minute         0.000000
Age                            0.000000
UniMAP_Last_Minute             0.000000
UniSysABP_Last_Minute          0.000000
In-hospital_death              0.000000
ICUType_1.0                    0.000000
ICUType_2.0                    0.000000
ICUType_3.0                    0.000000
ICUType_4.0                    0.000000
dtype: float64

In [272]:
df_combined.head(10)

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,Age,Gender,Height,SAPS-I,SOFA,Length_of_stay,Survival,In-hospital_death,ICUType_1.0,ICUType_2.0,ICUType_3.0,ICUType_4.0
0,137188,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.500000,10.000000,NaN,NaN,0.9,0.9,0.675000,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.500000,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.060000,1.5,1.8,0.000000,-20.000000,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.750000,40.0,39.0,51.0,187.0,73.0,121.666667,7.39,7.29,7.42,7.361429,85.0,71.0,NaN,NaN,NaN,NaN,NaN,37.6,36.3,38.9,37.329412,0.645041,2763.0,0.167785,3.775168,0.934510,13.3,9.3,13.3,59.60,59.6,60.0,38.0,77.0,59.859375,69.00,86.00,48.00,95.00,75.156250,8.942885,97.0,123.0,82.0,131.0,108.609375,10.529802,0.4,3.0,3.0,3.0,3.0,4.0,3.0,0.0,4.0,18.0,13.0,4.0,4.0,6.0,64.0,5.0,6.0,18.0,4.0,4.0,7.0,7.0,7.0,4.0,0.0,0.0,34.0,36.0,4.0,64.0,64.0,64.0,3.0,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0.0,-0.3,3.0,-3.1,0.6,-0.2,0.0,-50.0,9.0,0.0,-4.0,0.00,-0.18,-0.000198,0.000168,0.044188,-0.010776,0.000673,0.000002,0.000000,-0.000355,-2.380140,-0.001739,0.002434,0.004666,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2113.0,2113.0,2113.0,2113.0,2113.0,2113.0,0.0,2113.0,2819.0,2789.0,2113.0,2113.0,2799.0,2849.0,2113.0,2803.0,2819.0,2113.0,2113.0,2743.0,2743.0,2743.0,2799.0,0.0,0.0,2849.0,2849.0,2799.0,2849.0,2849.0,2849.0,2849.0,1320.0,22.0,0.0,167.6,15.0,16.0,13.0,-1.0,0,False,False,True,False
1,140351,2.2,2.2,2.2,2.200000,37.0,37.0,112.0,112.0,453.0,453.0,1.1,1.1,12.0,20.0,15.666667,20.000000,NaN,NaN,0.7,1.0,0.866667,1.0,1.0,0.500000,3.0,8.0,3.0,11.0,6.000000,199.0,105.0,234.0,170.600000,20.0,23.0,20.0,23.0,33.9,30.3,38.6,33.360000,99.0,96.0,71.0,117.0,97.528090,10.956619,2.9,5.9,2.9,5.9,4.400000,9.7,9.7,0.000000,4.123711,1.0,2.7,1.8,2.7,143.0,137.0,137.0,143.0,139.333333,44.0,33.0,69.0,310.0,73.0,110.000000,7.35,7.10,7.44,7.351500,123.0,92.0,NaN,NaN,NaN,98.0,96.0,34.7,34.7,37.6,36.679070,0.664232,3987.0,0.190721,5.085892,0.782265,27.1,16.8,27.1,72.60,98.9,54.0,29.0,90.0,48.739130,72.00,71.00,35.00,127.00,76.633333,16.502945,117.0,108.0,44.0,175.0,117.000000,25.219912,NaN,1.0,1.0,1.0,1.0,3.0,1.0,0.0,3.0,14.0,10.0,5.0,3.0,5.0,89.0,5.0,15.0,16.0,2.0,3.0,19.0,19.0,20.0,6.0,0.0,8.0,86.0,48.0,4.0,92.0,90.0,92.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.3,3.0,-1.0,3.0,-0.9,-6.0,-216.0,-24.0,1.0,-6.5,26.30,0.00,-0.000141,0.002588,-0.062102,-0.006374,-0.004262,0.000056,0.000000,0.000645,-1.168270,-0.002770,-0.002166,0.002073,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,950.0,950.0,950.0,950.0,950.0,2189.0,0.0,2189.0,2804.0,2804.0,2438.0,2189.0,2189.0,2864.0,2438.0,2610.0,2804.0,2189.0,2189.0,2757.0,2757.0,2757.0,2189.0,0.0,2804.0,2864.0,2864.0,2189.0,2864.0,2864.0,2864.0,2864.0,0.0,72.0,1.0,177.8,22.0,13.0,15.0,1007.0,0,False,True,False,False
2,141985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,12.0,9.666667,20.000000,NaN,NaN,0.6,0.6,0.533333,NaN,NaN,NaN,15.0,15.0,15.0,15.0,15.000000,105.0,105.0,154.0,124.666667,28.0,24.0,24.0,28.0,32.2,27.1,32.5,30.075000,86.0,78.0,78.0,111.0,89.170732,8.731845,3.3,3.5,3.3,3.7,3.475000,0.8,0.8,0.000000,0.000000,NaN,1.3,1.3,2.1,133.0,132.0,132.0,134.0,133.000000,41.0,39.0,51.0,267.0,95.0,NaN,7.43,7.35,7.43,7.398000,346.0,290.0,NaN,NaN,NaN,97.0,96.0,36.6,35.6,38.2,37.000000,0.629574,7140.0,0.083333,5.333333,1.997873,9.9,9.9,13.5,75.00,75.0,55.0,41.0,62.0,51.365854,80.33,73.00,60.00,83.33,70.861463,5.859821,131.0,117.0,80.0,131.0,106.853659,11.529443,0.3,0.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,11.0,3.0,3.0,4.0,41.0,4.0,3.0,0.0,3.0,3.0,5.0,5.0,5.0,3.0,0.0,2.0,12.0,33.0,3.0,41.0,41.0,41.0,1.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,-0.2,-4.0,0.3,0.2,0.8,-1.0,-170.0,-56.0,-1.0,0.7,0.00,0.00,0.000000,0.000000,0.037484,0.002859,-0.004726,0.000020,0.000000,0.000136,-30.023855,0.000029,-0.000678,-0.005132,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2163.0,0.0,2163.0,0.0,2846.0,2163.0,2163.0,2624.0,2846.0,2624.0,2140.0,0.0,2624.0,2163.0,2140.0,2140.0,2140.0,2163.0,0.0,2117.0,2666.0,2846.0,2163.0,2846.0,2846.0,2846.0,2846.0,1316.0,61.0,1.0,NaN,8.0,1.0,12.0,257.0,0,True,False,False,False
3,136263,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,20.0,14.666667,18.571429,NaN,NaN,0.6,1.1,0.800000,1.0,1.0,0.625000,3.0,15.0,3.0,15.0,12.142857,118.0,118.0,125.0,121.500000,27.0,29.0,27.0,29.0,28.9,27.4,31.9,29.600000,60.0,90.0,60.0,90.0,78.971429,7.014631,4.3,4.2,4.2,4.3,4.250000,NaN,NaN,NaN,NaN,1.0,2.2,2.2,2.2,137.0,136.0,136.0,137.0,136.500000,35.0,35.0,53.0,484.0,108.0,216.000000,7.52,7.34,7.52,7.402500,67.0,67.0,NaN,NaN,NaN,98.0,97.0,36.5,35.9,37.8,37.064000,0.672607,2847.0,0.323728,6.474564,1.221307,7.4,7.4,14.8,75.11,80.0,58.0,42.0,69.0,59.857143,75.00,72.00,55.67,89.00,76.076286,7.717743,107.0,106.0,83.0,127.0,107.600000,11.151892,NaN,0.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,4.0,7.0,2.0,3.0,4.0,35.0,2.0,0.0,6.0,1.0,2.0,8.0,8.0,8.0,4.0,0.0,4.0,25.0,21.0,4.0,35.0,35.0,35.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.5,2.0,-1.5,-0.1,0.0,-1.0,-366.0,5.0,-1.0,2.6,4.89,0.00,-0.001389,0.003582,0.004263,0.005479,0.011597,-0.000120,0.000000,0.001512,-169.160598,-0.001257,-0.001943,-0.001591,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2448.0,0.0,2448.0,471.0,2701.0,2448.0,2448.0,2448.0,2831.0,2448.0,0.0,1331.0,806.0,2448.0,872.0,872.0,872.0,2448.0,0.0,872.0,1211.0,1451.0,2448.0,2831.0,2831.0,2831.0,2831.0,0.0,67.0,1.0,167.6,17.0,9.0,9.0,-1.0,0,False,True,False,False
4,141669,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,13.0,12.000000,16.250000,NaN,NaN,0.8,0.8,0.766667,NaN,NaN,NaN,15.0,15.0,15.0,15.0,15.000000,267.0,175.0,267.0,220.500000,30.0,21.0,21.0,30.0,39.3,35.3,39.3,37.300000,73.0,83.0,54.0,84.0,69.428571,7.496805,2.8,4.6,2.8,5.0,3.820000,NaN,NaN,NaN,NaN,NaN,1.9,1.9,1.9,137.0,137.0,136.0,140.0,137.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,308.0,237.0,19.0,26.0,18.550000,NaN,NaN,36.6,36.0,37.1,36.654545,0.353167,4595.0,0.465549,3.491620,2.024611,8.9,7.3,8.9,71.60,71.6,66.0,50.0,93.0,70.027778,83.00,105.30,70.00,115.70,87.748056,11.373784,117.0,130.0,96.0,165.0,123.194444,15.863380,NaN,0.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,12.0,4.0,4.0,2.0,42.0,5.0,0.0,0.0,2.0,4.0,0.0,0.0,0.0,2.0,40.0,0.0,11.0,12.0,2.0,36.0,36.0,36.0,0.0,0.0,0.0,0.0,0.0,0.0,-2.0,0.0,-0.1,-9.0,-4.0,1.8,0.0,0.0,0.0,-71.0,0.0,-1.6,0.00,0.00,0.000000,0.000000,0.000593,-0.002046,0.000000,0.000000,0.000053,0.000018,3.267020,0.009731,0.010702,0.012650,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1616.0,0.0,1616.0,0.0,2756.0,1616.0,1616.0,1616.0,2756.0,1616.0,0.0,0.0,1616.0,1616.0,0.0,0.0,0.0,1616.0,2756.0,0.0,2756.0,2636.0,1616.0,2756.0,2756.0,2756.0,2756.0,0.0,50.0,0.0,NaN,7.0,0.0,4.0,-1.0,0,False,False,True,False
5,133368,3.0,3.0,3.0,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,34.0,26.333333,30.909091,NaN,NaN,0.8,1.2,1.033333,1.0,1.0,0.511765,3.0,14.0,3.0,14.0,9.500000,177.0,98.0,177.0,129.666667,26.0,22.0,22.0,26.0,38.1,37.3,39.9,38.425000,72.0,101.0,72.0,115.0,96.434783,10.177077,4.5,4.1,4.1,4.5,4.366667,4.9,4.9,69.387755,69.387755,1.0,1.4,1.4,2.7,141.0,143.0,140.0,143.0,141.333333,43.0,38.0,55.0,433.0,61.0,101.666667,7.40,7.24,7.42,7.326000,154.0,149.0,NaN,NaN,NaN,96.0,91.0,35.1,35.1,38.1,36.600000,0.810350,3387.0,0.000000,3.384419,0.674023,9.3,9.3,17.1,75.00,73.1,75.0,44.0,84.0,60.938144,99.00,78.00,60.00,114.00,83.868852,10.387493,136.0,110.0,93.0,167.0,125.061856,15.341131,NaN,1.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,17.0,12.0,3.0,3.0,4.0,69.0,3.0,5.0,12.0,3.0,3.0,15.0,15.0,15.0,3.0,0.0,8.0,13.0,47.0,3.0,97.0,122.0,97.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0,0.0,0.3,-4.0,0.3,-0.4,0.9,2.0,-372.0,-5.0,-5.0,7.8,-1.90,0.00,-0.000076,0.005446,-0.034969,0.007912,0.000562,-0.000052,0.000000,0.000159,-6.997156,-0.002798,0.000864,0.000644,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2166.0,0.0,0.0,0.0,0.0,2166.0,0.0,2166.0,2722.0,2662.0,2166.0,2166.0,2166.0,2842.0,2166.0,2355.0,2722.0,2166.0,2166.0,2617.0,2617.0,2617.0,2166.0,0.0,2617.0,2662.0,2842.0,2166.0,2842.0,2842.0,2842.0,2842.0,0.0,83.0,0.0,152.4,16.0,9.0,17.0,-1.0,0,False,True,False,False
6,132765,2.4,2.4,2.5,2.450000,38.0,46.0,14.0,14.0,33.0,33.0,0.7,0.7,24.0,24.0,20.666667,19.000000,NaN,NaN,1.5,1.5,1.233333,0.6,1.0,0.612500,3.0,3.0,3.0,11.0,5.416667,142.0,132.0,166.0,151.166667,16.0,17.0,13.0,18.0,40.5,27.6,40.5,34.800000,84.0,61.0,50.0,128.0,76.820513,14.851423,3.9,4.1,3.9,5.1,4.533333,7.2,8.9,-2.777778,-5.555556,1.0,2.6,1.7,2.6,136.0,131.0,127.0,137.0,132.500000,46.0,27.0,46.0,122.0,90.0,106.000000,7.26,7.22,7.48,7.318824,151.0,86.0,NaN,NaN,NaN,NaN,NaN,36.7,35.9,37.7,36.642857,0.578744,4360.0,0.304878,2.195122,1.082225,10.9,10.9,22.9,82.00,82.0,35.0,34.0,72.0,49.151515,48.00,83.00,43.00,102.00,69.422680,12.612688,79.0,136.0,60.0,173.0,122.111111,24.955016,0.1,2.0,2.0,2.0,2.0,6.0,2.0,0.0,6.0,16.0,12.0,6.0,6.0,7.0,78.0,6.0,16.0,16.0,6.0,6.0,17.0,17.0,17.0,6.0,0.0,0.0,14.0,46.0,6.0,99.0,97.0,99.0,2.0,0.1,8.0,-3.0,-11.0,0.0,-5.0,0.0,-0.5,1.0,-12.9,0.2,-0.6,-5.0,31.0,-65.0,0.0,5.5,0.00,-0.01,-0.000121,-0.002657,-0.001532,-0.011733,-0.004719,0.000089,0.000000,-0.000476,-1.170791,0.007026,0.008783,0.014085,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2374.0,2374.0,2374.0,2374.0,2374.0,2374.0,0.0,2374.0,2833.0,2713.0,2374.0,2374.0,2606.0,2833.0,2374.0,2690.0,2833.0,2374.0,2374.0,2690.0,2690.0,2690.0,2374.0,0.0,0.0,2713.0,2833.0,2374.0,0.0,2833.0,2833.0,2833.0,704.0,90.0,1.0,NaN,20.0,10.0,18.0,120.0,0,False,False,False,True
7,138320,NaN,NaN,NaN,NaN,82.0,82.0,67.0,67.0,265.0,265.0,NaN,NaN,13.0,15.0,14.000000,16.250000,211.0,211.0,0.8,1.0,0.900000,NaN,NaN,NaN,15.0,15.0,14.0,15.0,14.916667,126.0,107.0,126.0,116.500000,26.0,28.0,26.0,28.0,44.0,43.0,44.6,43.866667,64.0,79.0,64.0,87.0,73.900000,4.601003,4.0,4.3,4.0,4.3,4.133333,NaN,NaN,NaN,NaN,NaN,2.2,2.2,2.4,140.0,137.0,137.0,140.0,138.500000,39.0,39.0,39.0,71.0,71.0,NaN,7.40,7.40,7.40,7.400000,182.0,182.0,16.0,27.0,18.815789,97.0,97.0,37.7,36.1,37.9,37.175000,0.552885,4425.0,0.000000,1.616162,0.885943,10.5,9.9,10.5,99.00,99.0,70.0,37.0,88.0,62.428571,91.67,74.33,56.67,163.00,82.258000,19.862872,135.0,105.0,90.0,158.0,113.971429,17.114641,NaN,0.0,1.0,1.0,1.0,2.0,0.0,1.0,2.0,0.0,12.0,2.0,2.0,3.0,40.0,3.0,0.0,0.0,3.0,2.0,1.0,1.0,1.0,3.0,38.0,1.0,12.0,23.0,2.0,35.0,35.0,35.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.2,2.0,-1.0,0.3,0.0,-3.0,0.0,1.0,0.0,-0.6,0.00,0.00,0.000000,0.000081,-0.013514,0.002558,0.000000,0.000000,0.000379,0.000127,-10.738557,-0.007456,-0.012445,-0.012624,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,485.0,485.0,485.0,0.0,1891.0,485.0,1891.0,0.0,2780.0,1891.0,1891.0,1891.0,2780.0,1891.0,0.0,0.0,1891.0,1891.0,116.0,116.0,116.0,1891.0,2780.0,80.0,2780.0,2840.0,1891.0,2780.0,2780.0,2780.0,2780.0,0.0,66.0,1.0,175.3,8.0,2.0,3.0,-1.0,0,True,False,False,False
8,136295,NaN,NaN,NaN,NaN,38.0,38.0,71.0,71.0,63.0,63.0,NaN,NaN,16.0,16.0,15.333333,17.777778,NaN,NaN,1.2,1.2,1.033333,NaN,NaN,NaN,15.0,15.0,13.0,15.0,14.785714,150.0,107.0,150.0,123.666667,26.0,30.0,26.0,30.0,35.6,30.6,35.6,32.700000,88.0,94.0,79.0,102.0,90.033333,6.300300,4.4,3.8,3.8,4.4,4.033333,NaN,NaN,NaN,NaN,NaN,1.8,1.8,2.1,141.0,138.0,138.0,141.0,139.333333,NaN,NaN,NaN,NaN,NaN,NaN,7.42,7.42,7.42,7.420000,162.0,148.0,15.0,29.0,16.901639,NaN,NaN,35.7,35.3,37.9,37.033333,0.943237,4365.0,0.375000,3.750000,1.259146,8.9,6.5,8.9,80.00,80.0,61.0,50.0,80.0,61.672131,71.00,85.00,60.00,109.00,78.803279,12.748620,113.0,122.0,81.0,148.0,108.885246,18.430137,NaN,0.0,1.0,1.0,1.0,3.0,0.0,0.0,3.0,0.0,14.0,3.0,3.0,3.0,60.0,3.0,0.0,0.0,3.0,3.0,0.0,0.0,1.0,3.0,61.0,0.0,12.0,42.0,3.0,61.0,61.0,61.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.3,4.0,-5.0,-0.6,0.2,-3.0,0.0,-14.0,0.0,-2.4,0.00,0.00,0.000000,-0.000125,-0.017216,0.005135,0.000000,0.000000,0.002784,0.000931,0.422173,0.002028,0.004095,0.007874,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1113.0,1113.0,1113.0,0.0,2523.0,0.0,2523.0,0.0,2653.0,2523.0,2523.0,2523.0,2833.0,2523.0,0.0,0.0,2523.0,2523.0,0.0,0.0,1492.0,2523.0,2833.0,0.0,2713.0,2773.0,2523.0,0.0,2833.0,2833.0,2833.0,0.0,61.0,1.0,NaN,4.0,2.0,13.0,-1.0,0,False,False,False,True
9,134326,3.1,3.1,3.1,3.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0,11.500000,30.000000,NaN,NaN,0.4,0.6,0.550000,1.0,1.0,0.550000,8.0,10.0,7.0,11.0,8.545455,117.0,111.0,129.0,119.750000,22.0,27.0,22.0,27.0,34.8,30.1,34.8,32.975000,80.0,68.0,62.0,91.0,75.260000,8.095880,3.7,3.8,3.6,4.0,3.800000,1.2,2.1,NaN,NaN,1.0,1.6,1.6,2.0,134.0,141.0,134.0,141.0,136.750000,44.0,44.0,49.0,74.0,62.0,62.000000,7.42,7.35,7.44,7.398750,157.0,157.0,NaN,NaN,NaN,NaN,NaN,36.9,36.9,38.3,37.933333,0.373529,8200.0,0.694444,3.240741,1.670139,15.4,11.2,15.4,108.00,108.0,64.0,52.0,86.0,67.365385,87.00,94.00,68.00,101.00,88.916731,7.029892,133.0,146.0,95.0,159.0,131.884615,12.920047,NaN,1.0,0.0,0.0,0.0,4.0,0.0,0.0,4.0,14.0,22.0,4.0,4.0,4.0,50.0,5.0,2.0,15.0,4.0,4.0,8.0,8.0,8.0,4.0,0.0,0.0,15.0,38.0,4.0,52.0,52.0,52.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.2,5.0,-4.7,0.1,0.4,7.0,59.0,16.0,0.0,-4.2,0.00,0.00,-0.000148,0.001270,0.007430,0.005173,0.000763,0.000033,0.000000,0.000151,-70.785182,0.002558,0.004990,0.010517,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,101.0,0.0,0.0,0.0,0.0,2138.0,0.0,2138.0,2548.0,2858.0,2138.0,2138.0,2138.0,2858.0,2213.0,273.0,2548.0,2138.0,2138.0,2081.0,2081.0,2081.0,2138.0,0.0,0.0,2858.0,2858.0,2138.0,0.0,2858.0,2858.0,2858.0,0.0,59.0,1.0,NaN,12.0,7.0,13.0,-1.0,0,False,False,False,True

In [273]:
df_combined.describe()

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,Age,Gender,Height,SAPS-I,SOFA,Length_of_stay,Survival,In-hospital_death
count,12000.000000,4871.000000,4871.000000,4871.000000,4871.000000,5097.000000,5097.000000,5213.000000,5213.000000,5212.000000,5214.000000,5213.000000,5213.000000,11816.000000,11817.000000,11817.000000,11817.000000,948.000000,948.000000,11817.000000,11817.000000,11817.000000,8116.000000,8116.000000,8116.000000,11815.000000,11815.000000,11815.000000,11815.000000,11815.000000,11703.00000,11706.000000,11706.000000,11706.000000,11793.000000,11793.000000,11793.000000,11793.000000,11808.000000,11810.000000,11810.000000,11810.000000,11816.000000,11802.000000,11816.000000,11816.000000,11816.000000,11816.000000,11750.000000,11751.000000,11751.000000,11751.000000,11751.000000,6576.000000,6576.000000,4182.000000,3715.000000,7581.0,11699.000000,11708.000000,11708.000000,11784.000000,11788.000000,11788.000000,11788.000000,11788.000000,9055.000000,9055.000000,9055.000000,9050.000000,9054.000000,7591.000000,9096.000000,9103.00000,9103.000000,9103.000000,11794.000000,11802.000000,3322.000000,3328.000000,3328.000000,5358.000000,5362.000000,11776.000000,11815.000000,11815.000000,11815.000000,11815.000000,11690.000000,10931.000000,10931.000000,10931.000000,11750.000000,11763.000000,11763.000000,10998.000000,11072.000000,11792.000000,11816.000000,11816.000000,11816.000000,11803.000000,11806.000000,11816.000000,11816.000000,11816.000000,11816.000000,11802.000000,11796.000000,11816.000000,11816.000000,11816.000000,11816.000000,3201.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,11997.000000,12000.000000,11994.000000,12000.000000,12000.000000,12000.000000,11998.000000,11999.000000,11989.000000,11996.000000,11994.000000,11992.000000,11994.000000,11984.000000,11906.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.00000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.00000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.00000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,11988.000000,6261.000000,11482.000000,11597.000000,11828.000000,11908.000000,12000.000000
mean,147744.694750,2.959782,2.885095,3.000370,2.942854,109.746321,114.642927,150.092653,216.861500,222.719685,341.163023,1.908651,2.167696,25.756263,29.157570,25.427010,24.426145,156.107595,155.695148,1.355547,1.541161,1.355437,0.782410,0.832480,0.551167,10.037495,12.385950,8.277698,13.530851,11.643228,148.75015,108.804459,173.096617,137.207774,23.203256,24.281184,21.871839,25.448402,31.940286,28.592735,34.128315,31.395652,89.595819,85.924759,68.614675,112.325169,87.065322,10.105287,4.175157,4.073381,3.755110,4.547758,4.131139,2.654950,3.163190,0.433090,6.519956,1.0,1.928842,1.782550,2.247207,138.808130,138.867662,136.933661,140.760095,138.884653,41.410491,34.633793,47.449365,203.555470,92.845151,165.983954,7.370595,7.31770,7.440802,7.383668,215.074784,177.852483,19.981939,28.905649,19.638342,96.724655,95.031686,36.570211,35.885307,37.918138,37.002004,0.587417,4251.017682,0.236079,6.305545,1.271009,13.008770,10.474594,15.150296,81.243063,83.400091,62.842520,40.325152,87.010917,59.720403,82.887475,80.536437,56.339820,110.257006,79.384708,11.145321,124.774021,123.341556,87.180349,159.449898,120.467679,15.719809,2.752791,0.604083,0.786750,0.809167,0.808750,3.477250,0.817167,0.082917,3.494000,7.930250,15.499250,3.279167,3.405333,4.580500,57.255750,3.646083,2.029750,7.637000,3.405917,3.412583,5.753583,5.739250,6.015333,3.551417,13.766417,1.996667,21.603333,34.263583,3.231833,56.745250,56.280250,56.778917,0.619083,-0.013825,-1.422000,8.051192,-1.753605,0.012417,-0.484909,-0.018500,-0.003467,1.059333,-1.107951,-0.099683,0.112735,0.055852,-65.191262,-23.870672,-0.042179,-0.600964,1.964824,-0.027764,-0.000174,0.000769,-0.009518,-0.000479,-0.000369,0.000012,0.000016,0.000122,-16.346171,-0.000003,0.000497,0.001606,0.594083,0.575250,0.565583,0.565500,0.565583,0.015250,0.92100,0.015250,0.323667,0.015417,0.024500,0.017250,0.015833,0.015333,0.020750,0.452000,0.36825,0.024333,0.017667,0.245417,0.245500,0.241417,0.016500,0.722667,0.553167,0.015417,0.025833,0.019750,0.076500,0.015333,0.015333,0.015333,0.733250,474.436167,553.944000,568.976250,568.721833,580.859500,2207.383000,55.834333,2208.652083,1474.684833,2694.993417,2150.659083,2194.803333,2265.44150,2790.906333,2205.892667,776.686583,1382.702167,2161.044000,2203.341750,1504.502667,1505.324000,1565.939250,2174.363833,777.507083,757.710917,2699.166667,2689.520667,2156.725083,1916.745083,2786.483333,2784.363417,2786.501250,339.301500,64.529333,0.561144,169.146782,14.999565,6.663275,13.629016,134.961958,0.142250
std,8787.621488,0.660457,0.666761,0.640521,0.641694,145.576521,152.550958,621.545089,889.072133,896.424430,1370.070680,4.439789,4.876090,21.340629,22.791697,20.379941,12.781493,44.756021,44.787742,1.461876,1.612727,1.390033,0.252323,0.231372,0.131990,4.908701,3.639666,4.828723,2.630133,3.262094,73.83684,29.618857,85.377227,39.847157,4.678756,4.285436,4.574150,4.140478,5.959700,5.252867,4.797942,4.503538,20.054102,17.239563,14.029678,22.366685,14.734643,4.669537,0.722862,0.519734,0.513514,0.714088,0.481059,2.146722,2.687895,68.171310,64.926399,0.0,0.452545,0.345695,0.396400,4.741033,4.405947,4.418815,4.500969,4.141196,10.811032,7.832714,11.341402,122.758586,42.495789,99.375162,0.093374,0.09096,0.061447,0.056764,112.207344,98.994995,5.707012,6.344019,3.885286,3.735171,4.792340,1.060690,0.824109,0.746443,0.569658,0.256240,2857.643479,0.228647,10.568922,1.005372,10.348273,7.197489,11.359312,23.819445,24.417793,15.903909,10.118706,16.348520,9.764953,17.994802,15.278360,11.595537,18.501490,10.562754,3.514059,25.834143,22.274900,16.338134,24.691482,16.579279,5.161754,6.871148,0.927400,1.260518,1.282076,1.281006,1.645967,1.290430,0.290199,1.658119,7.215289,7.966489,1.756414,1.666714,2.551254,15.891241,1.878906,3.192107,7.413691,1.748209,1.829518,5.708568,5.690676,5.894078,1.921544,23.266352,3.402468,17.486775,12.385134,1.610218,16.672908,17.229619,16.679435,1.224722,0.161638,30.281917,357.420488,571.884016,0.842002,10.087947,1.016486,0.611454,3.558211,4.867914,0.729869,0.424740,4.029534,113.441646,55.855306,2.338883,6.485321,6.644084,1.759254,0.001132,0.001853,0.043678,0.007071,0.018143,0.000126,0.001522,0.000419,87.909890,0.004697,0.006159,0.007979,0.491089,0.494326,0.495701,0.495712,0.495701,0.122551,0.26975,0.122551,0.467894,0.123208,0.154602,0.130207,0.124836,0.122880,0.142552,0.497711,0.48235,0.154088,0.131742,0.430352,0.430401,0.427960,0.127393,0.447701,0.497186,0.123208,0.158644,0.139146,0.265808,0.122880,0.122880,0.122880,0.442279,810.397519,879.270803,886.379491,886.131617,895.504757,480.146465,258.412297,480.537670,1231.331514,377.350388,560.626950,496.344506,491.74324,367.517086,538.227135,990.829477,1237.437558,580.967311,503.354412,1125.745837,1125.501404,1127.759401,498.588145,1260.509990,1033.738204,375.913704,531.676337,509.548614,1326.113460,371.264599,372.561397,371.265256,706.379293,17.175677,0.496268,13.298488,5.207572,4.056709,12.786962,373.968472,0.349321
min,132539.000000,1.000000,1.000000,1.100000,1.100000,11.000000,12.000000,1.000000,1.000000,5.000000,5.000000,0.100000,0.100000,2.000000,2.000000,2.000000,2.272727,28.000000,28.000000,0.100000,0.100000,0.100000,0.210000,0.210000,0.210000,3.000000,3.000000,3.000000,3.000000,3.000000,21.00000,21.000000,47.000000,40.666667,5.000000,7.000000,5.000000,11.000000,10.000000,10.000000,10.300000,10.150000,23.000000,21.000000,20.000000,53.000000,35.543478,0.000000,1.500000,2.400000,1.500000,2.500000,2.500000,0.300000,0.400000,-2000.000000,-1233.333333,1.0,0.400000,0.400000,1.100000,100.000000,112.000000,100.000000,118.000000,110.800000,11.000000,10.000000,16.000000,20.000000,20.000000,20.000000,6.820000,6.80000,7.100000,7.085000,10.000000,10.000000,7.000000,14.000000,10.098039,51.000000,51.000000,26.100000,26.100000,35.300000,32.507692,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,0.500000,0.500000,21.700000,30.000000,15.000000,15.000000,22.000000,22.000000,10.000000,12.000000,10.000000,30.000000,30.000000,0.000000,40.000000,40.000000,40.000000,85.000000,77.179487,0.000000,0.010000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.800000,-529.000000,-10140.000000,-16456.000000,-20.600000,-97.000000,-35.000000,-12.900000,-23.000000,-26.300000,-6.400000,-2.800000,-26.000000,-432.000000,-566.000000,-43.000000,-264.900000,-120.000000,-47.470000,-0.040000,-0.008121,-1.178571,-0.051703,-0.833333,-0.003778,-0.027748,-0.006000,-6603.355705,-0.034465,-0.261929,-0.048315,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,15.000000,0.000000,12.700000,0.000000,0.000000,2.000000,-1.000000,0.000000
25%,140100.750000,2.500000,2.400000,2.600000,2.500000,58.000000,60.000000,17.000000,18.000000,25.000000,26.000000,0.400000,0.500000,13.000000,15.000000,12.750000,16.666667,124.000000,124.000000,0.700000,0.800000,0.700000,0.500000,0.600000,0.460000,5.000000,10.000000,3.000000,13.000000,9.312500,108.00000,90.000000,126.000000,111.808333,21.000000,22.000000,19.000000,23.000000,27.800000,25.000000,30.800000,28.261667,76.000000,74.000000,59.000000,96.000000,76.897607,6.939810,3.700000,3.700000,3.400000,4.100000,3.800000,1.300000,1.500000,0.000000,-2.859477,1.0,1.600000,1.600000,2.000000,136.000000,136.000000,135.000000,138.000000,136.500000,35.000000,30.000000,40.000000,97.000000,67.000000,91.666667,7.320000,7.27000,7.410000,7.351500,140.000000,111.000000,16.000000,24.000000,16.905649,97.000000,94.000000,35.900000,35.500000,37.400000,36.623241,0.405642,2532.500000,0.090580,2.012326,0.677080,8.400000,7.200000,10.200000,65.700000,67.200000,52.000000,34.000000,75.000000,53.019630,70.330000,70.000000,50.000000,97.000000,71.721908,8.611971,107.000000,107.000000,77.000000,142.000000,108.142857,12.030814,0.060000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,3.000000,0.000000,12.000000,2.000000,2.000000,3.000000,48.000000,2.000000,0.000000,0.000000,2.000000,2.000000,1.000000,1.000000,1.000000,2.000000,0.000000,0.000000,12.000000,29.000000,2.000000,47.000000,47.000000,47.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-4.000000,0.000000,-0.100000,-1.000000,-3.900000,-0.500000,-0.100000,-2.000000,-126.000000,-48.000000,0.000000,-2.800000,0.000000,0.000000,-0.000112,0.000000,-0.021540,-0.004604,-0.001621,0.000000,0.000000,-0.000125,-6.100542,-0.002864,-0.002860,-0.003135,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1969.000000,0.000000,1970.000000,0.000000,2694.000000,1908.000000,1956.000000,2038.00000,2831.000000,1982.000000,0.000000,0.000000,1930.000000,1970.000000,32.000000,32.000000,65.750000,1924.000000,0.000000,0.000000,2691.000000,2790.000000,1908.000000,0.000000,2829.000000,2829.000000,2829.000000,0.000000,53.000000,0.000000,162.600000,11.000000,3.000000,6.000000,-1.000000,0.000000
50%,147739.000000,3.000000,2.900000,3.000000,2.950000,78.000000,81.000000,30.000000,32.000000,45.000000,49.000000,0.700000,0.800000,19.000000,22.000000,18.750000,22.000000,153.000000,153.000000,0.900000,1.000000,0.925000,1.000000,1.000000,0.525000,11.000000,15.000000,7.000000,15.000000,12.500000,131.00000,106.000000,151.000000,129.400000,23.000000,24.000000,22.000000,25.000000,31.700000,28.000000,33.500000,30.650000,88.000000,85.000000,68.000000,110.000000,86.229968,9.159054,4.100000,4.000000,3.700000,4.400000,4.066667,1.900000,2.300000,0.000000,9.090909,1.0,1.900000,1.800000,2.200000,139.000000,139.000000,137.000000,141.000000,139.000000,40.000000,34.000000,46.000000,170.000000,82.000000,145.714286,7.380000,7.33000,7.440000,7.387647,197.000000,161.000000,19.000000,28.000000,19.043499,98.000000,96.000000,36.600000,36.000000,37.800000,36.987755,0.545511,3895.000000,0.196721,3.905447,1.074866,11.600000,9.600000,13.600000,78.000000,80.000000,61.000000,40.000000,85.000000,58.696898,81.000000,79.000000,56.000000,107.000000,77.995162,10.605418,122.000000,121.000000,86.000000,157.000000,117.968067,15.002089,0.280000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,3.000000,8.000000,13.000000,3.000000,3.000000,4.000000,55.000000,3.000000,1.000000,7.000000,3.000000,3.000000,5.000000,5.000000,5.000000,3.000000,0.000000,0.000000,14.000000,37.000000,3.000000,55.000000,54.000000,55.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,-1.100000,0.000000,0.100000,0.000000,0.000000,-16.000000,0.000000,-0.300000,0.000000,0.000000,0.000000,0.000121,-0.004473,-0.000263,0.000000,0.000000,0.000000,0.000100,-1.110305,-0.000009,0.000354,0.001300,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2291.000000,0.000000,2292.500000,1638.000000,2766.500000,2261.000000,2282.000000,2373.00000,2849.000000,2322.000000,140.000000,1362.000000,2289.000000,2298.000000,1849.500000,1851.000000,1995.000000,2255.000000,0.000000,0.000000,2769.000000,2835.000000,2238.000000,2829.000000,2848.000000,2848.000000,2848.000000,0.000000,67.000000,1.000000,170.200000,15.000000,7.000000,10.000000,-1.000000,0.000000

In [274]:
df_combined.columns.tolist()

['RecordID',
 'Albumin_Initial',
 'Albumin_Min',
 'Albumin_Max',
 'Albumin_Mean',
 'ALP_Initial',
 'ALP_Max',
 'ALT_Initial',
 'ALT_Max',
 'AST_Initial',
 'AST_Max',
 'Bilirubin_Initial',
 'Bilirubin_Max',
 'BUN_Initial',
 'BUN_Max',
 'BUN_Mean',
 'BUN_Creatinine_Ratio',
 'Cholesterol_Initial',
 'Cholesterol_Min',
 'Creatinine_Initial',
 'Creatinine_Max',
 'Creatinine_Mean',
 'FiO2_Initial',
 'FiO2_Max',
 'FiO2_Mean',
 'GCS_Initial',
 'GCS_Final',
 'GCS_Min',
 'GCS_Max',
 'GCS_Mean',
 'Glucose_Initial',
 'Glucose_Min',
 'Glucose_Max',
 'Glucose_Mean',
 'HCO3_Initial',
 'HCO3_Final',
 'HCO3_Min',
 'HCO3_Max',
 'HCT_Initial',
 'HCT_Min',
 'HCT_Max',
 'HCT_Mean',
 'HR_Initial',
 'HR_Final',
 'HR_Min',
 'HR_Max',
 'HR_Mean',
 'HR_SD',
 'K_Initial',
 'K_Final',
 'K_Min',
 'K_Max',
 'K_Mean',
 'Lactate_Initial',
 'Lactate_Max',
 'Lactate_Clearance_Rate_6H',
 'Lactate_Clearance_Rate_12H',
 'MechVent_Any',
 'Mg_Initial',
 'Mg_Min',
 'Mg_Max',
 'Na_Initial',
 'Na_Final',
 'Na_Min',
 'Na_Max',
 'Na_Mean',
 'PaCO2_Initial',
 'PaCO2_Min',
 'PaCO2_Max',
 'PaO2_Initial',
 'PaO2_Min',
 'PaO2_FiO2_Ratio',
 'pH_Initial',
 'pH_Min',
 'pH_Max',
 'pH_Mean',
 'Platelets_Initial',
 'Platelets_Min',
 'RespRate_Initial',
 'RespRate_Max',
 'RespRate_Mean',
 'SaO2_Initial',
 'SaO2_Min',
 'Temp_Initial',
 'Temp_Min',
 'Temp_Max',
 'Temp_Mean',
 'Temp_SD',
 'Urine_Sum',
 'Urine_MinRate',
 'Urine_MaxRate',
 'Urine_MeanRate',
 'WBC_Initial',
 'WBC_Min',
 'WBC_Max',
 'Weight_Initial',
 'Weight_Final',
 'UniDiasABP_Initial',
 'UniDiasABP_Min',
 'UniDiasABP_Max',
 'UniDiasABP_Mean',
 'UniMAP_Initial',
 'UniMAP_Final',
 'UniMAP_Min',
 'UniMAP_Max',
 'UniMAP_Mean',
 'UniMAP_SD',
 'UniSysABP_Initial',
 'UniSysABP_Final',
 'UniSysABP_Min',
 'UniSysABP_Max',
 'UniSysABP_Mean',
 'UniSysABP_SD',
 'Troponin_Max',
 'Albumin_Count',
 'ALP_Count',
 'ALT_Count',
 'AST_Count',
 'BUN_Count',
 'Bilirubin_Count',
 'Cholesterol_Count',
 'Creatinine_Count',
 'FiO2_Count',
 'GCS_Count',
 'Glucose_Count',
 'HCO3_Count',
 'HCT_Count',
 'HR_Count',
 'K_Count',
 'Lactate_Count',
 'MechVent_Count',
 'Mg_Count',
 'Na_Count',
 'PaCO2_Count',
 'PaO2_Count',
 'pH_Count',
 'Platelets_Count',
 'RespRate_Count',
 'SaO2_Count',
 'Temp_Count',
 'Urine_Count',
 'WBC_Count',
 'UniDiasABP_Count',
 'UniMAP_Count',
 'UniSysABP_Count',
 'Troponin_Count',
 'Albumin_Delta',
 'ALP_Delta',
 'ALT_Delta',
 'AST_Delta',
 'Bilirubin_Delta',
 'BUN_Delta',
 'Cholesterol_Delta',
 'Creatinine_Delta',
 'HCO3_Delta',
 'HCT_Delta',
 'K_Delta',
 'Mg_Delta',
 'Na_Delta',
 'PaO2_Delta',
 'Platelets_Delta',
 'SaO2_Delta',
 'WBC_Delta',
 'Weight_Delta',
 'Troponin_Delta',
 'FiO2_Slope',
 'GCS_Slope',
 'Glucose_Slope',
 'HR_Slope',
 'PaCO2_Slope',
 'pH_Slope',
 'RespRate_Slope',
 'Temp_Slope',
 'Urine_Rate_Slope',
 'UniDiasABP_Slope',
 'UniMAP_Slope',
 'UniSysABP_Slope',
 'Albumin_Miss',
 'ALP_Miss',
 'ALT_Miss',
 'AST_Miss',
 'Bilirubin_Miss',
 'BUN_Miss',
 'Cholesterol_Miss',
 'Creatinine_Miss',
 'FiO2_Miss',
 'GCS_Miss',
 'Glucose_Miss',
 'HCO3_Miss',
 'HCT_Miss',
 'HR_Miss',
 'K_Miss',
 'Lactate_Miss',
 'MechVent_Miss',
 'Mg_Miss',
 'Na_Miss',
 'PaCO2_Miss',
 'PaO2_Miss',
 'pH_Miss',
 'Platelets_Miss',
 'RespRate_Miss',
 'SaO2_Miss',
 'Temp_Miss',
 'Urine_Miss',
 'WBC_Miss',
 'Weight_Miss',
 'UniDiasABP_Miss',
 'UniMAP_Miss',
 'UniSysABP_Miss',
 'Troponin_Miss',
 'Albumin_Last_Minute',
 'ALP_Last_Minute',
 'ALT_Last_Minute',
 'AST_Last_Minute',
 'Bilirubin_Last_Minute',
 'BUN_Last_Minute',
 'Cholesterol_Last_Minute',
 'Creatinine_Last_Minute',
 'FiO2_Last_Minute',
 'GCS_Last_Minute',
 'Glucose_Last_Minute',
 'HCO3_Last_Minute',
 'HCT_Last_Minute',
 'HR_Last_Minute',
 'K_Last_Minute',
 'Lactate_Last_Minute',
 'MechVent_Last_Minute',
 'Mg_Last_Minute',
 'Na_Last_Minute',
 'PaCO2_Last_Minute',
 'PaO2_Last_Minute',
 'pH_Last_Minute',
 'Platelets_Last_Minute',
 'RespRate_Last_Minute',
 'SaO2_Last_Minute',
 'Temp_Last_Minute',
 'Urine_Last_Minute',
 'WBC_Last_Minute',
 'Weight_Last_Minute',
 'UniDiasABP_Last_Minute',
 'UniMAP_Last_Minute',
 'UniSysABP_Last_Minute',
 'Troponin_Last_Minute',
 'Age',
 'Gender',
 'Height',
 'SAPS-I',
 'SOFA',
 'Length_of_stay',
 'Survival',
 'In-hospital_death',
 'ICUType_1.0',
 'ICUType_2.0',
 'ICUType_3.0',
 'ICUType_4.0']

In [275]:
df_combined.to_csv(path+'/df_clean.csv', index=False)