In [79]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

import joblib

In [80]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [81]:
SEED = 42

np.random.seed(SEED)

# data Import

In [82]:
path = '/home/leewen/code/physionet'

In [83]:
df = pd.read_csv(path + '/df_clean.csv')

In [84]:
df.head(20)

,RecordID,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,Age,Gender,Height,SAPS-I,SOFA,Length_of_stay,Survival,In-hospital_death,ICUType_1.0,ICUType_2.0,ICUType_3.0,ICUType_4.0
0,137188,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.500000,10.000000,NaN,NaN,0.9,0.9,0.675000,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.500000,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.060000,1.5,1.8,0.000000,-20.000000,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.750000,40.0,39.0,51.0,187.0,73.0,121.666667,7.39,7.29,7.42,7.361429,85.0,71.0,NaN,NaN,NaN,NaN,NaN,37.6,36.3,38.9,37.329412,0.645041,2763.0,0.167785,3.775168,0.934510,13.3,9.3,13.3,59.60,59.6,60.0,38.0,77.0,59.859375,69.00,86.00,48.00,95.00,75.156250,8.942885,97.0,123.0,82.0,131.0,108.609375,10.529802,0.40,3.0,3.0,3.0,3.0,4.0,3.0,0.0,4.0,18.0,13.0,4.0,4.0,6.0,64.0,5.0,6.0,18.0,4.0,4.0,7.0,7.0,7.0,4.0,0.0,0.0,34.0,36.0,4.0,64.0,64.0,64.0,3.0,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0.0,-0.3,3.0,-3.1,0.6,-0.2,0.0,-50.0,9.0,0.0,-4.0,0.00,-0.18,-0.000198,0.000168,0.044188,-0.010776,0.000673,0.000002,0.000000,-0.000355,-2.380140,-0.001739,0.002434,0.004666,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2113.0,2113.0,2113.0,2113.0,2113.0,2113.0,0.0,2113.0,2819.0,2789.0,2113.0,2113.0,2799.0,2849.0,2113.0,2803.0,2819.0,2113.0,2113.0,2743.0,2743.0,2743.0,2799.0,0.0,0.0,2849.0,2849.0,2799.0,2849.0,2849.0,2849.0,2849.0,1320.0,22.0,0.0,167.6,15.0,16.0,13.0,-1.0,0,False,False,True,False
1,140351,2.2,2.2,2.2,2.200000,37.0,37.0,112.0,112.0,453.0,453.0,1.1,1.1,12.0,20.0,15.666667,20.000000,NaN,NaN,0.7,1.0,0.866667,1.0,1.0,0.500000,3.0,8.0,3.0,11.0,6.000000,199.0,105.0,234.0,170.600000,20.0,23.0,20.0,23.0,33.9,30.3,38.6,33.360000,99.0,96.0,71.0,117.0,97.528090,10.956619,2.9,5.9,2.9,5.9,4.400000,9.7,9.7,0.000000,4.123711,1.0,2.7,1.8,2.7,143.0,137.0,137.0,143.0,139.333333,44.0,33.0,69.0,310.0,73.0,110.000000,7.35,7.10,7.44,7.351500,123.0,92.0,NaN,NaN,NaN,98.0,96.0,34.7,34.7,37.6,36.679070,0.664232,3987.0,0.190721,5.085892,0.782265,27.1,16.8,27.1,72.60,98.9,54.0,29.0,90.0,48.739130,72.00,71.00,35.00,127.00,76.633333,16.502945,117.0,108.0,44.0,175.0,117.000000,25.219912,NaN,1.0,1.0,1.0,1.0,3.0,1.0,0.0,3.0,14.0,10.0,5.0,3.0,5.0,89.0,5.0,15.0,16.0,2.0,3.0,19.0,19.0,20.0,6.0,0.0,8.0,86.0,48.0,4.0,92.0,90.0,92.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.3,3.0,-1.0,3.0,-0.9,-6.0,-216.0,-24.0,1.0,-6.5,26.30,0.00,-0.000141,0.002588,-0.062102,-0.006374,-0.004262,0.000056,0.000000,0.000645,-1.168270,-0.002770,-0.002166,0.002073,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,950.0,950.0,950.0,950.0,950.0,2189.0,0.0,2189.0,2804.0,2804.0,2438.0,2189.0,2189.0,2864.0,2438.0,2610.0,2804.0,2189.0,2189.0,2757.0,2757.0,2757.0,2189.0,0.0,2804.0,2864.0,2864.0,2189.0,2864.0,2864.0,2864.0,2864.0,0.0,72.0,1.0,177.8,22.0,13.0,15.0,1007.0,0,False,True,False,False
2,141985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,12.0,9.666667,20.000000,NaN,NaN,0.6,0.6,0.533333,NaN,NaN,NaN,15.0,15.0,15.0,15.0,15.000000,105.0,105.0,154.0,124.666667,28.0,24.0,24.0,28.0,32.2,27.1,32.5,30.075000,86.0,78.0,78.0,111.0,89.170732,8.731845,3.3,3.5,3.3,3.7,3.475000,0.8,0.8,0.000000,0.000000,NaN,1.3,1.3,2.1,133.0,132.0,132.0,134.0,133.000000,41.0,39.0,51.0,267.0,95.0,NaN,7.43,7.35,7.43,7.398000,346.0,290.0,NaN,NaN,NaN,97.0,96.0,36.6,35.6,38.2,37.000000,0.629574,7140.0,0.083333,5.333333,1.997873,9.9,9.9,13.5,75.00,75.0,55.0,41.0,62.0,51.365854,80.33,73.00,60.00,83.33,70.861463,5.859821,131.0,117.0,80.0,131.0,106.853659,11.529443,0.30,0.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,11.0,3.0,3.0,4.0,41.0,4.0,3.0,0.0,3.0,3.0,5.0,5.0,5.0,3.0,0.0,2.0,12.0,33.0,3.0,41.0,41.0,41.0,1.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,-0.2,-4.0,0.3,0.2,0.8,-1.0,-170.0,-56.0,-1.0,0.7,0.00,0.00,0.000000,0.000000,0.037484,0.002859,-0.004726,0.000020,0.000000,0.000136,-30.023855,0.000029,-0.000678,-0.005132,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2163.0,0.0,2163.0,0.0,2846.0,2163.0,2163.0,2624.0,2846.0,2624.0,2140.0,0.0,2624.0,2163.0,2140.0,2140.0,2140.0,2163.0,0.0,2117.0,2666.0,2846.0,2163.0,2846.0,2846.0,2846.0,2846.0,1316.0,61.0,1.0,NaN,8.0,1.0,12.0,257.0,0,True,False,False,False
3,136263,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,20.0,14.666667,18.571429,NaN,NaN,0.6,1.1,0.800000,1.0,1.0,0.625000,3.0,15.0,3.0,15.0,12.142857,118.0,118.0,125.0,121.500000,27.0,29.0,27.0,29.0,28.9,27.4,31.9,29.600000,60.0,90.0,60.0,90.0,78.971429,7.014631,4.3,4.2,4.2,4.3,4.250000,NaN,NaN,NaN,NaN,1.0,2.2,2.2,2.2,137.0,136.0,136.0,137.0,136.500000,35.0,35.0,53.0,484.0,108.0,216.000000,7.52,7.34,7.52,7.402500,67.0,67.0,NaN,NaN,NaN,98.0,97.0,36.5,35.9,37.8,37.064000,0.672607,2847.0,0.323728,6.474564,1.221307,7.4,7.4,14.8,75.11,80.0,58.0,42.0,69.0,59.857143,75.00,72.00,55.67,89.00,76.076286,7.717743,107.0,106.0,83.0,127.0,107.600000,11.151892,NaN,0.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,4.0,7.0,2.0,3.0,4.0,35.0,2.0,0.0,6.0,1.0,2.0,8.0,8.0,8.0,4.0,0.0,4.0,25.0,21.0,4.0,35.0,35.0,35.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.5,2.0,-1.5,-0.1,0.0,-1.0,-366.0,5.0,-1.0,2.6,4.89,0.00,-0.001389,0.003582,0.004263,0.005479,0.011597,-0.000120,0.000000,0.001512,-169.160598,-0.001257,-0.001943,-0.001591,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2448.0,0.0,2448.0,471.0,2701.0,2448.0,2448.0,2448.0,2831.0,2448.0,0.0,1331.0,806.0,2448.0,872.0,872.0,872.0,2448.0,0.0,872.0,1211.0,1451.0,2448.0,2831.0,2831.0,2831.0,2831.0,0.0,67.0,1.0,167.6,17.0,9.0,9.0,-1.0,0,False,True,False,False
4,141669,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,13.0,12.000000,16.250000,NaN,NaN,0.8,0.8,0.766667,NaN,NaN,NaN,15.0,15.0,15.0,15.0,15.000000,267.0,175.0,267.0,220.500000,30.0,21.0,21.0,30.0,39.3,35.3,39.3,37.300000,73.0,83.0,54.0,84.0,69.428571,7.496805,2.8,4.6,2.8,5.0,3.820000,NaN,NaN,NaN,NaN,NaN,1.9,1.9,1.9,137.0,137.0,136.0,140.0,137.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,308.0,237.0,19.0,26.0,18.550000,NaN,NaN,36.6,36.0,37.1,36.654545,0.353167,4595.0,0.465549,3.491620,2.024611,8.9,7.3,8.9,71.60,71.6,66.0,50.0,93.0,70.027778,83.00,105.30,70.00,115.70,87.748056,11.373784,117.0,130.0,96.0,165.0,123.194444,15.863380,NaN,0.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,12.0,4.0,4.0,2.0,42.0,5.0,0.0,0.0,2.0,4.0,0.0,0.0,0.0,2.0,40.0,0.0,11.0,12.0,2.0,36.0,36.0,36.0,0.0,0.0,0.0,0.0,0.0,0.0,-2.0,0.0,-0.1,-9.0,-4.0,1.8,0.0,0.0,0.0,-71.0,0.0,-1.6,0.00,0.00,0.000000,0.000000,0.000593,-0.002046,0.000000,0.000000,0.000053,0.000018,3.267020,0.009731,0.010702,0.012650,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1616.0,0.0,1616.0,0.0,2756.0,1616.0,1616.0,1616.0,2756.0,1616.0,0.0,0.0,1616.0,1616.0,0.0,0.0,0.0,1616.0,2756.0,0.0,2756.0,2636.0,1616.0,2756.0,2756.0,2756.0,2756.0,0.0,50.0,0.0,NaN,7.0,0.0,4.0,-1.0,0,False,False,True,False
5,133368,3.0,3.0,3.0,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,34.0,26.333333,30.909091,NaN,NaN,0.8,1.2,1.033333,1.0,1.0,0.511765,3.0,14.0,3.0,14.0,9.500000,177.0,98.0,177.0,129.666667,26.0,22.0,22.0,26.0,38.1,37.3,39.9,38.425000,72.0,101.0,72.0,115.0,96.434783,10.177077,4.5,4.1,4.1,4.5,4.366667,4.9,4.9,69.387755,69.387755,1.0,1.4,1.4,2.7,141.0,143.0,140.0,143.0,141.333333,43.0,38.0,55.0,433.0,61.0,101.666667,7.40,7.24,7.42,7.326000,154.0,149.0,NaN,NaN,NaN,96.0,91.0,35.1,35.1,38.1,36.600000,0.810350,3387.0,0.000000,3.384419,0.674023,9.3,9.3,17.1,75.00,73.1,75.0,44.0,84.0,60.938144,99.00,78.00,60.00,114.00,83.868852,10.387493,136.0,110.0,93.0,167.0,125.061856,15.341131,NaN,1.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,17.0,12.0,3.0,3.0,4.0,69.0,3.0,5.0,12.0,3.0,3.0,15.0,15.0,15.0,3.0,0.0,8.0,13.0,47.0,3.0,97.0,122.0,97.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0,0.0,0.3,-4.0,0.3,-0.4,0.9,2.0,-372.0,-5.0,-5.0,7.8,-1.90,0.00,-0.000076,0.005446,-0.034969,0.007912,0.000562,-0.000052,0.000000,0.000159,-6.997156,-0.002798,0.000864,0.000644,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2166.0,0.0,0.0,0.0,0.0,2166.0,0.0,2166.0,2722.0,2662.0,2166.0,2166.0,2166.0,2842.0,2166.0,2355.0,2722.0,2166.0,2166.0,2617.0,2617.0,2617.0,2166.0,0.0,2617.0,2662.0,2842.0,2166.0,2842.0,2842.0,2842.0,2842.0,0.0,83.0,0.0,152.4,16.0,9.0,17.0,-1.0,0,False,True,False,False
6,132765,2.4,2.4,2.5,2.450000,38.0,46.0,14.0,14.0,33.0,33.0,0.7,0.7,24.0,24.0,20.666667,19.000000,NaN,NaN,1.5,1.5,1.233333,0.6,1.0,0.612500,3.0,3.0,3.0,11.0,5.416667,142.0,132.0,166.0,151.166667,16.0,17.0,13.0,18.0,40.5,27.6,40.5,34.800000,84.0,61.0,50.0,128.0,76.820513,14.851423,3.9,4.1,3.9,5.1,4.533333,7.2,8.9,-2.777778,-5.555556,1.0,2.6,1.7,2.6,136.0,131.0,127.0,137.0,132.500000,46.0,27.0,46.0,122.0,90.0,106.000000,7.26,7.22,7.48,7.318824,151.0,86.0,NaN,NaN,NaN,NaN,NaN,36.7,35.9,37.7,36.642857,0.578744,4360.0,0.304878,2.195122,1.082225,10.9,10.9,22.9,82.00,82.0,35.0,34.0,72.0,49.151515,48.00,83.00,43.00,102.00,69.422680,12.612688,79.0,136.0,60.0,173.0,122.111111,24.955016,0.10,2.0,2.0,2.0,2.0,6.0,2.0,0.0,6.0,16.0,12.0,6.0,6.0,7.0,78.0,6.0,16.0,16.0,6.0,6.0,17.0,17.0,17.0,6.0,0.0,0.0,14.0,46.0,6.0,99.0,97.0,99.0,2.0,0.1,8.0,-3.0,-11.0,0.0,-5.0,0.0,-0.5,1.0,-12.9,0.2,-0.6,-5.0,31.0,-65.0,0.0,5.5,0.00,-0.01,-0.000121,-0.002657,-0.001532,-0.011733,-0.004719,0.000089,0.000000,-0.000476,-1.170791,0.007026,0.008783,0.014085,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2374.0,2374.0,2374.0,2374.0,2374.0,2374.0,0.0,2374.0,2833.0,2713.0,2374.0,2374.0,2606.0,2833.0,2374.0,2690.0,2833.0,2374.0,2374.0,2690.0,2690.0,2690.0,2374.0,0.0,0.0,2713.0,2833.0,2374.0,0.0,2833.0,2833.0,2833.0,704.0,90.0,1.0,NaN,20.0,10.0,18.0,120.0,0,False,False,False,True
7,138320,NaN,NaN,NaN,NaN,82.0,82.0,67.0,67.0,265.0,265.0,NaN,NaN,13.0,15.0,14.000000,16.250000,211.0,211.0,0.8,1.0,0.900000,NaN,NaN,NaN,15.0,15.0,14.0,15.0,14.916667,126.0,107.0,126.0,116.500000,26.0,28.0,26.0,28.0,44.0,43.0,44.6,43.866667,64.0,79.0,64.0,87.0,73.900000,4.601003,4.0,4.3,4.0,4.3,4.133333,NaN,NaN,NaN,NaN,NaN,2.2,2.2,2.4,140.0,137.0,137.0,140.0,138.500000,39.0,39.0,39.0,71.0,71.0,NaN,7.40,7.40,7.40,7.400000,182.0,182.0,16.0,27.0,18.815789,97.0,97.0,37.7,36.1,37.9,37.175000,0.552885,4425.0,0.000000,1.616162,0.885943,10.5,9.9,10.5,99.00,99.0,70.0,37.0,88.0,62.428571,91.67,74.33,56.67,163.00,82.258000,19.862872,135.0,105.0,90.0,158.0,113.971429,17.114641,NaN,0.0,1.0,1.0,1.0,2.0,0.0,1.0,2.0,0.0,12.0,2.0,2.0,3.0,40.0,3.0,0.0,0.0,3.0,2.0,1.0,1.0,1.0,3.0,38.0,1.0,12.0,23.0,2.0,35.0,35.0,35.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.2,2.0,-1.0,0.3,0.0,-3.0,0.0,1.0,0.0,-0.6,0.00,0.00,0.000000,0.000081,-0.013514,0.002558,0.000000,0.000000,0.000379,0.000127,-10.738557,-0.007456,-0.012445,-0.012624,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,485.0,485.0,485.0,0.0,1891.0,485.0,1891.0,0.0,2780.0,1891.0,1891.0,1891.0,2780.0,1891.0,0.0,0.0,1891.0,1891.0,116.0,116.0,116.0,1891.0,2780.0,80.0,2780.0,2840.0,1891.0,2780.0,2780.0,2780.0,2780.0,0.0,66.0,1.0,175.3,8.0,2.0,3.0,-1.0,0,True,False,False,False
8,136295,NaN,NaN,NaN,NaN,38.0,38.0,71.0,71.0,63.0,63.0,NaN,NaN,16.0,16.0,15.333333,17.777778,NaN,NaN,1.2,1.2,1.033333,NaN,NaN,NaN,15.0,15.0,13.0,15.0,14.785714,150.0,107.0,150.0,123.666667,26.0,30.0,26.0,30.0,35.6,30.6,35.6,32.700000,88.0,94.0,79.0,102.0,90.033333,6.300300,4.4,3.8,3.8,4.4,4.033333,NaN,NaN,NaN,NaN,NaN,1.8,1.8,2.1,141.0,138.0,138.0,141.0,139.333333,NaN,NaN,NaN,NaN,NaN,NaN,7.42,7.42,7.42,7.420000,162.0,148.0,15.0,29.0,16.901639,NaN,NaN,35.7,35.3,37.9,37.033333,0.943237,4365.0,0.375000,3.750000,1.259146,8.9,6.5,8.9,80.00,80.0,61.0,50.0,80.0,61.672131,71.00,85.00,60.00,109.00,78.803279,12.748620,113.0,122.0,81.0,148.0,108.885246,18.430137,NaN,0.0,1.0,1.0,1.0,3.0,0.0,0.0,3.0,0.0,14.0,3.0,3.0,3.0,60.0,3.0,0.0,0.0,3.0,3.0,0.0,0.0,1.0,3.0,61.0,0.0,12.0,42.0,3.0,61.0,61.0,61.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.3,4.0,-5.0,-0.6,0.2,-3.0,0.0,-14.0,0.0,-2.4,0.00,0.00,0.000000,-0.000125,-0.017216,0.005135,0.000000,0.000000,0.002784,0.000931,0.422173,0.002028,0.004095,0.007874,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1113.0,1113.0,1113.0,0.0,2523.0,0.0,2523.0,0.0,2653.0,2523.0,2523.0,2523.0,2833.0,2523.0,0.0,0.0,2523.0,2523.0,0.0,0.0,1492.0,2523.0,2833.0,0.0,2713.0,2773.0,2523.0,0.0,2833.0,2833.0,2833.0,0.0,61.0,1.0,NaN,4.0,2.0,13.0,-1.0,0,False,False,False,True
9,134326,3.1,3.1,3.1,3.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0,11.500000,30.000000,NaN,NaN,0.4,0.6,0.550000,1.0,1.0,0.550000,8.0,10.0,7.0,11.0,8.545455,117.0,111.0,129.0,119.750000,22.0,27.0,22.0,27.0,34.8,30.1,34.8,32.975000,80.0,68.0,62.0,91.0,75.260000,8.095880,3.7,3.8,3.6,4.0,3.800000,1.2,2.1,NaN,NaN,1.0,1.6,1.6,2.0,134.0,141.0,134.0,141.0,136.750000,44.0,44.0,49.0,74.0,62.0,62.000000,7.42,7.35,7.44,7.398750,157.0,157.0,NaN,NaN,NaN,NaN,NaN,36.9,36.9,38.3,37.933333,0.373529,8200.0,0.694444,3.240741,1.670139,15.4,11.2,15.4,108.00,108.0,64.0,52.0,86.0,67.365385,87.00,94.00,68.00,101.00,88.916731,7.029892,133.0,146.0,95.0,159.0,131.884615,12.920047,NaN,1.0,0.0,0.0,0.0,4.0,0.0,0.0,4.0,14.0,22.0,4.0,4.0,4.0,50.0,5.0,2.0,15.0,4.0,4.0,8.0,8.0,8.0,4.0,0.0,0.0,15.0,38.0,4.0,52.0,52.0,52.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.2,5.0,-4.7,0.1,0.4,7.0,59.0,16.0,0.0,-4.2,0.00,0.00,-0.000148,0.001270,0.007430,0.005173,0.000763,0.000033,0.000000,0.000151,-70.785182,0.002558,0.004990,0.010517,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,101.0,0.0,0.0,0.0,0.0,2138.0,0.0,2138.0,2548.0,2858.0,2138.0,2138.0,2138.0,2858.0,2213.0,273.0,2548.0,2138.0,2138.0,2081.0,2081.0,2081.0,2138.0,0.0,0.0,2858.0,2858.0,2138.0,0.0,2858.0,2858.0,2858.0,0.0,59.0,1.0,NaN,12.0,7.0,13.0,-1.0,0,False,False,False,True
10,135256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,19.0,14.000000,38.000000,NaN,NaN,0.5,0.5,0.433333,1.0,1.0,0.514286,3.0,8.0,3.0,8.0,5.916667,193.0,178.0,193.0,185.500000,29.0,22.0,22.0,29.0,38.2,29.0,38.2,34.666667,82.0,120.0,74.0,175.0,101.857143,21.942141,4.6,4.2,4.2,4.6,4.400000,NaN,NaN,NaN,NaN,1.0,2.1,2.1,2.7,130.0,136.0,130.0,136.0,133.000000,40.0,30.0,46.0,291.0,98.0,245.000000,7.44,7.30,7.44,7.394167,230.0,75.0,NaN,NaN,NaN,100.0,96.0,37.2,35.2,37.9,36.959016,0.794014,3949.0,0.197020,18.388551,1.478052,7.3,4.7,15.9,54.00,62.9,75.0,42.0,85.0,63.702703,98.33,99.00,51.00,104.00,81.382838,11.014612,145.0,138.0,70.0,145.0,111.920000,15.414770,NaN,0.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,14.0,12.0,2.0,3.0,6.0,70.0,2.0,0.0,11.0,3.0,3.0,10.0,9.0,12.0,5.0,0.0,10.0,61.0,44.0,5.0,74.0,74.0,75.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,-7.0,-5.1,-0.4,0.3,6.0,-164.0,-83.0,-3.0,1.0,8.90,0.00,-0.000148,0.002765,-0.038760,0.005144,-0.004147,0.000026,0.000000,0.000788,-6.392857,0.000232,0.000983,0.004449,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1969.0,0.0,1969.0,2696.0,2696.0,481.0,1969.0,2421.0,2876.0,481.0,0.0,2696.0,1969.0,1969.0,2577.0,2577.0,2577.0,1969.0,0.0,2577.0,2696.0,2876.0,1969.0,2876.0,2876.0,2876.0,2876.0,0.0,83.0,0.0,162.6,23.0,9.0,27.0,163.0,0,False,True,False,False

In [85]:
df.dtypes

RecordID                        int64
Albumin_Initial               float64
Albumin_Min                   float64
Albumin_Max                   float64
Albumin_Mean                  float64
ALP_Initial                   float64
ALP_Max                       float64
ALT_Initial                   float64
ALT_Max                       float64
AST_Initial                   float64
AST_Max                       float64
Bilirubin_Initial             float64
Bilirubin_Max                 float64
BUN_Initial                   float64
BUN_Max                       float64
BUN_Mean                      float64
BUN_Creatinine_Ratio          float64
Cholesterol_Initial           float64
Cholesterol_Min               float64
Creatinine_Initial            float64
Creatinine_Max                float64
Creatinine_Mean               float64
FiO2_Initial                  float64
FiO2_Max                      float64
FiO2_Mean                     float64
GCS_Initial                   float64
GCS_Final                     float64
GCS_Min                       float64
GCS_Max                       float64
GCS_Mean                      float64
Glucose_Initial               float64
Glucose_Min                   float64
Glucose_Max                   float64
Glucose_Mean                  float64
HCO3_Initial                  float64
HCO3_Final                    float64
HCO3_Min                      float64
HCO3_Max                      float64
HCT_Initial                   float64
HCT_Min                       float64
HCT_Max                       float64
HCT_Mean                      float64
HR_Initial                    float64
HR_Final                      float64
HR_Min                        float64
HR_Max                        float64
HR_Mean                       float64
HR_SD                         float64
K_Initial                     float64
K_Final                       float64
K_Min                         float64
K_Max                         float64
K_Mean                        float64
Lactate_Initial               float64
Lactate_Max                   float64
Lactate_Clearance_Rate_6H     float64
Lactate_Clearance_Rate_12H    float64
MechVent_Any                  float64
Mg_Initial                    float64
Mg_Min                        float64
Mg_Max                        float64
Na_Initial                    float64
Na_Final                      float64
Na_Min                        float64
Na_Max                        float64
Na_Mean                       float64
PaCO2_Initial                 float64
PaCO2_Min                     float64
PaCO2_Max                     float64
PaO2_Initial                  float64
PaO2_Min                      float64
PaO2_FiO2_Ratio               float64
pH_Initial                    float64
pH_Min                        float64
pH_Max                        float64
pH_Mean                       float64
Platelets_Initial             float64
Platelets_Min                 float64
RespRate_Initial              float64
RespRate_Max                  float64
RespRate_Mean                 float64
SaO2_Initial                  float64
SaO2_Min                      float64
Temp_Initial                  float64
Temp_Min                      float64
Temp_Max                      float64
Temp_Mean                     float64
Temp_SD                       float64
Urine_Sum                     float64
Urine_MinRate                 float64
Urine_MaxRate                 float64
Urine_MeanRate                float64
WBC_Initial                   float64
WBC_Min                       float64
WBC_Max                       float64
Weight_Initial                float64
Weight_Final                  float64
UniDiasABP_Initial            float64
UniDiasABP_Min                float64
UniDiasABP_Max                float64
UniDiasABP_Mean               float64
UniMAP_Initial                float64
UniMAP_Final                  float64
UniMAP_Min                    float64
UniMAP_Max                    float64
UniMAP_Mean                   float64
UniMAP_SD                     float64
UniSysABP_Initial             float64
UniSysABP_Final               float64
UniSysABP_Min                 float64
UniSysABP_Max                 float64
UniSysABP_Mean                float64
UniSysABP_SD                  float64
Troponin_Max                  float64
Albumin_Count                 float64
ALP_Count                     float64
ALT_Count                     float64
AST_Count                     float64
BUN_Count                     float64
Bilirubin_Count               float64
Cholesterol_Count             float64
Creatinine_Count              float64
FiO2_Count                    float64
GCS_Count                     float64
Glucose_Count                 float64
HCO3_Count                    float64
HCT_Count                     float64
HR_Count                      float64
K_Count                       float64
Lactate_Count                 float64
MechVent_Count                float64
Mg_Count                      float64
Na_Count                      float64
PaCO2_Count                   float64
PaO2_Count                    float64
pH_Count                      float64
Platelets_Count               float64
RespRate_Count                float64
SaO2_Count                    float64
Temp_Count                    float64
Urine_Count                   float64
WBC_Count                     float64
UniDiasABP_Count              float64
UniMAP_Count                  float64
UniSysABP_Count               float64
Troponin_Count                float64
Albumin_Delta                 float64
ALP_Delta                     float64
ALT_Delta                     float64
AST_Delta                     float64
Bilirubin_Delta               float64
BUN_Delta                     float64
Cholesterol_Delta             float64
Creatinine_Delta              float64
HCO3_Delta                    float64
HCT_Delta                     float64
K_Delta                       float64
Mg_Delta                      float64
Na_Delta                      float64
PaO2_Delta                    float64
Platelets_Delta               float64
SaO2_Delta                    float64
WBC_Delta                     float64
Weight_Delta                  float64
Troponin_Delta                float64
FiO2_Slope                    float64
GCS_Slope                     float64
Glucose_Slope                 float64
HR_Slope                      float64
PaCO2_Slope                   float64
pH_Slope                      float64
RespRate_Slope                float64
Temp_Slope                    float64
Urine_Rate_Slope              float64
UniDiasABP_Slope              float64
UniMAP_Slope                  float64
UniSysABP_Slope               float64
Albumin_Miss                  float64
ALP_Miss                      float64
ALT_Miss                      float64
AST_Miss                      float64
Bilirubin_Miss                float64
BUN_Miss                      float64
Cholesterol_Miss              float64
Creatinine_Miss               float64
FiO2_Miss                     float64
GCS_Miss                      float64
Glucose_Miss                  float64
HCO3_Miss                     float64
HCT_Miss                      float64
HR_Miss                       float64
K_Miss                        float64
Lactate_Miss                  float64
MechVent_Miss                 float64
Mg_Miss                       float64
Na_Miss                       float64
PaCO2_Miss                    float64
PaO2_Miss                     float64
pH_Miss                       float64
Platelets_Miss                float64
RespRate_Miss                 float64
SaO2_Miss                     float64
Temp_Miss                     float64
Urine_Miss                    float64
WBC_Miss                      float64
Weight_Miss                   float64
UniDiasABP_Miss               float64
UniMAP_Miss                   float64
UniSysABP_Miss                float64
Troponin_Miss                 float64
Albumin_Last_Minute           float64
ALP_Last_Minute               float64
ALT_Last_Minute               float64
AST_Last_Minute               float64
Bilirubin_Last_Minute         float64
BUN_Last_Minute               float64
Cholesterol_Last_Minute       float64
Creatinine_Last_Minute        float64
FiO2_Last_Minute              float64
GCS_Last_Minute               float64
Glucose_Last_Minute           float64
HCO3_Last_Minute              float64
HCT_Last_Minute               float64
HR_Last_Minute                float64
K_Last_Minute                 float64
Lactate_Last_Minute           float64
MechVent_Last_Minute          float64
Mg_Last_Minute                float64
Na_Last_Minute                float64
PaCO2_Last_Minute             float64
PaO2_Last_Minute              float64
pH_Last_Minute                float64
Platelets_Last_Minute         float64
RespRate_Last_Minute          float64
SaO2_Last_Minute              float64
Temp_Last_Minute              float64
Urine_Last_Minute             float64
WBC_Last_Minute               float64
Weight_Last_Minute            float64
UniDiasABP_Last_Minute        float64
UniMAP_Last_Minute            float64
UniSysABP_Last_Minute         float64
Troponin_Last_Minute          float64
Age                           float64
Gender                        float64
Height                        float64
SAPS-I                        float64
SOFA                          float64
Length_of_stay                float64
Survival                      float64
In-hospital_death               int64
ICUType_1.0                      bool
ICUType_2.0                      bool
ICUType_3.0                      bool
ICUType_4.0                      bool
dtype: object

In [86]:
df.shape

(12000, 255)

# drop unused columns

In [87]:
columns_to_drop = ['RecordID', 'Length_of_stay', 'Survival', 'SAPS-I', 'SOFA']

In [88]:
df.drop(columns=columns_to_drop, inplace=True)

In [89]:
df.head(20)

,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Count,ALP_Count,ALT_Count,AST_Count,BUN_Count,Bilirubin_Count,Cholesterol_Count,Creatinine_Count,FiO2_Count,GCS_Count,Glucose_Count,HCO3_Count,HCT_Count,HR_Count,K_Count,Lactate_Count,MechVent_Count,Mg_Count,Na_Count,PaCO2_Count,PaO2_Count,pH_Count,Platelets_Count,RespRate_Count,SaO2_Count,Temp_Count,Urine_Count,WBC_Count,UniDiasABP_Count,UniMAP_Count,UniSysABP_Count,Troponin_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,Age,Gender,Height,In-hospital_death,ICUType_1.0,ICUType_2.0,ICUType_3.0,ICUType_4.0
0,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.500000,10.000000,NaN,NaN,0.9,0.9,0.675000,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.500000,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.060000,1.5,1.8,0.000000,-20.000000,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.750000,40.0,39.0,51.0,187.0,73.0,121.666667,7.39,7.29,7.42,7.361429,85.0,71.0,NaN,NaN,NaN,NaN,NaN,37.6,36.3,38.9,37.329412,0.645041,2763.0,0.167785,3.775168,0.934510,13.3,9.3,13.3,59.60,59.6,60.0,38.0,77.0,59.859375,69.00,86.00,48.00,95.00,75.156250,8.942885,97.0,123.0,82.0,131.0,108.609375,10.529802,0.40,3.0,3.0,3.0,3.0,4.0,3.0,0.0,4.0,18.0,13.0,4.0,4.0,6.0,64.0,5.0,6.0,18.0,4.0,4.0,7.0,7.0,7.0,4.0,0.0,0.0,34.0,36.0,4.0,64.0,64.0,64.0,3.0,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0.0,-0.3,3.0,-3.1,0.6,-0.2,0.0,-50.0,9.0,0.0,-4.0,0.00,-0.18,-0.000198,0.000168,0.044188,-0.010776,0.000673,0.000002,0.000000,-0.000355,-2.380140,-0.001739,0.002434,0.004666,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2113.0,2113.0,2113.0,2113.0,2113.0,2113.0,0.0,2113.0,2819.0,2789.0,2113.0,2113.0,2799.0,2849.0,2113.0,2803.0,2819.0,2113.0,2113.0,2743.0,2743.0,2743.0,2799.0,0.0,0.0,2849.0,2849.0,2799.0,2849.0,2849.0,2849.0,2849.0,1320.0,22.0,0.0,167.6,0,False,False,True,False
1,2.2,2.2,2.2,2.200000,37.0,37.0,112.0,112.0,453.0,453.0,1.1,1.1,12.0,20.0,15.666667,20.000000,NaN,NaN,0.7,1.0,0.866667,1.0,1.0,0.500000,3.0,8.0,3.0,11.0,6.000000,199.0,105.0,234.0,170.600000,20.0,23.0,20.0,23.0,33.9,30.3,38.6,33.360000,99.0,96.0,71.0,117.0,97.528090,10.956619,2.9,5.9,2.9,5.9,4.400000,9.7,9.7,0.000000,4.123711,1.0,2.7,1.8,2.7,143.0,137.0,137.0,143.0,139.333333,44.0,33.0,69.0,310.0,73.0,110.000000,7.35,7.10,7.44,7.351500,123.0,92.0,NaN,NaN,NaN,98.0,96.0,34.7,34.7,37.6,36.679070,0.664232,3987.0,0.190721,5.085892,0.782265,27.1,16.8,27.1,72.60,98.9,54.0,29.0,90.0,48.739130,72.00,71.00,35.00,127.00,76.633333,16.502945,117.0,108.0,44.0,175.0,117.000000,25.219912,NaN,1.0,1.0,1.0,1.0,3.0,1.0,0.0,3.0,14.0,10.0,5.0,3.0,5.0,89.0,5.0,15.0,16.0,2.0,3.0,19.0,19.0,20.0,6.0,0.0,8.0,86.0,48.0,4.0,92.0,90.0,92.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.3,3.0,-1.0,3.0,-0.9,-6.0,-216.0,-24.0,1.0,-6.5,26.30,0.00,-0.000141,0.002588,-0.062102,-0.006374,-0.004262,0.000056,0.000000,0.000645,-1.168270,-0.002770,-0.002166,0.002073,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,950.0,950.0,950.0,950.0,950.0,2189.0,0.0,2189.0,2804.0,2804.0,2438.0,2189.0,2189.0,2864.0,2438.0,2610.0,2804.0,2189.0,2189.0,2757.0,2757.0,2757.0,2189.0,0.0,2804.0,2864.0,2864.0,2189.0,2864.0,2864.0,2864.0,2864.0,0.0,72.0,1.0,177.8,0,False,True,False,False
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,12.0,9.666667,20.000000,NaN,NaN,0.6,0.6,0.533333,NaN,NaN,NaN,15.0,15.0,15.0,15.0,15.000000,105.0,105.0,154.0,124.666667,28.0,24.0,24.0,28.0,32.2,27.1,32.5,30.075000,86.0,78.0,78.0,111.0,89.170732,8.731845,3.3,3.5,3.3,3.7,3.475000,0.8,0.8,0.000000,0.000000,NaN,1.3,1.3,2.1,133.0,132.0,132.0,134.0,133.000000,41.0,39.0,51.0,267.0,95.0,NaN,7.43,7.35,7.43,7.398000,346.0,290.0,NaN,NaN,NaN,97.0,96.0,36.6,35.6,38.2,37.000000,0.629574,7140.0,0.083333,5.333333,1.997873,9.9,9.9,13.5,75.00,75.0,55.0,41.0,62.0,51.365854,80.33,73.00,60.00,83.33,70.861463,5.859821,131.0,117.0,80.0,131.0,106.853659,11.529443,0.30,0.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,11.0,3.0,3.0,4.0,41.0,4.0,3.0,0.0,3.0,3.0,5.0,5.0,5.0,3.0,0.0,2.0,12.0,33.0,3.0,41.0,41.0,41.0,1.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,-0.2,-4.0,0.3,0.2,0.8,-1.0,-170.0,-56.0,-1.0,0.7,0.00,0.00,0.000000,0.000000,0.037484,0.002859,-0.004726,0.000020,0.000000,0.000136,-30.023855,0.000029,-0.000678,-0.005132,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2163.0,0.0,2163.0,0.0,2846.0,2163.0,2163.0,2624.0,2846.0,2624.0,2140.0,0.0,2624.0,2163.0,2140.0,2140.0,2140.0,2163.0,0.0,2117.0,2666.0,2846.0,2163.0,2846.0,2846.0,2846.0,2846.0,1316.0,61.0,1.0,NaN,0,True,False,False,False
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,20.0,14.666667,18.571429,NaN,NaN,0.6,1.1,0.800000,1.0,1.0,0.625000,3.0,15.0,3.0,15.0,12.142857,118.0,118.0,125.0,121.500000,27.0,29.0,27.0,29.0,28.9,27.4,31.9,29.600000,60.0,90.0,60.0,90.0,78.971429,7.014631,4.3,4.2,4.2,4.3,4.250000,NaN,NaN,NaN,NaN,1.0,2.2,2.2,2.2,137.0,136.0,136.0,137.0,136.500000,35.0,35.0,53.0,484.0,108.0,216.000000,7.52,7.34,7.52,7.402500,67.0,67.0,NaN,NaN,NaN,98.0,97.0,36.5,35.9,37.8,37.064000,0.672607,2847.0,0.323728,6.474564,1.221307,7.4,7.4,14.8,75.11,80.0,58.0,42.0,69.0,59.857143,75.00,72.00,55.67,89.00,76.076286,7.717743,107.0,106.0,83.0,127.0,107.600000,11.151892,NaN,0.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,4.0,7.0,2.0,3.0,4.0,35.0,2.0,0.0,6.0,1.0,2.0,8.0,8.0,8.0,4.0,0.0,4.0,25.0,21.0,4.0,35.0,35.0,35.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.5,2.0,-1.5,-0.1,0.0,-1.0,-366.0,5.0,-1.0,2.6,4.89,0.00,-0.001389,0.003582,0.004263,0.005479,0.011597,-0.000120,0.000000,0.001512,-169.160598,-0.001257,-0.001943,-0.001591,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2448.0,0.0,2448.0,471.0,2701.0,2448.0,2448.0,2448.0,2831.0,2448.0,0.0,1331.0,806.0,2448.0,872.0,872.0,872.0,2448.0,0.0,872.0,1211.0,1451.0,2448.0,2831.0,2831.0,2831.0,2831.0,0.0,67.0,1.0,167.6,0,False,True,False,False
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,13.0,12.000000,16.250000,NaN,NaN,0.8,0.8,0.766667,NaN,NaN,NaN,15.0,15.0,15.0,15.0,15.000000,267.0,175.0,267.0,220.500000,30.0,21.0,21.0,30.0,39.3,35.3,39.3,37.300000,73.0,83.0,54.0,84.0,69.428571,7.496805,2.8,4.6,2.8,5.0,3.820000,NaN,NaN,NaN,NaN,NaN,1.9,1.9,1.9,137.0,137.0,136.0,140.0,137.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,308.0,237.0,19.0,26.0,18.550000,NaN,NaN,36.6,36.0,37.1,36.654545,0.353167,4595.0,0.465549,3.491620,2.024611,8.9,7.3,8.9,71.60,71.6,66.0,50.0,93.0,70.027778,83.00,105.30,70.00,115.70,87.748056,11.373784,117.0,130.0,96.0,165.0,123.194444,15.863380,NaN,0.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,12.0,4.0,4.0,2.0,42.0,5.0,0.0,0.0,2.0,4.0,0.0,0.0,0.0,2.0,40.0,0.0,11.0,12.0,2.0,36.0,36.0,36.0,0.0,0.0,0.0,0.0,0.0,0.0,-2.0,0.0,-0.1,-9.0,-4.0,1.8,0.0,0.0,0.0,-71.0,0.0,-1.6,0.00,0.00,0.000000,0.000000,0.000593,-0.002046,0.000000,0.000000,0.000053,0.000018,3.267020,0.009731,0.010702,0.012650,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1616.0,0.0,1616.0,0.0,2756.0,1616.0,1616.0,1616.0,2756.0,1616.0,0.0,0.0,1616.0,1616.0,0.0,0.0,0.0,1616.0,2756.0,0.0,2756.0,2636.0,1616.0,2756.0,2756.0,2756.0,2756.0,0.0,50.0,0.0,NaN,0,False,False,True,False
5,3.0,3.0,3.0,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,34.0,26.333333,30.909091,NaN,NaN,0.8,1.2,1.033333,1.0,1.0,0.511765,3.0,14.0,3.0,14.0,9.500000,177.0,98.0,177.0,129.666667,26.0,22.0,22.0,26.0,38.1,37.3,39.9,38.425000,72.0,101.0,72.0,115.0,96.434783,10.177077,4.5,4.1,4.1,4.5,4.366667,4.9,4.9,69.387755,69.387755,1.0,1.4,1.4,2.7,141.0,143.0,140.0,143.0,141.333333,43.0,38.0,55.0,433.0,61.0,101.666667,7.40,7.24,7.42,7.326000,154.0,149.0,NaN,NaN,NaN,96.0,91.0,35.1,35.1,38.1,36.600000,0.810350,3387.0,0.000000,3.384419,0.674023,9.3,9.3,17.1,75.00,73.1,75.0,44.0,84.0,60.938144,99.00,78.00,60.00,114.00,83.868852,10.387493,136.0,110.0,93.0,167.0,125.061856,15.341131,NaN,1.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,17.0,12.0,3.0,3.0,4.0,69.0,3.0,5.0,12.0,3.0,3.0,15.0,15.0,15.0,3.0,0.0,8.0,13.0,47.0,3.0,97.0,122.0,97.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0,0.0,0.3,-4.0,0.3,-0.4,0.9,2.0,-372.0,-5.0,-5.0,7.8,-1.90,0.00,-0.000076,0.005446,-0.034969,0.007912,0.000562,-0.000052,0.000000,0.000159,-6.997156,-0.002798,0.000864,0.000644,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2166.0,0.0,0.0,0.0,0.0,2166.0,0.0,2166.0,2722.0,2662.0,2166.0,2166.0,2166.0,2842.0,2166.0,2355.0,2722.0,2166.0,2166.0,2617.0,2617.0,2617.0,2166.0,0.0,2617.0,2662.0,2842.0,2166.0,2842.0,2842.0,2842.0,2842.0,0.0,83.0,0.0,152.4,0,False,True,False,False
6,2.4,2.4,2.5,2.450000,38.0,46.0,14.0,14.0,33.0,33.0,0.7,0.7,24.0,24.0,20.666667,19.000000,NaN,NaN,1.5,1.5,1.233333,0.6,1.0,0.612500,3.0,3.0,3.0,11.0,5.416667,142.0,132.0,166.0,151.166667,16.0,17.0,13.0,18.0,40.5,27.6,40.5,34.800000,84.0,61.0,50.0,128.0,76.820513,14.851423,3.9,4.1,3.9,5.1,4.533333,7.2,8.9,-2.777778,-5.555556,1.0,2.6,1.7,2.6,136.0,131.0,127.0,137.0,132.500000,46.0,27.0,46.0,122.0,90.0,106.000000,7.26,7.22,7.48,7.318824,151.0,86.0,NaN,NaN,NaN,NaN,NaN,36.7,35.9,37.7,36.642857,0.578744,4360.0,0.304878,2.195122,1.082225,10.9,10.9,22.9,82.00,82.0,35.0,34.0,72.0,49.151515,48.00,83.00,43.00,102.00,69.422680,12.612688,79.0,136.0,60.0,173.0,122.111111,24.955016,0.10,2.0,2.0,2.0,2.0,6.0,2.0,0.0,6.0,16.0,12.0,6.0,6.0,7.0,78.0,6.0,16.0,16.0,6.0,6.0,17.0,17.0,17.0,6.0,0.0,0.0,14.0,46.0,6.0,99.0,97.0,99.0,2.0,0.1,8.0,-3.0,-11.0,0.0,-5.0,0.0,-0.5,1.0,-12.9,0.2,-0.6,-5.0,31.0,-65.0,0.0,5.5,0.00,-0.01,-0.000121,-0.002657,-0.001532,-0.011733,-0.004719,0.000089,0.000000,-0.000476,-1.170791,0.007026,0.008783,0.014085,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2374.0,2374.0,2374.0,2374.0,2374.0,2374.0,0.0,2374.0,2833.0,2713.0,2374.0,2374.0,2606.0,2833.0,2374.0,2690.0,2833.0,2374.0,2374.0,2690.0,2690.0,2690.0,2374.0,0.0,0.0,2713.0,2833.0,2374.0,0.0,2833.0,2833.0,2833.0,704.0,90.0,1.0,NaN,0,False,False,False,True
7,NaN,NaN,NaN,NaN,82.0,82.0,67.0,67.0,265.0,265.0,NaN,NaN,13.0,15.0,14.000000,16.250000,211.0,211.0,0.8,1.0,0.900000,NaN,NaN,NaN,15.0,15.0,14.0,15.0,14.916667,126.0,107.0,126.0,116.500000,26.0,28.0,26.0,28.0,44.0,43.0,44.6,43.866667,64.0,79.0,64.0,87.0,73.900000,4.601003,4.0,4.3,4.0,4.3,4.133333,NaN,NaN,NaN,NaN,NaN,2.2,2.2,2.4,140.0,137.0,137.0,140.0,138.500000,39.0,39.0,39.0,71.0,71.0,NaN,7.40,7.40,7.40,7.400000,182.0,182.0,16.0,27.0,18.815789,97.0,97.0,37.7,36.1,37.9,37.175000,0.552885,4425.0,0.000000,1.616162,0.885943,10.5,9.9,10.5,99.00,99.0,70.0,37.0,88.0,62.428571,91.67,74.33,56.67,163.00,82.258000,19.862872,135.0,105.0,90.0,158.0,113.971429,17.114641,NaN,0.0,1.0,1.0,1.0,2.0,0.0,1.0,2.0,0.0,12.0,2.0,2.0,3.0,40.0,3.0,0.0,0.0,3.0,2.0,1.0,1.0,1.0,3.0,38.0,1.0,12.0,23.0,2.0,35.0,35.0,35.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.2,2.0,-1.0,0.3,0.0,-3.0,0.0,1.0,0.0,-0.6,0.00,0.00,0.000000,0.000081,-0.013514,0.002558,0.000000,0.000000,0.000379,0.000127,-10.738557,-0.007456,-0.012445,-0.012624,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,485.0,485.0,485.0,0.0,1891.0,485.0,1891.0,0.0,2780.0,1891.0,1891.0,1891.0,2780.0,1891.0,0.0,0.0,1891.0,1891.0,116.0,116.0,116.0,1891.0,2780.0,80.0,2780.0,2840.0,1891.0,2780.0,2780.0,2780.0,2780.0,0.0,66.0,1.0,175.3,0,True,False,False,False
8,NaN,NaN,NaN,NaN,38.0,38.0,71.0,71.0,63.0,63.0,NaN,NaN,16.0,16.0,15.333333,17.777778,NaN,NaN,1.2,1.2,1.033333,NaN,NaN,NaN,15.0,15.0,13.0,15.0,14.785714,150.0,107.0,150.0,123.666667,26.0,30.0,26.0,30.0,35.6,30.6,35.6,32.700000,88.0,94.0,79.0,102.0,90.033333,6.300300,4.4,3.8,3.8,4.4,4.033333,NaN,NaN,NaN,NaN,NaN,1.8,1.8,2.1,141.0,138.0,138.0,141.0,139.333333,NaN,NaN,NaN,NaN,NaN,NaN,7.42,7.42,7.42,7.420000,162.0,148.0,15.0,29.0,16.901639,NaN,NaN,35.7,35.3,37.9,37.033333,0.943237,4365.0,0.375000,3.750000,1.259146,8.9,6.5,8.9,80.00,80.0,61.0,50.0,80.0,61.672131,71.00,85.00,60.00,109.00,78.803279,12.748620,113.0,122.0,81.0,148.0,108.885246,18.430137,NaN,0.0,1.0,1.0,1.0,3.0,0.0,0.0,3.0,0.0,14.0,3.0,3.0,3.0,60.0,3.0,0.0,0.0,3.0,3.0,0.0,0.0,1.0,3.0,61.0,0.0,12.0,42.0,3.0,61.0,61.0,61.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.3,4.0,-5.0,-0.6,0.2,-3.0,0.0,-14.0,0.0,-2.4,0.00,0.00,0.000000,-0.000125,-0.017216,0.005135,0.000000,0.000000,0.002784,0.000931,0.422173,0.002028,0.004095,0.007874,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1113.0,1113.0,1113.0,0.0,2523.0,0.0,2523.0,0.0,2653.0,2523.0,2523.0,2523.0,2833.0,2523.0,0.0,0.0,2523.0,2523.0,0.0,0.0,1492.0,2523.0,2833.0,0.0,2713.0,2773.0,2523.0,0.0,2833.0,2833.0,2833.0,0.0,61.0,1.0,NaN,0,False,False,False,True
9,3.1,3.1,3.1,3.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0,11.500000,30.000000,NaN,NaN,0.4,0.6,0.550000,1.0,1.0,0.550000,8.0,10.0,7.0,11.0,8.545455,117.0,111.0,129.0,119.750000,22.0,27.0,22.0,27.0,34.8,30.1,34.8,32.975000,80.0,68.0,62.0,91.0,75.260000,8.095880,3.7,3.8,3.6,4.0,3.800000,1.2,2.1,NaN,NaN,1.0,1.6,1.6,2.0,134.0,141.0,134.0,141.0,136.750000,44.0,44.0,49.0,74.0,62.0,62.000000,7.42,7.35,7.44,7.398750,157.0,157.0,NaN,NaN,NaN,NaN,NaN,36.9,36.9,38.3,37.933333,0.373529,8200.0,0.694444,3.240741,1.670139,15.4,11.2,15.4,108.00,108.0,64.0,52.0,86.0,67.365385,87.00,94.00,68.00,101.00,88.916731,7.029892,133.0,146.0,95.0,159.0,131.884615,12.920047,NaN,1.0,0.0,0.0,0.0,4.0,0.0,0.0,4.0,14.0,22.0,4.0,4.0,4.0,50.0,5.0,2.0,15.0,4.0,4.0,8.0,8.0,8.0,4.0,0.0,0.0,15.0,38.0,4.0,52.0,52.0,52.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.2,5.0,-4.7,0.1,0.4,7.0,59.0,16.0,0.0,-4.2,0.00,0.00,-0.000148,0.001270,0.007430,0.005173,0.000763,0.000033,0.000000,0.000151,-70.785182,0.002558,0.004990,0.010517,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,101.0,0.0,0.0,0.0,0.0,2138.0,0.0,2138.0,2548.0,2858.0,2138.0,2138.0,2138.0,2858.0,2213.0,273.0,2548.0,2138.0,2138.0,2081.0,2081.0,2081.0,2138.0,0.0,0.0,2858.0,2858.0,2138.0,0.0,2858.0,2858.0,2858.0,0.0,59.0,1.0,NaN,0,False,False,False,True
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,19.0,14.000000,38.000000,NaN,NaN,0.5,0.5,0.433333,1.0,1.0,0.514286,3.0,8.0,3.0,8.0,5.916667,193.0,178.0,193.0,185.500000,29.0,22.0,22.0,29.0,38.2,29.0,38.2,34.666667,82.0,120.0,74.0,175.0,101.857143,21.942141,4.6,4.2,4.2,4.6,4.400000,NaN,NaN,NaN,NaN,1.0,2.1,2.1,2.7,130.0,136.0,130.0,136.0,133.000000,40.0,30.0,46.0,291.0,98.0,245.000000,7.44,7.30,7.44,7.394167,230.0,75.0,NaN,NaN,NaN,100.0,96.0,37.2,35.2,37.9,36.959016,0.794014,3949.0,0.197020,18.388551,1.478052,7.3,4.7,15.9,54.00,62.9,75.0,42.0,85.0,63.702703,98.33,99.00,51.00,104.00,81.382838,11.014612,145.0,138.0,70.0,145.0,111.920000,15.414770,NaN,0.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,14.0,12.0,2.0,3.0,6.0,70.0,2.0,0.0,11.0,3.0,3.0,10.0,9.0,12.0,5.0,0.0,10.0,61.0,44.0,5.0,74.0,74.0,75.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,-7.0,-5.1,-0.4,0.3,6.0,-164.0,-83.0,-3.0,1.0,8.90,0.00,-0.000148,0.002765,-0.038760,0.005144,-0.004147,0.000026,0.000000,0.000788,-6.392857,0.000232,0.000983,0.004449,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1969.0,0.0,1969.0,2696.0,2696.0,481.0,1969.0,2421.0,2876.0,481.0,0.0,2696.0,1969.0,1969.0,2577.0,2577.0,2577.0,1969.0,0.0,2577.0,2696.0,2876.0,1969.0,2876.0,2876.0,2876.0,2876.0,0.0,83.0,0.0,162.6,0,False,True,False,False
11,2.6,2.6,2.6,2.600000,230.0,230.0,249.0,249.0,147.0,147.0,0.9,0.9,41.0,41.0,34.666667,31.538462,NaN,NaN,1.3,1.3,1.200000,0.5,1.0,0.531250,9.0,15.0,9.0,15.0,11.461538,231.0,38.0,231.0,134.666667,22.0,25.0,22.0,25.0,26.8,26.7,28.7,27.400000,81.0,91.0,72.0,102.0,83.750000,6.930679,4.5,3.4,3.4,4.5,4.000000,1.5,1.5,0.000000,0.000000,1.0,2.4,2.4,2.4,137.0,138.0,137.0,139.0,138.000000,38.0,38.0,41.0,92.0,82.0,82.000000,7.37,7.36,7.37,7.365000,323.0,318.0,NaN,NaN,NaN,NaN,NaN,37.1,36.3,37.9,36.961538,0.433087,5300.0,0.485437,6.067961,1.276424,29.6,29.6,32.0,82.40,82.4,80.0,48.0,80.0,64.352941,100.00,101.00,63.00,102.30,82.744510,9.641107,140.0,149.0,93.0,157.0,119.529412,14.557957,NaN,2.0,3.0,3.0,3.0,3.0,3.0,0.0,3.0,16.0,13.0,3.0,3.0,3.0,52.0,3.0,2.0,14.0,3.0,3.0,2.0,2.0,2.0,3.0,0.0,0.0,13.0,48.0,3.0,51.0,51.0,51.0,0.0,0.0,-49.0,-116.0,-113.0,-0.4,-15.0,0.0,-0.3,3.0,1.9,-1.1,0.0,1.0,-10.0,102.0,0.0,2.4,0.00,0.00,0.000057,0.000932,-0.089183,0.004008,0.002757,-0.000009,0.000000,0.000177,1.171856,0.003000,0.004259,0.006775,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2261.0,2261.0,2261.0,2261.0,2261.0,2261.0,0.0,2261.0,2760.0,2760.0,2261.0,2261.0,2261.0,2880.0,2261.0,2540.0,2460.0,2261.0,2261.0,2480.0,2480.0,2480.0,2261.0,0.0,0.0,2820.0,2880.0,2261.0,2820.0,2880.0,2880.0,2880.0,0.0,39.0,0.0,NaN,0,False,False,True,False

In [90]:
df.dtypes

Albumin_Initial               float64
Albumin_Min                   float64
Albumin_Max                   float64
Albumin_Mean                  float64
ALP_Initial                   float64
ALP_Max                       float64
ALT_Initial                   float64
ALT_Max                       float64
AST_Initial                   float64
AST_Max                       float64
Bilirubin_Initial             float64
Bilirubin_Max                 float64
BUN_Initial                   float64
BUN_Max                       float64
BUN_Mean                      float64
BUN_Creatinine_Ratio          float64
Cholesterol_Initial           float64
Cholesterol_Min               float64
Creatinine_Initial            float64
Creatinine_Max                float64
Creatinine_Mean               float64
FiO2_Initial                  float64
FiO2_Max                      float64
FiO2_Mean                     float64
GCS_Initial                   float64
GCS_Final                     float64
GCS_Min                       float64
GCS_Max                       float64
GCS_Mean                      float64
Glucose_Initial               float64
Glucose_Min                   float64
Glucose_Max                   float64
Glucose_Mean                  float64
HCO3_Initial                  float64
HCO3_Final                    float64
HCO3_Min                      float64
HCO3_Max                      float64
HCT_Initial                   float64
HCT_Min                       float64
HCT_Max                       float64
HCT_Mean                      float64
HR_Initial                    float64
HR_Final                      float64
HR_Min                        float64
HR_Max                        float64
HR_Mean                       float64
HR_SD                         float64
K_Initial                     float64
K_Final                       float64
K_Min                         float64
K_Max                         float64
K_Mean                        float64
Lactate_Initial               float64
Lactate_Max                   float64
Lactate_Clearance_Rate_6H     float64
Lactate_Clearance_Rate_12H    float64
MechVent_Any                  float64
Mg_Initial                    float64
Mg_Min                        float64
Mg_Max                        float64
Na_Initial                    float64
Na_Final                      float64
Na_Min                        float64
Na_Max                        float64
Na_Mean                       float64
PaCO2_Initial                 float64
PaCO2_Min                     float64
PaCO2_Max                     float64
PaO2_Initial                  float64
PaO2_Min                      float64
PaO2_FiO2_Ratio               float64
pH_Initial                    float64
pH_Min                        float64
pH_Max                        float64
pH_Mean                       float64
Platelets_Initial             float64
Platelets_Min                 float64
RespRate_Initial              float64
RespRate_Max                  float64
RespRate_Mean                 float64
SaO2_Initial                  float64
SaO2_Min                      float64
Temp_Initial                  float64
Temp_Min                      float64
Temp_Max                      float64
Temp_Mean                     float64
Temp_SD                       float64
Urine_Sum                     float64
Urine_MinRate                 float64
Urine_MaxRate                 float64
Urine_MeanRate                float64
WBC_Initial                   float64
WBC_Min                       float64
WBC_Max                       float64
Weight_Initial                float64
Weight_Final                  float64
UniDiasABP_Initial            float64
UniDiasABP_Min                float64
UniDiasABP_Max                float64
UniDiasABP_Mean               float64
UniMAP_Initial                float64
UniMAP_Final                  float64
UniMAP_Min                    float64
UniMAP_Max                    float64
UniMAP_Mean                   float64
UniMAP_SD                     float64
UniSysABP_Initial             float64
UniSysABP_Final               float64
UniSysABP_Min                 float64
UniSysABP_Max                 float64
UniSysABP_Mean                float64
UniSysABP_SD                  float64
Troponin_Max                  float64
Albumin_Count                 float64
ALP_Count                     float64
ALT_Count                     float64
AST_Count                     float64
BUN_Count                     float64
Bilirubin_Count               float64
Cholesterol_Count             float64
Creatinine_Count              float64
FiO2_Count                    float64
GCS_Count                     float64
Glucose_Count                 float64
HCO3_Count                    float64
HCT_Count                     float64
HR_Count                      float64
K_Count                       float64
Lactate_Count                 float64
MechVent_Count                float64
Mg_Count                      float64
Na_Count                      float64
PaCO2_Count                   float64
PaO2_Count                    float64
pH_Count                      float64
Platelets_Count               float64
RespRate_Count                float64
SaO2_Count                    float64
Temp_Count                    float64
Urine_Count                   float64
WBC_Count                     float64
UniDiasABP_Count              float64
UniMAP_Count                  float64
UniSysABP_Count               float64
Troponin_Count                float64
Albumin_Delta                 float64
ALP_Delta                     float64
ALT_Delta                     float64
AST_Delta                     float64
Bilirubin_Delta               float64
BUN_Delta                     float64
Cholesterol_Delta             float64
Creatinine_Delta              float64
HCO3_Delta                    float64
HCT_Delta                     float64
K_Delta                       float64
Mg_Delta                      float64
Na_Delta                      float64
PaO2_Delta                    float64
Platelets_Delta               float64
SaO2_Delta                    float64
WBC_Delta                     float64
Weight_Delta                  float64
Troponin_Delta                float64
FiO2_Slope                    float64
GCS_Slope                     float64
Glucose_Slope                 float64
HR_Slope                      float64
PaCO2_Slope                   float64
pH_Slope                      float64
RespRate_Slope                float64
Temp_Slope                    float64
Urine_Rate_Slope              float64
UniDiasABP_Slope              float64
UniMAP_Slope                  float64
UniSysABP_Slope               float64
Albumin_Miss                  float64
ALP_Miss                      float64
ALT_Miss                      float64
AST_Miss                      float64
Bilirubin_Miss                float64
BUN_Miss                      float64
Cholesterol_Miss              float64
Creatinine_Miss               float64
FiO2_Miss                     float64
GCS_Miss                      float64
Glucose_Miss                  float64
HCO3_Miss                     float64
HCT_Miss                      float64
HR_Miss                       float64
K_Miss                        float64
Lactate_Miss                  float64
MechVent_Miss                 float64
Mg_Miss                       float64
Na_Miss                       float64
PaCO2_Miss                    float64
PaO2_Miss                     float64
pH_Miss                       float64
Platelets_Miss                float64
RespRate_Miss                 float64
SaO2_Miss                     float64
Temp_Miss                     float64
Urine_Miss                    float64
WBC_Miss                      float64
Weight_Miss                   float64
UniDiasABP_Miss               float64
UniMAP_Miss                   float64
UniSysABP_Miss                float64
Troponin_Miss                 float64
Albumin_Last_Minute           float64
ALP_Last_Minute               float64
ALT_Last_Minute               float64
AST_Last_Minute               float64
Bilirubin_Last_Minute         float64
BUN_Last_Minute               float64
Cholesterol_Last_Minute       float64
Creatinine_Last_Minute        float64
FiO2_Last_Minute              float64
GCS_Last_Minute               float64
Glucose_Last_Minute           float64
HCO3_Last_Minute              float64
HCT_Last_Minute               float64
HR_Last_Minute                float64
K_Last_Minute                 float64
Lactate_Last_Minute           float64
MechVent_Last_Minute          float64
Mg_Last_Minute                float64
Na_Last_Minute                float64
PaCO2_Last_Minute             float64
PaO2_Last_Minute              float64
pH_Last_Minute                float64
Platelets_Last_Minute         float64
RespRate_Last_Minute          float64
SaO2_Last_Minute              float64
Temp_Last_Minute              float64
Urine_Last_Minute             float64
WBC_Last_Minute               float64
Weight_Last_Minute            float64
UniDiasABP_Last_Minute        float64
UniMAP_Last_Minute            float64
UniSysABP_Last_Minute         float64
Troponin_Last_Minute          float64
Age                           float64
Gender                        float64
Height                        float64
In-hospital_death               int64
ICUType_1.0                      bool
ICUType_2.0                      bool
ICUType_3.0                      bool
ICUType_4.0                      bool
dtype: object

In [91]:
df.shape

(12000, 250)

In [92]:
#df.columns.tolist()

# delete ghost patients

In [93]:
col_count = [col for col in df.columns if col.endswith('_Count')]

In [94]:
df['Total_Obs_Count'] = df[col_count].sum(axis=1)

In [95]:
ghosts = df[df['Total_Obs_Count'] < 5].index

In [96]:
df = df.drop(index=ghosts)

In [97]:
df.shape

(11986, 251)

# feature engineering and log transformation

### compute total missing sum and log transform count

In [98]:
col_miss = [col for col in df.columns if col.endswith('_Miss')]

In [99]:
df['Total_Missing_Sum'] = df[col_miss].sum(axis=1)

In [100]:
df.shape

(11986, 252)

### log transformation of count variables

In [101]:
df[col_count] = df[col_count].apply(np.log1p)

In [102]:
df = df.rename(columns={col: col.replace('_Count', '_Log_Count') for col in col_count})

In [103]:
df.head(20)

,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Log_Count,ALP_Log_Count,ALT_Log_Count,AST_Log_Count,BUN_Log_Count,Bilirubin_Log_Count,Cholesterol_Log_Count,Creatinine_Log_Count,FiO2_Log_Count,GCS_Log_Count,Glucose_Log_Count,HCO3_Log_Count,HCT_Log_Count,HR_Log_Count,K_Log_Count,Lactate_Log_Count,MechVent_Log_Count,Mg_Log_Count,Na_Log_Count,PaCO2_Log_Count,PaO2_Log_Count,pH_Log_Count,Platelets_Log_Count,RespRate_Log_Count,SaO2_Log_Count,Temp_Log_Count,Urine_Log_Count,WBC_Log_Count,UniDiasABP_Log_Count,UniMAP_Log_Count,UniSysABP_Log_Count,Troponin_Log_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Minute,ALP_Last_Minute,ALT_Last_Minute,AST_Last_Minute,Bilirubin_Last_Minute,BUN_Last_Minute,Cholesterol_Last_Minute,Creatinine_Last_Minute,FiO2_Last_Minute,GCS_Last_Minute,Glucose_Last_Minute,HCO3_Last_Minute,HCT_Last_Minute,HR_Last_Minute,K_Last_Minute,Lactate_Last_Minute,MechVent_Last_Minute,Mg_Last_Minute,Na_Last_Minute,PaCO2_Last_Minute,PaO2_Last_Minute,pH_Last_Minute,Platelets_Last_Minute,RespRate_Last_Minute,SaO2_Last_Minute,Temp_Last_Minute,Urine_Last_Minute,WBC_Last_Minute,Weight_Last_Minute,UniDiasABP_Last_Minute,UniMAP_Last_Minute,UniSysABP_Last_Minute,Troponin_Last_Minute,Age,Gender,Height,In-hospital_death,ICUType_1.0,ICUType_2.0,ICUType_3.0,ICUType_4.0,Total_Obs_Count,Total_Missing_Sum
0,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.500000,10.000000,NaN,NaN,0.9,0.9,0.675000,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.500000,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.060000,1.5,1.8,0.000000,-20.000000,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.750000,40.0,39.0,51.0,187.0,73.0,121.666667,7.39,7.29,7.42,7.361429,85.0,71.0,NaN,NaN,NaN,NaN,NaN,37.6,36.3,38.9,37.329412,0.645041,2763.0,0.167785,3.775168,0.934510,13.3,9.3,13.3,59.60,59.6,60.0,38.0,77.0,59.859375,69.00,86.00,48.00,95.00,75.156250,8.942885,97.0,123.0,82.0,131.0,108.609375,10.529802,0.40,1.386294,1.386294,1.386294,1.386294,1.609438,1.386294,0.000000,1.609438,2.944439,2.639057,1.609438,1.609438,1.945910,4.174387,1.791759,1.945910,2.944439,1.609438,1.609438,2.079442,2.079442,2.079442,1.609438,0.000000,0.000000,3.555348,3.610918,1.609438,4.174387,4.174387,4.174387,1.386294,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0.0,-0.3,3.0,-3.1,0.6,-0.2,0.0,-50.0,9.0,0.0,-4.0,0.00,-0.18,-0.000198,0.000168,0.044188,-0.010776,0.000673,0.000002,0.000000,-0.000355,-2.380140,-0.001739,0.002434,0.004666,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2113.0,2113.0,2113.0,2113.0,2113.0,2113.0,0.0,2113.0,2819.0,2789.0,2113.0,2113.0,2799.0,2849.0,2113.0,2803.0,2819.0,2113.0,2113.0,2743.0,2743.0,2743.0,2799.0,0.0,0.0,2849.0,2849.0,2799.0,2849.0,2849.0,2849.0,2849.0,1320.0,22.0,0.0,167.6,0,False,False,True,False,463.0,3.0
1,2.2,2.2,2.2,2.200000,37.0,37.0,112.0,112.0,453.0,453.0,1.1,1.1,12.0,20.0,15.666667,20.000000,NaN,NaN,0.7,1.0,0.866667,1.0,1.0,0.500000,3.0,8.0,3.0,11.0,6.000000,199.0,105.0,234.0,170.600000,20.0,23.0,20.0,23.0,33.9,30.3,38.6,33.360000,99.0,96.0,71.0,117.0,97.528090,10.956619,2.9,5.9,2.9,5.9,4.400000,9.7,9.7,0.000000,4.123711,1.0,2.7,1.8,2.7,143.0,137.0,137.0,143.0,139.333333,44.0,33.0,69.0,310.0,73.0,110.000000,7.35,7.10,7.44,7.351500,123.0,92.0,NaN,NaN,NaN,98.0,96.0,34.7,34.7,37.6,36.679070,0.664232,3987.0,0.190721,5.085892,0.782265,27.1,16.8,27.1,72.60,98.9,54.0,29.0,90.0,48.739130,72.00,71.00,35.00,127.00,76.633333,16.502945,117.0,108.0,44.0,175.0,117.000000,25.219912,NaN,0.693147,0.693147,0.693147,0.693147,1.386294,0.693147,0.000000,1.386294,2.708050,2.397895,1.791759,1.386294,1.791759,4.499810,1.791759,2.772589,2.833213,1.098612,1.386294,2.995732,2.995732,3.044522,1.945910,0.000000,2.197225,4.465908,3.891820,1.609438,4.532599,4.510860,4.532599,0.000000,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.3,3.0,-1.0,3.0,-0.9,-6.0,-216.0,-24.0,1.0,-6.5,26.30,0.00,-0.000141,0.002588,-0.062102,-0.006374,-0.004262,0.000056,0.000000,0.000645,-1.168270,-0.002770,-0.002166,0.002073,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,950.0,950.0,950.0,950.0,950.0,2189.0,0.0,2189.0,2804.0,2804.0,2438.0,2189.0,2189.0,2864.0,2438.0,2610.0,2804.0,2189.0,2189.0,2757.0,2757.0,2757.0,2189.0,0.0,2804.0,2864.0,2864.0,2189.0,2864.0,2864.0,2864.0,2864.0,0.0,72.0,1.0,177.8,0,False,True,False,False,662.0,3.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,12.0,9.666667,20.000000,NaN,NaN,0.6,0.6,0.533333,NaN,NaN,NaN,15.0,15.0,15.0,15.0,15.000000,105.0,105.0,154.0,124.666667,28.0,24.0,24.0,28.0,32.2,27.1,32.5,30.075000,86.0,78.0,78.0,111.0,89.170732,8.731845,3.3,3.5,3.3,3.7,3.475000,0.8,0.8,0.000000,0.000000,NaN,1.3,1.3,2.1,133.0,132.0,132.0,134.0,133.000000,41.0,39.0,51.0,267.0,95.0,NaN,7.43,7.35,7.43,7.398000,346.0,290.0,NaN,NaN,NaN,97.0,96.0,36.6,35.6,38.2,37.000000,0.629574,7140.0,0.083333,5.333333,1.997873,9.9,9.9,13.5,75.00,75.0,55.0,41.0,62.0,51.365854,80.33,73.00,60.00,83.33,70.861463,5.859821,131.0,117.0,80.0,131.0,106.853659,11.529443,0.30,0.000000,0.000000,0.000000,0.000000,1.386294,0.000000,0.000000,1.386294,0.000000,2.484907,1.386294,1.386294,1.609438,3.737670,1.609438,1.386294,0.000000,1.386294,1.386294,1.791759,1.791759,1.791759,1.386294,0.000000,1.098612,2.564949,3.526361,1.386294,3.737670,3.737670,3.737670,0.693147,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,-0.2,-4.0,0.3,0.2,0.8,-1.0,-170.0,-56.0,-1.0,0.7,0.00,0.00,0.000000,0.000000,0.037484,0.002859,-0.004726,0.000020,0.000000,0.000136,-30.023855,0.000029,-0.000678,-0.005132,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2163.0,0.0,2163.0,0.0,2846.0,2163.0,2163.0,2624.0,2846.0,2624.0,2140.0,0.0,2624.0,2163.0,2140.0,2140.0,2140.0,2163.0,0.0,2117.0,2666.0,2846.0,2163.0,2846.0,2846.0,2846.0,2846.0,1316.0,61.0,1.0,NaN,0,True,False,False,False,273.0,9.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,20.0,14.666667,18.571429,NaN,NaN,0.6,1.1,0.800000,1.0,1.0,0.625000,3.0,15.0,3.0,15.0,12.142857,118.0,118.0,125.0,121.500000,27.0,29.0,27.0,29.0,28.9,27.4,31.9,29.600000,60.0,90.0,60.0,90.0,78.971429,7.014631,4.3,4.2,4.2,4.3,4.250000,NaN,NaN,NaN,NaN,1.0,2.2,2.2,2.2,137.0,136.0,136.0,137.0,136.500000,35.0,35.0,53.0,484.0,108.0,216.000000,7.52,7.34,7.52,7.402500,67.0,67.0,NaN,NaN,NaN,98.0,97.0,36.5,35.9,37.8,37.064000,0.672607,2847.0,0.323728,6.474564,1.221307,7.4,7.4,14.8,75.11,80.0,58.0,42.0,69.0,59.857143,75.00,72.00,55.67,89.00,76.076286,7.717743,107.0,106.0,83.0,127.0,107.600000,11.151892,NaN,0.000000,0.000000,0.000000,0.000000,1.386294,0.000000,0.000000,1.386294,1.609438,2.079442,1.098612,1.386294,1.609438,3.583519,1.098612,0.000000,1.945910,0.693147,1.098612,2.197225,2.197225,2.197225,1.609438,0.000000,1.609438,3.258097,3.091042,1.609438,3.583519,3.583519,3.583519,0.000000,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.5,2.0,-1.5,-0.1,0.0,-1.0,-366.0,5.0,-1.0,2.6,4.89,0.00,-0.001389,0.003582,0.004263,0.005479,0.011597,-0.000120,0.000000,0.001512,-169.160598,-0.001257,-0.001943,-0.001591,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2448.0,0.0,2448.0,471.0,2701.0,2448.0,2448.0,2448.0,2831.0,2448.0,0.0,1331.0,806.0,2448.0,872.0,872.0,872.0,2448.0,0.0,872.0,1211.0,1451.0,2448.0,2831.0,2831.0,2831.0,2831.0,0.0,67.0,1.0,167.6,0,False,True,False,False,259.0,9.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,13.0,12.000000,16.250000,NaN,NaN,0.8,0.8,0.766667,NaN,NaN,NaN,15.0,15.0,15.0,15.0,15.000000,267.0,175.0,267.0,220.500000,30.0,21.0,21.0,30.0,39.3,35.3,39.3,37.300000,73.0,83.0,54.0,84.0,69.428571,7.496805,2.8,4.6,2.8,5.0,3.820000,NaN,NaN,NaN,NaN,NaN,1.9,1.9,1.9,137.0,137.0,136.0,140.0,137.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,308.0,237.0,19.0,26.0,18.550000,NaN,NaN,36.6,36.0,37.1,36.654545,0.353167,4595.0,0.465549,3.491620,2.024611,8.9,7.3,8.9,71.60,71.6,66.0,50.0,93.0,70.027778,83.00,105.30,70.00,115.70,87.748056,11.373784,117.0,130.0,96.0,165.0,123.194444,15.863380,NaN,0.000000,0.000000,0.000000,0.000000,1.386294,0.000000,0.000000,1.386294,0.000000,2.564949,1.609438,1.609438,1.098612,3.761200,1.791759,0.000000,0.000000,1.098612,1.609438,0.000000,0.000000,0.000000,1.098612,3.713572,0.000000,2.484907,2.564949,1.098612,3.610918,3.610918,3.610918,0.000000,0.0,0.0,0.0,0.0,0.0,-2.0,0.0,-0.1,-9.0,-4.0,1.8,0.0,0.0,0.0,-71.0,0.0,-1.6,0.00,0.00,0.000000,0.000000,0.000593,-0.002046,0.000000,0.000000,0.000053,0.000018,3.267020,0.009731,0.010702,0.012650,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1616.0,0.0,1616.0,0.0,2756.0,1616.0,1616.0,1616.0,2756.0,1616.0,0.0,0.0,1616.0,1616.0,0.0,0.0,0.0,1616.0,2756.0,0.0,2756.0,2636.0,1616.0,2756.0,2756.0,2756.0,2756.0,0.0,50.0,0.0,NaN,0,False,False,True,False,256.0,14.0
5,3.0,3.0,3.0,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,34.0,26.333333,30.909091,NaN,NaN,0.8,1.2,1.033333,1.0,1.0,0.511765,3.0,14.0,3.0,14.0,9.500000,177.0,98.0,177.0,129.666667,26.0,22.0,22.0,26.0,38.1,37.3,39.9,38.425000,72.0,101.0,72.0,115.0,96.434783,10.177077,4.5,4.1,4.1,4.5,4.366667,4.9,4.9,69.387755,69.387755,1.0,1.4,1.4,2.7,141.0,143.0,140.0,143.0,141.333333,43.0,38.0,55.0,433.0,61.0,101.666667,7.40,7.24,7.42,7.326000,154.0,149.0,NaN,NaN,NaN,96.0,91.0,35.1,35.1,38.1,36.600000,0.810350,3387.0,0.000000,3.384419,0.674023,9.3,9.3,17.1,75.00,73.1,75.0,44.0,84.0,60.938144,99.00,78.00,60.00,114.00,83.868852,10.387493,136.0,110.0,93.0,167.0,125.061856,15.341131,NaN,0.693147,0.000000,0.000000,0.000000,1.386294,0.000000,0.000000,1.386294,2.890372,2.564949,1.386294,1.386294,1.609438,4.248495,1.386294,1.791759,2.564949,1.386294,1.386294,2.772589,2.772589,2.772589,1.386294,0.000000,2.197225,2.639057,3.871201,1.386294,4.584967,4.812184,4.584967,0.000000,0.0,0.0,0.0,0.0,0.0,16.0,0.0,0.3,-4.0,0.3,-0.4,0.9,2.0,-372.0,-5.0,-5.0,7.8,-1.90,0.00,-0.000076,0.005446,-0.034969,0.007912,0.000562,-0.000052,0.000000,0.000159,-6.997156,-0.002798,0.000864,0.000644,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2166.0,0.0,0.0,0.0,0.0,2166.0,0.0,2166.0,2722.0,2662.0,2166.0,2166.0,2166.0,2842.0,2166.0,2355.0,2722.0,2166.0,2166.0,2617.0,2617.0,2617.0,2166.0,0.0,2617.0,2662.0,2842.0,2166.0,2842.0,2842.0,2842.0,2842.0,0.0,83.0,0.0,152.4,0,False,True,False,False,576.0,7.0
6,2.4,2.4,2.5,2.450000,38.0,46.0,14.0,14.0,33.0,33.0,0.7,0.7,24.0,24.0,20.666667,19.000000,NaN,NaN,1.5,1.5,1.233333,0.6,1.0,0.612500,3.0,3.0,3.0,11.0,5.416667,142.0,132.0,166.0,151.166667,16.0,17.0,13.0,18.0,40.5,27.6,40.5,34.800000,84.0,61.0,50.0,128.0,76.820513,14.851423,3.9,4.1,3.9,5.1,4.533333,7.2,8.9,-2.777778,-5.555556,1.0,2.6,1.7,2.6,136.0,131.0,127.0,137.0,132.500000,46.0,27.0,46.0,122.0,90.0,106.000000,7.26,7.22,7.48,7.318824,151.0,86.0,NaN,NaN,NaN,NaN,NaN,36.7,35.9,37.7,36.642857,0.578744,4360.0,0.304878,2.195122,1.082225,10.9,10.9,22.9,82.00,82.0,35.0,34.0,72.0,49.151515,48.00,83.00,43.00,102.00,69.422680,12.612688,79.0,136.0,60.0,173.0,122.111111,24.955016,0.10,1.098612,1.098612,1.098612,1.098612,1.945910,1.098612,0.000000,1.945910,2.833213,2.564949,1.945910,1.945910,2.079442,4.369448,1.945910,2.833213,2.833213,1.945910,1.945910,2.890372,2.890372,2.890372,1.945910,0.000000,0.000000,2.708050,3.850148,1.945910,4.605170,4.584967,4.605170,1.098612,0.1,8.0,-3.0,-11.0,0.0,-5.0,0.0,-0.5,1.0,-12.9,0.2,-0.6,-5.0,31.0,-65.0,0.0,5.5,0.00,-0.01,-0.000121,-0.002657,-0.001532,-0.011733,-0.004719,0.000089,0.000000,-0.000476,-1.170791,0.007026,0.008783,0.014085,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2374.0,2374.0,2374.0,2374.0,2374.0,2374.0,0.0,2374.0,2833.0,2713.0,2374.0,2374.0,2606.0,2833.0,2374.0,2690.0,2833.0,2374.0,2374.0,2690.0,2690.0,2690.0,2374.0,0.0,0.0,2713.0,2833.0,2374.0,0.0,2833.0,2833.0,2833.0,704.0,90.0,1.0,NaN,0,False,False,False,True,617.0,3.0
7,NaN,NaN,NaN,NaN,82.0,82.0,67.0,67.0,265.0,265.0,NaN,NaN,13.0,15.0,14.000000,16.250000,211.0,211.0,0.8,1.0,0.900000,NaN,NaN,NaN,15.0,15.0,14.0,15.0,14.916667,126.0,107.0,126.0,116.500000,26.0,28.0,26.0,28.0,44.0,43.0,44.6,43.866667,64.0,79.0,64.0,87.0,73.900000,4.601003,4.0,4.3,4.0,4.3,4.133333,NaN,NaN,NaN,NaN,NaN,2.2,2.2,2.4,140.0,137.0,137.0,140.0,138.500000,39.0,39.0,39.0,71.0,71.0,NaN,7.40,7.40,7.40,7.400000,182.0,182.0,16.0,27.0,18.815789,97.0,97.0,37.7,36.1,37.9,37.175000,0.552885,4425.0,0.000000,1.616162,0.885943,10.5,9.9,10.5,99.00,99.0,70.0,37.0,88.0,62.428571,91.67,74.33,56.67,163.00,82.258000,19.862872,135.0,105.0,90.0,158.0,113.971429,17.114641,NaN,0.000000,0.693147,0.693147,0.693147,1.098612,0.000000,0.693147,1.098612,0.000000,2.564949,1.098612,1.098612,1.386294,3.713572,1.386294,0.000000,0.000000,1.386294,1.098612,0.693147,0.693147,0.693147,1.386294,3.663562,0.693147,2.564949,3.178054,1.098612,3.583519,3.583519,3.583519,0.000000,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.2,2.0,-1.0,0.3,0.0,-3.0,0.0,1.0,0.0,-0.6,0.00,0.00,0.000000,0.000081,-0.013514,0.002558,0.000000,0.000000,0.000379,0.000127,-10.738557,-0.007456,-0.012445,-0.012624,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,485.0,485.0,485.0,0.0,1891.0,485.0,1891.0,0.0,2780.0,1891.0,1891.0,1891.0,2780.0,1891.0,0.0,0.0,1891.0,1891.0,116.0,116.0,116.0,1891.0,2780.0,80.0,2780.0,2840.0,1891.0,2780.0,2780.0,2780.0,2780.0,0.0,66.0,1.0,175.3,0,True,False,False,False,262.0,6.0
8,NaN,NaN,NaN,NaN,38.0,38.0,71.0,71.0,63.0,63.0,NaN,NaN,16.0,16.0,15.333333,17.777778,NaN,NaN,1.2,1.2,1.033333,NaN,NaN,NaN,15.0,15.0,13.0,15.0,14.785714,150.0,107.0,150.0,123.666667,26.0,30.0,26.0,30.0,35.6,30.6,35.6,32.700000,88.0,94.0,79.0,102.0,90.033333,6.300300,4.4,3.8,3.8,4.4,4.033333,NaN,NaN,NaN,NaN,NaN,1.8,1.8,2.1,141.0,138.0,138.0,141.0,139.333333,NaN,NaN,NaN,NaN,NaN,NaN,7.42,7.42,7.42,7.420000,162.0,148.0,15.0,29.0,16.901639,NaN,NaN,35.7,35.3,37.9,37.033333,0.943237,4365.0,0.375000,3.750000,1.259146,8.9,6.5,8.9,80.00,80.0,61.0,50.0,80.0,61.672131,71.00,85.00,60.00,109.00,78.803279,12.748620,113.0,122.0,81.0,148.0,108.885246,18.430137,NaN,0.000000,0.693147,0.693147,0.693147,1.386294,0.000000,0.000000,1.386294,0.000000,2.708050,1.386294,1.386294,1.386294,4.110874,1.386294,0.000000,0.000000,1.386294,1.386294,0.000000,0.000000,0.693147,1.386294,4.127134,0.000000,2.564949,3.761200,1.386294,4.127134,4.127134,4.127134,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.3,4.0,-5.0,-0.6,0.2,-3.0,0.0,-14.0,0.0,-2.4,0.00,0.00,0.000000,-0.000125,-0.017216,0.005135,0.000000,0.000000,0.002784,0.000931,0.422173,0.002028,0.004095,0.007874,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1113.0,1113.0,1113.0,0.0,2523.0,0.0,2523.0,0.0,2653.0,2523.0,2523.0,2523.0,2833.0,2523.0,0.0,0.0,2523.0,2523.0,0.0,0.0,1492.0,2523.0,2833.0,0.0,2713.0,2773.0,2523.0,0.0,2833.0,2833.0,2833.0,0.0,61.0,1.0,NaN,0,False,False,False,True,406.0,10.0
9,3.1,3.1,3.1,3.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0,11.500000,30.000000,NaN,NaN,0.4,0.6,0.550000,1.0,1.0,0.550000,8.0,10.0,7.0,11.0,8.545455,117.0,111.0,129.0,119.750000,22.0,27.0,22.0,27.0,34.8,30.1,34.8,32.975000,80.0,68.0,62.0,91.0,75.260000,8.095880,3.7,3.8,3.6,4.0,3.800000,1.2,2.1,NaN,NaN,1.0,1.6,1.6,2.0,134.0,141.0,134.0,141.0,136.750000,44.0,44.0,49.0,74.0,62.0,62.000000,7.42,7.35,7.44,7.398750,157.0,157.0,NaN,NaN,NaN,NaN,NaN,36.9,36.9,38.3,37.933333,0.373529,8200.0,0.694444,3.240741,1.670139,15.4,11.2,15.4,108.00,108.0,64.0,52.0,86.0,67.365385,87.00,94.00,68.00,101.00,88.916731,7.029892,133.0,146.0,95.0,159.0,131.884615,12.920047,NaN,0.693147,0.000000,0.000000,0.000000,1.609438,0.000000,0.000000,1.609438,2.708050,3.135494,1.609438,1.609438,1.609438,3.931826,1.791759,1.098612,2.772589,1.609438,1.609438,2.197225,2.197225,2.197225,1.609438,0.000000,0.000000,2.772589,3.663562,1.609438,3.970292,3.970292,3.970292,0.000000,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.2,5.0,-4.7,0.1,0.4,7.0,59.0,16.0,0.0,-4.2,0.00,0.00,-0.000148,0.001270,0.007430,0.005173,0.000763,0.000033,0.000000,0.000151,-70.785182,0.002558,0.004990,0.010517,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,101.0,0.0,0.0,0.0,0.0,2138.0,0.0,2138.0,2548.0,2858.0,2138.0,2138.0,2138.0,2858.0,2213.0,273.0,2548.0,2138.0,2138.0,2081.0,2081.0,2081.0,2138.0,0.0,0.0,2858.0,2858.0,2138.0,0.0,2858.0,2858.0,2858.0,0.0,59.0,1.0,NaN,0,False,False,False,True,378.0,8.0

### convert _Last_Minute to _Last_Gap and compute Global_Last_Gap

In [104]:
col_last_minute = [col for col in df.columns if col.endswith('_Last_Minute')]

In [105]:
for col in col_last_minute:
    gap_name = col.replace('_Last_Minute', '_Last_Gap')
    df[gap_name] = 2880 - df[col]

In [106]:
df.shape

(11986, 285)

In [107]:
df = df.drop(columns=col_last_minute)

In [108]:
df.shape

(11986, 252)

In [109]:
col_gap = [col for col in df.columns if col.endswith('_Last_Gap')]
df['Global_Last_Gap'] = df[col_gap].min(axis=1)

In [110]:
df.shape

(11986, 253)

### One hot encoding for ICU type and -1 for gender

In [111]:
df['Gender'] = df['Gender'].fillna(-1)

In [112]:
col_icu = [col for col in df.columns if col.startswith('ICUType_')]
df[col_icu] = df[col_icu].astype(int)

In [113]:
df.shape

(11986, 253)

### compute expert composites: Shock_Index, GCS_MAP_Product, and Anion_Gap.

In [114]:
df['Shock_Index'] = df['HR_Final'] / df['UniSysABP_Final']
df['GCS_MAP_Product'] = df['GCS_Final'] * df['UniMAP_Final']
df['Net_Cation_Balance'] = (df['Na_Final'] + df['K_Final']) - df['HCO3_Final']

In [115]:
df.shape

(11986, 256)

In [116]:
df.head(20)

,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Log_Count,ALP_Log_Count,ALT_Log_Count,AST_Log_Count,BUN_Log_Count,Bilirubin_Log_Count,Cholesterol_Log_Count,Creatinine_Log_Count,FiO2_Log_Count,GCS_Log_Count,Glucose_Log_Count,HCO3_Log_Count,HCT_Log_Count,HR_Log_Count,K_Log_Count,Lactate_Log_Count,MechVent_Log_Count,Mg_Log_Count,Na_Log_Count,PaCO2_Log_Count,PaO2_Log_Count,pH_Log_Count,Platelets_Log_Count,RespRate_Log_Count,SaO2_Log_Count,Temp_Log_Count,Urine_Log_Count,WBC_Log_Count,UniDiasABP_Log_Count,UniMAP_Log_Count,UniSysABP_Log_Count,Troponin_Log_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Age,Gender,Height,In-hospital_death,ICUType_1.0,ICUType_2.0,ICUType_3.0,ICUType_4.0,Total_Obs_Count,Total_Missing_Sum,Albumin_Last_Gap,ALP_Last_Gap,ALT_Last_Gap,AST_Last_Gap,Bilirubin_Last_Gap,BUN_Last_Gap,Cholesterol_Last_Gap,Creatinine_Last_Gap,FiO2_Last_Gap,GCS_Last_Gap,Glucose_Last_Gap,HCO3_Last_Gap,HCT_Last_Gap,HR_Last_Gap,K_Last_Gap,Lactate_Last_Gap,MechVent_Last_Gap,Mg_Last_Gap,Na_Last_Gap,PaCO2_Last_Gap,PaO2_Last_Gap,pH_Last_Gap,Platelets_Last_Gap,RespRate_Last_Gap,SaO2_Last_Gap,Temp_Last_Gap,Urine_Last_Gap,WBC_Last_Gap,Weight_Last_Gap,UniDiasABP_Last_Gap,UniMAP_Last_Gap,UniSysABP_Last_Gap,Troponin_Last_Gap,Global_Last_Gap,Shock_Index,GCS_MAP_Product,Net_Cation_Balance
0,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.500000,10.000000,NaN,NaN,0.9,0.9,0.675000,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.500000,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.060000,1.5,1.8,0.000000,-20.000000,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.750000,40.0,39.0,51.0,187.0,73.0,121.666667,7.39,7.29,7.42,7.361429,85.0,71.0,NaN,NaN,NaN,NaN,NaN,37.6,36.3,38.9,37.329412,0.645041,2763.0,0.167785,3.775168,0.934510,13.3,9.3,13.3,59.60,59.6,60.0,38.0,77.0,59.859375,69.00,86.00,48.00,95.00,75.156250,8.942885,97.0,123.0,82.0,131.0,108.609375,10.529802,0.40,1.386294,1.386294,1.386294,1.386294,1.609438,1.386294,0.000000,1.609438,2.944439,2.639057,1.609438,1.609438,1.945910,4.174387,1.791759,1.945910,2.944439,1.609438,1.609438,2.079442,2.079442,2.079442,1.609438,0.000000,0.000000,3.555348,3.610918,1.609438,4.174387,4.174387,4.174387,1.386294,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0.0,-0.3,3.0,-3.1,0.6,-0.2,0.0,-50.0,9.0,0.0,-4.0,0.00,-0.18,-0.000198,0.000168,0.044188,-0.010776,0.000673,0.000002,0.000000,-0.000355,-2.380140,-0.001739,0.002434,0.004666,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,0.0,167.6,0,0,0,1,0,463.0,3.0,767.0,767.0,767.0,767.0,767.0,767.0,2880.0,767.0,61.0,91.0,767.0,767.0,81.0,31.0,767.0,77.0,61.0,767.0,767.0,137.0,137.0,137.0,81.0,2880.0,2880.0,31.0,31.0,81.0,31.0,31.0,31.0,31.0,1560.0,31.0,0.861789,602.00,115.6
1,2.2,2.2,2.2,2.200000,37.0,37.0,112.0,112.0,453.0,453.0,1.1,1.1,12.0,20.0,15.666667,20.000000,NaN,NaN,0.7,1.0,0.866667,1.0,1.0,0.500000,3.0,8.0,3.0,11.0,6.000000,199.0,105.0,234.0,170.600000,20.0,23.0,20.0,23.0,33.9,30.3,38.6,33.360000,99.0,96.0,71.0,117.0,97.528090,10.956619,2.9,5.9,2.9,5.9,4.400000,9.7,9.7,0.000000,4.123711,1.0,2.7,1.8,2.7,143.0,137.0,137.0,143.0,139.333333,44.0,33.0,69.0,310.0,73.0,110.000000,7.35,7.10,7.44,7.351500,123.0,92.0,NaN,NaN,NaN,98.0,96.0,34.7,34.7,37.6,36.679070,0.664232,3987.0,0.190721,5.085892,0.782265,27.1,16.8,27.1,72.60,98.9,54.0,29.0,90.0,48.739130,72.00,71.00,35.00,127.00,76.633333,16.502945,117.0,108.0,44.0,175.0,117.000000,25.219912,NaN,0.693147,0.693147,0.693147,0.693147,1.386294,0.693147,0.000000,1.386294,2.708050,2.397895,1.791759,1.386294,1.791759,4.499810,1.791759,2.772589,2.833213,1.098612,1.386294,2.995732,2.995732,3.044522,1.945910,0.000000,2.197225,4.465908,3.891820,1.609438,4.532599,4.510860,4.532599,0.000000,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.3,3.0,-1.0,3.0,-0.9,-6.0,-216.0,-24.0,1.0,-6.5,26.30,0.00,-0.000141,0.002588,-0.062102,-0.006374,-0.004262,0.000056,0.000000,0.000645,-1.168270,-0.002770,-0.002166,0.002073,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,72.0,1.0,177.8,0,0,1,0,0,662.0,3.0,1930.0,1930.0,1930.0,1930.0,1930.0,691.0,2880.0,691.0,76.0,76.0,442.0,691.0,691.0,16.0,442.0,270.0,76.0,691.0,691.0,123.0,123.0,123.0,691.0,2880.0,76.0,16.0,16.0,691.0,16.0,16.0,16.0,16.0,2880.0,16.0,0.888889,568.00,119.9
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,12.0,9.666667,20.000000,NaN,NaN,0.6,0.6,0.533333,NaN,NaN,NaN,15.0,15.0,15.0,15.0,15.000000,105.0,105.0,154.0,124.666667,28.0,24.0,24.0,28.0,32.2,27.1,32.5,30.075000,86.0,78.0,78.0,111.0,89.170732,8.731845,3.3,3.5,3.3,3.7,3.475000,0.8,0.8,0.000000,0.000000,NaN,1.3,1.3,2.1,133.0,132.0,132.0,134.0,133.000000,41.0,39.0,51.0,267.0,95.0,NaN,7.43,7.35,7.43,7.398000,346.0,290.0,NaN,NaN,NaN,97.0,96.0,36.6,35.6,38.2,37.000000,0.629574,7140.0,0.083333,5.333333,1.997873,9.9,9.9,13.5,75.00,75.0,55.0,41.0,62.0,51.365854,80.33,73.00,60.00,83.33,70.861463,5.859821,131.0,117.0,80.0,131.0,106.853659,11.529443,0.30,0.000000,0.000000,0.000000,0.000000,1.386294,0.000000,0.000000,1.386294,0.000000,2.484907,1.386294,1.386294,1.609438,3.737670,1.609438,1.386294,0.000000,1.386294,1.386294,1.791759,1.791759,1.791759,1.386294,0.000000,1.098612,2.564949,3.526361,1.386294,3.737670,3.737670,3.737670,0.693147,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,-0.2,-4.0,0.3,0.2,0.8,-1.0,-170.0,-56.0,-1.0,0.7,0.00,0.00,0.000000,0.000000,0.037484,0.002859,-0.004726,0.000020,0.000000,0.000136,-30.023855,0.000029,-0.000678,-0.005132,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,61.0,1.0,NaN,0,1,0,0,0,273.0,9.0,2880.0,2880.0,2880.0,2880.0,2880.0,717.0,2880.0,717.0,2880.0,34.0,717.0,717.0,256.0,34.0,256.0,740.0,2880.0,256.0,717.0,740.0,740.0,740.0,717.0,2880.0,763.0,214.0,34.0,717.0,34.0,34.0,34.0,34.0,1564.0,34.0,0.666667,1095.00,111.5
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,20.0,14.666667,18.571429,NaN,NaN,0.6,1.1,0.800000,1.0,1.0,0.625000,3.0,15.0,3.0,15.0,12.142857,118.0,118.0,125.0,121.500000,27.0,29.0,27.0,29.0,28.9,27.4,31.9,29.600000,60.0,90.0,60.0,90.0,78.971429,7.014631,4.3,4.2,4.2,4.3,4.250000,NaN,NaN,NaN,NaN,1.0,2.2,2.2,2.2,137.0,136.0,136.0,137.0,136.500000,35.0,35.0,53.0,484.0,108.0,216.000000,7.52,7.34,7.52,7.402500,67.0,67.0,NaN,NaN,NaN,98.0,97.0,36.5,35.9,37.8,37.064000,0.672607,2847.0,0.323728,6.474564,1.221307,7.4,7.4,14.8,75.11,80.0,58.0,42.0,69.0,59.857143,75.00,72.00,55.67,89.00,76.076286,7.717743,107.0,106.0,83.0,127.0,107.600000,11.151892,NaN,0.000000,0.000000,0.000000,0.000000,1.386294,0.000000,0.000000,1.386294,1.609438,2.079442,1.098612,1.386294,1.609438,3.583519,1.098612,0.000000,1.945910,0.693147,1.098612,2.197225,2.197225,2.197225,1.609438,0.000000,1.609438,3.258097,3.091042,1.609438,3.583519,3.583519,3.583519,0.000000,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.5,2.0,-1.5,-0.1,0.0,-1.0,-366.0,5.0,-1.0,2.6,4.89,0.00,-0.001389,0.003582,0.004263,0.005479,0.011597,-0.000120,0.000000,0.001512,-169.160598,-0.001257,-0.001943,-0.001591,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,67.0,1.0,167.6,0,0,1,0,0,259.0,9.0,2880.0,2880.0,2880.0,2880.0,2880.0,432.0,2880.0,432.0,2409.0,179.0,432.0,432.0,432.0,49.0,432.0,2880.0,1549.0,2074.0,432.0,2008.0,2008.0,2008.0,432.0,2880.0,2008.0,1669.0,1429.0,432.0,49.0,49.0,49.0,49.0,2880.0,49.0,0.849057,1080.00,111.2
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,13.0,12.000000,16.250000,NaN,NaN,0.8,0.8,0.766667,NaN,NaN,NaN,15.0,15.0,15.0,15.0,15.000000,267.0,175.0,267.0,220.500000,30.0,21.0,21.0,30.0,39.3,35.3,39.3,37.300000,73.0,83.0,54.0,84.0,69.428571,7.496805,2.8,4.6,2.8,5.0,3.820000,NaN,NaN,NaN,NaN,NaN,1.9,1.9,1.9,137.0,137.0,136.0,140.0,137.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,308.0,237.0,19.0,26.0,18.550000,NaN,NaN,36.6,36.0,37.1,36.654545,0.353167,4595.0,0.465549,3.491620,2.024611,8.9,7.3,8.9,71.60,71.6,66.0,50.0,93.0,70.027778,83.00,105.30,70.00,115.70,87.748056,11.373784,117.0,130.0,96.0,165.0,123.194444,15.863380,NaN,0.000000,0.000000,0.000000,0.000000,1.386294,0.000000,0.000000,1.386294,0.000000,2.564949,1.609438,1.609438,1.098612,3.761200,1.791759,0.000000,0.000000,1.098612,1.609438,0.000000,0.000000,0.000000,1.098612,3.713572,0.000000,2.484907,2.564949,1.098612,3.610918,3.610918,3.610918,0.000000,0.0,0.0,0.0,0.0,0.0,-2.0,0.0,-0.1,-9.0,-4.0,1.8,0.0,0.0,0.0,-71.0,0.0,-1.6,0.00,0.00,0.000000,0.000000,0.000593,-0.002046,0.000000,0.000000,0.000053,0.000018,3.267020,0.009731,0.010702,0.012650,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,50.0,0.0,NaN,0,0,0,1,0,256.0,14.0,2880.0,2880.0,2880.0,2880.0,2880.0,1264.0,2880.0,1264.0,2880.0,124.0,1264.0,1264.0,1264.0,124.0,1264.0,2880.0,2880.0,1264.0,1264.0,2880.0,2880.0,2880.0,1264.0,124.0,2880.0,124.0,244.0,1264.0,124.0,124.0,124.0,124.0,2880.0,124.0,0.638462,1579.50,120.6
5,3.0,3.0,3.0,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,34.0,26.333333,30.909091,NaN,NaN,0.8,1.2,1.033333,1.0,1.0,0.511765,3.0,14.0,3.0,14.0,9.500000,177.0,98.0,177.0,129.666667,26.0,22.0,22.0,26.0,38.1,37.3,39.9,38.425000,72.0,101.0,72.0,115.0,96.434783,10.177077,4.5,4.1,4.1,4.5,4.366667,4.9,4.9,69.387755,69.387755,1.0,1.4,1.4,2.7,141.0,143.0,140.0,143.0,141.333333,43.0,38.0,55.0,433.0,61.0,101.666667,7.40,7.24,7.42,7.326000,154.0,149.0,NaN,NaN,NaN,96.0,91.0,35.1,35.1,38.1,36.600000,0.810350,3387.0,0.000000,3.384419,0.674023,9.3,9.3,17.1,75.00,73.1,75.0,44.0,84.0,60.938144,99.00,78.00,60.00,114.00,83.868852,10.387493,136.0,110.0,93.0,167.0,125.061856,15.341131,NaN,0.693147,0.000000,0.000000,0.000000,1.386294,0.000000,0.000000,1.386294,2.890372,2.564949,1.386294,1.386294,1.609438,4.248495,1.386294,1.791759,2.564949,1.386294,1.386294,2.772589,2.772589,2.772589,1.386294,0.000000,2.197225,2.639057,3.871201,1.386294,4.584967,4.812184,4.584967,0.000000,0.0,0.0,0.0,0.0,0.0,16.0,0.0,0.3,-4.0,0.3,-0.4,0.9,2.0,-372.0,-5.0,-5.0,7.8,-1.90,0.00,-0.000076,0.005446,-0.034969,0.007912,0.000562,-0.000052,0.000000,0.000159,-6.997156,-0.002798,0.000864,0.000644,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,83.0,0.0,152.4,0,0,1,0,0,576.0,7.0,714.0,2880.0,2880.0,2880.0,2880.0,714.0,2880.0,714.0,158.0,218.0,714.0,714.0,714.0,38.0,714.0,525.0,158.0,714.0,714.0,263.0,263.0,263.0,714.0,2880.0,263.0,218.0,38.0,714.0,38.0,38.0,38.0,38.0,2880.0,38.0,0.918182,1092.00,125.1
6,2.4,2.4,2.5,2.450000,38.0,46.0,14.0,14.0,33.0,33.0,0.7,0.7,24.0,24.0,20.666667,19.000000,NaN,NaN,1.5,1.5,1.233333,0.6,1.0,0.612500,3.0,3.0,3.0,11.0,5.416667,142.0,132.0,166.0,151.166667,16.0,17.0,13.0,18.0,40.5,27.6,40.5,34.800000,84.0,61.0,50.0,128.0,76.820513,14.851423,3.9,4.1,3.9,5.1,4.533333,7.2,8.9,-2.777778,-5.555556,1.0,2.6,1.7,2.6,136.0,131.0,127.0,137.0,132.500000,46.0,27.0,46.0,122.0,90.0,106.000000,7.26,7.22,7.48,7.318824,151.0,86.0,NaN,NaN,NaN,NaN,NaN,36.7,35.9,37.7,36.642857,0.578744,4360.0,0.304878,2.195122,1.082225,10.9,10.9,22.9,82.00,82.0,35.0,34.0,72.0,49.151515,48.00,83.00,43.00,102.00,69.422680,12.612688,79.0,136.0,60.0,173.0,122.111111,24.955016,0.10,1.098612,1.098612,1.098612,1.098612,1.945910,1.098612,0.000000,1.945910,2.833213,2.564949,1.945910,1.945910,2.079442,4.369448,1.945910,2.833213,2.833213,1.945910,1.945910,2.890372,2.890372,2.890372,1.945910,0.000000,0.000000,2.708050,3.850148,1.945910,4.605170,4.584967,4.605170,1.098612,0.1,8.0,-3.0,-11.0,0.0,-5.0,0.0,-0.5,1.0,-12.9,0.2,-0.6,-5.0,31.0,-65.0,0.0,5.5,0.00,-0.01,-0.000121,-0.002657,-0.001532,-0.011733,-0.004719,0.000089,0.000000,-0.000476,-1.170791,0.007026,0.008783,0.014085,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,90.0,1.0,NaN,0,0,0,0,1,617.0,3.0,506.0,506.0,506.0,506.0,506.0,506.0,2880.0,506.0,47.0,167.0,506.0,506.0,274.0,47.0,506.0,190.0,47.0,506.0,506.0,190.0,190.0,190.0,506.0,2880.0,2880.0,167.0,47.0,506.0,2880.0,47.0,47.0,47.0,2176.0,47.0,0.448529,249.00,118.1
7,NaN,NaN,NaN,NaN,82.0,82.0,67.0,67.0,265.0,265.0,NaN,NaN,13.0,15.0,14.000000,16.250000,211.0,211.0,0.8,1.0,0.900000,NaN,NaN,NaN,15.0,15.0,14.0,15.0,14.916667,126.0,107.0,126.0,116.500000,26.0,28.0,26.0,28.0,44.0,43.0,44.6,43.866667,64.0,79.0,64.0,87.0,73.900000,4.601003,4.0,4.3,4.0,4.3,4.133333,NaN,NaN,NaN,NaN,NaN,2.2,2.2,2.4,140.0,137.0,137.0,140.0,138.500000,39.0,39.0,39.0,71.0,71.0,NaN,7.40,7.40,7.40,7.400000,182.0,182.0,16.0,27.0,18.815789,97.0,97.0,37.7,36.1,37.9,37.175000,0.552885,4425.0,0.000000,1.616162,0.885943,10.5,9.9,10.5,99.00,99.0,70.0,37.0,88.0,62.428571,91.67,74.33,56.67,163.00,82.258000,19.862872,135.0,105.0,90.0,158.0,113.971429,17.114641,NaN,0.000000,0.693147,0.693147,0.693147,1.098612,0.000000,0.693147,1.098612,0.000000,2.564949,1.098612,1.098612,1.386294,3.713572,1.386294,0.000000,0.000000,1.386294,1.098612,0.693147,0.693147,0.693147,1.386294,3.663562,0.693147,2.564949,3.178054,1.098612,3.583519,3.583519,3.583519,0.000000,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.2,2.0,-1.0,0.3,0.0,-3.0,0.0,1.0,0.0,-0.6,0.00,0.00,0.000000,0.000081,-0.013514,0.002558,0.000000,0.000000,0.000379,0.000127,-10.738557,-0.007456,-0.012445,-0.012624,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,66.0,1.0,175.3,0,1,0,0,0,262.0,6.0,2880.0,2395.0,2395.0,2395.0,2880.0,989.0,2395.0,989.0,2880.0,100.0,989.0,989.0,989.0,100.0,989.0,2880.0,2880.0,989.0,989.0,2764.0,2764.0,2764.0,989.0,100.0,2800.0,100.0,40.0,989.0,100.0,100.0,100.0,100.0,2880.0,40.0,0.752381,1114.95,113.3
8,NaN,NaN,NaN,NaN,38.0,38.0,71.0,71.0,63.0,63.0,NaN,NaN,16.0,16.0,15.333333,17.777778,NaN,NaN,1.2,1.2,1.033333,NaN,NaN,NaN,15.0,15.0,13.0,15.0,14.785714,150.0,107.0,150.0,123.666667,26.0,30.0,26.0,30.0,35.6,30.6,35.6,32.700000,88.0,94.0,79.0,102.0,90.033333,6.300300,4.4,3.8,3.8,4.4,4.033333,NaN,NaN,NaN,NaN,NaN,1.8,1.8,2.1,141.0,138.0,138.0,141.0,139.333333,NaN,NaN,NaN,NaN,NaN,NaN,7.42,7.42,7.42,7.420000,162.0,148.0,15.0,29.0,16.901639,NaN,NaN,35.7,35.3,37.9,37.033333,0.943237,4365.0,0.375000,3.750000,1.259146,8.9,6.5,8.9,80.00,80.0,61.0,50.0,80.0,61.672131,71.00,85.00,60.00,109.00,78.803279,12.748620,113.0,122.0,81.0,148.0,108.885246,18.430137,NaN,0.000000,0.693147,0.693147,0.693147,1.386294,0.000000,0.000000,1.386294,0.000000,2.708050,1.386294,1.386294,1.386294,4.110874,1.386294,0.000000,0.000000,1.386294,1.386294,0.000000,0.000000,0.693147,1.386294,4.127134,0.000000,2.564949,3.761200,1.386294,4.127134,4.127134,4.127134,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.3,4.0,-5.0,-0.6,0.2,-3.0,0.0,-14.0,0.0,-2.4,0.00,0.00,0.000000,-0.000125,-0.017216,0.005135,0.000000,0.000000,0.002784,0.000931,0.422173,0.002028,0.004095,0.007874,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,61.0,1.0,NaN,0,0,0,0,1,406.0,10.0,2880.0,1767.0,1767.0,1767.0,2880.0,357.0,2880.0,357.0,2880.0,227.0,357.0,357.0,357.0,47.0,357.0,2880.0,2880.0,357.0,357.0,2880.0,2880.0,1388.0,357.0,47.0,2880.0,167.0,107.0,357.0,2880.0,47.0,47.0,47.0,2880.0,47.0,0.770492,1275.00,111.8
9,3.1,3.1,3.1,3.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0,11.500000,30.000000,NaN,NaN,0.4,0.6,0.550000,1.0,1.0,0.550000,8.0,10.0,7.0,11.0,8.545455,117.0,111.0,129.0,119.750000,22.0,27.0,22.0,27.0,34.8,30.1,34.8,32.975000,80.0,68.0,62.0,91.0,75.260000,8.095880,3.7,3.8,3.6,4.0,3.800000,1.2,2.1,NaN,NaN,1.0,1.6,1.6,2.0,134.0,141.0,134.0,141.0,136.750000,44.0,44.0,49.0,74.0,62.0,62.000000,7.42,7.35,7.44,7.398750,157.0,157.0,NaN,NaN,NaN,NaN,NaN,36.9,36.9,38.3,37.933333,0.373529,8200.0,0.694444,3.240741,1.670139,15.4,11.2,15.4,108.00,108.0,64.0,52.0,86.0,67.365385,87.00,94.00,68.00,101.00,88.916731,7.029892,133.0,146.0,95.0,159.0,131.884615,12.920047,NaN,0.693147,0.000000,0.000000,0.000000,1.609438,0.000000,0.000000,1.609438,2.708050,3.135494,1.609438,1.609438,1.609438,3.931826,1.791759,1.098612,2.772589,1.609438,1.609438,2.197225,2.197225,2.197225,1.609438,0.000000,0.000000,2.772589,3.663562,1.609438,3.970292,3.970292,3.970292,0.000000,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.2,5.0,-4.7,0.1,0.4,7.0,59.0,16.0,0.0,-4.2,0.00,0.00,-0.000148,0.001270,0.007430,0.005173,0.000763,0.000033,0.000000,0.000151,-70.785182,0.002558,0.004990,0.010517,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,59.0,1.0,NaN,0,0,0,0,1,378.0,8.0,2779.0,2880.0,2880.0,2880.0,2880.0,742.0,2880.0,742.0,332.0,22.0,742.0,742.0,742.0,22.0,667.0,2607.0,332.0,742.0,742.0,799.0,799.0,799.0,742.0,2880.0,2880.0,22.0,22.0,742.0,2880.0,22.0,22.0,22.0,2880.0,22.0,0.465753,940.00,117.8

In [117]:
df.columns.to_list()

['Albumin_Initial',
 'Albumin_Min',
 'Albumin_Max',
 'Albumin_Mean',
 'ALP_Initial',
 'ALP_Max',
 'ALT_Initial',
 'ALT_Max',
 'AST_Initial',
 'AST_Max',
 'Bilirubin_Initial',
 'Bilirubin_Max',
 'BUN_Initial',
 'BUN_Max',
 'BUN_Mean',
 'BUN_Creatinine_Ratio',
 'Cholesterol_Initial',
 'Cholesterol_Min',
 'Creatinine_Initial',
 'Creatinine_Max',
 'Creatinine_Mean',
 'FiO2_Initial',
 'FiO2_Max',
 'FiO2_Mean',
 'GCS_Initial',
 'GCS_Final',
 'GCS_Min',
 'GCS_Max',
 'GCS_Mean',
 'Glucose_Initial',
 'Glucose_Min',
 'Glucose_Max',
 'Glucose_Mean',
 'HCO3_Initial',
 'HCO3_Final',
 'HCO3_Min',
 'HCO3_Max',
 'HCT_Initial',
 'HCT_Min',
 'HCT_Max',
 'HCT_Mean',
 'HR_Initial',
 'HR_Final',
 'HR_Min',
 'HR_Max',
 'HR_Mean',
 'HR_SD',
 'K_Initial',
 'K_Final',
 'K_Min',
 'K_Max',
 'K_Mean',
 'Lactate_Initial',
 'Lactate_Max',
 'Lactate_Clearance_Rate_6H',
 'Lactate_Clearance_Rate_12H',
 'MechVent_Any',
 'Mg_Initial',
 'Mg_Min',
 'Mg_Max',
 'Na_Initial',
 'Na_Final',
 'Na_Min',
 'Na_Max',
 'Na_Mean',
 'PaCO2_Initial',
 'PaCO2_Min',
 'PaCO2_Max',
 'PaO2_Initial',
 'PaO2_Min',
 'PaO2_FiO2_Ratio',
 'pH_Initial',
 'pH_Min',
 'pH_Max',
 'pH_Mean',
 'Platelets_Initial',
 'Platelets_Min',
 'RespRate_Initial',
 'RespRate_Max',
 'RespRate_Mean',
 'SaO2_Initial',
 'SaO2_Min',
 'Temp_Initial',
 'Temp_Min',
 'Temp_Max',
 'Temp_Mean',
 'Temp_SD',
 'Urine_Sum',
 'Urine_MinRate',
 'Urine_MaxRate',
 'Urine_MeanRate',
 'WBC_Initial',
 'WBC_Min',
 'WBC_Max',
 'Weight_Initial',
 'Weight_Final',
 'UniDiasABP_Initial',
 'UniDiasABP_Min',
 'UniDiasABP_Max',
 'UniDiasABP_Mean',
 'UniMAP_Initial',
 'UniMAP_Final',
 'UniMAP_Min',
 'UniMAP_Max',
 'UniMAP_Mean',
 'UniMAP_SD',
 'UniSysABP_Initial',
 'UniSysABP_Final',
 'UniSysABP_Min',
 'UniSysABP_Max',
 'UniSysABP_Mean',
 'UniSysABP_SD',
 'Troponin_Max',
 'Albumin_Log_Count',
 'ALP_Log_Count',
 'ALT_Log_Count',
 'AST_Log_Count',
 'BUN_Log_Count',
 'Bilirubin_Log_Count',
 'Cholesterol_Log_Count',
 'Creatinine_Log_Count',
 'FiO2_Log_Count',
 'GCS_Log_Count',
 'Glucose_Log_Count',
 'HCO3_Log_Count',
 'HCT_Log_Count',
 'HR_Log_Count',
 'K_Log_Count',
 'Lactate_Log_Count',
 'MechVent_Log_Count',
 'Mg_Log_Count',
 'Na_Log_Count',
 'PaCO2_Log_Count',
 'PaO2_Log_Count',
 'pH_Log_Count',
 'Platelets_Log_Count',
 'RespRate_Log_Count',
 'SaO2_Log_Count',
 'Temp_Log_Count',
 'Urine_Log_Count',
 'WBC_Log_Count',
 'UniDiasABP_Log_Count',
 'UniMAP_Log_Count',
 'UniSysABP_Log_Count',
 'Troponin_Log_Count',
 'Albumin_Delta',
 'ALP_Delta',
 'ALT_Delta',
 'AST_Delta',
 'Bilirubin_Delta',
 'BUN_Delta',
 'Cholesterol_Delta',
 'Creatinine_Delta',
 'HCO3_Delta',
 'HCT_Delta',
 'K_Delta',
 'Mg_Delta',
 'Na_Delta',
 'PaO2_Delta',
 'Platelets_Delta',
 'SaO2_Delta',
 'WBC_Delta',
 'Weight_Delta',
 'Troponin_Delta',
 'FiO2_Slope',
 'GCS_Slope',
 'Glucose_Slope',
 'HR_Slope',
 'PaCO2_Slope',
 'pH_Slope',
 'RespRate_Slope',
 'Temp_Slope',
 'Urine_Rate_Slope',
 'UniDiasABP_Slope',
 'UniMAP_Slope',
 'UniSysABP_Slope',
 'Albumin_Miss',
 'ALP_Miss',
 'ALT_Miss',
 'AST_Miss',
 'Bilirubin_Miss',
 'BUN_Miss',
 'Cholesterol_Miss',
 'Creatinine_Miss',
 'FiO2_Miss',
 'GCS_Miss',
 'Glucose_Miss',
 'HCO3_Miss',
 'HCT_Miss',
 'HR_Miss',
 'K_Miss',
 'Lactate_Miss',
 'MechVent_Miss',
 'Mg_Miss',
 'Na_Miss',
 'PaCO2_Miss',
 'PaO2_Miss',
 'pH_Miss',
 'Platelets_Miss',
 'RespRate_Miss',
 'SaO2_Miss',
 'Temp_Miss',
 'Urine_Miss',
 'WBC_Miss',
 'Weight_Miss',
 'UniDiasABP_Miss',
 'UniMAP_Miss',
 'UniSysABP_Miss',
 'Troponin_Miss',
 'Age',
 'Gender',
 'Height',
 'In-hospital_death',
 'ICUType_1.0',
 'ICUType_2.0',
 'ICUType_3.0',
 'ICUType_4.0',
 'Total_Obs_Count',
 'Total_Missing_Sum',
 'Albumin_Last_Gap',
 'ALP_Last_Gap',
 'ALT_Last_Gap',
 'AST_Last_Gap',
 'Bilirubin_Last_Gap',
 'BUN_Last_Gap',
 'Cholesterol_Last_Gap',
 'Creatinine_Last_Gap',
 'FiO2_Last_Gap',
 'GCS_Last_Gap',
 'Glucose_Last_Gap',
 'HCO3_Last_Gap',
 'HCT_Last_Gap',
 'HR_Last_Gap',
 'K_Last_Gap',
 'Lactate_Last_Gap',
 'MechVent_Last_Gap',
 'Mg_Last_Gap',
 'Na_Last_Gap',
 'PaCO2_Last_Gap',
 'PaO2_Last_Gap',
 'pH_Last_Gap',
 'Platelets_Last_Gap',
 'RespRate_Last_Gap',
 'SaO2_Last_Gap',
 'Temp_Last_Gap',
 'Urine_Last_Gap',
 'WBC_Last_Gap',
 'Weight_Last_Gap',
 'UniDiasABP_Last_Gap',
 'UniMAP_Last_Gap',
 'UniSysABP_Last_Gap',
 'Troponin_Last_Gap',
 'Global_Last_Gap',
 'Shock_Index',
 'GCS_MAP_Product',
 'Net_Cation_Balance']

In [118]:
col_order = ['Albumin_Initial',
 'Albumin_Min',
 'Albumin_Max',
 'Albumin_Mean',
 'ALP_Initial',
 'ALP_Max',
 'ALT_Initial',
 'ALT_Max',
 'AST_Initial',
 'AST_Max',
 'Bilirubin_Initial',
 'Bilirubin_Max',
 'BUN_Initial',
 'BUN_Max',
 'BUN_Mean',
 'BUN_Creatinine_Ratio',
 'Cholesterol_Initial',
 'Cholesterol_Min',
 'Creatinine_Initial',
 'Creatinine_Max',
 'Creatinine_Mean',
 'FiO2_Initial',
 'FiO2_Max',
 'FiO2_Mean',
 'GCS_Initial',
 'GCS_Final',
 'GCS_Min',
 'GCS_Max',
 'GCS_Mean',
 'Glucose_Initial',
 'Glucose_Min',
 'Glucose_Max',
 'Glucose_Mean',
 'HCO3_Initial',
 'HCO3_Final',
 'HCO3_Min',
 'HCO3_Max',
 'HCT_Initial',
 'HCT_Min',
 'HCT_Max',
 'HCT_Mean',
 'HR_Initial',
 'HR_Final',
 'HR_Min',
 'HR_Max',
 'HR_Mean',
 'HR_SD',
 'K_Initial',
 'K_Final',
 'K_Min',
 'K_Max',
 'K_Mean',
 'Lactate_Initial',
 'Lactate_Max',
 'Lactate_Clearance_Rate_6H',
 'Lactate_Clearance_Rate_12H',
 'MechVent_Any',
 'Mg_Initial',
 'Mg_Min',
 'Mg_Max',
 'Na_Initial',
 'Na_Final',
 'Na_Min',
 'Na_Max',
 'Na_Mean',
 'PaCO2_Initial',
 'PaCO2_Min',
 'PaCO2_Max',
 'PaO2_Initial',
 'PaO2_Min',
 'PaO2_FiO2_Ratio',
 'pH_Initial',
 'pH_Min',
 'pH_Max',
 'pH_Mean',
 'Platelets_Initial',
 'Platelets_Min',
 'RespRate_Initial',
 'RespRate_Max',
 'RespRate_Mean',
 'SaO2_Initial',
 'SaO2_Min',
 'Temp_Initial',
 'Temp_Min',
 'Temp_Max',
 'Temp_Mean',
 'Temp_SD',
 'Urine_Sum',
 'Urine_MinRate',
 'Urine_MaxRate',
 'Urine_MeanRate',
 'WBC_Initial',
 'WBC_Min',
 'WBC_Max',
 'Weight_Initial',
 'Weight_Final',
 'UniDiasABP_Initial',
 'UniDiasABP_Min',
 'UniDiasABP_Max',
 'UniDiasABP_Mean',
 'UniMAP_Initial',
 'UniMAP_Final',
 'UniMAP_Min',
 'UniMAP_Max',
 'UniMAP_Mean',
 'UniMAP_SD',
 'UniSysABP_Initial',
 'UniSysABP_Final',
 'UniSysABP_Min',
 'UniSysABP_Max',
 'UniSysABP_Mean',
 'UniSysABP_SD',
 'Troponin_Max',
 'Albumin_Log_Count',
 'ALP_Log_Count',
 'ALT_Log_Count',
 'AST_Log_Count',
 'BUN_Log_Count',
 'Bilirubin_Log_Count',
 'Cholesterol_Log_Count',
 'Creatinine_Log_Count',
 'FiO2_Log_Count',
 'GCS_Log_Count',
 'Glucose_Log_Count',
 'HCO3_Log_Count',
 'HCT_Log_Count',
 'HR_Log_Count',
 'K_Log_Count',
 'Lactate_Log_Count',
 'MechVent_Log_Count',
 'Mg_Log_Count',
 'Na_Log_Count',
 'PaCO2_Log_Count',
 'PaO2_Log_Count',
 'pH_Log_Count',
 'Platelets_Log_Count',
 'RespRate_Log_Count',
 'SaO2_Log_Count',
 'Temp_Log_Count',
 'Urine_Log_Count',
 'WBC_Log_Count',
 'UniDiasABP_Log_Count',
 'UniMAP_Log_Count',
 'UniSysABP_Log_Count',
 'Troponin_Log_Count',
 'Albumin_Delta',
 'ALP_Delta',
 'ALT_Delta',
 'AST_Delta',
 'Bilirubin_Delta',
 'BUN_Delta',
 'Cholesterol_Delta',
 'Creatinine_Delta',
 'HCO3_Delta',
 'HCT_Delta',
 'K_Delta',
 'Mg_Delta',
 'Na_Delta',
 'PaO2_Delta',
 'Platelets_Delta',
 'SaO2_Delta',
 'WBC_Delta',
 'Weight_Delta',
 'Troponin_Delta',
 'FiO2_Slope',
 'GCS_Slope',
 'Glucose_Slope',
 'HR_Slope',
 'PaCO2_Slope',
 'pH_Slope',
 'RespRate_Slope',
 'Temp_Slope',
 'Urine_Rate_Slope',
 'UniDiasABP_Slope',
 'UniMAP_Slope',
 'UniSysABP_Slope',
 'Albumin_Miss',
 'ALP_Miss',
 'ALT_Miss',
 'AST_Miss',
 'Bilirubin_Miss',
 'BUN_Miss',
 'Cholesterol_Miss',
 'Creatinine_Miss',
 'FiO2_Miss',
 'GCS_Miss',
 'Glucose_Miss',
 'HCO3_Miss',
 'HCT_Miss',
 'HR_Miss',
 'K_Miss',
 'Lactate_Miss',
 'MechVent_Miss',
 'Mg_Miss',
 'Na_Miss',
 'PaCO2_Miss',
 'PaO2_Miss',
 'pH_Miss',
 'Platelets_Miss',
 'RespRate_Miss',
 'SaO2_Miss',
 'Temp_Miss',
 'Urine_Miss',
 'WBC_Miss',
 'Weight_Miss',
 'UniDiasABP_Miss',
 'UniMAP_Miss',
 'UniSysABP_Miss',
 'Troponin_Miss',
 'Albumin_Last_Gap',
 'ALP_Last_Gap',
 'ALT_Last_Gap',
 'AST_Last_Gap',
 'Bilirubin_Last_Gap',
 'BUN_Last_Gap',
 'Cholesterol_Last_Gap',
 'Creatinine_Last_Gap',
 'FiO2_Last_Gap',
 'GCS_Last_Gap',
 'Glucose_Last_Gap',
 'HCO3_Last_Gap',
 'HCT_Last_Gap',
 'HR_Last_Gap',
 'K_Last_Gap',
 'Lactate_Last_Gap',
 'MechVent_Last_Gap',
 'Mg_Last_Gap',
 'Na_Last_Gap',
 'PaCO2_Last_Gap',
 'PaO2_Last_Gap',
 'pH_Last_Gap',
 'Platelets_Last_Gap',
 'RespRate_Last_Gap',
 'SaO2_Last_Gap',
 'Temp_Last_Gap',
 'Urine_Last_Gap',
 'WBC_Last_Gap',
 'Weight_Last_Gap',
 'UniDiasABP_Last_Gap',
 'UniMAP_Last_Gap',
 'UniSysABP_Last_Gap',
 'Troponin_Last_Gap',
 'Global_Last_Gap',
 'Total_Obs_Count',
 'Total_Missing_Sum',
 'Shock_Index',
 'GCS_MAP_Product',
 'Net_Cation_Balance',
 'Age',
 'Gender',
 'Height',
 'ICUType_1.0',
 'ICUType_2.0',
 'ICUType_3.0',
 'ICUType_4.0',
  'In-hospital_death']

In [119]:
df = df[col_order]

In [120]:
df.head(20)

,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Log_Count,ALP_Log_Count,ALT_Log_Count,AST_Log_Count,BUN_Log_Count,Bilirubin_Log_Count,Cholesterol_Log_Count,Creatinine_Log_Count,FiO2_Log_Count,GCS_Log_Count,Glucose_Log_Count,HCO3_Log_Count,HCT_Log_Count,HR_Log_Count,K_Log_Count,Lactate_Log_Count,MechVent_Log_Count,Mg_Log_Count,Na_Log_Count,PaCO2_Log_Count,PaO2_Log_Count,pH_Log_Count,Platelets_Log_Count,RespRate_Log_Count,SaO2_Log_Count,Temp_Log_Count,Urine_Log_Count,WBC_Log_Count,UniDiasABP_Log_Count,UniMAP_Log_Count,UniSysABP_Log_Count,Troponin_Log_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Gap,ALP_Last_Gap,ALT_Last_Gap,AST_Last_Gap,Bilirubin_Last_Gap,BUN_Last_Gap,Cholesterol_Last_Gap,Creatinine_Last_Gap,FiO2_Last_Gap,GCS_Last_Gap,Glucose_Last_Gap,HCO3_Last_Gap,HCT_Last_Gap,HR_Last_Gap,K_Last_Gap,Lactate_Last_Gap,MechVent_Last_Gap,Mg_Last_Gap,Na_Last_Gap,PaCO2_Last_Gap,PaO2_Last_Gap,pH_Last_Gap,Platelets_Last_Gap,RespRate_Last_Gap,SaO2_Last_Gap,Temp_Last_Gap,Urine_Last_Gap,WBC_Last_Gap,Weight_Last_Gap,UniDiasABP_Last_Gap,UniMAP_Last_Gap,UniSysABP_Last_Gap,Troponin_Last_Gap,Global_Last_Gap,Total_Obs_Count,Total_Missing_Sum,Shock_Index,GCS_MAP_Product,Net_Cation_Balance,Age,Gender,Height,ICUType_1.0,ICUType_2.0,ICUType_3.0,ICUType_4.0,In-hospital_death
0,2.3,2.2,2.3,2.266667,84.0,84.0,20.0,20.0,123.0,123.0,6.6,11.2,7.0,7.0,5.500000,10.000000,NaN,NaN,0.9,0.9,0.675000,1.0,1.0,0.655556,3.0,7.0,3.0,7.0,5.615385,101.0,88.0,173.0,127.500000,22.0,25.0,22.0,25.0,29.7,26.6,29.7,28.416667,109.0,106.0,88.0,139.0,109.265625,12.787943,4.0,4.6,3.6,4.6,4.060000,1.5,1.8,0.000000,-20.000000,1.0,2.2,1.7,2.2,136.0,136.0,136.0,139.0,136.750000,40.0,39.0,51.0,187.0,73.0,121.666667,7.39,7.29,7.42,7.361429,85.0,71.0,NaN,NaN,NaN,NaN,NaN,37.6,36.3,38.9,37.329412,0.645041,2763.0,0.167785,3.775168,0.934510,13.3,9.3,13.3,59.60,59.6,60.0,38.0,77.0,59.859375,69.00,86.00,48.00,95.00,75.156250,8.942885,97.0,123.0,82.0,131.0,108.609375,10.529802,0.40,1.386294,1.386294,1.386294,1.386294,1.609438,1.386294,0.000000,1.609438,2.944439,2.639057,1.609438,1.609438,1.945910,4.174387,1.791759,1.945910,2.944439,1.609438,1.609438,2.079442,2.079442,2.079442,1.609438,0.000000,0.000000,3.555348,3.610918,1.609438,4.174387,4.174387,4.174387,1.386294,0.0,-29.0,-6.0,-53.0,4.6,-1.0,0.0,-0.3,3.0,-3.1,0.6,-0.2,0.0,-50.0,9.0,0.0,-4.0,0.00,-0.18,-0.000198,0.000168,0.044188,-0.010776,0.000673,0.000002,0.000000,-0.000355,-2.380140,-0.001739,0.002434,0.004666,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,767.0,767.0,767.0,767.0,767.0,767.0,2880.0,767.0,61.0,91.0,767.0,767.0,81.0,31.0,767.0,77.0,61.0,767.0,767.0,137.0,137.0,137.0,81.0,2880.0,2880.0,31.0,31.0,81.0,31.0,31.0,31.0,31.0,1560.0,31.0,463.0,3.0,0.861789,602.00,115.6,22.0,0.0,167.6,0,0,1,0,0
1,2.2,2.2,2.2,2.200000,37.0,37.0,112.0,112.0,453.0,453.0,1.1,1.1,12.0,20.0,15.666667,20.000000,NaN,NaN,0.7,1.0,0.866667,1.0,1.0,0.500000,3.0,8.0,3.0,11.0,6.000000,199.0,105.0,234.0,170.600000,20.0,23.0,20.0,23.0,33.9,30.3,38.6,33.360000,99.0,96.0,71.0,117.0,97.528090,10.956619,2.9,5.9,2.9,5.9,4.400000,9.7,9.7,0.000000,4.123711,1.0,2.7,1.8,2.7,143.0,137.0,137.0,143.0,139.333333,44.0,33.0,69.0,310.0,73.0,110.000000,7.35,7.10,7.44,7.351500,123.0,92.0,NaN,NaN,NaN,98.0,96.0,34.7,34.7,37.6,36.679070,0.664232,3987.0,0.190721,5.085892,0.782265,27.1,16.8,27.1,72.60,98.9,54.0,29.0,90.0,48.739130,72.00,71.00,35.00,127.00,76.633333,16.502945,117.0,108.0,44.0,175.0,117.000000,25.219912,NaN,0.693147,0.693147,0.693147,0.693147,1.386294,0.693147,0.000000,1.386294,2.708050,2.397895,1.791759,1.386294,1.791759,4.499810,1.791759,2.772589,2.833213,1.098612,1.386294,2.995732,2.995732,3.044522,1.945910,0.000000,2.197225,4.465908,3.891820,1.609438,4.532599,4.510860,4.532599,0.000000,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.3,3.0,-1.0,3.0,-0.9,-6.0,-216.0,-24.0,1.0,-6.5,26.30,0.00,-0.000141,0.002588,-0.062102,-0.006374,-0.004262,0.000056,0.000000,0.000645,-1.168270,-0.002770,-0.002166,0.002073,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1930.0,1930.0,1930.0,1930.0,1930.0,691.0,2880.0,691.0,76.0,76.0,442.0,691.0,691.0,16.0,442.0,270.0,76.0,691.0,691.0,123.0,123.0,123.0,691.0,2880.0,76.0,16.0,16.0,691.0,16.0,16.0,16.0,16.0,2880.0,16.0,662.0,3.0,0.888889,568.00,119.9,72.0,1.0,177.8,0,1,0,0,0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,12.0,9.666667,20.000000,NaN,NaN,0.6,0.6,0.533333,NaN,NaN,NaN,15.0,15.0,15.0,15.0,15.000000,105.0,105.0,154.0,124.666667,28.0,24.0,24.0,28.0,32.2,27.1,32.5,30.075000,86.0,78.0,78.0,111.0,89.170732,8.731845,3.3,3.5,3.3,3.7,3.475000,0.8,0.8,0.000000,0.000000,NaN,1.3,1.3,2.1,133.0,132.0,132.0,134.0,133.000000,41.0,39.0,51.0,267.0,95.0,NaN,7.43,7.35,7.43,7.398000,346.0,290.0,NaN,NaN,NaN,97.0,96.0,36.6,35.6,38.2,37.000000,0.629574,7140.0,0.083333,5.333333,1.997873,9.9,9.9,13.5,75.00,75.0,55.0,41.0,62.0,51.365854,80.33,73.00,60.00,83.33,70.861463,5.859821,131.0,117.0,80.0,131.0,106.853659,11.529443,0.30,0.000000,0.000000,0.000000,0.000000,1.386294,0.000000,0.000000,1.386294,0.000000,2.484907,1.386294,1.386294,1.609438,3.737670,1.609438,1.386294,0.000000,1.386294,1.386294,1.791759,1.791759,1.791759,1.386294,0.000000,1.098612,2.564949,3.526361,1.386294,3.737670,3.737670,3.737670,0.693147,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,-0.2,-4.0,0.3,0.2,0.8,-1.0,-170.0,-56.0,-1.0,0.7,0.00,0.00,0.000000,0.000000,0.037484,0.002859,-0.004726,0.000020,0.000000,0.000136,-30.023855,0.000029,-0.000678,-0.005132,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2880.0,2880.0,2880.0,2880.0,2880.0,717.0,2880.0,717.0,2880.0,34.0,717.0,717.0,256.0,34.0,256.0,740.0,2880.0,256.0,717.0,740.0,740.0,740.0,717.0,2880.0,763.0,214.0,34.0,717.0,34.0,34.0,34.0,34.0,1564.0,34.0,273.0,9.0,0.666667,1095.00,111.5,61.0,1.0,NaN,1,0,0,0,0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,20.0,14.666667,18.571429,NaN,NaN,0.6,1.1,0.800000,1.0,1.0,0.625000,3.0,15.0,3.0,15.0,12.142857,118.0,118.0,125.0,121.500000,27.0,29.0,27.0,29.0,28.9,27.4,31.9,29.600000,60.0,90.0,60.0,90.0,78.971429,7.014631,4.3,4.2,4.2,4.3,4.250000,NaN,NaN,NaN,NaN,1.0,2.2,2.2,2.2,137.0,136.0,136.0,137.0,136.500000,35.0,35.0,53.0,484.0,108.0,216.000000,7.52,7.34,7.52,7.402500,67.0,67.0,NaN,NaN,NaN,98.0,97.0,36.5,35.9,37.8,37.064000,0.672607,2847.0,0.323728,6.474564,1.221307,7.4,7.4,14.8,75.11,80.0,58.0,42.0,69.0,59.857143,75.00,72.00,55.67,89.00,76.076286,7.717743,107.0,106.0,83.0,127.0,107.600000,11.151892,NaN,0.000000,0.000000,0.000000,0.000000,1.386294,0.000000,0.000000,1.386294,1.609438,2.079442,1.098612,1.386294,1.609438,3.583519,1.098612,0.000000,1.945910,0.693147,1.098612,2.197225,2.197225,2.197225,1.609438,0.000000,1.609438,3.258097,3.091042,1.609438,3.583519,3.583519,3.583519,0.000000,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.5,2.0,-1.5,-0.1,0.0,-1.0,-366.0,5.0,-1.0,2.6,4.89,0.00,-0.001389,0.003582,0.004263,0.005479,0.011597,-0.000120,0.000000,0.001512,-169.160598,-0.001257,-0.001943,-0.001591,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2880.0,2880.0,2880.0,2880.0,2880.0,432.0,2880.0,432.0,2409.0,179.0,432.0,432.0,432.0,49.0,432.0,2880.0,1549.0,2074.0,432.0,2008.0,2008.0,2008.0,432.0,2880.0,2008.0,1669.0,1429.0,432.0,49.0,49.0,49.0,49.0,2880.0,49.0,259.0,9.0,0.849057,1080.00,111.2,67.0,1.0,167.6,0,1,0,0,0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,13.0,12.000000,16.250000,NaN,NaN,0.8,0.8,0.766667,NaN,NaN,NaN,15.0,15.0,15.0,15.0,15.000000,267.0,175.0,267.0,220.500000,30.0,21.0,21.0,30.0,39.3,35.3,39.3,37.300000,73.0,83.0,54.0,84.0,69.428571,7.496805,2.8,4.6,2.8,5.0,3.820000,NaN,NaN,NaN,NaN,NaN,1.9,1.9,1.9,137.0,137.0,136.0,140.0,137.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,308.0,237.0,19.0,26.0,18.550000,NaN,NaN,36.6,36.0,37.1,36.654545,0.353167,4595.0,0.465549,3.491620,2.024611,8.9,7.3,8.9,71.60,71.6,66.0,50.0,93.0,70.027778,83.00,105.30,70.00,115.70,87.748056,11.373784,117.0,130.0,96.0,165.0,123.194444,15.863380,NaN,0.000000,0.000000,0.000000,0.000000,1.386294,0.000000,0.000000,1.386294,0.000000,2.564949,1.609438,1.609438,1.098612,3.761200,1.791759,0.000000,0.000000,1.098612,1.609438,0.000000,0.000000,0.000000,1.098612,3.713572,0.000000,2.484907,2.564949,1.098612,3.610918,3.610918,3.610918,0.000000,0.0,0.0,0.0,0.0,0.0,-2.0,0.0,-0.1,-9.0,-4.0,1.8,0.0,0.0,0.0,-71.0,0.0,-1.6,0.00,0.00,0.000000,0.000000,0.000593,-0.002046,0.000000,0.000000,0.000053,0.000018,3.267020,0.009731,0.010702,0.012650,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2880.0,2880.0,2880.0,2880.0,2880.0,1264.0,2880.0,1264.0,2880.0,124.0,1264.0,1264.0,1264.0,124.0,1264.0,2880.0,2880.0,1264.0,1264.0,2880.0,2880.0,2880.0,1264.0,124.0,2880.0,124.0,244.0,1264.0,124.0,124.0,124.0,124.0,2880.0,124.0,256.0,14.0,0.638462,1579.50,120.6,50.0,0.0,NaN,0,0,1,0,0
5,3.0,3.0,3.0,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,34.0,26.333333,30.909091,NaN,NaN,0.8,1.2,1.033333,1.0,1.0,0.511765,3.0,14.0,3.0,14.0,9.500000,177.0,98.0,177.0,129.666667,26.0,22.0,22.0,26.0,38.1,37.3,39.9,38.425000,72.0,101.0,72.0,115.0,96.434783,10.177077,4.5,4.1,4.1,4.5,4.366667,4.9,4.9,69.387755,69.387755,1.0,1.4,1.4,2.7,141.0,143.0,140.0,143.0,141.333333,43.0,38.0,55.0,433.0,61.0,101.666667,7.40,7.24,7.42,7.326000,154.0,149.0,NaN,NaN,NaN,96.0,91.0,35.1,35.1,38.1,36.600000,0.810350,3387.0,0.000000,3.384419,0.674023,9.3,9.3,17.1,75.00,73.1,75.0,44.0,84.0,60.938144,99.00,78.00,60.00,114.00,83.868852,10.387493,136.0,110.0,93.0,167.0,125.061856,15.341131,NaN,0.693147,0.000000,0.000000,0.000000,1.386294,0.000000,0.000000,1.386294,2.890372,2.564949,1.386294,1.386294,1.609438,4.248495,1.386294,1.791759,2.564949,1.386294,1.386294,2.772589,2.772589,2.772589,1.386294,0.000000,2.197225,2.639057,3.871201,1.386294,4.584967,4.812184,4.584967,0.000000,0.0,0.0,0.0,0.0,0.0,16.0,0.0,0.3,-4.0,0.3,-0.4,0.9,2.0,-372.0,-5.0,-5.0,7.8,-1.90,0.00,-0.000076,0.005446,-0.034969,0.007912,0.000562,-0.000052,0.000000,0.000159,-6.997156,-0.002798,0.000864,0.000644,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,714.0,2880.0,2880.0,2880.0,2880.0,714.0,2880.0,714.0,158.0,218.0,714.0,714.0,714.0,38.0,714.0,525.0,158.0,714.0,714.0,263.0,263.0,263.0,714.0,2880.0,263.0,218.0,38.0,714.0,38.0,38.0,38.0,38.0,2880.0,38.0,576.0,7.0,0.918182,1092.00,125.1,83.0,0.0,152.4,0,1,0,0,0
6,2.4,2.4,2.5,2.450000,38.0,46.0,14.0,14.0,33.0,33.0,0.7,0.7,24.0,24.0,20.666667,19.000000,NaN,NaN,1.5,1.5,1.233333,0.6,1.0,0.612500,3.0,3.0,3.0,11.0,5.416667,142.0,132.0,166.0,151.166667,16.0,17.0,13.0,18.0,40.5,27.6,40.5,34.800000,84.0,61.0,50.0,128.0,76.820513,14.851423,3.9,4.1,3.9,5.1,4.533333,7.2,8.9,-2.777778,-5.555556,1.0,2.6,1.7,2.6,136.0,131.0,127.0,137.0,132.500000,46.0,27.0,46.0,122.0,90.0,106.000000,7.26,7.22,7.48,7.318824,151.0,86.0,NaN,NaN,NaN,NaN,NaN,36.7,35.9,37.7,36.642857,0.578744,4360.0,0.304878,2.195122,1.082225,10.9,10.9,22.9,82.00,82.0,35.0,34.0,72.0,49.151515,48.00,83.00,43.00,102.00,69.422680,12.612688,79.0,136.0,60.0,173.0,122.111111,24.955016,0.10,1.098612,1.098612,1.098612,1.098612,1.945910,1.098612,0.000000,1.945910,2.833213,2.564949,1.945910,1.945910,2.079442,4.369448,1.945910,2.833213,2.833213,1.945910,1.945910,2.890372,2.890372,2.890372,1.945910,0.000000,0.000000,2.708050,3.850148,1.945910,4.605170,4.584967,4.605170,1.098612,0.1,8.0,-3.0,-11.0,0.0,-5.0,0.0,-0.5,1.0,-12.9,0.2,-0.6,-5.0,31.0,-65.0,0.0,5.5,0.00,-0.01,-0.000121,-0.002657,-0.001532,-0.011733,-0.004719,0.000089,0.000000,-0.000476,-1.170791,0.007026,0.008783,0.014085,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,506.0,506.0,506.0,506.0,506.0,506.0,2880.0,506.0,47.0,167.0,506.0,506.0,274.0,47.0,506.0,190.0,47.0,506.0,506.0,190.0,190.0,190.0,506.0,2880.0,2880.0,167.0,47.0,506.0,2880.0,47.0,47.0,47.0,2176.0,47.0,617.0,3.0,0.448529,249.00,118.1,90.0,1.0,NaN,0,0,0,1,0
7,NaN,NaN,NaN,NaN,82.0,82.0,67.0,67.0,265.0,265.0,NaN,NaN,13.0,15.0,14.000000,16.250000,211.0,211.0,0.8,1.0,0.900000,NaN,NaN,NaN,15.0,15.0,14.0,15.0,14.916667,126.0,107.0,126.0,116.500000,26.0,28.0,26.0,28.0,44.0,43.0,44.6,43.866667,64.0,79.0,64.0,87.0,73.900000,4.601003,4.0,4.3,4.0,4.3,4.133333,NaN,NaN,NaN,NaN,NaN,2.2,2.2,2.4,140.0,137.0,137.0,140.0,138.500000,39.0,39.0,39.0,71.0,71.0,NaN,7.40,7.40,7.40,7.400000,182.0,182.0,16.0,27.0,18.815789,97.0,97.0,37.7,36.1,37.9,37.175000,0.552885,4425.0,0.000000,1.616162,0.885943,10.5,9.9,10.5,99.00,99.0,70.0,37.0,88.0,62.428571,91.67,74.33,56.67,163.00,82.258000,19.862872,135.0,105.0,90.0,158.0,113.971429,17.114641,NaN,0.000000,0.693147,0.693147,0.693147,1.098612,0.000000,0.693147,1.098612,0.000000,2.564949,1.098612,1.098612,1.386294,3.713572,1.386294,0.000000,0.000000,1.386294,1.098612,0.693147,0.693147,0.693147,1.386294,3.663562,0.693147,2.564949,3.178054,1.098612,3.583519,3.583519,3.583519,0.000000,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.2,2.0,-1.0,0.3,0.0,-3.0,0.0,1.0,0.0,-0.6,0.00,0.00,0.000000,0.000081,-0.013514,0.002558,0.000000,0.000000,0.000379,0.000127,-10.738557,-0.007456,-0.012445,-0.012624,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2880.0,2395.0,2395.0,2395.0,2880.0,989.0,2395.0,989.0,2880.0,100.0,989.0,989.0,989.0,100.0,989.0,2880.0,2880.0,989.0,989.0,2764.0,2764.0,2764.0,989.0,100.0,2800.0,100.0,40.0,989.0,100.0,100.0,100.0,100.0,2880.0,40.0,262.0,6.0,0.752381,1114.95,113.3,66.0,1.0,175.3,1,0,0,0,0
8,NaN,NaN,NaN,NaN,38.0,38.0,71.0,71.0,63.0,63.0,NaN,NaN,16.0,16.0,15.333333,17.777778,NaN,NaN,1.2,1.2,1.033333,NaN,NaN,NaN,15.0,15.0,13.0,15.0,14.785714,150.0,107.0,150.0,123.666667,26.0,30.0,26.0,30.0,35.6,30.6,35.6,32.700000,88.0,94.0,79.0,102.0,90.033333,6.300300,4.4,3.8,3.8,4.4,4.033333,NaN,NaN,NaN,NaN,NaN,1.8,1.8,2.1,141.0,138.0,138.0,141.0,139.333333,NaN,NaN,NaN,NaN,NaN,NaN,7.42,7.42,7.42,7.420000,162.0,148.0,15.0,29.0,16.901639,NaN,NaN,35.7,35.3,37.9,37.033333,0.943237,4365.0,0.375000,3.750000,1.259146,8.9,6.5,8.9,80.00,80.0,61.0,50.0,80.0,61.672131,71.00,85.00,60.00,109.00,78.803279,12.748620,113.0,122.0,81.0,148.0,108.885246,18.430137,NaN,0.000000,0.693147,0.693147,0.693147,1.386294,0.000000,0.000000,1.386294,0.000000,2.708050,1.386294,1.386294,1.386294,4.110874,1.386294,0.000000,0.000000,1.386294,1.386294,0.000000,0.000000,0.693147,1.386294,4.127134,0.000000,2.564949,3.761200,1.386294,4.127134,4.127134,4.127134,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.3,4.0,-5.0,-0.6,0.2,-3.0,0.0,-14.0,0.0,-2.4,0.00,0.00,0.000000,-0.000125,-0.017216,0.005135,0.000000,0.000000,0.002784,0.000931,0.422173,0.002028,0.004095,0.007874,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2880.0,1767.0,1767.0,1767.0,2880.0,357.0,2880.0,357.0,2880.0,227.0,357.0,357.0,357.0,47.0,357.0,2880.0,2880.0,357.0,357.0,2880.0,2880.0,1388.0,357.0,47.0,2880.0,167.0,107.0,357.0,2880.0,47.0,47.0,47.0,2880.0,47.0,406.0,10.0,0.770492,1275.00,111.8,61.0,1.0,NaN,0,0,0,1,0
9,3.1,3.1,3.1,3.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0,11.500000,30.000000,NaN,NaN,0.4,0.6,0.550000,1.0,1.0,0.550000,8.0,10.0,7.0,11.0,8.545455,117.0,111.0,129.0,119.750000,22.0,27.0,22.0,27.0,34.8,30.1,34.8,32.975000,80.0,68.0,62.0,91.0,75.260000,8.095880,3.7,3.8,3.6,4.0,3.800000,1.2,2.1,NaN,NaN,1.0,1.6,1.6,2.0,134.0,141.0,134.0,141.0,136.750000,44.0,44.0,49.0,74.0,62.0,62.000000,7.42,7.35,7.44,7.398750,157.0,157.0,NaN,NaN,NaN,NaN,NaN,36.9,36.9,38.3,37.933333,0.373529,8200.0,0.694444,3.240741,1.670139,15.4,11.2,15.4,108.00,108.0,64.0,52.0,86.0,67.365385,87.00,94.00,68.00,101.00,88.916731,7.029892,133.0,146.0,95.0,159.0,131.884615,12.920047,NaN,0.693147,0.000000,0.000000,0.000000,1.609438,0.000000,0.000000,1.609438,2.708050,3.135494,1.609438,1.609438,1.609438,3.931826,1.791759,1.098612,2.772589,1.609438,1.609438,2.197225,2.197225,2.197225,1.609438,0.000000,0.000000,2.772589,3.663562,1.609438,3.970292,3.970292,3.970292,0.000000,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.2,5.0,-4.7,0.1,0.4,7.0,59.0,16.0,0.0,-4.2,0.00,0.00,-0.000148,0.001270,0.007430,0.005173,0.000763,0.000033,0.000000,0.000151,-70.785182,0.002558,0.004990,0.010517,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2779.0,2880.0,2880.0,2880.0,2880.0,742.0,2880.0,742.0,332.0,22.0,742.0,742.0,742.0,22.0,667.0,2607.0,332.0,742.0,742.0,799.0,799.0,799.0,742.0,2880.0,2880.0,22.0,22.0,742.0,2880.0,22.0,22.0,22.0,2880.0,22.0,378.0,8.0,0.465753,940.00,117.8,59.0,1.0,NaN,0,0,0,1,0

In [121]:
df.shape

(11986, 256)

In [122]:
df.dtypes

Albumin_Initial               float64
Albumin_Min                   float64
Albumin_Max                   float64
Albumin_Mean                  float64
ALP_Initial                   float64
ALP_Max                       float64
ALT_Initial                   float64
ALT_Max                       float64
AST_Initial                   float64
AST_Max                       float64
Bilirubin_Initial             float64
Bilirubin_Max                 float64
BUN_Initial                   float64
BUN_Max                       float64
BUN_Mean                      float64
BUN_Creatinine_Ratio          float64
Cholesterol_Initial           float64
Cholesterol_Min               float64
Creatinine_Initial            float64
Creatinine_Max                float64
Creatinine_Mean               float64
FiO2_Initial                  float64
FiO2_Max                      float64
FiO2_Mean                     float64
GCS_Initial                   float64
GCS_Final                     float64
GCS_Min                       float64
GCS_Max                       float64
GCS_Mean                      float64
Glucose_Initial               float64
Glucose_Min                   float64
Glucose_Max                   float64
Glucose_Mean                  float64
HCO3_Initial                  float64
HCO3_Final                    float64
HCO3_Min                      float64
HCO3_Max                      float64
HCT_Initial                   float64
HCT_Min                       float64
HCT_Max                       float64
HCT_Mean                      float64
HR_Initial                    float64
HR_Final                      float64
HR_Min                        float64
HR_Max                        float64
HR_Mean                       float64
HR_SD                         float64
K_Initial                     float64
K_Final                       float64
K_Min                         float64
K_Max                         float64
K_Mean                        float64
Lactate_Initial               float64
Lactate_Max                   float64
Lactate_Clearance_Rate_6H     float64
Lactate_Clearance_Rate_12H    float64
MechVent_Any                  float64
Mg_Initial                    float64
Mg_Min                        float64
Mg_Max                        float64
Na_Initial                    float64
Na_Final                      float64
Na_Min                        float64
Na_Max                        float64
Na_Mean                       float64
PaCO2_Initial                 float64
PaCO2_Min                     float64
PaCO2_Max                     float64
PaO2_Initial                  float64
PaO2_Min                      float64
PaO2_FiO2_Ratio               float64
pH_Initial                    float64
pH_Min                        float64
pH_Max                        float64
pH_Mean                       float64
Platelets_Initial             float64
Platelets_Min                 float64
RespRate_Initial              float64
RespRate_Max                  float64
RespRate_Mean                 float64
SaO2_Initial                  float64
SaO2_Min                      float64
Temp_Initial                  float64
Temp_Min                      float64
Temp_Max                      float64
Temp_Mean                     float64
Temp_SD                       float64
Urine_Sum                     float64
Urine_MinRate                 float64
Urine_MaxRate                 float64
Urine_MeanRate                float64
WBC_Initial                   float64
WBC_Min                       float64
WBC_Max                       float64
Weight_Initial                float64
Weight_Final                  float64
UniDiasABP_Initial            float64
UniDiasABP_Min                float64
UniDiasABP_Max                float64
UniDiasABP_Mean               float64
UniMAP_Initial                float64
UniMAP_Final                  float64
UniMAP_Min                    float64
UniMAP_Max                    float64
UniMAP_Mean                   float64
UniMAP_SD                     float64
UniSysABP_Initial             float64
UniSysABP_Final               float64
UniSysABP_Min                 float64
UniSysABP_Max                 float64
UniSysABP_Mean                float64
UniSysABP_SD                  float64
Troponin_Max                  float64
Albumin_Log_Count             float64
ALP_Log_Count                 float64
ALT_Log_Count                 float64
AST_Log_Count                 float64
BUN_Log_Count                 float64
Bilirubin_Log_Count           float64
Cholesterol_Log_Count         float64
Creatinine_Log_Count          float64
FiO2_Log_Count                float64
GCS_Log_Count                 float64
Glucose_Log_Count             float64
HCO3_Log_Count                float64
HCT_Log_Count                 float64
HR_Log_Count                  float64
K_Log_Count                   float64
Lactate_Log_Count             float64
MechVent_Log_Count            float64
Mg_Log_Count                  float64
Na_Log_Count                  float64
PaCO2_Log_Count               float64
PaO2_Log_Count                float64
pH_Log_Count                  float64
Platelets_Log_Count           float64
RespRate_Log_Count            float64
SaO2_Log_Count                float64
Temp_Log_Count                float64
Urine_Log_Count               float64
WBC_Log_Count                 float64
UniDiasABP_Log_Count          float64
UniMAP_Log_Count              float64
UniSysABP_Log_Count           float64
Troponin_Log_Count            float64
Albumin_Delta                 float64
ALP_Delta                     float64
ALT_Delta                     float64
AST_Delta                     float64
Bilirubin_Delta               float64
BUN_Delta                     float64
Cholesterol_Delta             float64
Creatinine_Delta              float64
HCO3_Delta                    float64
HCT_Delta                     float64
K_Delta                       float64
Mg_Delta                      float64
Na_Delta                      float64
PaO2_Delta                    float64
Platelets_Delta               float64
SaO2_Delta                    float64
WBC_Delta                     float64
Weight_Delta                  float64
Troponin_Delta                float64
FiO2_Slope                    float64
GCS_Slope                     float64
Glucose_Slope                 float64
HR_Slope                      float64
PaCO2_Slope                   float64
pH_Slope                      float64
RespRate_Slope                float64
Temp_Slope                    float64
Urine_Rate_Slope              float64
UniDiasABP_Slope              float64
UniMAP_Slope                  float64
UniSysABP_Slope               float64
Albumin_Miss                  float64
ALP_Miss                      float64
ALT_Miss                      float64
AST_Miss                      float64
Bilirubin_Miss                float64
BUN_Miss                      float64
Cholesterol_Miss              float64
Creatinine_Miss               float64
FiO2_Miss                     float64
GCS_Miss                      float64
Glucose_Miss                  float64
HCO3_Miss                     float64
HCT_Miss                      float64
HR_Miss                       float64
K_Miss                        float64
Lactate_Miss                  float64
MechVent_Miss                 float64
Mg_Miss                       float64
Na_Miss                       float64
PaCO2_Miss                    float64
PaO2_Miss                     float64
pH_Miss                       float64
Platelets_Miss                float64
RespRate_Miss                 float64
SaO2_Miss                     float64
Temp_Miss                     float64
Urine_Miss                    float64
WBC_Miss                      float64
Weight_Miss                   float64
UniDiasABP_Miss               float64
UniMAP_Miss                   float64
UniSysABP_Miss                float64
Troponin_Miss                 float64
Albumin_Last_Gap              float64
ALP_Last_Gap                  float64
ALT_Last_Gap                  float64
AST_Last_Gap                  float64
Bilirubin_Last_Gap            float64
BUN_Last_Gap                  float64
Cholesterol_Last_Gap          float64
Creatinine_Last_Gap           float64
FiO2_Last_Gap                 float64
GCS_Last_Gap                  float64
Glucose_Last_Gap              float64
HCO3_Last_Gap                 float64
HCT_Last_Gap                  float64
HR_Last_Gap                   float64
K_Last_Gap                    float64
Lactate_Last_Gap              float64
MechVent_Last_Gap             float64
Mg_Last_Gap                   float64
Na_Last_Gap                   float64
PaCO2_Last_Gap                float64
PaO2_Last_Gap                 float64
pH_Last_Gap                   float64
Platelets_Last_Gap            float64
RespRate_Last_Gap             float64
SaO2_Last_Gap                 float64
Temp_Last_Gap                 float64
Urine_Last_Gap                float64
WBC_Last_Gap                  float64
Weight_Last_Gap               float64
UniDiasABP_Last_Gap           float64
UniMAP_Last_Gap               float64
UniSysABP_Last_Gap            float64
Troponin_Last_Gap             float64
Global_Last_Gap               float64
Total_Obs_Count               float64
Total_Missing_Sum             float64
Shock_Index                   float64
GCS_MAP_Product               float64
Net_Cation_Balance            float64
Age                           float64
Gender                        float64
Height                        float64
ICUType_1.0                     int64
ICUType_2.0                     int64
ICUType_3.0                     int64
ICUType_4.0                     int64
In-hospital_death               int64
dtype: object

In [123]:
(df.isnull().sum()/len(df)*100).sort_values(ascending=False)

Cholesterol_Min               92.090773
Cholesterol_Initial           92.090773
Troponin_Max                  73.293843
RespRate_Initial              72.284332
RespRate_Max                  72.234273
RespRate_Mean                 72.234273
Lactate_Clearance_Rate_12H    69.005506
Lactate_Clearance_Rate_6H     65.109294
Albumin_Max                   59.360921
Albumin_Mean                  59.360921
Albumin_Initial               59.360921
Albumin_Min                   59.360921
ALP_Initial                   57.475388
ALP_Max                       57.475388
AST_Initial                   56.515935
Bilirubin_Initial             56.507592
Bilirubin_Max                 56.507592
ALT_Initial                   56.507592
ALT_Max                       56.507592
AST_Max                       56.499249
SaO2_Initial                  55.297847
SaO2_Min                      55.264475
Height                        47.780744
Lactate_Initial               45.135992
Lactate_Max                   45.135992
MechVent_Any                  36.759553
PaO2_FiO2_Ratio               36.667779
FiO2_Mean                     32.287669
FiO2_Max                      32.287669
FiO2_Initial                  32.287669
PaO2_Initial                  24.495244
PaO2_Min                      24.461872
PaCO2_Initial                 24.453529
PaCO2_Min                     24.453529
PaCO2_Max                     24.453529
pH_Initial                    24.111463
pH_Min                        24.053062
pH_Max                        24.053062
pH_Mean                       24.053062
Urine_MinRate                  8.801936
Urine_MaxRate                  8.801936
Urine_MeanRate                 8.801936
Weight_Initial                 8.267979
Weight_Final                   7.650592
Urine_Sum                      2.469548
Mg_Initial                     2.394460
Glucose_Initial                2.361088
Glucose_Min                    2.336059
Glucose_Max                    2.336059
Glucose_Mean                   2.336059
Mg_Min                         2.319373
Mg_Max                         2.319373
Net_Cation_Balance             2.144168
WBC_Initial                    1.968964
K_Initial                      1.968964
K_Mean                         1.960621
K_Max                          1.960621
K_Min                          1.960621
K_Final                        1.960621
WBC_Min                        1.860504
WBC_Max                        1.860504
Temp_Initial                   1.752044
Na_Initial                     1.685300
Na_Max                         1.651927
Na_Mean                        1.651927
Na_Final                       1.651927
Na_Min                         1.651927
UniDiasABP_Initial             1.618555
Shock_Index                    1.618555
HCO3_Max                       1.610212
HCO3_Final                     1.610212
HCO3_Initial                   1.610212
HCO3_Min                       1.610212
Platelets_Initial              1.601869
UniSysABP_Final                1.585183
UniSysABP_Initial              1.535124
Platelets_Min                  1.535124
HR_Final                       1.535124
UniMAP_Initial                 1.526781
GCS_MAP_Product                1.510095
UniMAP_Final                   1.501752
HCT_Initial                    1.493409
HCT_Mean                       1.476723
HCT_Min                        1.476723
HCT_Max                        1.476723
GCS_Max                        1.426664
Temp_Mean                      1.426664
Temp_SD                        1.426664
GCS_Mean                       1.426664
GCS_Min                        1.426664
GCS_Final                      1.426664
GCS_Initial                    1.426664
Temp_Min                       1.426664
Temp_Max                       1.426664
HR_Mean                        1.418321
HR_Initial                     1.418321
UniSysABP_SD                   1.418321
UniMAP_Min                     1.418321
UniMAP_SD                      1.418321
UniMAP_Mean                    1.418321
UniSysABP_Min                  1.418321
UniSysABP_Max                  1.418321
UniDiasABP_Mean                1.418321
UniDiasABP_Max                 1.418321
UniMAP_Max                     1.418321
UniDiasABP_Min                 1.418321
UniSysABP_Mean                 1.418321
HR_Max                         1.418321
HR_SD                          1.418321
BUN_Initial                    1.418321
HR_Min                         1.418321
Creatinine_Mean                1.409978
BUN_Creatinine_Ratio           1.409978
Creatinine_Max                 1.409978
BUN_Max                        1.409978
BUN_Mean                       1.409978
Creatinine_Initial             1.409978
Weight_Delta                   0.784248
WBC_Delta                      0.133489
Mg_Delta                       0.091774
Platelets_Delta                0.066745
BUN_Delta                      0.050058
SaO2_Delta                     0.050058
PaO2_Delta                     0.050058
Na_Delta                       0.033372
AST_Delta                      0.025029
HCT_Delta                      0.016686
K_Delta                        0.008343
K_Log_Count                    0.000000
HR_Log_Count                   0.000000
HCT_Log_Count                  0.000000
HCO3_Log_Count                 0.000000
Glucose_Log_Count              0.000000
GCS_Log_Count                  0.000000
FiO2_Log_Count                 0.000000
Creatinine_Log_Count           0.000000
Cholesterol_Log_Count          0.000000
Bilirubin_Log_Count            0.000000
BUN_Log_Count                  0.000000
AST_Log_Count                  0.000000
ALT_Log_Count                  0.000000
ALP_Log_Count                  0.000000
Albumin_Log_Count              0.000000
Lactate_Log_Count              0.000000
UniSysABP_Log_Count            0.000000
UniMAP_Log_Count               0.000000
UniDiasABP_Log_Count           0.000000
WBC_Log_Count                  0.000000
Urine_Log_Count                0.000000
Temp_Log_Count                 0.000000
SaO2_Log_Count                 0.000000
RespRate_Log_Count             0.000000
Cholesterol_Delta              0.000000
Bilirubin_Delta                0.000000
ALP_Delta                      0.000000
ALT_Delta                      0.000000
PaCO2_Log_Count                0.000000
MechVent_Log_Count             0.000000
Mg_Log_Count                   0.000000
Na_Log_Count                   0.000000
HCO3_Delta                     0.000000
Creatinine_Delta               0.000000
Troponin_Log_Count             0.000000
Troponin_Delta                 0.000000
FiO2_Slope                     0.000000
GCS_Slope                      0.000000
Glucose_Slope                  0.000000
HR_Slope                       0.000000
PaCO2_Slope                    0.000000
pH_Slope                       0.000000
RespRate_Slope                 0.000000
Temp_Slope                     0.000000
Urine_Rate_Slope               0.000000
UniDiasABP_Slope               0.000000
UniMAP_Slope                   0.000000
UniSysABP_Slope                0.000000
Albumin_Miss                   0.000000
ALP_Miss                       0.000000
ALT_Miss                       0.000000
AST_Miss                       0.000000
Bilirubin_Miss                 0.000000
BUN_Miss                       0.000000
Cholesterol_Miss               0.000000
Creatinine_Miss                0.000000
FiO2_Miss                      0.000000
GCS_Miss                       0.000000
Glucose_Miss                   0.000000
HCO3_Miss                      0.000000
Albumin_Delta                  0.000000
PaO2_Log_Count                 0.000000
pH_Log_Count                   0.000000
Platelets_Log_Count            0.000000
Lactate_Miss                   0.000000
K_Miss                         0.000000
HR_Miss                        0.000000
HCT_Miss                       0.000000
MechVent_Miss                  0.000000
Mg_Miss                        0.000000
Na_Miss                        0.000000
PaCO2_Miss                     0.000000
SaO2_Miss                      0.000000
Temp_Miss                      0.000000
Urine_Miss                     0.000000
WBC_Miss                       0.000000
PaO2_Miss                      0.000000
pH_Miss                        0.000000
Platelets_Miss                 0.000000
RespRate_Miss                  0.000000
Troponin_Miss                  0.000000
Albumin_Last_Gap               0.000000
ALP_Last_Gap                   0.000000
ALT_Last_Gap                   0.000000
AST_Last_Gap                   0.000000
Bilirubin_Last_Gap             0.000000
BUN_Last_Gap                   0.000000
Cholesterol_Last_Gap           0.000000
Creatinine_Last_Gap            0.000000
FiO2_Last_Gap                  0.000000
GCS_Last_Gap                   0.000000
Glucose_Last_Gap               0.000000
Weight_Miss                    0.000000
UniDiasABP_Miss                0.000000
UniMAP_Miss                    0.000000
UniSysABP_Miss                 0.000000
K_Last_Gap                     0.000000
HR_Last_Gap                    0.000000
HCT_Last_Gap                   0.000000
HCO3_Last_Gap                  0.000000
Lactate_Last_Gap               0.000000
MechVent_Last_Gap              0.000000
Mg_Last_Gap                    0.000000
Na_Last_Gap                    0.000000
RespRate_Last_Gap              0.000000
SaO2_Last_Gap                  0.000000
Temp_Last_Gap                  0.000000
Urine_Last_Gap                 0.000000
PaCO2_Last_Gap                 0.000000
PaO2_Last_Gap                  0.000000
pH_Last_Gap                    0.000000
Platelets_Last_Gap             0.000000
UniMAP_Last_Gap                0.000000
UniDiasABP_Last_Gap            0.000000
Weight_Last_Gap                0.000000
WBC_Last_Gap                   0.000000
Total_Obs_Count                0.000000
Global_Last_Gap                0.000000
Troponin_Last_Gap              0.000000
UniSysABP_Last_Gap             0.000000
Total_Missing_Sum              0.000000
Age                            0.000000
Gender                         0.000000
ICUType_1.0                    0.000000
ICUType_2.0                    0.000000
ICUType_3.0                    0.000000
ICUType_4.0                    0.000000
In-hospital_death              0.000000
dtype: float64

In [124]:
df.describe()

,Albumin_Initial,Albumin_Min,Albumin_Max,Albumin_Mean,ALP_Initial,ALP_Max,ALT_Initial,ALT_Max,AST_Initial,AST_Max,Bilirubin_Initial,Bilirubin_Max,BUN_Initial,BUN_Max,BUN_Mean,BUN_Creatinine_Ratio,Cholesterol_Initial,Cholesterol_Min,Creatinine_Initial,Creatinine_Max,Creatinine_Mean,FiO2_Initial,FiO2_Max,FiO2_Mean,GCS_Initial,GCS_Final,GCS_Min,GCS_Max,GCS_Mean,Glucose_Initial,Glucose_Min,Glucose_Max,Glucose_Mean,HCO3_Initial,HCO3_Final,HCO3_Min,HCO3_Max,HCT_Initial,HCT_Min,HCT_Max,HCT_Mean,HR_Initial,HR_Final,HR_Min,HR_Max,HR_Mean,HR_SD,K_Initial,K_Final,K_Min,K_Max,K_Mean,Lactate_Initial,Lactate_Max,Lactate_Clearance_Rate_6H,Lactate_Clearance_Rate_12H,MechVent_Any,Mg_Initial,Mg_Min,Mg_Max,Na_Initial,Na_Final,Na_Min,Na_Max,Na_Mean,PaCO2_Initial,PaCO2_Min,PaCO2_Max,PaO2_Initial,PaO2_Min,PaO2_FiO2_Ratio,pH_Initial,pH_Min,pH_Max,pH_Mean,Platelets_Initial,Platelets_Min,RespRate_Initial,RespRate_Max,RespRate_Mean,SaO2_Initial,SaO2_Min,Temp_Initial,Temp_Min,Temp_Max,Temp_Mean,Temp_SD,Urine_Sum,Urine_MinRate,Urine_MaxRate,Urine_MeanRate,WBC_Initial,WBC_Min,WBC_Max,Weight_Initial,Weight_Final,UniDiasABP_Initial,UniDiasABP_Min,UniDiasABP_Max,UniDiasABP_Mean,UniMAP_Initial,UniMAP_Final,UniMAP_Min,UniMAP_Max,UniMAP_Mean,UniMAP_SD,UniSysABP_Initial,UniSysABP_Final,UniSysABP_Min,UniSysABP_Max,UniSysABP_Mean,UniSysABP_SD,Troponin_Max,Albumin_Log_Count,ALP_Log_Count,ALT_Log_Count,AST_Log_Count,BUN_Log_Count,Bilirubin_Log_Count,Cholesterol_Log_Count,Creatinine_Log_Count,FiO2_Log_Count,GCS_Log_Count,Glucose_Log_Count,HCO3_Log_Count,HCT_Log_Count,HR_Log_Count,K_Log_Count,Lactate_Log_Count,MechVent_Log_Count,Mg_Log_Count,Na_Log_Count,PaCO2_Log_Count,PaO2_Log_Count,pH_Log_Count,Platelets_Log_Count,RespRate_Log_Count,SaO2_Log_Count,Temp_Log_Count,Urine_Log_Count,WBC_Log_Count,UniDiasABP_Log_Count,UniMAP_Log_Count,UniSysABP_Log_Count,Troponin_Log_Count,Albumin_Delta,ALP_Delta,ALT_Delta,AST_Delta,Bilirubin_Delta,BUN_Delta,Cholesterol_Delta,Creatinine_Delta,HCO3_Delta,HCT_Delta,K_Delta,Mg_Delta,Na_Delta,PaO2_Delta,Platelets_Delta,SaO2_Delta,WBC_Delta,Weight_Delta,Troponin_Delta,FiO2_Slope,GCS_Slope,Glucose_Slope,HR_Slope,PaCO2_Slope,pH_Slope,RespRate_Slope,Temp_Slope,Urine_Rate_Slope,UniDiasABP_Slope,UniMAP_Slope,UniSysABP_Slope,Albumin_Miss,ALP_Miss,ALT_Miss,AST_Miss,Bilirubin_Miss,BUN_Miss,Cholesterol_Miss,Creatinine_Miss,FiO2_Miss,GCS_Miss,Glucose_Miss,HCO3_Miss,HCT_Miss,HR_Miss,K_Miss,Lactate_Miss,MechVent_Miss,Mg_Miss,Na_Miss,PaCO2_Miss,PaO2_Miss,pH_Miss,Platelets_Miss,RespRate_Miss,SaO2_Miss,Temp_Miss,Urine_Miss,WBC_Miss,Weight_Miss,UniDiasABP_Miss,UniMAP_Miss,UniSysABP_Miss,Troponin_Miss,Albumin_Last_Gap,ALP_Last_Gap,ALT_Last_Gap,AST_Last_Gap,Bilirubin_Last_Gap,BUN_Last_Gap,Cholesterol_Last_Gap,Creatinine_Last_Gap,FiO2_Last_Gap,GCS_Last_Gap,Glucose_Last_Gap,HCO3_Last_Gap,HCT_Last_Gap,HR_Last_Gap,K_Last_Gap,Lactate_Last_Gap,MechVent_Last_Gap,Mg_Last_Gap,Na_Last_Gap,PaCO2_Last_Gap,PaO2_Last_Gap,pH_Last_Gap,Platelets_Last_Gap,RespRate_Last_Gap,SaO2_Last_Gap,Temp_Last_Gap,Urine_Last_Gap,WBC_Last_Gap,Weight_Last_Gap,UniDiasABP_Last_Gap,UniMAP_Last_Gap,UniSysABP_Last_Gap,Troponin_Last_Gap,Global_Last_Gap,Total_Obs_Count,Total_Missing_Sum,Shock_Index,GCS_MAP_Product,Net_Cation_Balance,Age,Gender,Height,ICUType_1.0,ICUType_2.0,ICUType_3.0,ICUType_4.0,In-hospital_death
count,4871.000000,4871.000000,4871.000000,4871.000000,5097.000000,5097.000000,5213.000000,5213.000000,5212.000000,5214.000000,5213.000000,5213.000000,11816.000000,11817.000000,11817.000000,11817.000000,948.000000,948.000000,11817.000000,11817.000000,11817.000000,8116.000000,8116.000000,8116.000000,11815.000000,11815.000000,11815.000000,11815.000000,11815.000000,11703.00000,11706.000000,11706.000000,11706.000000,11793.000000,11793.000000,11793.000000,11793.000000,11807.000000,11809.000000,11809.000000,11809.000000,11816.000000,11802.000000,11816.000000,11816.000000,11816.000000,11816.000000,11750.000000,11751.000000,11751.000000,11751.000000,11751.000000,6576.000000,6576.000000,4182.000000,3715.000000,7580.0,11699.000000,11708.000000,11708.000000,11784.000000,11788.000000,11788.000000,11788.000000,11788.000000,9055.000000,9055.000000,9055.000000,9050.000000,9054.000000,7591.000000,9096.000000,9103.00000,9103.000000,9103.000000,11794.000000,11802.000000,3322.000000,3328.000000,3328.000000,5358.000000,5362.000000,11776.000000,11815.000000,11815.000000,11815.000000,11815.000000,11690.000000,10931.000000,10931.000000,10931.000000,11750.000000,11763.000000,11763.000000,10995.000000,11069.000000,11792.000000,11816.000000,11816.000000,11816.000000,11803.000000,11806.000000,11816.000000,11816.000000,11816.000000,11816.000000,11802.000000,11796.000000,11816.000000,11816.000000,11816.000000,11816.000000,3201.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11983.000000,11986.000000,11980.000000,11986.000000,11986.000000,11986.000000,11984.000000,11985.000000,11975.000000,11982.000000,11980.000000,11978.000000,11980.000000,11970.000000,11892.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000,11792.000000,11805.000000,11729.000000,11986.000000,11986.000000,6259.000000,11986.000000,11986.000000,11986.000000,11986.000000,11986.000000
mean,2.959782,2.885095,3.000370,2.942854,109.746321,114.642927,150.092653,216.861500,222.719685,341.163023,1.908651,2.167696,25.756263,29.157570,25.427010,24.426145,156.107595,155.695148,1.355547,1.541161,1.355437,0.782410,0.832480,0.551167,10.037495,12.385950,8.277698,13.530851,11.643228,148.75015,108.804459,173.096617,137.207774,23.203256,24.281184,21.871839,25.448402,31.940849,28.593014,34.129063,31.396168,89.595819,85.924759,68.614675,112.325169,87.065322,10.105287,4.175157,4.073381,3.755110,4.547758,4.131139,2.654950,3.163190,0.433090,6.519956,1.0,1.928842,1.782550,2.247207,138.808130,138.867662,136.933661,140.760095,138.884653,41.410491,34.633793,47.449365,203.555470,92.845151,165.983954,7.370595,7.31770,7.440802,7.383668,215.074784,177.852483,19.981939,28.905649,19.638342,96.724655,95.031686,36.570211,35.885307,37.918138,37.002004,0.587417,4251.017682,0.236079,6.305545,1.271009,13.008770,10.474594,15.150296,81.239764,83.397399,62.842520,40.325152,87.010917,59.720403,82.887475,80.536437,56.339820,110.257006,79.384708,11.145321,124.774021,123.341556,87.180349,159.449898,120.467679,15.719809,2.752791,0.351876,0.413465,0.423928,0.423849,1.439648,0.426462,0.056393,1.442917,1.629685,2.700151,1.376600,1.420238,1.620419,3.994561,1.458482,0.736732,1.548640,1.406387,1.411068,1.469977,1.468353,1.500931,1.442484,1.077876,0.664856,2.891561,3.422151,1.378811,3.980968,3.969750,3.981550,0.301739,-0.013841,-1.423661,8.060596,-1.755654,0.012431,-0.485476,-0.018522,-0.003471,1.060571,-1.109246,-0.099800,0.112867,0.055917,-65.267446,-23.898572,-0.042229,-0.601667,1.967138,-0.027797,-0.000174,0.000770,-0.009529,-0.000480,-0.000370,0.000012,0.000016,0.000122,-16.365263,-0.000003,0.000498,0.001608,0.593609,0.574754,0.565076,0.564992,0.565076,0.014100,0.920908,0.014100,0.322877,0.014267,0.023361,0.016102,0.014767,0.014183,0.019606,0.451360,0.367596,0.023194,0.016519,0.244535,0.244619,0.240531,0.015351,0.722343,0.552645,0.014267,0.024695,0.018605,0.075672,0.014183,0.014183,0.014183,0.732938,2405.009678,2325.408977,2310.359169,2310.613883,2298.462039,670.038712,2824.100451,668.768146,1403.592691,181.858752,726.828884,682.633072,611.942266,85.833806,671.530786,2102.406224,1495.698732,716.431837,674.084682,1373.740030,1372.917737,1312.231687,703.096446,2101.584766,2121.404055,177.680627,187.337894,720.755798,961.016102,90.261972,92.384365,90.244035,2540.302186,42.994410,389.761138,8.025196,0.721240,997.316618,118.670910,64.546221,0.559236,169.143202,0.147172,0.210829,0.357667,0.284332,0.142416
std,0.660457,0.666761,0.640521,0.641694,145.576521,152.550958,621.545089,889.072133,896.424430,1370.070680,4.439789,4.876090,21.340629,22.791697,20.379941,12.781493,44.756021,44.787742,1.461876,1.612727,1.390033,0.252323,0.231372,0.131990,4.908701,3.639666,4.828723,2.630133,3.262094,73.83684,29.618857,85.377227,39.847157,4.678756,4.285436,4.574150,4.140478,5.959639,5.253002,4.797457,4.503380,20.054102,17.239563,14.029678,22.366685,14.734643,4.669537,0.722862,0.519734,0.513514,0.714088,0.481059,2.146722,2.687895,68.171310,64.926399,0.0,0.452545,0.345695,0.396400,4.741033,4.405947,4.418815,4.500969,4.141196,10.811032,7.832714,11.341402,122.758586,42.495789,99.375162,0.093374,0.09096,0.061447,0.056764,112.207344,98.994995,5.707012,6.344019,3.885286,3.735171,4.792340,1.060690,0.824109,0.746443,0.569658,0.256240,2857.643479,0.228647,10.568922,1.005372,10.348273,7.197489,11.359312,23.820298,24.419043,15.903909,10.118706,16.348520,9.764953,17.994802,15.278360,11.595537,18.501490,10.562754,3.514059,25.834143,22.274900,16.338134,24.691482,16.579279,5.161754,6.871148,0.461237,0.535419,0.539590,0.539385,0.351073,0.542900,0.194087,0.352449,1.223111,0.491903,0.404071,0.360488,0.455988,0.534703,0.407723,0.805738,1.256340,0.407823,0.386617,1.024097,1.023402,1.037716,0.383647,1.747339,0.854140,0.674180,0.715078,0.364798,0.543199,0.548606,0.543252,0.535357,0.161732,30.299559,357.629077,572.218015,0.842493,10.093827,1.017079,0.611811,3.560105,4.870609,0.730287,0.424971,4.031887,113.486010,55.881975,2.340249,6.489080,6.647652,1.760281,0.001133,0.001854,0.043702,0.007075,0.018153,0.000126,0.001523,0.000420,87.959444,0.004700,0.006163,0.007983,0.491180,0.494401,0.495768,0.495779,0.495768,0.117907,0.269894,0.117907,0.467596,0.118593,0.151052,0.125874,0.120625,0.118251,0.138649,0.497649,0.482171,0.150525,0.127467,0.429829,0.429879,0.427424,0.122951,0.447862,0.497242,0.118593,0.155202,0.135131,0.264483,0.118251,0.118251,0.118251,0.442443,810.708369,879.580230,886.683573,886.435685,895.807423,474.459203,258.556132,474.848655,1231.017911,366.149760,556.111890,490.929748,486.021185,355.129883,533.231790,991.052151,1237.273444,576.589656,497.980001,1125.227481,1124.981365,1127.146464,493.306532,1260.965693,1034.017174,364.631119,523.975566,504.483139,1325.267725,359.051406,360.412877,359.051924,706.696490,107.113636,107.453550,4.023154,0.206512,348.437673,5.880943,17.167993,0.498512,13.299026,0.354292,0.407914,0.479333,0.451114,0.349491
min,1.000000,1.000000,1.100000,1.100000,11.000000,12.000000,1.000000,1.000000,5.000000,5.000000,0.100000,0.100000,2.000000,2.000000,2.000000,2.272727,28.000000,28.000000,0.100000,0.100000,0.100000,0.210000,0.210000,0.210000,3.000000,3.000000,3.000000,3.000000,3.000000,21.00000,21.000000,47.000000,40.666667,5.000000,7.000000,5.000000,11.000000,10.000000,10.000000,10.300000,10.150000,23.000000,21.000000,20.000000,53.000000,35.543478,0.000000,1.500000,2.400000,1.500000,2.500000,2.500000,0.300000,0.400000,-2000.000000,-1233.333333,1.0,0.400000,0.400000,1.100000,100.000000,112.000000,100.000000,118.000000,110.800000,11.000000,10.000000,16.000000,20.000000,20.000000,20.000000,6.820000,6.80000,7.100000,7.085000,10.000000,10.000000,7.000000,14.000000,10.098039,51.000000,51.000000,26.100000,26.100000,35.300000,32.507692,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,0.500000,0.500000,21.700000,30.000000,15.000000,15.000000,22.000000,22.000000,10.000000,12.000000,10.000000,30.000000,30.000000,0.000000,40.000000,40.000000,40.000000,85.000000,77.179487,0.000000,0.010000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.800000,-529.000000,-10140.000000,-16456.000000,-20.600000,-97.000000,-35.000000,-12.900000,-23.000000,-26.300000,-6.400000,-2.800000,-26.000000,-432.000000,-566.000000,-43.000000,-264.900000,-120.000000,-47.470000,-0.040000,-0.008121,-1.178571,-0.051703,-0.833333,-0.003778,-0.027748,-0.006000,-6603.355705,-0.034465,-0.261929,-0.048315,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,1.000000,0.185841,60.000000,91.500000,15.000000,-1.000000,12.700000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.500000,2.400000,2.600000,2.500000,58.000000,60.000000,17.000000,18.000000,25.000000,26.000000,0.400000,0.500000,13.000000,15.000000,12.750000,16.666667,124.000000,124.000000,0.700000,0.800000,0.700000,0.500000,0.600000,0.460000,5.000000,10.000000,3.000000,13.000000,9.312500,108.00000,90.000000,126.000000,111.808333,21.000000,22.000000,19.000000,23.000000,27.800000,25.000000,30.800000,28.266667,76.000000,74.000000,59.000000,96.000000,76.897607,6.939810,3.700000,3.700000,3.400000,4.100000,3.800000,1.300000,1.500000,0.000000,-2.859477,1.0,1.600000,1.600000,2.000000,136.000000,136.000000,135.000000,138.000000,136.500000,35.000000,30.000000,40.000000,97.000000,67.000000,91.666667,7.320000,7.27000,7.410000,7.351500,140.000000,111.000000,16.000000,24.000000,16.905649,97.000000,94.000000,35.900000,35.500000,37.400000,36.623241,0.405642,2532.500000,0.090580,2.012326,0.677080,8.400000,7.200000,10.200000,65.700000,67.200000,52.000000,34.000000,75.000000,53.019630,70.330000,70.000000,50.000000,97.000000,71.721908,8.611971,107.000000,107.000000,77.000000,142.000000,108.142857,12.030814,0.060000,0.000000,0.000000,0.000000,0.000000,1.098612,0.000000,0.000000,1.386294,0.000000,2.564949,1.098612,1.098612,1.386294,3.912023,1.098612,0.000000,0.000000,1.098612,1.098612,0.693147,0.693147,0.693147,1.098612,0.000000,0.000000,2.564949,3.401197,1.098612,3.871201,3.871201,3.871201,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-4.000000,0.000000,-0.100000,-1.000000,-3.900000,-0.500000,-0.100000,-2.000000,-126.000000,-48.000000,0.000000,-2.800000,0.000000,0.000000,-0.000113,0.000000,-0.021616,-0.004609,-0.001627,0.000000,0.000000,-0.000125,-6.115689,-0.002868,-0.002868,-0.003145,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2272.000000,2000.500000,1927.000000,1930.250000,1855.000000,354.000000,2880.000000,352.000000,138.000000,55.000000,356.000000,357.000000,285.000000,14.000000,319.000000,1295.250000,148.000000,337.000000,346.000000,293.000000,293.000000,267.000000,372.000000,107.250000,1218.250000,46.000000,22.000000,383.250000,24.000000,15.000000,15.000000,15.000000,2755.250000,12.000000,326.000000,4.000000,0.575540,780.000000,114.900000,53.000000,0.000000,162.600000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.000000,2.900000,3.000000,2.950000,78.000000,81.000000,30.000000,32.000000,45.000000,49.000000,0.700000,0.800000,19.000000,22.000000,18.750000,22.000000,153.000000,153.000000,0.900000,1.000000,0.925000,1.000000,1.000000,0.525000,11.000000,15.000000,7.000000,15.000000,12.500000,131.00000,106.000000,151.000000,129.400000,23.000000,24.000000,22.000000,25.000000,31.700000,28.000000,33.500000,30.650000,88.000000,85.000000,68.000000,110.000000,86.229968,9.159054,4.100000,4.000000,3.700000,4.400000,4.066667,1.900000,2.300000,0.000000,9.090909,1.0,1.900000,1.800000,2.200000,139.000000,139.000000,137.000000,141.000000,139.000000,40.000000,34.000000,46.000000,170.000000,82.000000,145.714286,7.380000,7.33000,7.440000,7.387647,197.000000,161.000000,19.000000,28.000000,19.043499,98.000000,96.000000,36.600000,36.000000,37.800000,36.987755,0.545511,3895.000000,0.196721,3.905447,1.074866,11.600000,9.600000,13.600000,78.000000,80.000000,61.000000,40.000000,85.000000,58.696898,81.000000,79.000000,56.000000,107.000000,77.995162,10.605418,122.000000,121.000000,86.000000,157.000000,117.968067,15.002089,0.280000,0.000000,0.000000,0.000000,0.000000,1.386294,0.000000,0.000000,1.386294,2.197225,2.639057,1.386294,1.386294,1.609438,4.025352,1.386294,0.693147,2.079442,1.386294,1.386294,1.791759,1.791759,1.791759,1.386294,0.000000,0.000000,2.708050,3.637586,1.386294,4.025352,4.007333,4.025352,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,-1.100000,0.000000,0.100000,0.000000,0.000000,-16.000000,0.000000,-0.300000,0.000000,0.000000,0.000000,0.000123,-0.004517,-0.000268,0.000000,0.000000,0.000000,0.000101,-1.115753,-0.000016,0.000358,0.001306,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2880.000000,2880.000000,2880.000000,2880.000000,2880.000000,589.000000,2880.000000,587.000000,1236.000000,113.000000,617.000000,597.000000,506.500000,31.000000,556.500000,2739.000000,1513.000000,590.000000,581.000000,1029.000000,1028.000000,883.000000,624.000000,2880.000000,2880.000000,111.000000,45.000000,641.000000,51.000000,32.000000,32.000000,32.000000,2880.000000,27.000000,379.000000,8.000000,0.696429,1035.000000,118.300000,67.000000,1.000000,170.200000,0.000000,0.000000,0.000000,0.000000,0.000000

# train test data split

In [125]:
X = df.drop(columns=['In-hospital_death'])
y = df['In-hospital_death']

In [126]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=SEED, stratify=y)

In [127]:
X_train.reset_index(drop=True, inplace=True)
y_train.reset_index(drop=True, inplace=True)

In [128]:
X_test.reset_index(drop=True, inplace=True)
y_test.reset_index(drop=True, inplace=True)

In [129]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((9588, 255), (2398, 255), (9588,), (2398,))

# output tree-based model feature set

In [130]:
X_train.to_csv(path+'/X_train_tree.csv', index=False)
X_test.to_csv(path+'/X_test_tree.csv', index=False)
y_train.to_csv(path+'/y_train.csv', index=False)
y_test.to_csv(path+'/y_test.csv', index=False)

# missing value imputation

### zero imputation

In [131]:
delta_slope_cols = [c for c in X_train.columns if 'Delta' in c or 'Slope' in c]

In [132]:
X_train[delta_slope_cols] = X_train[delta_slope_cols].fillna(0)
X_test[delta_slope_cols] = X_test[delta_slope_cols].fillna(0)

### median imputation

In [133]:
imputer = SimpleImputer(strategy='median')
X_train_imputed = imputer.fit_transform(X_train)
X_test_imputed = imputer.transform(X_test)

In [134]:
X_train_smote = pd.DataFrame(X_train_imputed, columns=X_train.columns)
X_test_smote = pd.DataFrame(X_test_imputed, columns=X_test.columns)

In [135]:
X_train_smote.isnull().sum().sum()

np.int64(0)

In [136]:
X_test_smote.isnull().sum().sum()

np.int64(0)

In [137]:
X_train_smote.to_csv(path+'/X_train_smote.csv', index=False)
X_test_smote.to_csv(path+'/X_test_smote.csv', index=False)

# standardization

In [138]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_smote)
X_test_scaled = scaler.transform(X_test_smote)

In [139]:
X_train_linear = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_linear = pd.DataFrame(X_test_scaled, columns=X_test.columns)

# output linear-based model feature set

In [140]:
X_train_linear.to_csv(path+'/X_train_linear.csv', index=False)
X_test_linear.to_csv(path+'/X_test_linear.csv', index=False)

In [141]:
joblib.dump(X_train.columns, path+'/feature_name.pkl')
joblib.dump(imputer, path+'/median_imputer.pkl')
joblib.dump(scaler, path+'/standard_scaler.pkl')

['/home/leewen/code/physionet/standard_scaler.pkl']